T7344 kintone: レコード追加　の作成
Questetra/Addon-XML pull request #212
Opened 2020-09-03 05:20 UTC by tatsumiQ

レビューをお願いいたします。

2020-09-03 06:44 UTC, hatanaka-akihiro requested changes
総じて、解りやすいと思いました。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +<label locale="ja">kintone: レコード追加</label>
日英で Kintone/kintone と表記が異なります。

英語ページは混在していますね。ロゴは小文字だけど、文中は大文字っぽい。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +<label locale="ja">kintone: レコード追加</label>
ロゴにあわせて "kintone" の方か。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +    <label>C5: String type data Item that will save Record ID</label>
最近のアイテム。 

- STRING DATA
- String type data item

２パターンあるが、"item" の "I" が大文字なのはミスかな。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +  let recordObj = {};
プロパティの追加はしていますが、recordObj 自体は書き換えていないと思います。

こういう場合、const で良いです。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +    apiUri = `https://${domain}/k/guest/${guestSpaceId}/v1/record.json`;
guestSpaceId のチェックもできないですかね。

/ を使って、まったく違う API へのアクセスにできるかもしれません。

そんな悪いことはできないと思いますが。

2020-09-03 06:44 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +  let recordObj = {};
別に let で問題ないです。

2020-09-04 02:02 UTC, tatsumiQ commented on kintone-record-add.xml
> +<label locale="ja">kintone: レコード追加</label>
"kintone" に修正しました。ラベルのみ日英ともに "kintone" とし、他（文中）は日本語では "kintone"、英語では "Kintone" に統一します。

2020-09-04 02:03 UTC, tatsumiQ commented on kintone-record-add.xml
> +    <label>C5: String type data Item that will save Record ID</label>
表記ミスでしたので、 "String type data item" としました。

2020-09-04 02:07 UTC, tatsumiQ commented on kintone-record-add.xml
> +  let recordObj = {};
再代入しているわけではないので const で良かったのですね。
他の修正のついでに修正しておきました。

2020-09-04 02:08 UTC, tatsumiQ commented on kintone-record-add.xml
> +    apiUri = `https://${domain}/k/guest/${guestSpaceId}/v1/record.json`;
guestSpaceId のチェックを追加しました。
ID の扱いを統一する観点から、appId のチェックも追加しました。
kintone の ID はすべて自然数です。

2020-09-04 02:09 UTC, tatsumiQ commented
@hatanaka-akihiro さん
ご指摘の箇所を修正しましたので、再レビューをお願いいたします。

2020-09-04 05:04 UTC, merged