engine を「2」に変更
Questetra/Addon-XML pull request #214
Opened 2020-09-07 03:06 UTC by Tonoyama

t7402
`engine-type`を`2`に変更しました。

テスト仕様書：
https://docs.google.com/spreadsheets/d/1N2fidm2Xq86x4QZYGeA2u5cAPb_GK_cJqmkGZkQu3XE/edit#gid=0

レビューをお願いします。

2020-09-07 05:07 UTC, tatsumiQ requested changes
エンジンの変更と併せて、他に変更すべき箇所がないか定義ファイル全体を確認するようにしてください。
詳しくはチケットに記載します。

2020-09-07 05:07 UTC, tatsumiQ commented on any-website-file-download.xml
>  <last-modified>2019-03-22</last-modified>
日付を最終更新日に更新してください。

2020-09-07 06:11 UTC, Tonoyama commented on any-website-file-download.xml
>  <last-modified>2019-03-22</last-modified>
テスト仕様書の URL は、GitHub から削除し、Trac など他の媒体で掲載します。

2020-09-08 01:17 UTC, tatsumiQ requested changes
最近更新されている他の定義ファイルを参考にしてもらえればと思いますが、現在は下のような書き方が推奨されています。
main() の中身は簡潔にしたほうが分かりやすいです（複雑な処理は関数化する）。
他の定義ファイルを参考に、工夫してみてください。

```
main();
function main() {
// ここに主となる処理を書く

}

// main() 内で使う関数は適宜コメントを付けつつ main() の下で定義
function func1() {
}
```

2020-09-08 01:17 UTC, tatsumiQ commented on any-website-file-download.xml
> +const httpStatus  = response.getStatusCode()
```suggestion
const httpStatus  = response.getStatusCode();
```

2020-09-08 01:17 UTC, tatsumiQ commented on any-website-file-download.xml
>  // convert 'java.lang.String' to 'javascript string'
このコメントは不要だと思うので削除してください。

2020-09-08 01:17 UTC, tatsumiQ commented on any-website-file-download.xml
>    const error = "Failed to download \n STATUS:" + httpStatus + "\n" + responseTxt;
文字列の連結は使わずテンプレート文字列を使用してください。
また、レスポンスの内容はエラーに含めずに、`engine.log()` でログ出力してください。
```suggestion
  const error = `Failed to download. STATUS: ${httpStatus}`;
```

2020-09-08 01:17 UTC, tatsumiQ commented on any-website-file-download.xml
>  engine.log( "STATUS: " + httpStatus );
ここもテンプレート文字列を使用してください。

2020-09-10 05:19 UTC, tatsumiQ requested changes
定義した関数は main 関数内で呼び出します。
関数には適宜、引数や返り値を設定します。
```
main(); // main() の実行

// main() の定義
function main() {
  let fileUrl = configs.get( "conf_DataIdA" );
  const result = func1( fileUrl ); // fileUrl を引数にとって func1() を実行し、結果を変数 result に代入
  func2( result ); // result を引数にして func2() を実行
}

// func1 の定義（引数 fileUrl、返り値 result）
function func1( fileUrl ) {
  // ここに func1() にさせたい処理を書く
  return result; // result を返す
}

// func2 の定義（引数 result、返り値なし）
function func2( result ) {
  // ここに func2() にさせたい処理を書く
}
```

今のコードはこの形で書けていません。
引数や返り値の理解があやふやな場合は、以下のページを参考にしてみてください。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions

2020-09-11 01:25 UTC, tatsumiQ requested changes
関数化できていますね。
不要な処理や、処理の順番がおかしいところがあるので、コメントを付けました。
１〜４の順番に読んでもらえれば分かりやすいと思います。

2020-09-11 01:25 UTC, tatsumiQ commented on any-website-file-download.xml
> +  const saveAs  = configs.get( "conf_SaveAs" );
１：
この部分では工程コンフィグからデータの読み出しをしています。
このコードではファイル名を指すものとして fileName と saveAs の2つの変数が使われていますが、61行目で saveAs が fileName に代入されていて、最終的にイコールになっています。
なので、fileName を使うのをやめて saveAs に統一したほうが分かりやすくなります。
（おそらく、当初は saveAs が空なら URL からファイル名を生成して fileName に代入する予定が、途中でやめたのだと思います）

あと、fileUrl も他と同様に再代入されないので、let ではなく const にします。

```suggestion
  const fileUrl = configs.get( "conf_DataIdA" );
  const dataIdB = configs.get( "conf_DataIdB" );
  const saveAs  = configs.get( "conf_SaveAs" );
```

2020-09-11 01:25 UTC, tatsumiQ commented on any-website-file-download.xml
> +  const qfile = saveFile( fileName, response );
２：
ファイル名を指す変数を saveAs に統一することにしたので、ここの fileName を saveAs に変更します。
```suggestion
  const qfile = saveFile( saveAs, response );
```

2020-09-11 01:25 UTC, tatsumiQ commented on any-website-file-download.xml
> +  }
３：
ここでは、saveAs が空文字列かどうかをチェックし、空文字列であればエラーにしています。
このチェックは、saveAs を他のところで使う前に行う必要があります（空文字列はファイル名として使えないので、実際に使ってしまう前にチェックする）。
なので、このコードは40行目の`const qfile = saveFile( saveAs, response );`の前に持っていきます。

また、ファイル名を指す変数を saveAs に統一することにしたので、fileName への代入が不要になります。
```suggestion
  if( saveAs === "" ){
    throw "Downloaded File Name isn't set";
  }
```

2020-09-11 01:25 UTC, tatsumiQ commented on any-website-file-download.xml
> +  }
４：
ここでは fileUrl が http ではじまる文字列かどうかをチェックして、httpではじまらない文字列（URL として不正な文字列）の場合はエラーにしています。

このチェックも、fileUrl を使用する前に行う必要があります。
39行目の ` const response = accessToTheUrl( fileUrl );` の前に持っていきます。
```suggestion
  if ( ! fileUrl.startsWith('http') ) {
    throw "Invalid URL. URL must start with either http or https.";
  }
```

2020-09-11 02:58 UTC, tatsumiQ requested changes
レビューしました。
コメントを１〜４の順番に読んでもらえると分かりやすいと思います。
その後に、番号のついていないコメントを読んでください。

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
>    //let UrlforName = decodeURI();
ここは不要になったコードをコメントアウトしているだけなので、消しておきましょう。
```suggestion
```

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
>    }
１：
53行目〜57行目でワークフローデータの参照を行っています。
39行目の `//// == Data Retrieving / ワークフローデータの参照 ==` の後ろに移動させると分かりやすくなります。

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
> +  const qfile = saveFile( saveAs, response );
２：
40行目から50行目が「演算」部分です。
`//// == Calculating / 演算 ==` のコメントは40行目の前に持っていきます。

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
>    const databyNum = dataUpdating( processFiles, dataIdB, qfile )
３：
59行目でデータの出力（ワークフローデータへの代入）を行っています。
この行の前にコメントを入れると分かりやすくなります。

変数 databyNum は使われていないので不要です。

関数名は他と揃えて動詞スタートにすると良いです。
```suggestion
  //// == ワークフローデータへの代入 / Data Updating ==
  updateData( processFiles, dataIdB, qfile );
```

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
> +<last-modified>2020-09-10</last-modified>
last-modified は更新のたびに最新の日付にします。

2020-09-11 02:58 UTC, tatsumiQ commented on any-website-file-download.xml
> +}
４：
変数 databyNum は使っていないので不要です。
```suggestion
function updateData( processFiles, dataIdB, qfile ) {
  processFiles.add( qfile );
  engine.setDataByNumber( dataIdB, processFiles );
}
```

2020-09-11 05:15 UTC, Tonoyama commented on any-website-file-download.xml
>    }
やってみたのですが、うまく動かず元のコードに戻る形となりました。
39行目で`}`をつけた場合、変数がスコープ外になるため、
`ReferenceError: "fileUrl" is not defined at line number 13`が起きました。

2020-09-11 05:27 UTC, tatsumiQ commented on any-website-file-download.xml
>    }
`}` だけでなく、53行目〜57行目をまるごと39行目の後ろ（40行目〜）に移動させます。
```
  let processFiles = engine.findDataByNumber( dataIdB );
  // java.util.ArrayList <com.questetra.bpms.core.event.scripttask.QfileView>
  if (processFiles === null) {
    processFiles = new java.util.ArrayList();
  }
```

2020-09-11 06:35 UTC, Tonoyama commented on any-website-file-download.xml
>    }
修正を反映しました

2020-09-14 01:14 UTC, tatsumiQ requested changes
かなり見やすいコードになってきました。
コメントを付けた部分の修正をお願いいたします。

2020-09-14 01:14 UTC, tatsumiQ commented on any-website-file-download.xml
> +  updateData( processFiles, dataIdB, qfile )
コメントとコードが対応していないので、修正してください。
```suggestion
  //// == Data Retrieving / ワークフローデータの参照 == 
  let processFiles = engine.findDataByNumber( dataIdB );
  // java.util.ArrayList <com.questetra.bpms.core.event.scripttask.QfileView>
  if (processFiles === null) {
    processFiles = new java.util.ArrayList();
  }

  //// == Calculating / 演算 ==
  if ( ! fileUrl.startsWith('http') ) {
    throw "Invalid URL. URL must start with either http or https.";
  }
  const response = accessToTheUrl( fileUrl );

  if( saveAs === "" ){
    throw "Downloaded File Name isn't set";
  }
  const qfile = saveFile( saveAs, response );

  //// == Data Updating / ワークフローデータへの代入 == 
  updateData( processFiles, dataIdB, qfile )
```

2020-09-14 01:14 UTC, tatsumiQ commented on any-website-file-download.xml
>  /// Error Handling
削除
```suggestion
```

2020-09-14 01:14 UTC, tatsumiQ commented on any-website-file-download.xml
> +  const response = httpRequest.get( fileUrl ); // HttpResponseWrapper
ここをこのように書けば、URL に接続できない場合に意図通りのエラー内容が出力されるようになると思います。
```suggestion
  try {
    const response = httpRequest.get( fileUrl ); // HttpResponseWrapper
  } catch (e) {
    throw `Unable to access ${fileUrl}.`;
  }
```

2020-09-14 01:14 UTC, tatsumiQ commented on any-website-file-download.xml
> +  engine.log( responseTxt );
エラーにレスポンス本文（responseTxt）を含めると長すぎる場合があるので、エラーに含めるのはステータスコードまでにして、レスポンス本文はエラーを出す前にログ出力してください。
```suggestion
  engine.log( `STATUS: ${httpStatus}` );
  engine.log( responseTxt );
  if (httpStatus >= 300) {
    throw `Failed to download. STATUS: + ${httpStatus}`;
```

2020-09-14 02:47 UTC, tatsumiQ requested changes
前回のレビューで指摘したコメント挿入場所の修正等もお願いします。
last-modified の更新も忘れずに。

2020-09-14 02:47 UTC, tatsumiQ commented on any-website-file-download.xml
> +  }
変数 response がスコープ外になってしまうので、先に宣言しておく必要がありました（すみません）。
```suggestion
  let response;
  try {
    response = httpRequest.get( fileUrl ); // HttpResponseWrapper
  } catch (e) {
    throw `Unable to access ${fileUrl}.`;
  }
```

2020-09-14 05:23 UTC, tatsumiQ requested changes
細かいですが、不要なコメントが残っていたので削除をお願いします。

2020-09-14 05:23 UTC, tatsumiQ commented on any-website-file-download.xml
> +  /// File Name (from URI Path with Regular Expression
このコメントは無い方が良いです。（コードの内容と合致しないので）
```suggestion
```

2020-09-15 01:42 UTC, tatsumiQ reviewed
コードはこれで良いと思います。お疲れ様でした。

2020-09-15 02:10 UTC, hatanaka-akihiro requested changes

2020-09-15 02:10 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +    throw `Failed to download. STATUS: + ${httpStatus}`;
この "+" は要るのでしょうか。

2020-09-15 02:10 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +  }
このチェックは、先にすべき。

ここでエラーになったら、HTTP リクエストが無駄になるから。

2020-09-18 01:03 UTC, tatsumiQ reviewed
修正を確認しました。問題ありません。

2020-09-18 01:28 UTC, merged