Update box-folder-link-create.xml
Questetra/Addon-XML pull request #218
Opened 2020-09-10 05:09 UTC by suese-sayaka

@hatanaka-akihiro  さん

日付更新と、英語のconfigラベルを「C3: Datetime....」に修正しました。
ご確認をお願いします。

2020-09-11 02:01 UTC, hatanaka-akihiro requested changes

2020-09-11 02:01 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> -    <label>C3: Date Time type data Item with Expiration of the Link</label>
ついで。
"data Item" というのも変。"Data item" ならまだ解るが．．．
全部小文字で。

2020-09-11 02:01 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> -    <label>C3: Date Time type data Item with Expiration of the Link</label>
他の config も。

2020-09-13 23:59 UTC, suese-sayaka commented on box-folder-link-create.xml
> -    <label>C3: Date Time type data Item with Expiration of the Link</label>
@hatanaka-akihiro  さん

config C3 、config C4、 config C5 の英語ラベル　「data Item.....」を「data item......」に修正しました。
ご確認をお願いします。

2020-09-14 00:05 UTC, merged