T7345: kintone: レコード取得　の作成
Questetra/Addon-XML pull request #220
Opened 2020-09-14 02:31 UTC by tatsumiQ

@hatanaka-akihiro さん
レビューをお願いいたします。

2020-09-14 09:10 UTC, hatanaka-akihiro requested changes

2020-09-14 09:10 UTC, hatanaka-akihiro commented on kintone-record-get.xml
> +    const toString = Object.prototype.toString; // オブジェクトクラス判別用の toString
この辺の判定。

fielValueObj === undefined
fieldValueObj === null
typeof fieldValueObj === 'string'

等で判定不能でしょうか？

2020-09-14 09:10 UTC, hatanaka-akihiro commented on kintone-record-get.xml
> +      if ( dataDefList[i].matchDataType("STRING_TEXTFIELD") && ( dataStringList[i].indexOf('\n') !== -1) ) {
QBPMS 自身のチェックに任せて良いとも思います。

2020-09-18 06:26 UTC, tatsumiQ commented on kintone-record-get.xml
> +    const toString = Object.prototype.toString; // オブジェクトクラス判別用の toString
修正しました。（undefined の場合は value プロパティにアクセスできないため、先にチェックを行うようにしました）

2020-09-18 06:27 UTC, tatsumiQ commented on kintone-record-get.xml
> +      if ( dataDefList[i].matchDataType("STRING_TEXTFIELD") && ( dataStringList[i].indexOf('\n') !== -1) ) {
改行が含まれる場合のチェックは QBPMS のバリデーションに任せるように変更しました。

2020-09-18 06:28 UTC, tatsumiQ commented
@hatanaka-akihiro さん
レビューコメントおよびチケットでご指摘いただいた点を修正しました。
ご確認をお願いいたします。

2020-09-18 07:32 UTC, merged