T7245:Box: ファイルアップロード より大きいサイズのファイルをアップロードできるように
Questetra/Addon-XML pull request #221
Opened 2020-09-14 06:19 UTC by R-Matsubayashi

通信数をアップロード開始前にチェックするように変更

2020-09-15 01:25 UTC, tatsumiQ requested changes
コメントを付けた箇所に加え、main() 関数が長くなっているので関数を分けたほうが良いと思いました。
たとえば、67行目〜84行目を `prepareSessions()` という関数にするなど。
ご検討ください。

2020-09-15 01:25 UTC, tatsumiQ commented on box-file-upload.xml
> +      }
同じ if 文が２箇所にあります（70〜72行目と、77〜80行目）。
分かりやすさの観点からも、for 文を抜けてから一度確認すれば十分だと思います。

2020-09-15 01:25 UTC, tatsumiQ commented on box-file-upload.xml
> +      requestNum = processLargeFile(token,files.get(i),folderId,uploadedFileData,session[i]);
ここで requestNum に代入する必要はなくなったと思います。
```suggestion
      processLargeFile(token,files.get(i),folderId,uploadedFileData,session[i]);
```

2020-09-15 01:25 UTC, tatsumiQ commented on box-file-upload.xml
> +  engine.log("---upload successful---");
まだアップロードが完了していないのに upload successful とログを出すのは違和感があります（１つ目のファイルアップロードに失敗する場合にもこのログが出てしまう）。
「以下のファイルがアップロード成功」という意味であれば、アップロード開始時に `uploading {ファイル名} ...` 、アップロード成功時に `successful` と出力するのはいかがでしょうか。
こうしておけばアップロード失敗時にファイル名を出力する必要もなくなると思います（uploadLargefile() にログ出力のためだけに引数にファイル名を取っているのが、不要になる）。

2020-09-17 01:31 UTC, tatsumiQ requested changes
修正漏れと思われる箇所がありましたので、ご確認をお願いします。

2020-09-17 01:31 UTC, tatsumiQ commented on box-file-upload.xml
> +  uploadAllFiles(token,files.get(i),folderId,uploadedFileData,session[i]);
このままでも動くかもしれませんが、意味合いとしては以下が正しいのではないでしょうか。
```suggestion
  uploadAllFiles(token,files,folderId,uploadedFileData,session);
```

2020-09-17 01:32 UTC, tatsumiQ commented on box-file-upload.xml
> +  engine.log("---upload successful---");
ログ内容が分かりやすくなりました。

2020-09-17 01:34 UTC, tatsumiQ commented on box-file-upload.xml
> +      }
この指摘ではセッション作成前にファイル数でチェックする必要があるという観点が抜けていました。すみません。
セッション作成前と作成後のチェックではっきり分けることで分かりやすくなりました。

2020-09-23 02:18 UTC, tatsumiQ requested changes
仕様変更による実行速度への影響が気になっています。
ご確認をお願いいたします。

2020-09-23 02:18 UTC, tatsumiQ commented on box-file-upload.xml
> +  }
フォルダ内に存在するファイル/フォルダ名を配列に格納して、後から includes() で存在チェックを行っています。
ロジックは正しいのですが、フォルダ内に大量のファイル/フォルダがある場合（調べたところ、上限は15,000個？）に実行速度が極端に遅くなるのではと懸念します。
（どのくらい効果があるかは分かりませんが、Array の includes() メソッドよりも Set の has() メソッドのほうが速そうです）

実行速度への影響次第ではファイル名の事前チェックはあきらめたほうが良いかもしれません。

2020-09-29 01:16 UTC, tatsumiQ commented
レビューしました。問題ないと思います。

2020-09-29 01:27 UTC, hatanaka-akihiro requested changes

2020-09-29 01:27 UTC, hatanaka-akihiro commented on box-file-upload.xml
> +    throw `failed to create upload session \nstatus: ${status}`;
throw するエラーメッセージに、ファイル名を入れた方が良いです。
複数ファイルアップロードなので。

2020-09-29 01:27 UTC, hatanaka-akihiro commented on box-file-upload.xml
> +    throw `failed to upload\nstatus: ${status}`;
throw するエラーメッセージに、ファイル名を入れた方が良いです。
複数ファイルアップロードなので。

2020-09-29 01:27 UTC, hatanaka-akihiro commented on box-file-upload.xml
> +    throw `failed to commit upload session \nstatus: ${status}`;
throw するエラーメッセージに、ファイル名を入れた方が良いです。
複数ファイルアップロードなので。

2020-09-30 03:08 UTC, R-Matsubayashi commented on box-file-upload.xml
> +    throw `failed to upload\nstatus: ${status}`;
uploadAllFilesを呼んだ段階でファイル名はログに出ているので、エラー時でもファイル名は残りますが、それでは駄目でしょうか？(下のcommitに関しても同様です。session作成時には出ていないのでこちらは足しておきます)

2020-09-30 03:19 UTC, R-Matsubayashi commented on box-file-upload.xml
> +    throw `failed to upload\nstatus: ${status}`;
@hatanaka-akihiro

2020-09-30 03:19 UTC, hatanaka-akihiro commented on box-file-upload.xml
> +    throw `failed to upload\nstatus: ${status}`;
エラー通知メールを考慮しての話です。
エラー通知メールには、ログは含まれず、エラーメッセージのみが含まれます。

2020-09-30 04:13 UTC, merged