T7428: kintone: 選択肢データの一括取得　の作成
Questetra/Addon-XML pull request #223
Opened 2020-09-28 05:38 UTC by tatsumiQ

@hatanaka-akihiro さん
レビューをお願いいたします。

2020-09-28 08:15 UTC, hatanaka-akihiro requested changes

2020-09-28 08:15 UTC, hatanaka-akihiro commented on kintone-choice-download.xml
> +  const fieldsString = Array.from( params.fields ).map( (field, i) => `fields[${i}]=${field}` ).join('&');
Array.from は mapFn を引数に取れるので、```map()``` は要らないかもしれません。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/from

2020-09-28 08:15 UTC, hatanaka-akihiro commented on kintone-choice-download.xml
> +/** 選択肢 ID と選択肢ラベルの配列の値をチェックし、以下の場合はエラーとする
/** の後ろの改行忘れか。
他の関数とコメントの書き方が異なる。
細かい話です。

2020-09-29 02:10 UTC, tatsumiQ commented
@hatanaka-akihiro さん
指摘いただいた点を修正しました（１つ目はコピペ後の修正漏れでした。すみません）。
ご確認のほど、お願いいたします。

2020-09-29 02:33 UTC, merged