Create box-folder-create-collaboation.xml
Questetra/Addon-XML pull request #224
Opened 2020-10-05 03:00 UTC by suese-sayaka

畠中さん

ソースコードを新規作成しました。
ご確認をお願いいたします。

2020-10-05 04:33 UTC, hatanaka-akihiro requested changes

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    <label locale="ja">C3: 指定ユーザのメールアドレス(Box)</label>
「編集者とする Box ユーザのメールアドレス」という表現にしては？

- 「ユーザ」よりも「Box ユーザ」の方が、「QBPMS ユーザ」との混同が無い。
- 設定で「指定」するのは当たり前で、「何の指定をするか」具体的な方が良い。

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  let linesArray = emailaddress.split(",");
「改行区切り」にも対応して欲しい。
文字型複数行では、カンマ区切りより改行区切りの方がスッキリするから。

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  }
emailAddress の配列にするところまで含めて、別関数 or ```decideEmailaddress()``` の中に入れた方が良いです。

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +<script><![CDATA[
基本的な概念の確認です。
「共有リンク」と同じく、「コラボレーション」も、Box フォルダ１つにつき、最大 1 つでしょうか。

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
このエラーが発生するのは、具体的にはどのような使い方をした場合でしょうか。

「エラーを無視する」ことも考えられるわけで、確認したい次第です。

2020-10-05 04:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    }else if (status >= 300) {
300 未満で、「処理失敗ではない」とみなせる場合があるということでしょうか。

2020-10-06 00:31 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    <label locale="ja">C3: 指定ユーザのメールアドレス(Box)</label>
「編集者とする Box ユーザのメールアドレス」という表現に修正しました。

2020-10-06 00:31 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  let linesArray = emailaddress.split(",");
「改行区切り」と「カンマ区切り」の両方に対応するよう修正しました。

2020-10-06 00:32 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  }
decideEmailaddress() の中に入れました。

2020-10-06 00:33 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +<script><![CDATA[
フォルダ１つにつき、1ユーザにつき１コラボレーションです。
フォルダ内に３ユーザがコラボレーションされている場合、コラボレーションIDは３つあります。

2020-10-06 00:38 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
既にコラボレーションされているユーザは、エラーにしました。
（「既に作成されている共有リンクはエラーにする」と同じかんじにしました。

2020-10-06 00:51 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    }else if (status >= 300) {
エラー一覧を見直し、400以上に修正しました。

2020-10-12 07:27 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  if(emailaddress === "" ||emailaddress === null) {
decideEmailaddress() の中に入れるべき。
チェックタイミングも含めて、考えること。

2020-10-12 07:27 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  }
folderId のチェックも、decideEmailAddress() にあわせて、 decideFolderId() 内に入れる。

2020-10-12 07:27 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
「既に作成されている共有リンクはエラーにする」と同じにするなら、最初にコラボレーションの有無を調べて、「コラボレーションが存在するならエラー」の方が良いです。

このやり方だと、すでにコラボレーションが存在しても、ユーザが違えばエラーになりません。

2020-10-12 07:27 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  }
全体的な if 文の構成として、違和感があります。

```
if (status === 201) {
  ...
}
if (status !== 201) {
  ...
}
```

2020-10-12 07:27 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    }else if (status >= 300) {
今の分岐の形だと、400 未満で 201 でない場合、すべて処理失敗ではない／処理成功になります。

それで良いのでしょうか。

2020-10-12 07:29 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +<script><![CDATA[
「権限の付与」と同じような感じなのでしょうか。理解できたと思います。

2020-10-15 05:48 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  if(emailaddress === "" ||emailaddress === null) {
修正しました。

2020-10-15 05:49 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  }
修正しました。

2020-10-15 05:49 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  }
修正しました。

2020-10-15 05:51 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
最初にコラボレーションの有無を調べる方法は無いと思います。
Boxのフォルダオブジェクトにも、ユーザオブジェクトにも、コラボレーションの情報がありません。

ユーザひとりひとりにそのフォルダのコラボレーションIDが作成されるので、ユーザが違ってエラーにならなくて大丈夫だと思います。

2020-10-15 05:52 UTC, suese-sayaka commented
畠中さん
修正したのでご確認ください。
OAuth2設定名も変更いたしました。

2020-10-15 05:57 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
> 最初にコラボレーションの有無を調べる方法は無いと思います。

https://ja.developer.box.com/reference/get-folders-id-collaborations/

2020-10-15 06:04 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    throw `Failed to create collboration, user(${emailaddress})_already_collaborator \n status: ${status}\n${responseTxt}`;
responseTxt を、エラーに含めるのはやめよう。
エラーの内容はエラー通知メールに含まれるが、responseTxt は大きいから。
エラー時に、ログ出力するのは良いです。

2020-10-15 06:04 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  }
異常 (status !== 201) を先に持ってきた方が良いです。
処理が打ち切られるので、else が要らなくなります。

```
if (status !== 201) {
  if (status === 400 && ... ) {
    throw
  }
  throw
}

if (jsonRes['invite_email'] === null) {
  ...
```

2020-10-15 06:06 UTC, hatanaka-akihiro requested changes

2020-10-15 06:06 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    <label locale="ja">C1: 認証設定</label>
気を利かしてくれたのだと思いますが、Box は "OAuth2 設定" のままで良いと思います。

kintone のアイテムは OAuth2 を使っていないので、名前を変えました。

2020-10-19 05:45 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
ありがとうございます。
コラボレーションリストを取得する関数　「getCollaborationList」を追加し、全体を見直しました。

まず「getCollaborationList」でリクエストをひとつ使ってしまうので、今回のソースコードでは、アドオンでは10人のコラボレーションが作成されません。
9人作成（招待）され、10人目で「HTTP requests must be up to 10」というエラーが出ます。
これでもよろしいでしょうか？

その場合、37行目の処理
  if (numOfLines > httpClient.getRequestingLimit()){
  	throw "Number of Email address is over the limit."
  }
を、httpClient.getRequestingLimit()-1 として、「Number of Email address is over the limit」のエラーが出るようにした方がよいでしょうか

2020-10-19 05:47 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  engine.log(`${responseTxt} \n`);
修正しました

2020-10-19 05:47 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    throw `Failed to create collboration, user(${emailaddress})_already_collaborator \n status: ${status}\n${responseTxt}`;
修正しました

2020-10-19 05:48 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    <label locale="ja">C1: 認証設定</label>
意味がわかりました。ありがとうございます。

2020-10-19 05:48 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
> 9人作成（招待）され、10人目で「HTTP requests must be up to 10」というエラーが出ます。
> これでもよろしいでしょうか？

特に問題ありません。


> その場合、37行目の処理
> ...
> を、httpClient.getRequestingLimit()-1 とした方がよいでしょうか

```httpClient.getRequestingLimit()-1``` とした方が良いです。

2020-10-19 05:48 UTC, suese-sayaka commented
畠中さん
ソースコードを修正しました。ご確認をお願いいたします。

2020-10-20 04:48 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
httpClient.getRequestingLimit()-1 に修正しました。

2020-10-20 04:48 UTC, suese-sayaka commented
畠中さん
ソースコードを修正しました。ご確認をお願いいたします。

2020-10-20 05:23 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
「フォルダにコラボレーションが存在するならエラー」なので、「getCollaborationList() の返り値が空でない時点でエラー」だと思います。「あるユーザについて、コラボレーションが存在するならエラー」になっています。

また「コラボレーションがない」ことを前提にするので、judgeEmailAddress は要らないと思います。

2020-10-20 05:28 UTC, hatanaka-akihiro requested changes

2020-10-20 05:28 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  engine.log(`${responseTxt}`);
正常時の、レスポンスのログ出力が残っています。

2020-10-20 05:28 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  }
ここで、メールアドレスの重複チェックもした方が良いかな。

2020-10-26 02:58 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  }
メールアドレスの重複チェック処理を加えました。

2020-10-26 03:00 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  engine.log(`${responseTxt}`);
このリストのログを出力しておくことで、コラボレーション作成関数「createCollaboration()」で処理失敗したときに、原因を調べやすいかと思ったのですが、どうでしょうか。

2020-10-26 06:33 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
@suese-sayaka 

この件が、抜けています。

2020-10-27 03:29 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
@hatanaka-akihiro  さん
getCollaborationList()　で、それぞれのユーザのコラボレーションIDがあれば返ってくるので（5人コラボレーションされていたらコラボレーションIDは5個）、「あるユーザについて、コラボレーションが存在するならエラー」にしないといけないと思ったので、judgeEmailaddress() の処理を追加しました。

2020-11-09 03:30 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +        throw `Failed to create collboration, user_already_collaborator \n status: ${status}\n${responseTxt}`;
@hatanaka-akihiro  さん

既にコラボレーションが存在するフォルダはエラーになるよう、処理を修正しました。

2020-11-09 07:43 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    <label>C1: OAuth2 Setting Name</label>
履歴を見ると、"Name" "名" は、一度、取っています。

それがもとに戻っています。

作業の仕方がまずいかもしれません。ちょっとつらい、ミスです。

2020-11-09 07:43 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  throw `Failed to create collboration, this folder(ID:${folderId}) is already collaborated.`;
"Failed to ...collaboration. This folder..."

「エラーメッセージは１文」と制約はありません。２文で良いかと。

2020-11-09 07:43 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  engine.log(`${responseTxt}`);
要らないのでは？

createCollaboration() で役に立つのは、具体的にどのような場合ですか？

2020-11-09 08:05 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    <label>C1: OAuth2 Setting Name</label>
t7246 ブランチの履歴を見て、何がまずかったか解りました。

末瀬さんが気を利かして「認証設定」に変更してくれましたが、「もともままで良い」という話があったと思います。

戻す際のミスのようです。

2020-11-26 02:49 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    <label>C1: OAuth2 Setting Name</label>
すみません、修正しました。

2020-11-26 02:49 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  throw `Failed to create collboration, this folder(ID:${folderId}) is already collaborated.`;
２文に修正しました。

2020-11-26 02:51 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  engine.log(`${responseTxt}`);
既にコラボレーションされているメールアドレスの有無をチェックしていた頃のログ出力処理を残したままでした。
削除しました。

2020-11-26 02:51 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。抜粋で動作確認済です。
よろしくお願いします。

2020-11-26 07:26 UTC, hatanaka-akihiro requested changes

2020-11-26 07:26 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  *  @return {String}  コラボレーションリストの オブジェクト
引数のコメントが抜けているようです。

あとコメントの終わりと、function の間に空行を入れないように。

2020-11-26 07:26 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  //create collaboration on box
コメントの形式が、他の関数と異なります。

2020-11-26 07:26 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  const token = configs.get("conf_OAuth2");
```authSetting()``` を使うように変えたのは良いです。

```token``` という変数名が．．．
「参照する認証設定」を保持している変数なので。

2020-11-26 07:31 UTC, hatanaka-akihiro requested changes

2020-11-26 07:31 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    throw `Failed to get folder information \n status: ${status}`;
細かいですが、149 行目と形式が異なっています。

2020-11-26 07:31 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  throw `Failed to create collboration \n status: ${status}`;
ここも、少し上とエラーメッセージの形式が異なっています。

2020-11-26 07:31 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +    throw `Failed to get folder information \n status: ${status}`;
あと先にステータスチェックをした方が良いです。

200 でない場合に、レスポンスを解析する意味が無いので。

2020-11-26 07:31 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  throw `Failed to create collboration \n status: ${status}`;
ここも先にステータスをチェックした方が良いです。

201 でない場合に、レスポンスを解析する意味が無いので。

2020-11-30 00:43 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  *  @return {String}  コラボレーションリストの オブジェクト
引数のコメントを記載しました。
空行を削除しました。

2020-11-30 00:43 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  //create collaboration on box
コメントの形式を修正しました。

2020-11-30 00:43 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  const token = configs.get("conf_OAuth2");
修正しました。

2020-11-30 00:45 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +    throw `Failed to get folder information \n status: ${status}`;
形式を修正しました。
先にステータスチェック処理をするよう修正しました。

2020-11-30 00:45 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  throw `Failed to create collboration \n status: ${status}`;
形式を修正しました。
先にステータスチェック処理をするよう修正しました。

2020-11-30 00:45 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。
よろしくお願いします。

2020-11-30 01:10 UTC, hatanaka-akihiro requested changes

2020-11-30 01:10 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  engine.log(`status: ${status}\n`);
最後の \n は要らないです。

2020-11-30 01:10 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  engine.log(`status: ${status}\n`);
プログラムの流れ上、201 であることが確定しているので、要らないようにも思います。201 で無かったら、ここまで来ない。

2020-11-30 01:10 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  * @param {String} emailaddress[i] コラボレーションするメールアドレス
この関数の仕様として考えると、[i] は要らないです。
この関数を使用する際に、渡す変数のことは考えない。

2020-11-30 01:10 UTC, hatanaka-akihiro commented on box-folder-create-collaboation.xml
> +  * @param {Numeric} i+1  メールアドレスカウント番号
```i+1``` というのも、この関数の仕様として考えると、訳が分らないので、要らないです。

「メールアドレスカウント番号」というのも、今一つ。あくまで、この関数の仕様として、どういう表現が適当か、考えてましょう。

2020-11-30 01:56 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  engine.log(`status: ${status}\n`);
削除しました。

2020-11-30 01:56 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  * @param {String} emailaddress[i] コラボレーションするメールアドレス
修正しました。

2020-11-30 01:56 UTC, suese-sayaka commented on box-folder-create-collaboation.xml
> +  * @param {Numeric} i+1  メールアドレスカウント番号
修正しました。

2020-11-30 01:56 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。

2020-12-01 00:52 UTC, merged