Update box-folder-link-create.xml
Questetra/Addon-XML pull request #226
Opened 2020-10-06 04:02 UTC by suese-sayaka

畠中さん
ソースコードを更新しました。よろしくお願いします。

・有効期限を設定していない場合、パスワードを設定していない場合の注意書きを「summary」に追加

・フォルダに共有リンクが無い場合は共有リンクを作成し、既に共有リンクがある場合はエラーにする処理を追加

・共有リンクが既にあるかを調べるためのフォルダ情報取得処理を追加

・関数化

2020-10-06 04:16 UTC, hatanaka-akihiro requested changes

2020-10-06 04:16 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +  if (status >= 400) {
レスポンスは 200 でなかったら、全てエラーにするべきでは？

https://developer.box.com/reference/get-folders-id/

2020-10-06 04:16 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +  if (status >= 400) {
エラーとして扱う範囲を狭くした理由は？

2020-10-06 04:16 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +  if (existingUrl === null){
エラーチェックを先に持ってきて処理を終わらせる形の方が、コードがすっきりします。

```
if (existingUrl !== null) {
  ...
  throw error;
}

const sharedLinkUrl = createSharedLink(...);
```

2020-10-08 04:32 UTC, suese-sayaka commented on box-folder-link-create.xml
> +  if (status >= 400) {
「200以外であればエラーにする」　処理に修正しました。

2020-10-08 04:34 UTC, suese-sayaka commented on box-folder-link-create.xml
> +  if (status >= 400) {
ファイルコピーのものと流用してしまっていたので、400以上に変更したのですが、200以外ありませんでしたので
「200以外であればエラーにする」　処理に修正しました。

2020-10-08 04:34 UTC, suese-sayaka commented on box-folder-link-create.xml
> +  if (existingUrl === null){
修正しました。

2020-10-12 07:44 UTC, hatanaka-akihiro requested changes

2020-10-12 07:44 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +   }else{
この else は要らないです。

if の方が throw で終わってしまうから。

2020-10-12 07:44 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +}
main() の中で、getFolderInformation() と createSharedLink() が定義されている形になっているでしょうか。

必要性がなければ、main() の外に定義している方が良いです。

2020-10-19 02:53 UTC, suese-sayaka commented on box-folder-link-create.xml
> +   }else{
修正しました。

2020-10-19 02:53 UTC, suese-sayaka commented on box-folder-link-create.xml
> +}
getFolderInformation() と createSharedLink() を、main() の外に定義しました。

2020-10-19 02:54 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。（関係するテストも確認しました）
ご確認をお願いいたします。

2020-10-19 05:36 UTC, hatanaka-akihiro requested changes

2020-10-19 05:36 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +    const error = `Failed to get folder information`;
レスポンス全体をエラーメッセージに入れなくて良いですが、ステータスは短いので入れて良いです。

入れたほうが良いです。

2020-10-19 05:36 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
> +    sharedlinkUrl = createSharedLink(token, folderId, unsharedDate, password);
sharedLinkUrl は、ここで const 宣言で大丈夫では？

2020-10-19 05:36 UTC, hatanaka-akihiro commented on box-folder-link-create.xml
>    token = httpClient.getOAuth2Token(configs.get("OAuth2"));
token は、ここで const 宣言で大丈夫では？

2020-10-20 02:52 UTC, suese-sayaka commented on box-folder-link-create.xml
> +<summary locale="ja">Box 上のフォルダにアクセスできる URL を作成します （有効期限の指定が無い場合は無期限で、パスワードの指定が無い場合はパスワード要求無しで作成します）</summary>
修正しました。

2020-10-20 02:52 UTC, suese-sayaka commented on box-folder-link-create.xml
> +    const error = `Failed to get folder information`;
修正しました。

2020-10-20 02:52 UTC, suese-sayaka commented on box-folder-link-create.xml
> +    sharedlinkUrl = createSharedLink(token, folderId, unsharedDate, password);
修正しました。

2020-10-20 02:52 UTC, suese-sayaka commented on box-folder-link-create.xml
>    token = httpClient.getOAuth2Token(configs.get("OAuth2"));
修正しました。

2020-10-20 02:53 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しましたので、ご確認をお願いします。

2020-10-20 05:18 UTC, merged