ファイル新規作成
Questetra/Addon-XML pull request #228
Opened 2020-10-08 01:38 UTC by chica-non

畠中さん
「7079 : Google スプレッドシート: ファイル作成」のアドオンを作成しました。ご確認よろしくお願いします。

2020-10-08 07:04 UTC, hatanaka-akihiro requested changes
レビューをしました。

同じことが指摘できる箇所は、省略しています。

2020-10-08 07:04 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +  const userId = configs.get("Conf_UserID");
以下で動くはず。これが推奨する形です。

```
const quser = configs.getObject('Conf_UserID');
```

2020-10-08 07:04 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +  if (fileName == "" || fileName == null) {
```==``` ではなく、```===``` を使用するように。

2020-10-08 07:04 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    jsonRes["parents"] = [ parentFolderId + '' ];
もう ``` + ''``` をしなくて良いです。String であることを確実にしたいなら
```String(parentFolderId)``` の方がベター。

2020-10-21 02:09 UTC, hatanaka-akihiro requested changes

2020-10-21 03:29 UTC, chica-non commented on google-sheets-file-create.xml
> +    const error = `Failed to update sheet title \n status: ${status}\n ${responseTxt}`;
修正しました。ログの位置を変更しました。

2020-10-21 03:30 UTC, chica-non commented
畠中さん
修正しました。ご確認よろしくお願いします。

2020-10-26 02:02 UTC, hatanaka-akihiro requested changes

2020-10-26 02:02 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +  * @param {String} fileName  ファイル名
return が抜けている。
createFile() は return があるかと。

2020-10-26 02:08 UTC, hatanaka-akihiro requested changes

2020-10-26 02:08 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +  <config name="Conf_ParentFolderId" el-enabled="true">
Conf_ParentFolderId は、

form-type="SELECT" editable="true" select-data-type="STRING_TEXTFIELD”

に変更をお願いします。要は「文字型単一行データ項目か、固定値で指定」。

昔はこれができなかったので el-enabled=true にしたものが多いのですが、最近は「本当に柔軟に指定して良いもの以外には使わない」ように変わってきています。

2020-10-28 03:58 UTC, chica-non commented on google-sheets-file-create.xml
> +  * @param {String} fileName  ファイル名
retuneのコメントを追加しました。

2020-10-28 03:58 UTC, chica-non commented on google-sheets-file-create.xml
> +  <config name="Conf_ParentFolderId" el-enabled="true">
指摘の通りに修正しました。

2020-10-28 03:58 UTC, chica-non commented
畠中さん
ソースを修正しました。ご確認よろしくお願いします。

2020-10-28 05:34 UTC, merged