Create box-folder-link-delete
Questetra/Addon-XML pull request #238
Opened 2020-11-09 06:08 UTC by suese-sayaka

@hatanaka-akihiro  さん
ソースコードを作成しました。動作確認済です。
よろしくお願いします。

フォルダが既に共有リンクされているか調べ、共有リンクがある場合は削除する。
共有リンクが無い場合はエラーにする。

2020-11-09 09:07 UTC, hatanaka-akihiro requested changes

2020-11-09 09:07 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +    throw error;
エラーメッセージに、レスポンス全体 (responseTxt) は含めない。長くなるから。
ログに記録するのは OK。

2020-11-09 09:07 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  engine.log(responseTxt); //function deleteSharedLink()のエラー調査用に出力
正常系で、レスポンス全体のログ出力はしないように。

役立つところがあるなら、その部分だけログ出力するように。

2020-11-09 09:07 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +<label>Box: Delete Shared Link to Folder</label>
"to Folder" というのは、おかしいと思いました。

2020-11-09 09:07 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +<summary locale="ja">Box 上の指定フォルダの共有リンク URL を削除します （共有リンクが無い場合は削除できません）</summary>
「無い場合は削除できません」は要らないと思いました。当たり前の話なので。
「無い場合は、エラーとなります」なら解ります。

2020-11-09 09:07 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +    <label locale="ja">C1: OAuth2 設定名</label>
"Name" "名" は要らない。

2020-11-16 02:15 UTC, suese-sayaka commented on box-folder-link-delete
> +    throw error;
修正しました。

2020-11-16 02:16 UTC, suese-sayaka commented on box-folder-link-delete
> +  engine.log(responseTxt); //function deleteSharedLink()のエラー調査用に出力
もう一度考えなおし、ログ出力をしないようにしました。
（エラーになる場合は、共有リンクが無いので、その情報は不要だと気づきました）

2020-11-16 02:17 UTC, suese-sayaka commented on box-folder-link-delete
> +<label>Box: Delete Shared Link to Folder</label>
「of Folder」に修正しました。

2020-11-16 02:17 UTC, suese-sayaka commented on box-folder-link-delete
> +<summary locale="ja">Box 上の指定フォルダの共有リンク URL を削除します （共有リンクが無い場合は削除できません）</summary>
「無い場合は、エラーとなります」に修正しました。

2020-11-16 02:17 UTC, suese-sayaka commented on box-folder-link-delete
> +    <label locale="ja">C1: OAuth2 設定名</label>
修正しました。

2020-11-16 02:18 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しましたので、ご確認をお願いいたします。
抜粋で、動作確認済です。

2020-11-17 01:59 UTC, hatanaka-akihiro requested changes

2020-11-17 01:59 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  token = httpClient.getOAuth2Token(configs.get("OAuth2"));
OAuth2 がらみで、12.3 からスクリプトの仕様を変更します。
未テストですが、このアイテムは標準アイテムにもなっていないものなので、変更を加えます。

これまで
```javascript
const token = httpClient.getOAuth2Token(configs.get("OAuth2"));
httpClient.begin().bearer(token)...
```

となっていたコードを

```javascript
httpClient.begin().authSetting(configs.get("OAuth2"))...
```

に変更してください。
```getOAuth2Token()``` ```bearer()``` 両方とも使わず、```authSetting()``` 1つに置き換えます。

2020-11-17 01:59 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +    <label locale="ja">C1: OAuth2 設定 </label>
他の変更があるので、ついでに。
最後のスペース不要。日英のラベル両方とも。

2020-11-24 02:06 UTC, suese-sayaka commented on box-folder-link-delete
> +  token = httpClient.getOAuth2Token(configs.get("OAuth2"));
変更しました。

2020-11-24 02:07 UTC, suese-sayaka commented on box-folder-link-delete
> +    <label locale="ja">C1: OAuth2 設定 </label>
最後のスペースを削除しました。

2020-11-24 02:07 UTC, suese-sayaka commented
畠中さん
ソースコードを修正ましたのでご確認をお願いいたします。

2020-11-24 06:45 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  token = httpClient.getOAuth2Token(configs.get("OAuth2"));
サンプルではこのように記載しましたが、実際の実装では、他との統一性など考慮するようにしましょう。

これまで通り、configs へのアクセスは ```main()``` の中で行い、```getFolderInformation()``` 等の関数には、その値のみ渡すほうが良いと思います。

2020-11-24 06:47 UTC, hatanaka-akihiro requested changes

2020-11-24 06:47 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +    .authSetting(configs.get("OAuth2"))
実際の実装では、サンプルをそのまま採用しないように。他との統一性など、考慮するようにしましょう。

これまで通り、configs へのアクセスは main() の中で行い、getFolderInformation() 等の関数には、その値のみ渡すほうが良いと思います。

2020-11-26 01:46 UTC, suese-sayaka commented on box-folder-link-delete
> +    .authSetting(configs.get("OAuth2"))
修正しました。

2020-11-26 01:46 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。抜粋で動作確認済です。
よろしくお願いします。

2020-11-26 07:20 UTC, hatanaka-akihiro requested changes

2020-11-26 07:20 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  const token = configs.get("OAuth2");
変数名の token は、実際に持つ値の意味と違いすぎると思います。

2020-11-26 07:20 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  * @return {String}  フォルダの共有リンクオブジェクト
最近の他のものを見ると、関数の引数についてもコメントに記載しているようです。

2020-11-26 07:20 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  *  Delete Shared Link to Folder on Box  共有リンク削除
最近の他のものを見ると、関数の引数についてもコメントに記載しているようです。

2020-11-30 00:08 UTC, suese-sayaka commented on box-folder-link-delete
> +  const token = configs.get("OAuth2");
修正しました

2020-11-30 00:09 UTC, suese-sayaka commented on box-folder-link-delete
> +  * @return {String}  フォルダの共有リンクオブジェクト
コメントを記載しました

2020-11-30 00:09 UTC, suese-sayaka commented on box-folder-link-delete
> +  *  Delete Shared Link to Folder on Box  共有リンク削除
コメントを記載しました

2020-11-30 00:09 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。
よろしくお願いします。

2020-11-30 00:56 UTC, hatanaka-akihiro requested changes

2020-11-30 00:56 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  * @param {String} folderId  共有リンクを削除したいフォルダのID
この関数の仕様として考えると、folderID が「共有リンクを削除したいフォルダの ID」というのは変です。

2020-11-30 00:58 UTC, hatanaka-akihiro requested changes

2020-11-30 00:58 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  * Get Folder Information on Box  フォルダが既に共有リンク作成されているか調べる
細かいですが、日本語がおかしいです。
「共有リンク作成されているか」

2020-11-30 00:58 UTC, hatanaka-akihiro commented on box-folder-link-delete
> +  * @param {String} folderId  共有リンクを削除したいフォルダのID
この関数の仕様として考えると、folderID が「共有リンクを削除したいフォルダの ID」というのは変です。共有リンクを削除する機能は持っていませんので。

2020-11-30 01:33 UTC, suese-sayaka commented on box-folder-link-delete
> +  * Get Folder Information on Box  フォルダが既に共有リンク作成されているか調べる
修正しました。

2020-11-30 01:33 UTC, suese-sayaka commented on box-folder-link-delete
> +  * @param {String} folderId  共有リンクを削除したいフォルダのID
修正しました。

2020-11-30 01:34 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。

2020-12-01 00:50 UTC, merged