T7516：Gmail: メール取得　未設定の保存先データ項目があっても動作するように
Questetra/Addon-XML pull request #245
Opened 2020-11-26 06:22 UTC by tatsumiQ

以下の点を修正しました。
* 未設定の保存先データ項目があっても動作するように
* To/Cc/Bcc のメールアドレス、表示名一覧が To → Cc → Bcc の順になるように

未対応事項
* アイコンの設定（IconMaker への登録待ち）

2020-11-26 07:55 UTC, hatanaka-akihiro requested changes
OAuth2 がらみの処理。今は以下のようになっていると思います。
```
const auth = configs.get("conf_auth");
const apiToken = httpClient.getOAuth2Token( auth );
httpClient.begin().bearer( apiToken )
```

これを以下の形に変えてもらえますか。
```
const auth = configs.get("conf_auth");
httpClient.begin().authSetting(auth)
```

2020-11-27 01:53 UTC, tatsumiQ commented
@hatanaka-akihiro さん
> これを以下の形に変えてもらえますか。
> 
> ```
> const auth = configs.get("conf_auth");
> httpClient.begin().authSetting(auth)
> ```

修正しました。正常系の動作に問題がないことを確認済みです。

2020-12-25 05:58 UTC, hatanaka-akihiro requested changes

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>    return messageId;
開発中に、```editable="true"``` にしていた？その名残りですか？
必須項目だし、```return engine.findData(messageIdDef);``` でも良いはずなので。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +      if ( dataItemNumList.indexOf( dataItemNum ) !== -1 ) { // データ項目番号が重複していればエラー
```includes()``` が使えないでしょうか。
配列ではなく、```Set``` を使っても良いと思います。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +  // Subject が複数件ある場合は最初の Subject ヘッダを採用する
From ヘッダは必ず 1 件なのに、Subject は複数ありうるのか。たんなる感想です。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +    if ( headerNameLower === "from" ) {
javascript は 文字列で switch が使える。
どちらが解りやすいか、なんとも言えないけど。

```
switch(headerNameLower) {
  case 'from':
    ...
  case 'to':
  case 'cc':
  case 'bcc':
    ...
  case 'date':
    ...
  case 'subject':
    ...
}
```

```if ... if ...``` より
```if ... elseif``` の方が、処理は効率的。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +    let headerNameLower = header.name.toLowerCase();
const にしておいて、変化しないことを保証しておいた方が良いと思いました。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>    const dispositionHeaders = part.headers.filter( header => {
```find()``` で良いように思いました。
```filter()``` だと全要素調査すると思う。
```find()``` だと最初に見つけた時点で打ち切り。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>    const contentTypeHeaders = part.headers.filter( header => {
```find()``` で良いように思いました。以下略。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +    return "application/octet-stream"; // Default
2 箇所で同じ定数が出てきたので、関数内で良いので、const 定義しておくのが良いかな。

2020-12-25 05:58 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>      if ( attachment.body.data === undefined ) { // data がなければ、attachmentId から data を取得して格納
好みもあるけど、インデントはあまり深くならない方が良い。

なので、

```if ( attachment.body.data !== undefined ) { return; }```

「data があれば、以降の処理を行わない」という形の方が良い。

2020-12-28 01:28 UTC, tatsumiQ commented on gmail-message-get.xml
>    return messageId;
他の定義ファイルを下敷きに編集したため、不要な処理が残ってしまっていました。
修正しました。

2020-12-28 04:46 UTC, hatanaka-akihiro requested changes

2020-12-28 04:46 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +  * @return {String} disposition  "Content-Disposition" ヘッダの値（ヘッダが無い場合は undefined）
ヘッダが無い場合は null では？

2020-12-28 04:46 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +  const dispositionHeader = part.headers.find( header => header.name.toLowerCase() === "content-disposition" );
こちらは dispositionHeader が undefined の場合の処理を入れなくて大丈夫なのだろうか。

2020-12-28 07:30 UTC, merged