Create box-file-download.xml
Questetra/Addon-XML pull request #255
Opened 2020-12-22 00:44 UTC by suese-sayaka

畠中さん

ソースコードを作成しました。
よろしくお願いします。

2020-12-22 04:51 UTC, hatanaka-akihiro requested changes

2020-12-22 04:51 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  }
ファイル名のチェックは any-website-file-download と同じく、基本、Questetra BPM Suite に任せるで良いと思いました。

もし現時点の形で行くなら、`getBoxFileName()` で取得したファイル名に対して、チェックをしていないのもおかしい。(Box のファイル名が、Questetra BPM Suite で OK とも限らない)

2020-12-22 04:51 UTC, hatanaka-akihiro commented on box-file-download.xml
> +function boxFileDownload(oauth2, fileId){
関数名は動詞の方が適当です。
`downloadBoxFile` なら理解できます。

2020-12-22 04:51 UTC, hatanaka-akihiro commented on box-file-download.xml
> +    <label>C4: File type data item to add the downloaded files</label>
ダウンロードするファイルは１つだけなので、単数形 "downloaded file" の方が適当

2020-12-22 04:51 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  let file = engine.findData( fileDef );
ファイルは複数ありえるので、`files` という変数名の方がベター。`fileList` も OK。

2020-12-22 04:51 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  engine.setData( fileDef, file );
私なら、ダウンロード処理を除いて、```findData``` から ```setData``` まで、１つの関数にまとめます。

2020-12-28 01:46 UTC, suese-sayaka commented on box-file-download.xml
> +  engine.setData( fileDef, file );
@hatanaka-akihiro  さん
findData から setData まで、１つの関数にまとめようと思い、１つにまとめた関数の中に、

「 let files = engine.findData( filesDef );」

を入れたのですが、この部分でエラーが出ます。「スクリプトエラーが発生しました。  at line number 75」

engine.findDataは、メイン関数内でないといけないとかのルールはありますか？
「」

2020-12-28 01:57 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  engine.setData( fileDef, file );
> engine.findDataは、メイン関数内でないといけないとかのルールはありますか？

ありません。

"filesDef" というのが気になりました。

2020-12-28 04:24 UTC, suese-sayaka commented on box-file-download.xml
> +  }
すみません、Box側に処理するアイテムと混同してしまいました。ファイルチェックの処理は、Box側でのものなので、削除しました。

2020-12-28 04:24 UTC, suese-sayaka commented on box-file-download.xml
> +  let file = engine.findData( fileDef );
修正しました。

2020-12-28 04:24 UTC, suese-sayaka commented on box-file-download.xml
> +  engine.setData( fileDef, file );
ありがとうございました。

ひとつの関数にまとめました。

2020-12-28 04:25 UTC, suese-sayaka commented on box-file-download.xml
> +    <label>C4: File type data item to add the downloaded files</label>
修正しました。

2020-12-28 04:25 UTC, suese-sayaka commented on box-file-download.xml
> +function boxFileDownload(oauth2, fileId){
修正しました。

2020-12-28 04:26 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。よろしくお願いします。

2020-12-28 05:02 UTC, hatanaka-akihiro requested changes

2020-12-28 05:02 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  saveFile( fileName, response, files );
```
function processFile(fileName, oauth2, fileId);
  const response = downloadBoxFile(oauth2, fileId);
  saveFile(fileName, response);
}
```

2 行だけなので、関数を削除して、main() に吸収させるかな。

2020-12-28 05:02 UTC, hatanaka-akihiro commented on box-file-download.xml
> +  saveFile( fileName, response, files );
configs へのアクセスは main() の中で行い、saveFile は
```
function saveFile(filesDef, fileName, response){
```

が良いかもしれない。もっと言うと

```
function saveFile(filesDef, fileName, contentType, content){
```

が良いかもしれない。

2020-12-29 03:34 UTC, suese-sayaka commented on box-file-download.xml
> +function processTheFile( fileName, oauth2, fileId ) {
関数を削除しました。

2020-12-29 03:34 UTC, suese-sayaka commented on box-file-download.xml
> +  saveFile( fileName, response, files );
修正しました。

2020-12-29 03:35 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。よろしくお願いします。

2020-12-29 04:12 UTC, hatanaka-akihiro requested changes

2020-12-29 04:12 UTC, hatanaka-akihiro commented on box-file-download.xml
> +function downloadBoxFile(oauth2, fileId){
response 全体ではなく、contentType と content (response.getResponse()) だけを返すように改良してみてください。

レスポンスの解析まで含めて、関数の中に閉じる方がベターです。

2020-12-29 04:12 UTC, hatanaka-akihiro commented on box-file-download.xml
> +function downloadBoxFile(oauth2, fileId){
API の呼び出しは、「レスポンスの解析まで含めて一連の処理」と考えるのが良いので。

2021-01-04 01:20 UTC, suese-sayaka commented on box-file-download.xml
> +function downloadBoxFile(oauth2, fileId){
ありがとうございます。
修正しました。

2021-01-04 01:21 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。よろしくお願いします。

2021-01-04 02:31 UTC, merged