change engine from Nashorn to GraalJS
Questetra/Addon-XML pull request #259
Opened 2021-01-12 05:35 UTC by chica-non

畠中さん

ソースを修正しました。ご確認お願いします。
70～73行は削除した方がよいでしょうか？

2021-01-12 05:56 UTC, hatanaka-akihiro requested changes

2021-01-12 05:56 UTC, hatanaka-akihiro commented on google-sheets-row-append.xml
> +  accessLog += `${response.getResponseAsString()}\n`;
レスポンス全体をログに含めるのは、エラーの時だけにしてください。
またエラーメッセージには、レスポンス全体を含めないように。含めるのは、ステータスコードまで。レスポンス全体を含めると、ログのサイズが大きくなりやすいので。

つまり以下のような感じになります。

```
if (httpStatus !== 200) {
  engine.log(response.getResponseAsString());
  throw `Http Status is not 200: ${httpStatus}`;
}
```

2021-01-12 05:56 UTC, hatanaka-akihiro commented on google-sheets-row-append.xml
> +<label locale="ja">Google スプレッドシート: 行追加★★★★★★修正日付★★</label>
開発をしやすくするためのラベル変更でしょうか。
元に戻し忘れています。

2021-01-12 05:56 UTC, hatanaka-akihiro commented on google-sheets-row-append.xml
>    if( response.getStatusCode() != 200 ){
```httpStatus``` および ```!==``` を使った方が良いです。

2021-01-12 05:56 UTC, hatanaka-akihiro commented
> 70～73行は削除した方がよいでしょうか？

そうですね。Copyright とか残しておく理由はないので、削除しておいてください。

2021-01-15 05:50 UTC, chica-non commented
畠中さん
指摘箇所を修正しました。ご確認よろしくお願いします。

2021-01-18 07:13 UTC, merged