Update slack-chat-post-bots.xml
Questetra/Addon-XML pull request #275
Opened 2021-02-04 05:36 UTC by suese-sayaka

@hatanaka-akihiro  さん
関数分割しました。
よろしくお願いいたします。

2021-02-05 02:28 UTC, hatanaka-akihiro requested changes

2021-02-05 02:28 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
== ではなく === の方が良いと思いますが、比較対象の値は null ではないと思います。

2021-02-05 02:28 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
>      attachAdd(attachment, "TitleLink", "title_link");
「Title の設定がなければ、TitleLink の設定をしない」ということだと思います。

後々の throw "Message to send isn't set."; のところと、条件の書き方を合わせた方が良いでしょう。
つまり attachment を使用して判定する。

2021-02-08 00:15 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
@hatanaka-akihiro さん

function attachAdd(attachment, config, attachName)の関数で、ログを出力させてみました。
「engine.log(`config:${config} attachment:${attachment[attachName]}`);
}」


function attachAdd(attachment, config, attachName){
  const value = configs.get(config);
  if (value !== "" && value !== null){
    attachment[attachName] = value;
  }
  engine.log(`config:${config} attachment:${attachment[attachName]}`);
}

空の場合は、${attachment[attachName]}は「undefined」になります。


それから、畠中さんのコメントの処理の前にもログ出力をさせてみました。
engine.log(attachment["title"]);
engine.log(attachment["text"]);
engine.log(text);
 if (attachment["title"] == null && attachment["title"] == null && text == ""){
    throw "Message to send isn't set.";
  }
こちらでは、空の場合は、attachment["title"]とattachment["title"]はnullが出力されますので、比較対象はnullでよいかと思ったのですが、畠中さんのコメントに対する答えになっているか分からないので、自分の解釈が間違っていたら教えてください。

2021-02-08 00:24 UTC, hatanaka-akihiro requested changes

2021-02-08 00:24 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
```configs.get(config)``` の値が空 (空文字列 or null) の場合、attachment に値を設定していません。

したがって、```attachment[attachName]``` は undefined のはずです。

そもそも２か所のログ出力で、結果が異なるというのも変です。
何か間違えていると思います。

2021-02-08 02:26 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
@hatanaka-akihiro  さん
let attachment = {};の次に、

engine.log(attachment["title"]);
engine.log(attachment["text"]);
としても、nullが出力されます。
---------------------------------------
function main() {
  const token = configs.get("Token");
  let text = "";
  if (configs.get("Text") !== "" && configs.get("Text") !== null){
    text = configs.get("Text");
  }
  const channel = configs.get("ChannelName");
  
  let attachment = {};

engine.log(attachment["title"]);
engine.log(attachment["text"]);
------------------------------------------------

もともと
  let attachment = {};でnullなので、function attachAdd(attachment, config, attachName)でconfigs.get(config) の値が空 (空文字列 or null) の場合、何もしないのでnullのままなのでしょうか

2021-02-08 02:43 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
```engine.log()``` の動きかもしれないな。
そもそも ```engine.log()``` は String しか受け付けないので、そこで型変換が起こっている可能性があります。
つまり、もともとの値を出力していない可能性。

```
engine.log(attachment['title'] === undefined ? "true" : "false");
engine.log(attachment['title'] === null ? "true" : "false");
```

として、どちらで true がログ出力されますか。

2021-02-08 03:53 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
@hatanaka-akihiro  さん
下記の二箇所に
engine.log(attachment['title'] === undefined ? "true" : "false");
engine.log(attachment['title'] === null ? "true" : "false");
のログ出力させました。
ーーーーーーーーーーーーーーーーー
function main() {
  const token = configs.get("Token");
  let text = "";
  if (configs.get("Text") !== "" && configs.get("Text") !== null){
    text = configs.get("Text");
  }
  const channel = configs.get("ChannelName");
  
  let attachment = {};

engine.log(attachment['title'] === undefined ? "true" : "false");
engine.log(attachment['title'] === null ? "true" : "false");

  attachAdd(attachment, "Fallback", "fallback");
  attachAdd(attachment, "Color", "color");
  attachAdd(attachment, "Title", "title");
    if (attachment["title"] !== null){
    attachAdd(attachment, "TitleLink", "title_link");
  }
  attachAdd(attachment, "AttachText", "text");

engine.log(attachment['title'] === undefined ? "true" : "false");
engine.log(attachment['title'] === null ? "true" : "false");

 if (attachment["title"] == null && attachment["text"] == null && text == ""){
    throw "Message to send isn't set.";
ーーーーーーーーーーーーーーーーーーーーーーーーー

結果、
true
false
true
false
と出力されました。

2021-02-08 04:21 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
つまり undefined ということです。

技術的な話をすると、```engine.log(String)``` は Java のメソッド／機能。Java には undefined はないので、型変換されて null になったと考えられます。

```attachAdd``` の方のログ出力で undefined と出力されていたのは、```engine.log(String)``` に渡す前に、Javascript で String に変換されていたからです。'null' と出力されていた方も、Javascript で String に変換してから ```engine.log(String)``` を呼び出していれば、undefined とログ出力されたことでしょう。

2021-02-09 02:37 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + if (attachment["title"] == null && attachment["text"] == null && text == ""){
@hatanaka-akihiro  さん
ありがとうございました。
比較対象を「undefined」にしました。
== ではなく ===に修正しました。

2021-02-09 02:37 UTC, suese-sayaka commented on slack-chat-post-bots.xml
>      attachAdd(attachment, "TitleLink", "title_link");
attachment を使用して判定するよう修正しました。

2021-02-09 06:32 UTC, hatanaka-akihiro requested changes

2021-02-09 06:32 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
ここで配列に変えるのは、気持ち悪いと思いました。

javascript は、変数にどのような型の値でも入れることができますが、途中で変えるようなことは、基本、すべきでないです。

2021-02-15 05:58 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
@hatanaka-akihiro  さん

ソースコードを修正しましたが、畠中さんのコメントの答えになっているでしょうか。。
ご確認をお願いいたします。

2021-02-15 06:50 UTC, hatanaka-akihiro requested changes

2021-02-15 06:50 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
この名前にするなら、"attachArray" とした方が良いです。

そもそもですが、このアイテムで複数の attachment を扱う見込みは低いと思います。
ですので ```sendMessage()``` に配列を渡す作りにする必要なかったと思います。

ではどこで配列に変えるか。
```sendMessage()``` の中、```jsonReq["attachments"]``` に代入するタイミングだと思います。
API リクエストで必要だから配列にするのであって、それより遥か前に、配列に変える理由は無いと思います。

2021-02-15 07:06 UTC, hatanaka-akihiro requested changes

2021-02-15 07:06 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + if (attachment !== {}){
もともとのコードから変えていない部分だと思いますが、この比較が気になりました。

```Object.keys()``` を使用した

``` if (Object.keys(attachment).length !== 0) {```

に変えてください。

「attachment が何らかのプロパティを持つ場合」という条件になるはずです。

2021-02-16 01:24 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + if (attachment !== {}){
@hatanaka-akihiro  さん

"attacharray"を"attachArray"に修正しました。

比較文を　「if (Object.keys(attachment).length !== 0) {」　に修正しました。

attachArray　の配列に変えるタイミングを　sendMessage() 　の中に修正しました。

よろしくお願いします。

2021-02-16 05:45 UTC, merged