Update slack-file-upload-bots.xml
Questetra/Addon-XML pull request #283
Opened 2021-02-25 03:52 UTC by suese-sayaka

畠中さん

ソースコードを修正しました。
・engine を 2 に修正
・OK時のログ出力を削除
・テンプレート文字列に修正

テスト済です
よろしくお願いいたします。

2021-02-25 04:14 UTC, hatanaka-akihiro requested changes

2021-02-25 04:14 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
>    if (responseJson.ok == false ) {
=== の比較の方が良いです。
false との比較で良いのかどうかは解りません。

2021-02-25 04:14 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
>    if (responseJson.ok == false ) {
```!== (正常な場合の値)```

の方が良いでしょうね。

2021-02-25 04:14 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
status を使用しなくなっていると思います。

エラー時でも、status をログ出力しなくて良いのか、疑問ですが。

2021-02-25 04:14 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
>    if (file == null){
```===``` か ```!==``` の方が良いです。

2021-02-25 04:14 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
>    const file = engine.findDataByNumber(configs.get("File"));
新しい方式に書き換えてください。

2021-03-01 05:58 UTC, suese-sayaka commented on slack-file-upload-bots.xml
>    if (responseJson.ok == false ) {
!== true に修正しました。

2021-03-01 06:01 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
エラー時も、200を返す（bots 投稿も同様）ので、削除しました。

2021-03-01 06:01 UTC, suese-sayaka commented on slack-file-upload-bots.xml
>    if (file == null){
=== に修正しました。

2021-03-01 06:01 UTC, suese-sayaka commented on slack-file-upload-bots.xml
>    const file = engine.findDataByNumber(configs.get("File"));
修正しました。

2021-03-01 06:02 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ソースコードを修正しましたのでよろしくお願いいたします。

2021-03-01 06:37 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
> エラー時も、200を返す（bots 投稿も同様）ので、削除しました。

「200 を返さない場合は無い」と言い切れるのでしょうか。

2021-03-02 01:00 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
@hatanaka-akihiro  さん
テスト仕様書のエラーのケースは全て200が返ってくるのですが、その他、どんなエラーケースがあるか分からないのでstatusをログ出力するよう修正しました。
ありがとうございました。

2021-03-02 01:28 UTC, hatanaka-akihiro requested changes

2021-03-02 01:28 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
「存在しないトークン」を指定した場合も、200 が返ってきたのでしょうか。
普通は 200 を返さないパターンだと思ったので。

いずれにせよ、まず status をチェックし、200 の時に限って ```JSON.parse()``` するようにしてください。200 でない場合、JSON.parse() に失敗する、応答が JSON でない可能性があると考えました。

2021-03-02 04:12 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
「存在しないトークン」を指定した場合も、200 が返ってきます。
 status をチェックし、200 の時に限って JSON.parse() するように処理を加えました。

ご確認をよろしくお願いいたします。

2021-03-02 04:31 UTC, hatanaka-akihiro requested changes

2021-03-02 04:31 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +  let files = engine.findData( filesDef );
この後、files に変更はない前提のはずなので、const で良いです。

2021-03-02 04:31 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
>    let response = httpClient.begin()
response も変更がないのでは。つまり const で良いのでは。

2021-03-02 04:31 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> -  engine.log("status:" + status);
この修正だと、200 でない場合、responseJson が undefined だと思います。

undefined なので、responseJson.ok のところでエラー。

2021-03-02 13:17 UTC, closed without merging