T7395:文字型データ項目に保存する場合のみ、Meet URL を作成
Questetra/Addon-XML pull request #284
Opened 2021-02-25 07:08 UTC by Tonoyama

以下の変更を行いました。

- 文字型データ項目(`eventDescription`, `eventLocation`)のどちらかが空でない場合、Meet URL を作成。
- 説明情報を`TEXTFIELD`から`TEXTAREA`に変更。

2021-03-01 03:06 UTC, tatsumiQ requested changes
レビューしました。コメントをご確認ください。

また、Google カレンダーの URL も保存できるようにしてください。
C8: Google カレンダーの URL を保存する文字型データ項目
C9: Google Meet の URL を保存する文字型データ項目

2021-03-05 01:32 UTC, tatsumiQ requested changes
Google カレンダーの URL も保存できるようにしてください。
C8: Google カレンダーの URL を保存する文字型データ項目
C9: Google Meet の URL を保存する文字型データ項目

保存を insertEvent 関数内で行うのであれば、113行目のコメントを
`Google カレンダーにイベントを追加し、URL を保存する`
としておいてください。

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label>C1: User Who Connects to Google Calendar</label>
```suggestion
    <label>C1: User who connects to Google Calendar</label>
```
大文字から小文字に。

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label locale="ja">C5: 予定終了時刻が格納されている日時型データを選択してください (未設定の場合、+1:00)</label>
```suggestion
    <label locale="ja">C5: 予定終了時刻が格納されている日時型データを選択してください (未設定の場合、+1:00)</label>
```
```suggestion
    <label locale="ja">C5: 予定終了時刻が格納されている日時型データ項目 (未設定の場合、+1:00)</label>
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
>      <label locale="ja">C4: 予定開始時刻が格納されている日時型データを選択してください</label>
```suggestion
    <label locale="ja">C4: 予定開始時刻が格納されている日時型データ項目</label>
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label locale="ja">C8: Google Meet の URL を保存する文字型データデータ項目</label>
```suggestion
    <label>C8: String type data item that will save Google Meet URL</label>
    <label locale="ja">C8: Google Meet の URL を保存する文字型データデータ項目</label>
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  const meetUrlDataDef = configs.getObject("conf_meetUrl");
この処理は
//// == 工程コンフィグの参照 / Config Retrieving ==
のなかで行うようにしてください。

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  const response = "";
```suggestion
```
ここで response を宣言する必要はないので、削除してください。

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    endDate
```suggestion
    startDate,
    endDate,
    meetUrlDataDef
```
response はいらないはずですし、順番として meetUrlDataDef が先に来ているのに違和感があります。

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> + * @param {AddableTimestamp} endDate 終了日時
```suggestion
 * @param {AddableTimestamp} startDate 開始日時
 * @param {AddableTimestamp} endDate 終了日時
  * @param {ProcessDataDefinitionView} meetUrlDataDef Meet URL を保存する文字型データ項目
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  endDate
```suggestion
  startDate,
  endDate,
  meetUrlDataDef
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  }
変数 response はここで let で宣言しておけば使えます。
関数の外で宣言して引数として渡す必要はないです。
```suggestion
  let response;
  if (meetUrlDataDef !== null) {
    response = httpClient
      .begin()
      .googleOAuth2(quser, "Calendar")
      .queryParam("conferenceDataVersion", "1")
      .body(JSON.stringify(myObj), "application/json")
      .post(uri);
  } else {
    response = httpClient
      .begin()
      .googleOAuth2(quser, "Calendar")
      .body(JSON.stringify(myObj), "application/json")
      .post(uri);
  }
```

2021-03-05 01:32 UTC, tatsumiQ commented on google-calendar-event-insert.xml
>      throw `Failed to insert event.\nstatus:${status}`;
改行を除いておいてください。
```suggestion
    throw `Failed to insert event. status:${status}`;
```

2021-03-05 02:01 UTC, hatanaka-akihiro requested changes

2021-03-05 02:01 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +  }
リクエスト内容がほぼ同じなので、更に、以下のように改良すれば良いです。

```javascript
let request = httpClient
	      .begin()
	      .googleOAuth2(quser, "Calendar");
if (meetUrlDataDef !== null) {
  request = request.queryParam("conferenceDataVersion", "1");
}
const response = request.body(JSON.stringify(myObj), "application/json")
	      .post(uri);
```

2021-03-10 01:57 UTC, tatsumiQ requested changes
レビューしました。
動作に直接関係ない部分で、修正をお願いします。

2021-03-10 01:57 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> + * @param {HttpResponseWrapper} meetUrlDataDef Meet URL を保存する文字型データ項目
```suggestion
 * @param {ProcessDataDefinitionView} eventUrlDataDef Calendar URL を保存する文字型データ項目
 * @param {ProcessDataDefinitionView} meetUrlDataDef Meet URL を保存する文字型データ項目
```

2021-03-10 01:57 UTC, tatsumiQ commented on google-calendar-event-insert.xml
>      <label>C4: Datetime type data item for Event Start</label>
```suggestion
    <label>C4: Data item for Event Start Datetime</label>
```
日本語表記にあわせて Datetime type を削除し、最後に Datetime と付けておいてください。

2021-03-10 01:57 UTC, tatsumiQ commented on google-calendar-event-insert.xml
>      <label>C5: Datetime type data item for Event End (Not-selected +1:00)</label>
```suggestion
    <label>C5: Data item for Event End Datetime (Not-selected +1:00)</label>
```

2021-03-10 01:57 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label>C8: String type data item that will save Google Calendar URL</label>
```suggestion
    <label>C8: Data item that will save Google Calendar URL</label>
```
こちらも String type を除いてください。

2021-03-10 01:57 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label>C9: String type data item that will save Google Meet URL</label>
```suggestion
    <label>C9: Data item that will save Google Meet URL</label>
```

2021-03-12 05:29 UTC, tatsumiQ requested changes
追加で申し訳ありませんが、C8 の表記修正をお願いします。

2021-03-12 05:29 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label locale="ja">C8: Google カレンダー の URL を保存するデータ項目</label>
すみません。「Google カレンダー の URL」は表現として不適切なように思うので、下記の通り修正してください。
```suggestion
    <label>C8: Data item that will save Event URL</label>
    <label locale="ja">C8: 予定の URL を保存するデータ項目</label>
```

2021-03-18 02:41 UTC, tatsumiQ requested changes
場所の form-type は TEXTFIELD のままにしてください。

あとは動作に直接影響のない、細かな修正です。

2021-03-18 02:41 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  <config name="conf_DataIdF" required="false" el-enabled="true" form-type="TEXTAREA">
場所は TEXTFIELD のままにしてください。
```suggestion
  <config name="conf_DataIdF" required="false" el-enabled="true" form-type="TEXTFIELD">
```

2021-03-18 02:41 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +    <label locale="ja">C9: 予定の URL を保存するデータ項目</label>
```suggestion
    <label locale="ja">C9: 予定 URL を保存するデータ項目</label>
```
C8 と統一する意味で「の」が無いほうが良いと思いました。
前回の修正指示からの変更となりすみません。

2021-03-18 02:41 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> + * @param {ProcessDataDefinitionView} eventUrlDataDef Calendar URL を保存する文字型データ項目
```suggestion
 * @param {ProcessDataDefinitionView} eventIdDataDef Event ID を保存する文字型データ項目
 * @param {ProcessDataDefinitionView} eventUrlDataDef Event URL を保存する文字型データ項目
```
コンフィグの表記と揃えて Event か 予定 としておくのが良いと思いました。

2021-03-18 02:41 UTC, tatsumiQ commented on google-calendar-event-insert.xml
> +  const eventIdDataDef = configs.getObject("conf_eventId");
```suggestion
  const eventIdDataDef = configs.getObject("conf_eventId");
  const eventUrlDataDef = configs.getObject("conf_eventUrl");
  const meetUrlDataDef = configs.getObject("conf_meetUrl");
```
細かいですが、順番を揃えておいたほうが良いと思います。

2021-03-18 06:57 UTC, merged