Update slack-file-upload-bots.xml
Questetra/Addon-XML pull request #288
Opened 2021-03-04 02:14 UTC by suese-sayaka

@hatanaka-akihiro  さん

・files / response で、let から const に修正しました。
・「200 でない場合、responseJson が undefined なので、responseJson.ok でエラーになる」件について、修正しました。

ご確認をお願いいたします。

2021-03-04 04:37 UTC, hatanaka-akihiro requested changes

2021-03-04 04:37 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +
素朴な疑問です。

200 でない場合に、```JSON.parse()``` する必要があるのでしょうか。

2021-03-04 04:55 UTC, hatanaka-akihiro requested changes

2021-03-04 04:55 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +  }
Slack のドキュメントを見ましたが、HTTP のレスポンスコードについては明記されていません。一応、すべての応答は JSON オブジェクトを返すらしいですが、怪しいです。

https://api.slack.com/web#slack-web-api__basics__post-bodies__errors-specific-to-passing-json

なので、status とは関係なく、失敗する可能性を考慮しながら ```JSON.parse()``` を行う、以下の形を取るのが良さそうです。このアイテムに限らず、Slack 系アイテム全般的に。

```
let responseJson;
try {
     responseJson = JSON.parse(responseTxt);
} catch(e) {
  //エラー処理。status, responseTxt をログ出力する。
}
if (responseJson.ok !== true) {
  // エラー処理。status, responseTxt をログ出力する。
}
// 正常応答の場合の処理
```

2021-03-08 01:22 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> +  }
@hatanaka-akihiro  さん
ありがとうございます。修正しましたのでご確認をお願いいたします。

2021-03-08 01:53 UTC, hatanaka-akihiro requested changes

2021-03-08 01:53 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +	engine.log(`status: ${status}`);
インデントがおかしい。

2021-03-08 01:53 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +	engine.log(`status: ${status}`);
インデントがおかしい。

2021-03-08 02:34 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> +	engine.log(`status: ${status}`);
@hatanaka-akihiro  さん
インデントを合わせました。

2021-03-08 04:42 UTC, merged