T7657: Google ドライブ: フォルダ検索　Google API の変更への対応
Questetra/Addon-XML pull request #289
Opened 2021-03-09 06:08 UTC by tatsumiQ

@hatanaka-akihiro さん

レビューいただけますと幸いです。

2021-03-09 07:19 UTC, hatanaka-akihiro requested changes

2021-03-09 07:19 UTC, hatanaka-akihiro commented on google-drive-folder-search.xml
>      <label locale="ja">C5: 検索したフォルダの表示 URL を保存する文字型データ項目</label>
最近のものは「データ項目」"Data item" で済ませて、型表記を省略しています。
ついでに取ってもらえますか。

2021-03-09 07:19 UTC, hatanaka-akihiro commented on google-drive-folder-search.xml
>    setFolderData(idDataDef, folderIdsStr, folderNum);
今回の改良とは異なりますが、配列を引数に取っては？と思いました。

join 処理は setFolderData() に関係した処理だと思ったので。

2021-03-09 07:19 UTC, hatanaka-akihiro commented on google-drive-folder-search.xml
> +    return null;
素朴な質問です。
null が返るのはどのような場合ですか？
マイドライブ？

2021-03-10 01:05 UTC, tatsumiQ commented on google-drive-folder-search.xml
> +    return null;
@hatanaka-akihiro さん

driveId があるのは「共有ドライブ内にあるフォルダの場合」のみです。
「共有ドライブにない場合」、つまり下記3つの場合に null が返ります。
* 親フォルダ指定が空白の場合（マイドライブのルートが検索対象となるので）
* マイドライブ内のフォルダを親フォルダとして指定した場合
* 共有されたフォルダ（他人のマイドライブにある）を親フォルダとして指定した場合

2021-03-10 09:22 UTC, hatanaka-akihiro requested changes

2021-03-10 09:22 UTC, hatanaka-akihiro commented on google-drive-folder-search.xml
> +    return null;
共有されたフォルダ（他人のマイドライブにある）

が抜けていました。了解しました。

2021-03-10 09:22 UTC, hatanaka-akihiro commented on google-drive-folder-search.xml
> +  setFolderData(urlDataDef, folderUrlList, folderNum);
folderNum は引数に渡さなくて良さそうですね。
folderIdList.length / folderUrlList.length と同じ値のはず。

2021-03-11 02:23 UTC, merged