T7718 「開始: Google カレンダー: 予定開始時」の追加
Questetra/Addon-XML pull request #293
Opened 2021-03-12 02:27 UTC by hatanaka-akihiro

2021-03-12 06:12 UTC, tatsumiQ requested changes
レビューしました。ご確認をお願いします。

2021-03-12 06:12 UTC, tatsumiQ commented on start_event/google-calendar-event-started.xml
> +        time += engine.getTimeZoneOffsetInMinutes() * 60 * 1000;
正確には QBPMS のタイムゾーンのオフセットを取得するのでなく、カレンダーのタイムゾーンのオフセットを取得しなければならないのではないでしょうか？（一致することが多いとは思いますが）
```
let timeZone = json.timeZone; // カレンダーのタイムゾーン 
if (start.timeZone !== undefined) { // イベントに別のタイムゾーンが設定されている場合
   timeZone = start.timeZone;
}
// タイムゾーンの文字列からオフセットをミリ秒で取得（現在のスクリプトタスクの機能では不可？）
```

2021-03-12 06:45 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +        time += engine.getTimeZoneOffsetInMinutes() * 60 * 1000;
QBPMS のタイムゾーンでイベント一覧を取得していたつもりですが、API リクエストに "timeZone" パラメータが抜けていますね。

見直します。

2021-03-12 08:21 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +    <summary>Start Process when the start time of the event has passed on Google Calendar.</summary>
提案通りに変更しました。

2021-03-12 08:21 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +            <label>C1: User Who Connects with Google Calendar</label>
指摘通りに修正しました。

2021-03-12 08:21 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +        throw `Failed to get records. status: ${status}`;
修正しました。

2021-03-12 08:36 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +        time += engine.getTimeZoneOffsetInMinutes() * 60 * 1000;
まず start.datetime !== undefined の場合についてです。
この場合、datetime の文字列にはタイムゾーン情報が含まれており、datetimeFormatter はタイムゾーンも含めて解釈します。なので、現状の実装で問題ありません。

次に start.datetime === undefined の場合についてです。
「終日予定」のデータを表しています。これはタイムゾーンの概念および時刻を持っていません。
どのタイムゾーンで見ても、同じ日の予定になります。
従って「終日予定」の日付は、ワークフローエンジンのタイムゾーンにおいて、「その日の 00:00:00 を指している」と解釈するようにしています。「終日予定は処理対象としない」とどちらを選択するか考えた結果、こちらの実装を選択しました。


追伸：
「終日予定」のデータについて、最初の実装時は、このように解釈していませんでした。
API リクエスト時に timeZone パラメータでワークフローエンジンのタイムゾーンを指定し忘れていただけです。
結局のところ、当初の想定と同じ実装になっていますが。

2021-03-12 08:37 UTC, hatanaka-akihiro commented
更に「予定終了日時」も保存可能なように改良しています。

2021-03-15 01:04 UTC, hatanaka-akihiro commented
予定 ID がらみで更に改良しています。
Google カレンダーで、プロセス開始済みの予定の開始日時が変更される場合への対応です。

2021-03-15 01:44 UTC, tatsumiQ requested changes
@hatanaka-akihiro さん

一箇所だけご確認をお願いします。

2021-03-15 01:44 UTC, tatsumiQ commented on start_event/google-calendar-event-started.xml
> +        .queryParam('timeZone', engine.getTimeZoneId())
勘違いしているかもしれませんが、最終的に timeZone のクエリパラメータ指定は不要になったのかなと思いました。

2021-03-15 02:29 UTC, hatanaka-akihiro commented on start_event/google-calendar-event-started.xml
> +        .queryParam('timeZone', engine.getTimeZoneId())
はい。なくても動くはずですが、入れました。

ワークフローエンジンのタイムゾーンで日時のデータで処理しよう、という程度のものです。

2021-03-15 03:03 UTC, tatsumiQ commented on start_event/google-calendar-event-started.xml
> +        .queryParam('timeZone', engine.getTimeZoneId())
> はい。なくても動くはずですが、入れました。
承知しました。

2021-03-15 03:04 UTC, merged