Update slack-chat-post-bots.xml
Questetra/Addon-XML pull request #314
Opened 2021-04-26 05:54 UTC by suese-sayaka

@hatanaka-akihiro  さん

ソースコードを修正しました。
ご確認をお願いいたします。抜粋でテスト済です。

2021-04-26 06:36 UTC, hatanaka-akihiro requested changes

2021-04-26 06:36 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +    request = request.body(JSON.stringify(jsonReq), "application/json; charset=UTF-8")
コードの最後に、セミコロンが無いです。

2021-04-26 06:36 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
>    if (responseJson.ok == false ) {
slack-file-upload-bots にあわせて `!== true` の方が良いです。

2021-04-27 01:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +    request = request.body(JSON.stringify(jsonReq), "application/json; charset=UTF-8")
修正しました。

2021-04-27 01:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
>    if (responseJson.ok == false ) {
修正しました。

2021-04-27 01:34 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ソースコードを修正しました。
Bot トークンの設定もチェックする処理を加え、"auth setting not found"のエラーログの確認をしました。

2021-04-27 03:20 UTC, hatanaka-akihiro requested changes

2021-04-27 03:20 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +<last-modified>2021-01-14</last-modified>
おかしいです

2021-04-27 03:20 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
前より authSetting() が使用される条件が狭まっています。
また「両方設定されている場合は `authSetting()` が優先」という、当初の要件が満たされていません。

2021-04-27 04:50 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +<last-modified>2021-01-14</last-modified>
修正しました

2021-04-27 04:51 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
@hatanaka-akihiro さん
もう一度修正しましたのでご確認をお願いします。

2021-04-27 05:00 UTC, hatanaka-akihiro requested changes

2021-04-27 05:07 UTC, hatanaka-akihiro requested changes

2021-04-27 05:07 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
いや。間違っているか。

`oauth2 !== "" || oauth2 !== null` 

この条件だと、「常に true になる」ような。

2021-05-06 03:35 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
@hatanaka-akihiro  さん

修正し、if else だけにまとめました。
よろしくお願いいたします。

2021-05-06 04:18 UTC, hatanaka-akihiro requested changes

2021-05-06 04:18 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
間違っていないですが、もう少しシンプルになるはずです。

2021-05-06 06:00 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
ありがとうございます。
修正しました。

2021-05-06 06:42 UTC, hatanaka-akihiro requested changes

2021-05-06 06:42 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
`&&` は `||` より優先度が上です。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

なので
```
if (oauth2 !== "" && oauth2 !== null || token === "" || token === null){
```
で良いです。カッコ内のカッコが全て不要。

2021-05-10 00:29 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
@hatanaka-akihiro  さん
ありがとうございます。
カッコを削除しました。

2021-05-10 00:41 UTC, merged