T7737:Google カレンダー: 予定のカレンダー移動　の作成
Questetra/Addon-XML pull request #317
Opened 2021-04-30 08:57 UTC by Tonoyama

ドキュメント：
https://developers.google.com/calendar/v3/reference/events/move

2021-05-06 02:22 UTC, tatsumiQ requested changes
レビューしました。コメントをご確認ください。

2021-05-06 02:22 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +    }
`conf_Destination` を TEXTFIELD にし、空白を許可するのであれば `conf_CalendarId` と同様の処理になります。

2021-05-06 02:22 UTC, tatsumiQ commented on google-calendar-event-move.xml
> + * @param {String} destination カレンダー識別子
ID と識別子は同じ意味なので、表記を統一しておいたほうがいいです。
```suggestion
 * @param {String} destination 移動先カレンダーID
```

2021-05-06 02:22 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +    }
`destination` の形式も同様にチェックしておくのがいいです。
（片方だけチェックするのは一貫性がない）

2021-05-06 02:22 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +        .post(uri);
```suggestion
    const response = httpClient.begin()
        .googleOAuth2(quser, "Calendar")
        .body(JSON.stringify(myObj), "application/json")
        .post(uri);
```

2021-05-06 02:22 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +    myObj.destination = destination;
ドキュメントには destination はクエリパラメータに指定とありますが、これで動くのでしょうか。

2021-05-06 08:48 UTC, Tonoyama commented on google-calendar-event-move.xml
> +    <label locale="ja">C2: Calendar ID (空白の場合、プライマリのカレンダー)</label>
翻訳的にはいいと思うのですが、ラベルを64文字以下にするQBPMSの制限に引っかかりました。

2021-05-07 01:15 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +    <label locale="ja">C2: Calendar ID (空白の場合、プライマリのカレンダー)</label>
良いと思います。ただし ( の前に半角スペースを入れてください。（文字数ぴったりになると思います）
`C2: Calendar ID of the current event (Primary Calendar if blank)`

2021-05-07 08:53 UTC, Tonoyama commented on google-calendar-event-move.xml
> +    myObj.destination = destination;
はい。動きます。

2021-05-10 01:27 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +  </config>
空白を許可しないのか、空白の場合はプライマリのカレンダーにするのか、どちらでしょうか？
「プライマリ以外のカレンダー→プライマリのカレンダー」への移動を考えると、空白を許可しても良いように思います。
いずれにしても、「予定の移動先となるカレンダー ID」の「となる」はいらないと思います。

空白の場合はプライマリのカレンダーにするのであれば、日本語にもその旨を追記。
```suggestion
  <config name="conf_Destination" form-type="TEXTFIELD">
    <label>C3: Destination Calendar ID (Primary Calendar if blank)</label>
    <label locale="ja">C3: 予定の移動先カレンダー ID (空白の場合、プライマリのカレンダー)</label>
  </config>
```

もし空白を許可しないのであれば、`required="true"` にして、英語ラベルを修正。
```suggestion
  <config name="conf_Destination" required="true" form-type="TEXTFIELD">
    <label>C3: Destination Calendar ID</label>
    <label locale="ja">C3: 予定の移動先カレンダー ID</label>
  </config>
```

2021-05-10 01:31 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +    }
空白を許可する（プライマリとして扱う）のであれば、calendarId と同じ処理に。
空白を許可しない場合、`required="true"` にすればこの空値確認の処理は不要になります。

2021-05-10 01:33 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +        throw "Invalid Calendar ID";
`Invalid Destination Calendar ID` との区別のため、以下のようにしておくのはどうでしょうか。

```suggestion
        throw "Invalid Source Calendar ID";
```

2021-05-17 01:04 UTC, tatsumiQ requested changes
レビューしました。１点修正をお願いします。

2021-05-17 01:04 UTC, tatsumiQ commented on google-calendar-event-move.xml
> +  <config name="conf_Destination" required="true" form-type="TEXTFIELD">
空白を許可することになったと思うので、`required="true"` を外してください。

```suggestion
  <config name="conf_Destination" form-type="TEXTFIELD">
```

2021-05-21 01:02 UTC, tatsumiQ approved these changes

2021-05-21 01:02 UTC, merged