change around OAuth2 authentication
Questetra/Addon-XML pull request #326
Opened 2021-05-27 05:20 UTC by chica-non

巽さん

OAuth2 認証まわりとログ出力を変更しました。ご確認よろしくお願いします。

2021-05-27 05:40 UTC, tatsumiQ requested changes
細かなところで２点、修正をお願いします。

2021-05-27 05:40 UTC, tatsumiQ commented on onedrive-file-delete.xml
> +  return JSON.parse( response.getResponseAsString() );
```suggestion
  return JSON.parse( responseStr );
```

2021-05-27 05:40 UTC, tatsumiQ commented on onedrive-file-delete.xml
>    let response = httpClient.begin()
```suggestion
  const response = httpClient.begin()
```

2021-05-28 02:00 UTC, chica-non commented
巽さん
apply suggestionsをしたので、ご確認お願いします。

2021-05-28 02:57 UTC, tatsumiQ approved these changes

2021-05-28 02:58 UTC, merged