Create google-sheets-rowdata-get
Questetra/Addon-XML pull request #335
Opened 2021-07-08 02:53 UTC by suese-sayaka

@hatanaka-akihiro  さん

ソースコードを作成しました。
ご確認をお願いいたします。

2021-07-08 03:09 UTC, hatanaka-akihiro requested changes

2021-07-08 03:09 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +          convertedData2 = java.lang.String.valueOf( dataString );
dataString 自体が String では？
String なら String への変換は不要です。

2021-07-08 03:09 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +        case 'DATE':
日付型には、YMD / MD / YM / Y の 4 タイプありますが、全てに対応しているのでしょうか？

YMD にしか対応していないなら、select-data-type から絞った方が良いです。

2021-07-08 05:56 UTC, suese-sayaka commented on google-sheets-rowdata-get
> +          convertedData2 = java.lang.String.valueOf( dataString );
@hatanaka-akihiro  さん 
DateTimeRenderOption　は、日時データを文字列で出力するようなので、選択型は　dataString 自体が は Boolean なので、String への処理を残します。

2021-07-08 05:57 UTC, suese-sayaka commented on google-sheets-rowdata-get
> +        case 'DATE':
YMD / MD / YM / Y の 4 タイプ全てに対応していることを確認しました。

2021-07-08 05:58 UTC, suese-sayaka commented
@tatsumiQ  さん

ソースコードのレビューをお願いいたします。

2021-07-08 06:02 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +          convertedData2 = java.lang.String.valueOf( dataString );
@suese-sayaka 

日時データについては、言及していません。

> 選択型は　dataString 自体が は Boolean なので、String への処理を残します。

どういうことでしょう？
Boolean だと true / false の2種類の値しかありません。
選択型の選択肢は 2 つとは限らないので、Boolean というのは変です。

2021-07-08 06:11 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +        case 'DATE':
本当に対応しているでしょうか？

YMD 形式のデータを、MD / YM / Y のデータ項目に入れるという形になっていませんか？

それなら、「対応していない」としてください。

あと日時型もですが、DateTimeRenderOption を指定したら、内部データがシリアル値の場合の処理は要らないのでは？

2021-07-08 06:14 UTC, hatanaka-akihiro requested changes

2021-07-08 06:14 UTC, hatanaka-akihiro commented on google-sheets-row-get
> +            const dateFormatter = new java.text.SimpleDateFormat( "yyyy/MM/dd HH:mm:ss" );
yyyy/MM/dd HH:mm:ss の形式しか指定できないでしょうか。

気になるのは、yyyy-mm-dd HH:mm 書式の文字列を処理できないという点です。

google-sheets-row-append.xml と対なので、日時型データの標準テキストは取得できて欲しいです。

2021-07-08 06:15 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +        case 'DATE':
@suese-sayaka 

本当に対応しているでしょうか？

YMD 形式のデータを、MD / YM / Y のデータ項目に入れるという形になっていませんか？

それなら、「対応していない」としてください。

あと日時型もですが、DateTimeRenderOption を指定したら、内部データがシリアル値の場合の処理は要らないのでは？

2021-07-09 04:23 UTC, tatsumiQ requested changes
convertTypeAndSetData() の中はまだ詳しく見ていませんが、ひとまず気付いた点を書きました。

2021-07-09 04:23 UTC, tatsumiQ commented on google-sheets-row-get
> +  return dataStringList;
ここで最大10列のデータに絞っておけば良いかと思います。
1000文字制限というのは選択肢データの話のように思うので、ここでは不要ではないでしょうか。
```suggestion
  const jsonObj = JSON.parse( responseStr );

  if (jsonObj.values === undefined ) {
    throw `No Data in range.`;
  }

  const dataStringList = jsonObj.values[0].slice(0, COLUMN_NUM); // 最大10列

  return dataStringList;
```

2021-07-09 04:23 UTC, tatsumiQ commented on google-sheets-row-get
> +
この関数のなかでループさせるのが良いと思います。
また、「データ項目の設定はあるけれど、データの存在しない列」については、データ項目を空データで上書きするのが良いのでは。
```suggestion
function setDataByLists( valueDefList, dataStringList ) {
  valueDefList.forEach( (valueDef, i) => {
    if ( valueDef !== null) {
      if ( i > dataStringList.length - 1 ) { // dataStringList の要素がない場合
        engine.setData( valueDef, null ); // 空データで上書き（null を渡して動くかどうか、試していません）
      }
      const dataString = dataStringList[i];
      ...
    }
  });
```

2021-07-09 06:07 UTC, tatsumiQ requested changes
追加です。

2021-07-12 04:58 UTC, suese-sayaka commented on google-sheets-rowdata-get
> +        case 'DATE':
DATE_YMD  に修正しました。

内部データがシリアル値の場合の処理を削除しました。

2021-07-12 04:59 UTC, suese-sayaka commented on google-sheets-row-get
> +            const dateFormatter = new java.text.SimpleDateFormat( "yyyy/MM/dd HH:mm:ss" );
yyyy-mm-dd HH:mm 書式の文字列のみ処理できるよう修正しました。

2021-07-12 04:59 UTC, suese-sayaka commented on google-sheets-row-get
> +<summary locale="ja">Google スプレッドシートから指定した行のデータを取得します。</summary>
修正しました。

2021-07-12 04:59 UTC, suese-sayaka commented on google-sheets-row-get
> +    <label>C5: Column Range to Get (e.g. "A:J")(Up to 10 column)</label>
修正しました。

2021-07-12 05:00 UTC, suese-sayaka commented on google-sheets-row-get
> +    <label>C6_1: Data item that stores the values in the 1st column </label>
修正しました。

2021-07-12 05:00 UTC, suese-sayaka commented on google-sheets-row-get
> +    <label locale="ja">C6_1: 列範囲のうち ２ 列目の値を保存するデータ項目</label>
半角で統一しました。

2021-07-12 05:01 UTC, suese-sayaka commented on google-sheets-row-get
> +  * @return {Stromg} rowNo  行番号
修正しました。

2021-07-12 05:01 UTC, suese-sayaka commented on google-sheets-row-get
> +  }
修正しました。

2021-07-12 05:01 UTC, suese-sayaka commented on google-sheets-row-get
> +  rangeArr = range.split(':');
range が不正な形式でないかチェックする処理を追加しました。

2021-07-12 05:02 UTC, suese-sayaka commented on google-sheets-row-get
> +  const uri = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${sheetTitle}!${rangeArr[0]}${rowNo}:${rangeArr[1]}${rowNo}`;
シートタイトルをエンコードするよう、処理を加えました。

2021-07-12 05:03 UTC, suese-sayaka commented on google-sheets-row-get
> +  return dataStringList;
削除しました。

2021-07-12 05:04 UTC, suese-sayaka commented on google-sheets-row-get
> +
修正しました。

2021-07-12 05:08 UTC, suese-sayaka commented on google-sheets-row-get
> +          convertedData.add( convertedData2 );
getRowData() で String の配列を取得するよう修正しました。
convertedData2 = java.lang.String.valueOf( dataString )の処理を削除しました。

2021-07-12 05:08 UTC, suese-sayaka commented on google-sheets-row-get
> +          } else{
処理を削除しました。

2021-07-12 05:19 UTC, suese-sayaka commented on google-sheets-rowdata-get
> +          convertedData2 = java.lang.String.valueOf( dataString );
@hatanaka-akihiro  さん

スプレッドシートの選択型は、チェックボックス（チェック：true   チェックしない:false）のみだと思っていました。
プルダウンリストも作成できますが、選択する値が文字、数字、日付などとtrue/false だったのでこの処理にしました。
スプレッドシート側の選択型についてまだ理解できていないのでもう少し勉強します。

2021-07-12 06:56 UTC, tatsumiQ requested changes
レビューしました。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
>    let dataStringList = getRowData( oauth, sheetId, sheetTitle, rowNo, range );
let → const に

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +  const idReg = new RegExp( '^[A-Z]:[A-Z]$' );
これだと A-Z 列までしか指定できませんが、AA 列以降も作成することができます。
`'^[A-Z]+:[A-Z]+$'` とすれば、AA 列以降にも対応できると思います。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +  enSheetTitle = encodeURIComponent(sheetTitle);
rangeArr, enSheetTitle ともに const にする。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +  const uri = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${enSheetTitle}!${rangeArr[0]}${rowNo}:${rangeArr[1]}${rowNo}`;
sheetId も何もチェックされないままここまでくるので、encodeURIComponent() しておいたほうが良いと思います。
不正な sheetId の場合に、どのエラーになるのかが定まらないので。
（空白などが含まれると get() のところで URL が不正な旨のエラー、URL として問題なければ 404）
エンコードしておけば URL として不正になることはないので、必ず 404 になるはずです。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +        engine.setData( valueDef, null );
このあとに return; を入れないと、dataString が undefined になってしまうと思います。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +  if ( dataString === "" || dataString === null || dataString === undefined) { // 空値の場合は null を設定
setDataByLists() 内で dataString が undefined にならないように処理すれば、undefined かどうかの判定は必要なくなるはずです。
関数コメントに dataString は String 型だとあるのに、undefined かどうかのチェックをここに入れるのはおかしいです。

2021-07-12 06:56 UTC, tatsumiQ commented on google-sheets-row-get
> +          convertedData = new java.sql.Timestamp( dateFormatter.parse( dataString ).getTime() );
これだと日時が UTC で解釈され、保存されるように思います。
QBPMS のシステムのタイムゾーンで解釈する仕様のほうが、実用に促しているのではないでしょうか。

2021-07-13 02:01 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +        case 'DATE':
@suese-sayaka 

Questetra の日付・日時型は対象から除外するので、本 conversation は resolve します。

2021-07-13 02:02 UTC, hatanaka-akihiro commented on google-sheets-rowdata-get
> +          convertedData2 = java.lang.String.valueOf( dataString );
@suese-sayaka 

> 選択型の選択肢は 2 つとは限らないので、Boolean というのは変です。

この選択型は「Questetra の選択型」という意味でした。

ひとまず Questetra の選択型は対象から除外するので、本 conversation は resolve します。

2021-07-13 04:22 UTC, suese-sayaka commented on google-sheets-row-get
> +  const uri = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${enSheetTitle}!${rangeArr[0]}${rowNo}:${rangeArr[1]}${rowNo}`;
sheetId についても encodeURIComponent()  しました。

2021-07-13 04:23 UTC, suese-sayaka commented on google-sheets-row-get
> +        engine.setData( valueDef, null );
修正しました。

2021-07-13 04:23 UTC, suese-sayaka commented on google-sheets-row-get
> +  if ( dataString === "" || dataString === null || dataString === undefined) { // 空値の場合は null を設定
修正しました。

2021-07-13 04:24 UTC, suese-sayaka commented
@tatsumiQ  さん

いったん文字型データ項目にのみ保存するよう、不要な処理をコメントアウトしました。
ご確認をお願いいたします。

2021-07-13 05:10 UTC, tatsumiQ commented on google-sheets-row-get
> +          convertedData = new java.sql.Timestamp( dateFormatter.parse( dataString ).getTime() );
日時型への保存は除外するので、本 conversation は resolve します。

2021-07-13 05:11 UTC, tatsumiQ approved these changes

2021-07-13 05:15 UTC, merged