T7853:Google スプレッドシート: シート追加　の作成
Questetra/Addon-XML pull request #336
Opened 2021-07-08 09:11 UTC by Tonoyama

スプレッドシート ID をもとに新しいシートを追加できるようにした。

API ドキュメント：
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate

2021-07-12 02:08 UTC, tatsumiQ requested changes
レビューしました。
ファイル名も google-sheets-sheet-add.xml に変更をお願いします。

2021-07-12 02:08 UTC, tatsumiQ commented on google-sheets-add-new-sheet.xml
> +  const uri = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/:batchUpdate`;
sheetId に / などが混入しても意図しないパスにならないように、encodeURIComponent() しておくのがいいです。
あと、: の前の / は不要なのでは。
```suggestion
  const uri = `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}:batchUpdate`;
```

2021-07-12 02:08 UTC, tatsumiQ commented on google-sheets-add-new-sheet.xml
> +        throw `Failed to create tabs.`;
使う言葉は統一した方がいいです。シートを作成・追加することを add と言っているなら、最後まで add で。
```suggestion
        throw `Failed to add a new sheet.`;
```

2021-07-12 02:08 UTC, tatsumiQ commented on google-sheets-add-new-sheet.xml
> +  engine.log("Succeeded to create Sheet");
```suggestion
  engine.log("Succeeded to add a sheet.");
```

2021-07-12 02:08 UTC, tatsumiQ commented on google-sheets-add-new-sheet.xml
> +  };
sheetTitle が空白の場合に、properties をセットしないようにしてください。

2021-07-15 01:57 UTC, tatsumiQ requested changes
レビューしました。
プルリクエストに2つファイルが含まれているので、google-sheets-add-new-sheet.xml のほうは対象から除外してください。

2021-07-15 01:57 UTC, tatsumiQ commented on google-sheets-sheet-add.xml
> +  }
空かどうか調べるのは sheetId ではなく sheetTitle です。
空の場合にだけ properties をセットすればいいので、たとえば以下のように書けます。
requestObj は再代入していないので、const で定義できます。
```
const requestObj = {
  requests: [
    { "addSheet": {} }
  ]
};
if (sheetTitle !== "" && sheetTitle !== null) {
  requestObj.requests[0].addSheet["properties"] = {
    "title": sheetTitle
  };
}
```

2021-07-15 08:44 UTC, Tonoyama commented
https://github.com/Questetra/Addon-XML/pull/338 に新しくプルリクエストを作りました。

本プルリクエストには、2つ(google-sheets-sheet-add.xml, google-sheets-add-new-sheet.xml)ファイルが含まれていました。そのため、https://github.com/Questetra/Addon-XML/pull/338 を作成しました。

2021-07-15 08:44 UTC, closed without merging