Create google-sheets-row-update.xml
Questetra/Addon-XML pull request #341
Opened 2021-07-26 05:54 UTC by suese-sayaka

@tatsumiQ  さん

ソースコードを作成しました。おおまかに動作確認しています。ご確認をお願いいたします。

C6_1～C6_10: 列範囲のうち 1 列目の値を更新するデータ項目～10 列目の値を更新するデータ項目について

　いったん、全て未設定（未入力）の場合はエラーとせずに、全て空白で更新されるようにしました。（エラーにする処理はコメントアウトしました）
　EL式で参照先が重複している場合も、同じ値で更新されるようにしました。

2021-07-26 07:26 UTC, tatsumiQ requested changes
レビューしました。

* C6 がすべて空白（未入力）の場合 → 空白で更新される
* C6 で EL 式の参照先が重複する場合 → 同じ値で更新される
で良いと思います。

気になったのが、たとえばシートにC列までしかなく、列範囲に A:Cと指定して、C6_1〜C6_3にのみ値を入力、C6_4 以降を空白のままにした場合、A〜C列の値は更新できるのでしょうか？

2021-07-26 07:26 UTC, tatsumiQ commented on google-sheets-row-update.xml
> +}
```suggestion
  /**
  * configから更新情報を読み出し、JSON オブジェクトを返す
  * @param {Array<String>} dataArray 更新後の値の配列
  * @return {Object} requestObj  JSON オブジェクト
  */
function buildRequestObj( dataArray ) {
  const requestObj = {};
  requestObj.majorDimension = "ROWS";
  requestObj.values = [];
  requestObj.values.push(dataArray);
  return requestObj;
}
```

2021-07-26 07:26 UTC, tatsumiQ commented on google-sheets-row-update.xml
> +    .queryParam( "includeValuesInResponse", "true" )
レスポンスにセルの値は不要だと思うので、この一行は不要ではないでしょうか？

2021-07-29 05:49 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +<label>Google Sheets: Get Row </label>
修正しました

2021-07-29 05:49 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +    <label>C2: Source Spreadsheet ID</label>
修正しました

2021-07-29 05:49 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +    <label>C3: Source Sheet Title</label>
修正しました

2021-07-29 05:49 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +    <label>C4: Row to Get (e.g. "1", "11")</label>
修正しました

2021-07-29 05:49 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +    <label locale="ja">C5: 更新する列範囲 (例 "A:J""K:L") (最大 10 列)</label>
修正しました

2021-07-29 05:50 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  updateRowData( oauth, sheetId, sheetTitle, rowNo, range );
追加しました

2021-07-29 05:50 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +function updateRowData( oauth, sheetId, sheetTitle, rowNo, range ) {
追加しました

2021-07-29 05:50 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  const requestObj = retrieveContent();
変更しました

2021-07-29 05:50 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +}
修正しました

2021-07-29 05:50 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +    .queryParam( "includeValuesInResponse", "true" )
不要でした。削除しました。

2021-07-29 05:51 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  return rowNo;
修正しました

2021-07-29 05:58 UTC, suese-sayaka commented
@tatsumiQ  さん

ソースコードを修正しました。

「たとえばシートにC列までしかなく、列範囲に A:Cと指定して、C6_1〜C6_3にのみ値を入力、C6_4 以降を空白のままにした場合、A〜C列の値は更新できるか」についてですが、できませんでした。
lettersToNumber　という関数（サイトからさがしました）を使用して、列範囲が10未満の場合、列範囲分の値しか更新市内処理に修正しました。

また、「たとえばシートにC列までしかなく、列範囲に C:Mと指定する」と、このソースコードでは、D~M列が追加されます。（列範囲にD:N列と指定するとエラーになります）
D~M列が追加されるのが、API側の処理なのか、調べます。

2021-07-30 02:02 UTC, tatsumiQ requested changes
レビューしました。

2021-08-02 03:13 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +let COLUMN_NUM = 10;
修正しました

2021-08-02 03:13 UTC, suese-sayaka commented on google-sheets-row-update.xml
>    checkRowNoAndRange( rowNo, range );
修正しました

2021-08-02 03:14 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  for (let i = 0; i < COLUMN_NUM; i++) {
列数の計算結果が0以下の場合はエラーになるよう修正しました

2021-08-02 03:14 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +return dataArray;
修正しました

2021-08-02 03:14 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  const rangeArr2 = range.split(':');
修正しました

2021-08-02 03:14 UTC, suese-sayaka commented on google-sheets-row-update.xml
> + }
修正しました

2021-08-02 03:14 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +function lettersToNumber(letters){
修正しました

2021-08-02 03:15 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しましたのでご確認をお願いいたします。

2021-08-02 06:47 UTC, tatsumiQ requested changes
レビューしました。
コメントをご確認ください。

2021-08-02 06:47 UTC, tatsumiQ commented on google-sheets-row-update.xml
> +  }
他の変数の形式とそろえて、変数名は `columnNum` のほうが良いと思います。
エラーメッセージはここも "Invalid Range." で良いと思ったのと、
書き方として、以下のほうがすっきりと書けます。
```
let columnNum = lettersToNumber(rangeArr[1]) - lettersToNumber(rangeArr[0]) + 1;
if (columnNum <= 0) {
  throw "Invalid Range.";
}
if (columnNum > COLUMN_MAX_NUM) {
  columnNum = COLUMN_MAX_NUM;
}
```

2021-08-02 06:47 UTC, tatsumiQ commented on google-sheets-row-update.xml
> +  * @param {String} rangeArr 更新する列範囲の最初の列と最終の列が格納された配列
引数の型が `String` から `Array<String>` に変更になっていますが、コメントが修正されていません。

2021-08-02 06:47 UTC, tatsumiQ commented on google-sheets-row-update.xml
> + * @param {String} rangeArr 更新する列範囲の最初の列と最終の列が格納された配列
引数の型が `String` から `Array<String>` に変更になっていますが、コメントが修正されていません。

2021-08-03 00:19 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  }
ありがとうございます。修正しました。

2021-08-03 00:19 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +  * @param {String} rangeArr 更新する列範囲の最初の列と最終の列が格納された配列
修正しました

2021-08-03 00:19 UTC, suese-sayaka commented on google-sheets-row-update.xml
> + * @param {String} rangeArr 更新する列範囲の最初の列と最終の列が格納された配列
修正しました

2021-08-03 00:19 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しましたのでご確認をお願いいたします。

2021-08-03 01:01 UTC, tatsumiQ requested changes
レビューしました。あと１点、インデントの修正をお願いいたします。

2021-08-03 01:01 UTC, tatsumiQ commented on google-sheets-row-update.xml
> +}
細かいですが、インデントが揃っていないです。

2021-08-03 02:08 UTC, suese-sayaka commented on google-sheets-row-update.xml
> +}
ありがとうございます。修正しました。

2021-08-03 02:08 UTC, suese-sayaka commented
@tatsumiQ  さん
インデントを揃えました。ご確認をお願いいたします。

2021-08-03 02:23 UTC, tatsumiQ approved these changes

2021-08-03 02:24 UTC, merged