Create box-file-link-create.xml
Questetra/Addon-XML pull request #342
Opened 2021-08-03 04:11 UTC by suese-sayaka

@tatsumiQ  さん
ソースコードを作成しました。
ご確認をお願いいたします。

2021-08-03 06:25 UTC, tatsumiQ requested changes
レビューしました。
config 名を `conf_XXX` の形式にしていただきたいのと、命名規則を揃える・シンプルにしたほうがいいです。
`conf_` のあとの語頭を大文字にするのであれば、すべての config で語頭を大文字に。
`conf_DownloadPass` は長いので、 `conf_Password` で良いように思います。
`conf_DownloadUrlItem` も長くなるので、`conf_SharedLink` などで良さそうです。

2021-08-03 06:25 UTC, tatsumiQ commented on box-file-link-create.xml
> +  }
必須ではないですが、「ファイルが既に共有リンク作成されているか調べる」目的の関数なら関数名を `checkExistingSharedLink()` にして、共有リンクがある場合は関数内でエラーにしてしまったほうが、`main()` 関数がシンプルになります。
`existingUrl` はエラーを出す目的以外では使っていないので、返り値にする必要はないと思います。

2021-08-03 06:25 UTC, tatsumiQ commented on box-file-link-create.xml
> +  let jsonBody = {};
再代入していないので const で良いと思います。
```suggestion
  const jsonBody = {};
```

2021-08-03 06:25 UTC, tatsumiQ commented on box-file-link-create.xml
> +  }
変数名 `UrlData` が他のところと形式が揃っていないので、`urlDef` など、形式を揃えておいてください。

2021-08-05 04:20 UTC, suese-sayaka commented on box-file-link-create.xml
> +<summary>Create a URL to access the specified file on Box. Created indefinitely if blank, Created without a password request if blank.</summary>
ありがとうございます。変更しました。

2021-08-05 04:20 UTC, suese-sayaka commented on box-file-link-create.xml
> +  <config name="DownloadPass" form-type="SELECT" select-data-type="STRING">
修正しました

2021-08-05 04:20 UTC, suese-sayaka commented on box-file-link-create.xml
> +  <config name="DownloadUrlItem" form-type="SELECT" select-data-type="STRING" required="true">
修正しました

2021-08-05 04:20 UTC, suese-sayaka commented on box-file-link-create.xml
> +    <label>C5: Data item that will save web the Shared Link</label>
削除しました

2021-08-05 04:21 UTC, suese-sayaka commented on box-file-link-create.xml
> +  <config name="OAuth2" required="true" form-type="OAUTH2" oauth2-setting-name="https://app.box.com/api/oauth2/root_readwrite">
修正しました

2021-08-05 04:21 UTC, suese-sayaka commented on box-file-link-create.xml
> +  }
修正しました

2021-08-05 04:21 UTC, suese-sayaka commented on box-file-link-create.xml
> +  }
ありがとうございます。修正しました。

2021-08-05 04:23 UTC, suese-sayaka commented on box-file-link-create.xml
> +  let jsonBody = {};
修正しました

2021-08-05 04:23 UTC, suese-sayaka commented on box-file-link-create.xml
> +  }
修正しました

2021-08-05 04:27 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しました。
指摘くださった箇所に加え、「C2: 共有するファイル ID」を、form-type="SELECT" select-data-type="STRING_TEXTFIELD" editable="true" に変更しました。

ご確認をお願いいたします。

2021-08-06 01:31 UTC, tatsumiQ requested changes
レビューしました。
細かいところで表記が揃っていないところがいくつかありましたので、修正をお願いします。

2021-08-06 01:31 UTC, tatsumiQ commented on box-file-link-create.xml
> +    throw "File ID is blank";
`||` の後にスペースを挿入してください。

2021-08-06 01:31 UTC, tatsumiQ commented on box-file-link-create.xml
> +  function checkExistingSharedLink(oauth2, fileId) {
インデントがずれています。

2021-08-06 01:31 UTC, tatsumiQ commented on box-file-link-create.xml
> +    <label locale="ja">C2: 共有するファイル ID </label>
ID のあとに不要なスペースがあります。

2021-08-06 01:31 UTC, tatsumiQ commented on box-file-link-create.xml
>    }
`urlDef`（語頭小文字）にしたほうが、ほかの変数と形式がそろいます。

2021-08-06 01:50 UTC, tatsumiQ requested changes
追加です。

2021-08-06 01:50 UTC, tatsumiQ commented on box-file-link-create.xml
> +    <label locale="ja">C4: リンクのパスワードが格納されているデータ項目</label>
C2 がデータ項目を選択する仕様になったのに併せて、C3 と C4 の「〜が格納されているデータ項目」はなくても良いように思いました。（ないほうが、C2 と書き方が揃うのではないかと）
```suggestion
    <label>C3: Expiration of the Link</label>
    <label locale="ja">C3: リンクに設定する有効期限</label>
  </config>
  <config name="conf_Password" form-type="SELECT" select-data-type="STRING_TEXTFIELD">
    <label>C4: Password of the Link</label>
    <label locale="ja">C4: リンクに設定するパスワード</label>
```

2021-08-10 00:56 UTC, suese-sayaka commented on box-file-link-create.xml
> +    throw "File ID is blank";
修正しました

2021-08-10 00:56 UTC, suese-sayaka commented on box-file-link-create.xml
> +  function checkExistingSharedLink(oauth2, fileId) {
修正しました

2021-08-10 00:56 UTC, suese-sayaka commented on box-file-link-create.xml
> +    <label locale="ja">C2: 共有するファイル ID </label>
修正しました

2021-08-10 00:57 UTC, suese-sayaka commented on box-file-link-create.xml
>    }
修正しました

2021-08-10 00:57 UTC, suese-sayaka commented on box-file-link-create.xml
> +    <label locale="ja">C4: リンクのパスワードが格納されているデータ項目</label>
修正しました

2021-08-10 00:57 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しました。ご確認をお願いいたします。

2021-08-10 02:16 UTC, tatsumiQ commented on box-file-link-create.xml
> +    <label locale="ja">C4: リンクのパスワードが格納されているデータ項目</label>
英語のほうも `Data item with` はいらないと思います。

2021-08-10 02:42 UTC, suese-sayaka commented on box-file-link-create.xml
> +    <label locale="ja">C4: リンクのパスワードが格納されているデータ項目</label>
修正しました

2021-08-10 02:42 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しました。ご確認をお願いいたします。

2021-08-10 04:05 UTC, tatsumiQ approved these changes

2021-08-10 04:05 UTC, merged