Create box-file-link-delete.xml
Questetra/Addon-XML pull request #343
Opened 2021-08-05 05:57 UTC by suese-sayaka

巽さん

ソースコードを作成しました。
ご確認をお願いいたします。

2021-08-06 02:06 UTC, tatsumiQ requested changes
レビューしました。

2021-08-06 02:06 UTC, tatsumiQ commented on box-file-link-delete.xml
> +  * @param {String} OAuth2 認証設定
```suggestion
  * @param {String} oauth2 OAuth2 認証設定
```

2021-08-06 02:06 UTC, tatsumiQ commented on box-file-link-delete.xml
> +  const url = "https://api.box.com/2.0/files/" + fileId + "?fields=shared_link";
```suggestion
  const url = `https://api.box.com/2.0/files/${fileId}?fields=shared_link`;
```

2021-08-06 02:06 UTC, tatsumiQ commented on box-file-link-delete.xml
> +    const error = `Failed to delete \n status: ${status}`;
68行目と形式を揃えると、以下のようになるかと。
```suggestion
    const error = `Failed to delete. status:${status}`;
```

2021-08-10 01:03 UTC, suese-sayaka commented on box-file-link-delete.xml
> +  * @param {String} OAuth2 認証設定
修正しました

2021-08-10 01:03 UTC, suese-sayaka commented on box-file-link-delete.xml
> +  const url = "https://api.box.com/2.0/files/" + fileId + "?fields=shared_link";
修正しました

2021-08-10 01:03 UTC, suese-sayaka commented on box-file-link-delete.xml
> +    const error = `Failed to delete \n status: ${status}`;
修正しました

2021-08-10 01:04 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しました。ご確認をお願いいたします。

2021-08-10 02:23 UTC, tatsumiQ approved these changes

2021-08-10 02:24 UTC, merged