Create google-sheets-sheet-copy.xml
Questetra/Addon-XML pull request #344
Opened 2021-08-06 08:47 UTC by Tonoyama

参考ドキュメント：
シートコピー：
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo

シートタイトル変更：
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate

2021-08-10 01:59 UTC, tatsumiQ requested changes
レビューしました。
チケットの詳細と仕様が変わってしまっている部分があります。

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +<summary locale="ja">Google スプレッドシートのシートをコピーします。</summary>
コピー先を指定できることが伝わったほうが良いと思うので、下記の文面はどうでしょうか。
```suggestion
<summary>Copy a single Google Sheet to the same or another spreadsheet.</summary>
<summary locale="ja">Google スプレッドシートのシートを同じ、または別のスプレッドシートにコピーします。</summary>
```

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  <config name="conf_spreadSheetId" required="true" form-type="TEXTFIELD">
config 名の形式を揃えてください。conf_のあとの語頭を大文字にするのであれば、すべての config で語頭を大文字に。たとえば `conf_SheetId` など（`conf_SpreadSheetId` でもいいですが、長いので）。

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +    <label>C2: Copy Source Spreadsheet ID</label>
Copy Source でコピー元という意味だということが分かりにくいので、`C2: Copy-Source Spreadsheet ID` と `-` を入れるか、Copy を抜いて `C2: Source Spreadsheet ID` でもいいと思います。

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  </config>
チケットの説明と仕様が変わってしまっています。
シート ID ではなく「コピーするシートのタイトル」を設定する仕様にしてください。

アイテム内でシートのタイトルからシート ID を取得する方法は、
https://github.com/Questetra/Addon-XML/blob/master/google-sheets-row-append.xml
の `getSheetId()` 関数を参考にしてください。

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +    <label>C4: Destination Spreadsheet ID (if blank, set automatically)</label>
set automatically（自動設定）ではなく、同じスプレッドシートにコピーされることをきちんと書いたほうがいいです。
```suggestion
    <label>C4: Destination Spreadsheet ID (if blank, the same spreadsheet as the source)</label>
```

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  <config name="conf_New_SheetTitle" required="false" form-type="TEXTFIELD" el-enabled="true">
New のあとの `_` はないほうがいいです（他のところでも単語の区切りに記号を入れていないので、形式を統一する）。
```suggestion
  <config name="conf_NewSheetTitle" required="false" form-type="TEXTFIELD" el-enabled="true">
```

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +    <label locale="ja">C4: コピー先スプレッドシートの ID（空白の場合、同じスプレッドシート）</label>
C4 と C5 で（）の表記がぶれている（全角or半角）ので、どちらかに統一したほうがいいです。

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  }
* destinationDef は ProcessDataDefinitionView なので、""（空白文字列）になることはあり得ません。
* `editable="true"` なので、文字列が直接指定されている可能性も考慮しなければなりません（destinationDef が null なら、直接指定されている可能性）。
```suggestion
  const destinationDef = configs.getObject("conf_Destination");
  let destination = "";
  if (destinationDef === null) {
    // ProcessDataDefinitionView が null ということは、データ項目としては設定されていない
    // 直接指定されている文字列を読み出す
    destination = configs.get("conf_Destination");
  }else{
    // ProcessDataDefinitionView が null でないということは、データ項目として設定されている
    // データ項目の値を読み出す
    destination = engine.findData(destinationDef);
  }
  if (destination === "" || destination === null) {
    destination = spreadSheetId;
  }
```

2021-08-10 01:59 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  if (destinationSheetId !== null) {
destinationSheetId が null の場合というのは、どのような場合でしょうか？
コピーが成功したなら、シート ID が存在しないということはあり得ないのでは？

新しいシートのタイトルが設定されている場合にのみ実行する
`if (sheetTitle !== null && sheetTitle !== "") {`
というのなら分かります。

2021-08-12 08:37 UTC, Tonoyama commented on google-sheets-sheet-copy.xml
> +    <label>C2: Copy Source Spreadsheet ID</label>
C2: Source Spreadsheet ID
C3: Source Sheet Title
に変更しました。

2021-08-12 08:39 UTC, Tonoyama commented on google-sheets-sheet-copy.xml
> +    <label>C4: Destination Spreadsheet ID (if blank, set automatically)</label>
64文字を超えてしまうため、短くする必要があります。

63文字の場合、こうなりました。
C4: Destination Spreadsheet ID (if blank, the same spreadsheet)

2021-08-12 08:41 UTC, Tonoyama commented on google-sheets-sheet-copy.xml
> +    <label locale="ja">C4: コピー先スプレッドシートの ID（空白の場合、同じスプレッドシート）</label>
全角に修正しました。

2021-08-12 08:45 UTC, Tonoyama commented on google-sheets-sheet-copy.xml
> +  if (destinationSheetId !== null) {
確かにコピーが成功した場合、シート ID が存在しないということはあり得ません。
`if (sheetTitle !== null && sheetTitle !== "") {`
に修正しました。

2021-08-13 02:36 UTC, tatsumiQ requested changes
コードの流れはこれで問題ないと思います。
書き方（形式）の部分でいくつか指摘を書きましたので、ご対応をお願いします。

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  if (destinationSheetTitle !== null) {
destinationSheetTitle は String 型なので、空文字列の場合も考慮しておくべきではないでしょうか。
`if (destinationSheetTitle !== "" && destinationSheetTitle !== null) {`

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +function setTitle(oauth2, destination, destinationSheetId, destinationSheetTitle) {
関数の説明と中身が合っていないです。
「Google スプレッドシートに新しいシートを追加」→「Google スプレッドシートのシート名を変更する」

関数を定義するさいの引数の名前や説明は、その関数を単体で見たときに意味が通るように書いたほうがいいです。
「Google スプレッドシートのシート名を変更する」のに、コピー先かどうかは関係ありません。
（この定義ファイルの中で、コピー先のシート名を変更するのに使っているだけ）
```
/**
 * Google スプレッドシートのシート名を変更する
 * @param {String} oauth2 OAuth2 認証設定
 * @param {String} spreadSheetId スプレッドシートの ID
 * @param {String} sheetId シートの ID
 * @param {String} newSheetTitle シートの新しいタイトル
 */
function setTitle(oauth2, spreadSheetId, sheetId, newSheetTitle) {
```

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +function copySheet(oauth2, spreadSheetId, SheetId, destination) {
語頭小文字に統一してください（119行目も）。
```suggestion
function copySheet(oauth2, spreadSheetId, sheetId, destination) {
```

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  }
他の箇所とインデントが揃っていません。
```suggestion
  if (status >= 300) {
    engine.log(`Status: ${status}`);
    engine.log(responseStr);
    throw `Failed to copy sheet.`;
  }
```

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  }
インデントが揃っていません。
```suggestion
  requestObj.requests[0] = {
    updateSheetProperties: {
      fields: 'title',
      properties: {
        "title": destinationSheetTitle,
        "sheetId": destinationSheetId
      }
    }
  }
```

2021-08-13 02:36 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  }
他のところとインデントが揃っていません。
```suggestion
  if (status >= 300) {
    engine.log(`Status: ${status}`);
    engine.log(responseStr);
    throw `Failed to set sheet title.`;
  }
```

2021-08-16 01:09 UTC, tatsumiQ requested changes
レビューしました。
質問いただいている部分とあわせて、修正をお願いします。

2021-08-16 01:09 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> + */
返り値の情報も書いておいてください。
```suggestion
 * @param {String} sheetTitle シートタイトル
 * @return {Number} sheetId シート ID
 */
```

2021-08-16 01:53 UTC, tatsumiQ commented
追加です。
「C5: 新しいシートのタイトル」が100文字を超える場合、setTitle() でエラーになってしまうのではないでしょうか。
（copySheet() までは成功し、タイトルが自動設定されたコピー先シートが残る）

「C5: 新しいシートのタイトル」が setTitle() に失敗するような文字数（おそらく100文字超えだと思いますが、実際に試して確認してください）の場合は、あらかじめエラーにしておいたほうが良いと思います。
72 行目の `const newSheetTitle = configs.get("conf_NewSheetTitle");` の後あたりで、文字数のチェック（文字数制限超えの場合はエラー）を追加してください。

2021-08-23 01:49 UTC, tatsumiQ requested changes
レビューしました。

2021-08-23 01:49 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +  if (100 <= newSheetTitle.length) {
100文字までは設定できるのではないでしょうか。
調べたい対象を左辺に置くのがふつうなので、以下のように書いてください。
```suggestion
  if (newSheetTitle.length > 100) {
```

2021-08-23 01:49 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +    throw "Sheet Title is too long.";
何文字以下にすれば良いか書いておくと親切だと思います（エラーになった時に、修正しやすい）。
```suggestion
    throw "Sheet Title is too long. It cannot be longer than 100 characters.";
```

2021-08-23 01:49 UTC, tatsumiQ commented on google-sheets-sheet-copy.xml
> +    setTitle(oauth2, spreadSheetId, sheetId, newSheetTitle);
これだとコピー元のシートタイトルが変更されてしまうのでは。
コピー先のシートタイトルが変更されるようにしてください。
```suggestion
    setTitle(oauth2, spreadSheetId, sheetId, newSheetTitle);
```

2021-08-30 01:39 UTC, tatsumiQ approved these changes

2021-08-30 01:40 UTC, merged