Create box-collaboration-add.xml
Questetra/Addon-XML pull request #347
Opened 2021-08-23 06:02 UTC by suese-sayaka

@tatsumiQ  さん

ソースコードのレビューをお願いいたします。

仕様については、チケット 7986 の、コメント8 に記載しました。

2021-08-24 02:32 UTC, tatsumiQ requested changes
レビューしました。コードはほぼ問題ないと思いますが、ラベルの表記等で修正をお願いします。

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +    <label locale="ja">C4: アクセス権限が付与される項目の種類</label>
「アクセス権限が付与される」という説明が逆に分かりにくいように思いました。
シンプルに下記のようにするのはどうでしょうか。
```suggestion
    <label>C4: Item type (file or folder)</label>
    <label locale="ja">C4: 項目の種類（ファイルまたはフォルダ）</label>
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +			</item>
ラベルの頭文字は大文字にしているので、揃えたほうが良いかと思います。
```suggestion
			<label>Editor</label>
			<label locale="ja">編集者</label>
			</item>
	  <item value="viewer">
			<label>Viewer</label>
			<label locale="ja">ビューア</label>
			</item>
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +			<label>folder</label>
こちらもラベルの頭を大文字に。
```suggestion
			<label>File</label>
			<label locale="ja">ファイル</label>
			</item>
	  <item value="folder">
			<label>Folder</label>
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +  <config name="conf_FileOrFolderId" required="true" form-type="SELECT" select-data-type="STRING_TEXTFIELD" editable="true">
修正しなくてもいいですが、`conf_FoleOrFolderId` だと長いので、`conf_ItemId` でも良いかと思います。

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +    <label locale="ja">C5: コラボレーションするファイル/フォルダの ID</label>
collaborate with は「（人）と共同作業する」という意味なので、ファイル/フォルダを説明する表現としてはおかしいと思いました。
```suggestion
    <label>C5: File/Folder ID to add a collaboration to</label>
    <label locale="ja">C5: コラボレーションを追加するファイル/フォルダの ID</label>
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +    jsonReq["role"] = role;
const でいいはずなのと、インデントがずれています。
```suggestion
  const jsonReq = {};
  jsonReq["item"] = {"id": fileOrFolderId, "type": itemType};
  jsonReq["accessible_by"] = {"login": emailAddress };
  jsonReq["role"] = role;
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +    }
インデントがずれています。
```suggestion
    }else{
      throw `Failed to add collaboration. status: ${status}`;
    }
  }
```

2021-08-24 02:32 UTC, tatsumiQ commented on box-collaboration-add.xml
> +     throw `Failed to add collaboration. status: ${status}`;
ここでもエラーをスローする前にレスポンス本文を出力したほうが良いと思います。

2021-08-31 04:31 UTC, suese-sayaka commented on box-collaboration-add.xml
> +<summary locale="ja">Box の指定ファイルもしくはフォルダに、指定ユーザをコラボレーションします。指定ユーザはBoxアカウントのメールアドレスで指定します。</summary>
修正しました

2021-08-31 04:32 UTC, suese-sayaka commented on box-collaboration-add.xml
> +<help-page-url locale="ja">https://support.questetra.com/ja/addons/box-collaboration-add/</help-page-url>
修正しました

2021-08-31 04:32 UTC, suese-sayaka commented on box-collaboration-add.xml
> +    <label locale="ja">C2: Box ユーザのメールアドレス</label>
ありがとうございます。修正しました。

2021-08-31 04:33 UTC, suese-sayaka commented on box-collaboration-add.xml
> +			</item>
インデントを揃えました

2021-08-31 04:33 UTC, suese-sayaka commented on box-collaboration-add.xml
> +    <label locale="ja">C4: アクセス権限が付与される項目の種類</label>
ありがとうございます。修正しました。

2021-08-31 04:33 UTC, suese-sayaka commented on box-collaboration-add.xml
> +			</item>
修正しました

2021-08-31 04:33 UTC, suese-sayaka commented on box-collaboration-add.xml
> +			<label>folder</label>
修正しました

2021-08-31 04:34 UTC, suese-sayaka commented on box-collaboration-add.xml
> +  <config name="conf_FileOrFolderId" required="true" form-type="SELECT" select-data-type="STRING_TEXTFIELD" editable="true">
修正しました

2021-08-31 04:34 UTC, suese-sayaka commented on box-collaboration-add.xml
> +    <label locale="ja">C5: コラボレーションするファイル/フォルダの ID</label>
修正しました

2021-08-31 04:34 UTC, suese-sayaka commented on box-collaboration-add.xml
> +    jsonReq["role"] = role;
修正しました
インデントを揃えました

2021-08-31 04:34 UTC, suese-sayaka commented on box-collaboration-add.xml
> +    }
インデントを揃えました

2021-08-31 04:35 UTC, suese-sayaka commented on box-collaboration-add.xml
> +     throw `Failed to add collaboration. status: ${status}`;
出力処理を追加しました

2021-08-31 04:35 UTC, suese-sayaka commented
@tatsumiQ  さん
ソースコードを修正しましたのでご確認をお願いいたします。

2021-08-31 06:37 UTC, tatsumiQ approved these changes

2021-08-31 06:37 UTC, merged