T7985:単体テストを追加
Questetra/Addon-XML pull request #362
Opened 2021-10-06 08:57 UTC by Tonoyama

列数の確認と単体テストを追加

2021-10-08 11:20 UTC, hatanaka-akihiro requested changes

2021-10-08 11:20 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +<label locale="ja">アドオン：コンバータ (Excel-CSV ファイル to テーブル型データ)</label>
名前を変えてはいけないです。

2021-10-08 11:20 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  if (myFiles.size() !== null) {
プログラムの意味が変わっています。

2021-10-14 00:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  expect(engine.findData(tableDef)).toEqual('hogehoge');
テーブル型データ項目の値は、複数の行と列を持つ、複雑なデータ構造になっています。

`hogehoge` という文字列と比較できるような、単純な値ではありません。

このアイテムと役割が反対の、converter-table-to-excelcsv の <script> のコードを理解すると良いでしょう。

2021-10-15 08:26 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目にオブジェクトを定義する
コードとコメントが合致していないです。

2021-10-15 08:27 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目をセットする
コードとコメントが合致していないです。

2021-10-15 08:28 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ArrayList 型に文字コードUTF-16LE-BOM, タブ区切りで"hogehoge"という文字列の「テスト.csv」ファイルを作成。
コメントが長いので、`files.add()` と `engine.createQfile()` のコードを分けましょう。

2021-10-15 08:28 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目を「Table_DataId」という名前で定義する
コードとコメントが合致していないです。

2021-10-15 08:29 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目にセットする
「何をセットする」か記載。

2021-10-15 08:29 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目を
コメントが切れています。

2021-10-15 08:30 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  execute();
`execute()` に対しても、コメントを記載すること。

2021-10-15 08:31 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 追加する行に加える型
コメントがおかしいです。
「行に加える型？」

2021-10-15 08:31 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +    // 新しい行に文字列を追加する
ちょっと違います。コメントを修正すること。

2021-10-15 08:31 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 文字列"hogehoge"を追加する
違いますね。修正すること。

2021-10-20 08:23 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  execute();
実行
としました。

2021-10-20 08:23 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目を
// テーブル型データ項目の値を取り出す
としました。

2021-10-20 08:24 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目にセットする
// テーブル型データ項目に値をセットする

2021-10-20 08:24 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目をセットする
// ArrayList 型に CSV ファイルを追加
  files.add(
    // 文字コードUTF-16LE-BOM, タブ区切りで"hogehoge"という文字列の「テスト.csv」
    engine.createQfile("テスト.csv", "text/tab-separated-values; charset=x-UTF-16LE-BOM","hogehoge")
  );
としました。

2021-10-20 08:27 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目をセットする
ファイル型データ項目に値を指定
としました。

2021-10-20 08:28 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目にオブジェクトを定義する
```
  // ファイル型データ項目を準備して、config に指定
  const fileDef = engine.createDataDefinition("ファイル", 5, "q_file", "FILE");
  // ファイル型データ項目を挿入する
```
としました。

2021-10-20 09:23 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 追加する行に加える型
おかしいです。修飾を削除してシンプルな文にすれば、どこがおかしいか解ります。

「関数」これは正しい。
「オブジェクトを定義する関数」？？？

2021-10-21 04:25 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // 追加する行に加える型
// 新しい行に文字列を追加する関数
としました。

2021-10-21 07:26 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +const assertFile = (file, name, contentType) => {
使用していますか？

2021-10-21 07:34 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目を「Table_DataId」という名前で定義する
まだ解消していないです。

「Table_DataId という名前で定義している」のではない。
Table_DataId という名前がついた設定項目 (<config>) に、テーブル型データ項目を指定している。

2021-10-21 07:36 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +    // 新しい行に文字列を追加する
先ほど口頭で話しましたが、「追加していない」です。

新しい行 (newRow) の "string" という名前 (フィールド名) がついた列に、値 (string) を指定している。

2021-10-21 07:36 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 文字列"hogehoge"を追加する
まだ解消していないです。

2021-10-21 07:37 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  execute();
何を実行？

2021-10-21 07:37 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目に値を指定
「値を指定」していないです。

2021-10-21 07:38 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目の0行０列目の値がhogehogeであることを確認
半角・全角のゼロが混じっている。

2021-11-04 04:22 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目を挿入する
`config に設定`というのが見つかりませんでした。
「// ファイル型データ項目を準備して、config に指定」はそのままにしています。

2021-11-04 04:47 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目の行数が1である
> まだ解消していないです。

```javascript
// 新しい行を用意する関数
const addRow = (string) => {
    const newRow = list.addRow();
};
// 文字列"hogehoge"を追加する
addRow("hogehoge");
```
としました。

>「入力データ」とは何を指していますか？

`テーブル型データ項目に値を指定`としました。

> 「テーブル型データ項目」ではなく「テーブル型データ項目の値」。その前に「値を取りだす」と記載していることと、整合性が取れていない。

```javascript
// テーブル型データ項目に格納されているオブジェクトを返す
const myTable = engine.findData(tableDef);
```
としました。

2021-11-04 04:51 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +test("success-1row-1column", () => {
修正しました。

2021-11-04 05:46 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +      if (newRow.size() < cellsArray.length || newRow.size() > cellsArray.length) {
改変前はエラーではありませんでした。
小さい場合はエラーにならないようにします。

2021-11-04 05:57 UTC, hatanaka-akihiro requested changes

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +      if (newRow.size() < cellsArray.length || newRow.size() > cellsArray.length) {
@Tonoyama 

テスト仕様書としてどうかではなく、元々の動きとしてどうか、確認してもらえますか？

ExcelCSV の列数 < テーブル型データ項目の列数の場合、スクリプトを見る限りはエラーになる気がしないです。スクリプトの実行後、QBPMS 側のチェックでバリデーションエラーになる可能性があります。

ExcelCSV の列数 > テーブル型データ項目の列数の場合も同様です。スクリプトを見る限りはエラーになる気がしない。スクリプトの実行後、QBPMS 側のチェックでバリデーションエラーになる可能性があります。

詳細に、元の動きを確認した方が良さそうです。

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +test("success-1row-1column", () => {
関数のコメントは、基本

```
/**
 * (コメント)
 */
```
の形で記載してください。

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目を挿入する
「config に指定」を「config に設定」と記載していました。

「ファイル型データ項目を準備して、config に指定」というコメントが、２行分をまとめて説明しているのでは？

```
const fileDef = engine.createDataDefinition("ファイル", 5, "q_file", "FILE");
configs.putObject("File_DataId", fileDef);
```

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目に CSV ファイルを追加
CSV ファイルを追加している対象は、「ファイル型データ項目」ではないです。

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +    engine.createQfile("テスト.csv", "text/tab-separated-values; charset=x-UTF-16LE-BOM","hogehoge")
読みずらいので、```files.add()``` の外に出すように。

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目を指定する
この行も要らないのでは？

「テーブル型データ項目を準備して、config に指定」で 2 行分説明しているのでは？

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  const addRow = (string) => {
この string 引数の意味は？
関数の中で使っていないようですが．．．

2021-11-04 05:57 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目の行数が1である
```myTable``` は「テーブル型データ項目そのもの」ではないです。
「テーブル型データ項目の値」です。

2021-11-04 07:16 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // ファイル型データ項目に CSV ファイルを追加
> テスト仕様書としてどうかではなく、元々の動きとしてどうか、確認してもらえますか？

ファイルの列数がテーブル型データ項目よりも多い場合
・エラーは出ず、用意したテーブル型データ項目の数だけ格納される

ファイルの列数がテーブル型データ項目よりも少ない場合
・バリデーションエラー　列数が正しくありません

列数が少ない場合は、バリデーションエラーになるため、テストメソッドから「テーブル型データ項目よりも少ない列数」を消します。

テーブル型データ項目よりも多い列数の場合は、元々あったスクリプトエラーで「列数が正しくありません」と判定します。

2021-11-05 00:25 UTC, hatanaka-akihiro requested changes

2021-11-05 00:25 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +    engine.createQfile("テスト.csv", "text/tab-separated-values; charset=x-UTF-16LE-BOM","hogehoge")
違います。

`engine.createQfile()` の処理を `files.add()` の外に出すように。

2021-11-05 00:25 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  const addRow = () => {
たいして何もしていない、この関数は必要ですか？

2021-11-05 00:25 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 文字列"hogehoge"を追加する
関数 `addRow()` に引数は定義されていないですが．．．

2021-11-05 00:25 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  execute();
何も解消されていないですが。

2021-11-05 00:25 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目の行数が1である
解消していないです。

2021-11-11 04:11 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +    engine.createQfile("テスト.csv", "text/tab-separated-values; charset=x-UTF-16LE-BOM","hogehoge")
```javascript
const fileArrayList = engine.createQfile()
files.add(fileArrayList);
```
のようにしました

2021-11-11 04:15 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目の行数が1である
```
// テーブル型データ項目の値を参照する
```
に変更しました。

2021-11-11 08:08 UTC, hatanaka-akihiro requested changes

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  execute();
// <script> のスクリプトを実行

で良いです。

「スクリプトで何を実行しているか」まで言及する必要はありません。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  files.add(fileArrayList);
// ArrayList に CSV ファイルを追加

というコメントは、この行に対して記載するべき。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 文字コードUTF-16LE-BOM, タブ区切りで"hogehoge"という文字列の「テスト.csv」
// CSV ファイルを作成

程度で良いと思います。

ちなみに

"hogehoge" という文字列の

は間違っています。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 新しい行を用意する関数
どこにも関数は見当たらないですが。。。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  engine.setData(tableDef, list);
意図的に、スクリプト実行前に、テーブル型データ項目に値を設定しているのだと思います。
今は１行追加しただけで、すべての列の値が空。
どうせなら、なにか設定したほうが良いです。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  expect(numOfCols).toEqual(1);
ちなみに、これは「 0 行目の列数が 1 であること」しか確認していない。
本当は、「1 行目の列数が 1 であること」も確認したほうが良いです。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +test("overwrite-2row-1column", () => {
先の "success-2row-1column" のテストケースと、どういう違いをもたせようとしたのでしょうか？

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // 新しい行を用意する関数
わざわざ関数を用意する必要があるのでしょうか。

2021-11-11 08:08 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  addRow('', '', '', '');
addRow() 関数には引数が定義されていませんが。。。

2021-11-18 04:49 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +test("overwrite-2row-1column", () => {
```
newRow.setCol(0, "fugafuga");
```
で上書きしました。

2021-11-18 04:57 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  engine.setData(tableDef, list);
```
newRow.setCol(0, "hogehoge");
```
を設定しました。

2021-11-18 07:53 UTC, hatanaka-akihiro requested changes

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  expect(numOfCols).toEqual(1);
今度は、「1 行目の列数が 1 であること」しか確認していないです。
0 行目も 1 行目も 列数が 1 であることを確認するようにしてみましょう。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目に ListArray を作成する
'overwrite-2row-1column' のテストケースと同じく、「テーブル型データ項目の既存の値が、上書きされる」ことを確認していますよ。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目に ListArray を作成する
'overwrite-2row-1column' のテストケースと同じく、「テーブル型データ項目の既存の値が、上書きされる」ことを確認していますよ。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目に ListArray を作成する
意図したものであれば、このテストケースの名前に 'overwrite' と入っていないのが気になります。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  expect(numOfCols).toEqual(4);
どうせなら、0 行目も 1 行目も列数が 4 であることを確認しましょう。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +        throw `列数が正しくありません`
エラーメッセージは英語にするように。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +        throw `列数が正しくありません`
多言語対応を考えて。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  // テーブル型データ項目に ListArray を作成する
テーブル型データ項目に値を持たせた状態で、テストをしなくて良いかな。

結果に影響を与えないので。

2021-11-18 07:53 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  const list = tableDef.createListArray();
テーブル型データ項目に値を持たせた状態で、テストをしなくて良いかな。

結果に影響を与えないので。

2021-11-23 00:15 UTC, hatanaka-akihiro requested changes

2021-11-23 00:15 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  engine.setData(tableDef, null);
デフォルト値は null なので、書かなくても良いです。今のままでも問題ありません。

2021-11-23 00:15 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +  expect(myTable.get(0, 0)).toEqual("hogehoge");
このテストケースでは、ここにコメントを書かないのですね。
「行数」「列数」と書いてきているのに。
```
// テーブル型データ項目の各カラムの値
```
と書いては？

2021-11-23 00:15 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> + * 上書きした2行1列の正常系
「上書き」というキーワードとプログラムから内容を理解するけど、文章としては変です。
1 文にまとめる必要はないです。
1 文目は「2行1列の正常系」。2 文目は考えましょう。

2021-11-23 00:15 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +        throw `Incorrect number of columns`
エラーメッセージから、何行目か解るようにしよう。

2021-11-23 00:15 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +test("over-columns", () => {
このパターンも、スクリプトのレベルでエラーとなるようにしてください。

2021-11-24 08:59 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> + * 上書きした2行1列の正常系
```
/**
 * 2行1列の正常系
 * テーブル型データ項目の値を上書き
 */
```
に変更しました。

2021-11-24 09:04 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +        throw `Incorrect number of columns`
```
      if (cellsArray.length < newRow.size() || newRow.size() > cellsArray.length) {
        throw `Incorrect number of columns in line 52`;
      }
```
としました。

2021-11-25 04:00 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> + * }}
`tableDef`プロパティは文字列のため、`String`にしました。

2021-11-25 04:04 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +  engine.setData(tableDef, null);
了解です。`engine.setData(tableDef, null);`だと型がわかりやすいと思うのでそのままにしておきます。

2021-11-25 05:22 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> + * }}
「テーブル型データ項目というオブジェクトを返す。」ように書き方を修正しました。
```
/**
 * 1列のテーブル型データ項目の設定の準備
 * @return {Object} tableDef テーブル型データ項目
 */
```

2021-11-25 08:17 UTC, hatanaka-akihiro requested changes

2021-11-25 08:17 UTC, hatanaka-akihiro commented on converter-excelcsv-to-table.xml
> +        throw `Incorrect number of columns in line ${newRow.size()}`;
`newRow.size()` はテーブルの列数だと思います。
テーブルの行数 (=ファイルで何行目か) を指定したいのでは？

2021-11-26 08:45 UTC, Tonoyama commented on converter-excelcsv-to-table.xml
> +        throw `Incorrect number of columns in line ${newRow.size()}`;
テーブルの行数に変更しました。
```
 // テーブル型データ項目の値の行数
const numOfRows = myFiles.size();
if (cellsArray.length !== newRow.size()) {
  throw `Incorrect number of rows at ${numOfRows.size()}`;
}
```

2021-12-02 05:26 UTC, merged