単体テストのコードを追加
Questetra/Addon-XML pull request #364
Opened 2021-10-07 05:55 UTC by suese-sayaka

@hatanaka-akihiro  さん

色々よく分かっていないのですが、コードを作成しました。
何が良くないかとか、理解できていないかとか、教えてください。

2021-10-07 06:27 UTC, hatanaka-akihiro requested changes
２つコメントを書きましたが、

まずは converter-dateToJaEra および converter-textfile-to-string の単体テストがどういう内容になっているか、しっかり理解するところから始めましょう。

2021-10-07 06:27 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +
ここまでは「データ項目やデータの準備」。

この後、`execute()` で `<script>` タグのスクリプトを実行させ、
`expect()` を使用してスクリプトの実行結果を確認する必要があります。

2021-10-07 06:27 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    configs.putObject('File_Name', stringDef);
stringDef は「文字型データ項目」になっていますが、'FILE_NAME' は`form-type="SELECT"` ではないので、おかしいです。

2021-10-11 02:41 UTC, hatanaka-akihiro requested changes
全般的にコメントを追加すること。

2021-10-11 02:41 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const assertFile = (file, name, contentType) => {
インデントを整える。

2021-10-11 02:41 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    expect(file.getContentType()).toEqual(contentType);
ファイルの中身をチェックする部分も含めてしまった方が良いです。

2021-10-11 02:41 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const textdata = 'test\test\test'
`test\test\test` は、テストで意図した文字列でしょうか。

`\t` はコントロールコードです。

意図した文字列なら良いですが。

2021-10-11 05:14 UTC, suese-sayaka commented on generator-textfile.xml
> +    expect(file.getContentType()).toEqual(contentType);
修正しました

2021-10-11 05:14 UTC, suese-sayaka commented on generator-textfile.xml
> +    const textdata = 'test\test\test'
\n に修正しました

2021-10-11 05:44 UTC, hatanaka-akihiro requested changes

2021-10-11 05:44 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +test('success1', () => {
がんばって、それらしいテスト名を考えましょう。
(数字の 1 2 で区別するのは、極力、避ける)

2021-10-11 05:44 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const file0 = files.get(0);
`assertFile()` と、ファイルに関するチェックを、別関数にまとめていたのは良かったです。

前の指摘は、`assertFile()` の中で、ファイルの中身もチェックした方が良い、という指摘です。

2021-10-11 05:44 UTC, hatanaka-akihiro commented on generator-textfile.xml
> + * ファイル型データに中身の無いファイルが１つ添付されている
> ファイル型データに添付ファイルが無い
> 指定されているファイルの中身が空
> のパターンも、勉強もかねて、テストケースとして追加してください。

という条件と違っています。

2021-10-11 05:44 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const file0 = files.get(0);
つまり `assertFile()` という関数が無くなったのは残念です。

2021-10-11 06:09 UTC, hatanaka-akihiro commented on generator-textfile.xml
> + * ファイル型データに中身の無いファイルが１つ添付されている
> 指定されているファイルの中身が空

とは、

Text_Data の設定値が空文字列

という意味です。

2021-10-12 00:52 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

再修正しました。

以下、どのように修正が必要なのか教えてください。
事前に設定しているファイルの中身と、作成されたファイルの中身は同じですが、「assertFile」関数で、事前に設定しているファイルでエラーが出ます。
「クラスパスには複数のSLF4Jバインディングが含まれます」というエラーです。

https://sanjo.questetra.net/jenkins/view/trunk/job/userweb_test_addon/lastBuild/com.questetra$bpms/testReport/com.questetra.bpms.core.event.addon.test/ScriptTest/success___1file_attached/

2021-10-12 02:22 UTC, hatanaka-akihiro requested changes

2021-10-12 02:22 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    files.add(engine.createQfile('事前ファイル.txt', 'text/plain', textdata));
ここで textdata は使用しないほうが良いです。

また事前に添付されているファイルの中身は、Text_Data と同じ値で無い方が良いです。

「Text_Data の設定に影響を受けない」という確認にならないので。

2021-10-12 02:22 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    expect(text).toEqual(content);
ファイルの中身が `test\ntest\ntest` であるファイルを

```
    let text = '';
    fileRepository.readFile(file, 'UTF-8', (line) => {
        text += line + '\n';
    });
```

で読み込んだら、text の値がどのようになるか、手計算で確かめてみましょう。
`test\ntest\ntest` にならないはずです。
`1\n2\n3\n` も `1\n2\n3\n` になりません。
なるようにするためには、一工夫必要です。

2021-10-12 02:22 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    engine.setData(fileDef, null);
コメントを追加する。

2021-10-12 03:02 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    expect(text).toEqual(content);
```fileRepository.readFile()``` の3番目の引数 (関数) が呼ばれる回数。1 行ごとに呼ばれる仕様ですが

空文字列 -> 0 回
`1\n2\n3\n` -> 3 回
`1\n2\n3` -> 3 回
`1\n\n2\n3` -> 4 回

途中の空行で関数は呼ばれるものの、最後の空行では呼ばれない。

2021-10-12 03:19 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ありがとうございます。
「assertFile」関数　を修正しました。
空文字列の場合と、そうでない場合で、処理を分けました。
よろしくお願いいたします。
テストはOKでした。

2021-10-12 03:32 UTC, hatanaka-akihiro requested changes

2021-10-12 03:32 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const assertFile = (file, name, contentType, content) => {
インデントが良くないです。

2021-10-12 03:32 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +	}else
if と同じく、中括弧を使うこと。

2021-10-12 03:32 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    assertFile(file1, 'テスト.txt', 'text/plain', textdata);
`textdata` と同じように、 `filename` を使わないのは何故か。

2021-10-12 03:57 UTC, suese-sayaka commented on generator-textfile.xml
> +    const assertFile = (file, name, contentType, content) => {
修正しました

2021-10-12 03:57 UTC, suese-sayaka commented on generator-textfile.xml
> +	}else
修正しました

2021-10-12 03:57 UTC, suese-sayaka commented on generator-textfile.xml
> +    assertFile(file1, 'テスト.txt', 'text/plain', textdata);
修正しました

2021-10-12 03:57 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
再修正しました。よろしくお願いいたします。

2021-10-12 05:01 UTC, hatanaka-akihiro requested changes

2021-10-12 05:01 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    files.add(engine.createQfile('事前ファイル.txt', 'text/plain', '事前ファイル'));
あえてファイルの中身を `\n` 終わりにするように。

2021-10-14 02:01 UTC, suese-sayaka commented on generator-textfile.xml
> +    }else{
対応しました

2021-10-14 02:01 UTC, suese-sayaka commented on generator-textfile.xml
> +    files.add(engine.createQfile('事前ファイル.txt', 'text/plain', '事前ファイル'));
修正しました

2021-10-14 04:54 UTC, hatanaka-akihiro requested changes

2021-10-14 04:54 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    }
まだ `assertFile()` のインデントはおかしいです。

2021-10-14 04:54 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +}
正規表現を使わずとも、簡単に実現できます。

関数を定義するなら、他にあわせて、アロー関数にするように。

ただ簡単な判定なので、別関数にしなくても良いと思います。

2021-10-14 04:54 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    engine.setData(fileDef, null);
修正されていないです

2021-10-18 00:39 UTC, suese-sayaka commented on generator-textfile.xml
> +    }
インデントを修正しました。

2021-10-18 04:47 UTC, merged