field 属性を指定、単体テストコードを追加
Questetra/Addon-XML pull request #367
Opened 2021-10-19 03:00 UTC by suese-sayaka

@hatanaka-akihiro  さん

スクリプトに field 属性を指定しました。
単体テストコードを追加しました。

よろしくお願いいたします。

2021-10-19 03:11 UTC, hatanaka-akihiro requested changes

2021-10-19 03:11 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +// 文字型データ項目を準備して、config に指定
インデントは次の行に揃える

2021-10-19 03:11 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> + * @param configs
@param を書くなら、きちんと全部書く。そうか一切、書かない。

2021-10-19 03:11 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
'Email address is blank' と似ているので、コメントに、どういうテストケースか記載してください。

2021-10-19 03:11 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +        assertRequest(request, 'testuser@questetra.com', '12345','file', 'editor');
リクエスト内容は、テストケースごとに変えるべき。まったく同じは意味がないです。

2021-10-19 04:28 UTC, suese-sayaka commented on box-collaboration-add.xml
> + * @param configs
修正しました

2021-10-19 04:29 UTC, suese-sayaka commented on box-collaboration-add.xml
> +        assertRequest(request, 'testuser@questetra.com', '12345','file', 'editor');
リクエスト内容をテストケースで変えました。

2021-10-19 04:29 UTC, suese-sayaka commented on box-collaboration-add.xml
> +// 文字型データ項目を準備して、config に指定
修正しました。

2021-10-19 04:30 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。
よろしくお願いいたします。

2021-10-19 04:36 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
コメント内容が間違っていると思います。

2021-10-19 04:38 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Failed - other collaboration failures', () => {
テスト名から、テストの内容が解りませんでした。改良してください。

2021-10-19 04:40 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
すべてのテストケースについて、コメントを記載してください。

「わかりにくいものだけ」と思っていましたが、すべてに。

2021-10-19 04:41 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> + * @param configs
他にもあります。

2021-10-21 02:35 UTC, suese-sayaka commented on box-collaboration-add.xml
> + * @param configs
リクエストのテストのパラメータを修正しました。

2021-10-21 02:35 UTC, suese-sayaka commented on box-collaboration-add.xml
> +test('Email address is null', () => {
コメント内容を修正しました。

すべてのテストケースにコメントを記載しました。

2021-10-21 02:36 UTC, suese-sayaka commented on box-collaboration-add.xml
> +test('Failed - other collaboration failures', () => {
テスト名を修正しました。

2021-10-21 02:36 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
再修正しましたのでご確認をお願いいたします。

2021-10-21 03:10 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> + */
url method contentType body はオブジェクト内のプロパティなので、厳密には、違う形での記載になるはずです。

JSDoc のマニュアルを調べてみてください。

https://jsdoc.app/tags-param.html

2021-10-21 03:12 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
「設定」は、configs の方で使用した方が良い言葉。
もうちょっときちんと記載した方が良いです。

conf_EmailAddress にデータ項目を設定しているが．．．

2021-10-21 03:14 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
あと関数に対するコメントは

```
/**
 *
 */
```

の形の方が良いです。

2021-10-21 03:14 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +// 固定値（メールアドレス）を指定していて、空の場合
これも。他も見直してください。

conf_EmailAddress に固定値で設定しているが．．．

2021-10-21 03:14 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +// 固定値（メールアドレス）を指定していて、空の場合
各テストケース（関数）に対するコメント。他も含めて、もう一度、見直してください。

2021-10-21 04:36 UTC, suese-sayaka commented on box-collaboration-add.xml
> + */
ありがとうございます。
記載を修正しました。

2021-10-21 04:37 UTC, suese-sayaka commented on box-collaboration-add.xml
> +// 固定値（メールアドレス）を指定していて、空の場合
各テストケース（関数）に対するコメントを修正しました。

/**
 *
 */
の形に修正しました。

2021-10-21 06:53 UTC, hatanaka-akihiro requested changes

2021-10-21 06:53 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> + * @param {Object}request
おそらく {Object} のあと、スペースが必要

2021-10-21 06:53 UTC, hatanaka-akihiro commented on box-collaboration-add.xml
> +test('Email address is null', () => {
テストケースのコメント見直しを、もう１度。

2021-10-25 00:46 UTC, suese-sayaka commented on box-collaboration-add.xml
> + * @param {Object}request
修正しました

2021-10-25 00:47 UTC, suese-sayaka commented on box-collaboration-add.xml
> +test('Email address is null', () => {
コメントを修正しました

2021-10-25 06:37 UTC, merged