fields 属性を指定　単体テストコードを追加
Questetra/Addon-XML pull request #373
Opened 2021-11-01 05:57 UTC by suese-sayaka

@hatanaka-akihiro  さん

fields 属性を指定しました。
単体テストコードを追加しました。

ご確認をお願いいたします。

2021-11-01 06:21 UTC, hatanaka-akihiro requested changes

2021-11-01 06:21 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    .queryParam("fields", " ")
スペースが必要でしたか？

2021-11-01 06:21 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    expect(url).toEqual(`https://api.box.com/2.0/files/${fileId}?fields=+`);
queryParam() のところで、スペースなしでも動くのであれば、この URL も変わるはず。

2021-11-04 01:15 UTC, suese-sayaka commented on box-file-move.xml
> +    .queryParam("fields", " ")
スペースが必要でした。
最初、空文字で試したのですが、空（""）を指定すると、レスポンスは標準レプリゼンテーションになりました。
スペース（" "）を指定したところ、レスポンスは簡易レプリゼンテーションになりましたので、スペースを指定しました。
いずれもBox側のAPI呼び出しの実行と QBPMS で確認済です。
チケットにこのことを記載しておくべきでした。

2021-11-04 01:25 UTC, hatanaka-akihiro requested changes

2021-11-04 01:25 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    .queryParam("fields", " ")
@suese-sayaka 

> チケットにこのことを記載しておくべきでした。
コードに、コメントとして記載しておくべきです。
将来、コードを改良しようとする人も、このスペースに疑問を持つはずなので。

その前に、2 つ確認です。

空 ("") の場合、assertRequest() でのテストで、URL に fields パラメータは含まれていましたか？QBPMS 本体の動きの影響を受けているかどうかの確認です。

Box API リファレンスにある「この API を試す」機能で、空("") だとダメだと確認しましたか？

2021-11-04 01:56 UTC, suese-sayaka commented on box-file-move.xml
> +    .queryParam("fields", " ")
@hatanaka-akihiro  さん

空 ("") の場合、assertRequest() でのテストで、URL に fields パラメータは含まれていました。
...les/87654321?fields=[]　のように、空を指定していました。

スクリプトで fields を何も指定しない（.queryParam("fields", "")　自体のコードを記載しない）場合、assertRequest() でのテストで、URL に fields パラメータは含まれませんでした。
...m/2.0/files/87654321[]　のように、 fillds の記載がありませんでした。

Box API リファレンスにある「この API を試す」機能で、空("") だとレスポンスは標準レプリゼンテーションが返ってくることを確認済です。
QBPMS 側でも確認済です。

2021-11-04 02:08 UTC, hatanaka-akihiro requested changes

2021-11-04 02:08 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    .queryParam("fields", " ")
@suese-sayaka 
了解です。ならコメントにしっかり記載するように。

結局、「レスポンスにフィールドは含まれない」ようにはできないので、"id" を指定するのが良いかもしれません。スペース 1 つより意味を持っているので。

2021-11-04 02:55 UTC, hatanaka-akihiro requested changes

2021-11-04 02:55 UTC, hatanaka-akihiro commented on box-file-move.xml
> +        //レスポンスは、簡易版レプリゼンテーション
「簡易版リプリゼンテーション」ではないです。
ファイルの「簡易版」には、id, type, etag のほかに、file_version や name 等が含まれます。

https://ja.developer.box.com/reference/resources/file--mini/

2021-11-04 02:57 UTC, suese-sayaka commented on box-file-move.xml
> +    .queryParam("fields", " ")
@hatanaka-akihiro  さん
"id" 指定に変更しました。
ご確認をお願いいたします。

2021-11-04 03:03 UTC, hatanaka-akihiro requested changes

2021-11-04 03:03 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', null);
小さな NG ですが、この時点では folderId を指定した方が良いです。

「conf_FolderId にデータ項目を設定しているが、そのデータ項目の値が空でエラーになる場合」との違いは、次の行しかない。

「次の行で conf_FolderId が上書きされない」バグがある場合を考えると、`prepareConfigs()` で同じエラーになる設定値を用意しない方が良いです。

2021-11-04 03:06 UTC, suese-sayaka commented on box-file-move.xml
> +        //レスポンスは、簡易版レプリゼンテーション
修正しました

2021-11-04 03:08 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
コメントを修正しました。

2021-11-04 03:49 UTC, suese-sayaka commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', null);
ありがとうございます。
修正しました。

2021-11-04 03:50 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
テストコードを修正しました。

2021-11-04 04:42 UTC, hatanaka-akihiro requested changes

2021-11-04 04:42 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', '');
空文字列も意味がないです。

2021-11-04 04:59 UTC, suese-sayaka commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', '');
@hatanaka-akihiro さん
この部分を、folderId を指定（12345 など）すると、テストのビルドでNGになります。
この部分のみの変更では、NGになるということでしょうか。何か、更に処理が必要なのでしょうか。
実際、データ項目が設定されていて、データ項目の値が指定されていて、更に固定値を指定することはできるのでしょうか。

2021-11-04 05:11 UTC, hatanaka-akihiro requested changes

2021-11-04 05:11 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', '');
なるほど。どういう状態か解りませした。
`prepareConfigs()` のあと

```
configs.putObject('conf_FolderId', null);
configs.put('conf_FolderId', '');
```

でいけると思います。

が、

```
configs.put('conf_FolderId', '');
```

だけで動くように、エンジン側を改良します。

2021-11-04 05:34 UTC, hatanaka-akihiro commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', '');
@suese-sayaka 

改良しました。

2021-11-04 05:52 UTC, suese-sayaka commented on box-file-move.xml
> +    prepareConfigs(configs, '87654321', '');
@hatanaka-akihiro  さん
テストコードを修正しました。
ビルドOKでした。
ありがとうございました。

ご確認をお願いいたします。

2021-11-04 06:08 UTC, hatanaka-akihiro requested changes

2021-11-04 06:08 UTC, hatanaka-akihiro commented on box-file-move.xml
> +        expect(e.message).endsWith('No Folder ID ');
スペースが最後に入っている件、元のスクリプトを修正してもらえますか。

2021-11-08 00:41 UTC, suese-sayaka commented on box-file-move.xml
> +        expect(e.message).endsWith('No Folder ID ');
元のスクリプトを修正し、その部分の単体テストコードを修正しました。

2021-11-08 02:36 UTC, merged