add unit test code
Questetra/Addon-XML pull request #374
Opened 2021-11-02 02:36 UTC by chica-non

畠中さん

テストコードを追加しました。
出力ログを見やすいようにstatus:とエラコードの間にスペースを入れました。
レビューをお願いします。

2021-11-02 04:35 UTC, hatanaka-akihiro requested changes

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * emailAddress id は、文字型データ項目で指定
conf_EmailAddress, conf_ItemId と記載した方が良いです。
メソッド引数にある emailAddress, id と指示しているものが違うので。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * @param fileOrFolderId
同じ param が2つある

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    configs.put('conf_Role', 'viewer');
`prepareConfigs()` を使用した上で、conf_EmailAddress の設定値を更に上書きすれば良いです。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    configs.put('conf_Role', 'editor');
prepareConfigs() を使用した上で、conf_ItemId の設定値を更に上書きすれば良いです。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * conf_ItemType が 'folder' で、 conf_ItemId がルートフォルダ（"0"）でエラーになる場合
'folders' が正しいのでしょうか。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * conf_ItemType が 'folder' で、 conf_ItemId がルートフォルダ（"0"）でエラーになる場合
conf_ItemType に指定する 'files' 'folders' は、定数定義した方が良いように思いました。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, 'file', 'testuser@questetra.com', null, 'viewer');
'file' ではなく、'files' では？

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, 'folders', 'testuser@questetra.com', '0', 'editor');
conf_Role で指定する 'editor' 'viewer' も、定数定義した方が良いように思いました。

2021-11-02 04:35 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * コラボレーションのリストにコラボレーションがない(実際はeditorなのにviewerを指定)
「指定したロールに関するコラボレーションはあるけれども、指定したユーザに関するコラボレーションがない」パターンのテストケースも、あった方が良いです。

2021-11-04 03:27 UTC, chica-non commented
畠中さん

修正しました。レビューをお願いします。
指摘されたことの他に、不要なコードを削除し、正常系について文字型データ項目の値をチェックを追加しました。

2021-11-04 04:54 UTC, hatanaka-akihiro requested changes

2021-11-04 04:54 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, FOLDERS, '', '12345', VIEWER);
これだと、

「conf_EmailAddress にデータ項目を設定しているが、そのデータ項目の値が空("") 」

になっています。固定値での指定になっていない。

(実際には、文字型データ項目の値として、空文字列は指定できない。内部で null に変換されるので)

`prepareConfigs()` の後、conf_EmailAddress の設定を固定値で上書きする必要があります。

2021-11-04 04:54 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, FILES, 'testuser@questetra.com', '', EDITOR);
'Email address is blank' でのミスと同じ。

2021-11-04 04:54 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> + * conf_ItemType が 'folder' で、 conf_ItemId がルートフォルダ（"0"）でエラーになる場合
コメントを修正できていないようです。

2021-11-08 01:33 UTC, chica-non commented
畠中さん

指摘事項を修正しました。レビューをお願いします。

2021-11-08 02:56 UTC, hatanaka-akihiro requested changes

2021-11-08 02:56 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, FOLDERS, '', '12345', VIEWER);
- 文字型データ項目の値として、空は指定できない。
- `configs.put('conf_EmailAddress', '');` がなかったとしても、`Email address is blank` のスクリプトエラーになる

ので、emailAddress に指定する値は「`Email address is blank` のエラーにならない値」が良いです。

2021-11-08 02:56 UTC, hatanaka-akihiro commented on box-collaboration-delete.xml
> +    prepareConfigs(configs, FILES, 'testuser@questetra.com', '', EDITOR);
再び `Email address is blank` の指摘事項と同じです。

2021-11-09 03:23 UTC, chica-non commented
畠中さん

レビューをお願いします。
prepareConfigsの引数を''から任意の値に変更しました。

2021-11-10 01:10 UTC, merged