単体テストコードを追加
Questetra/Addon-XML pull request #376
Opened 2021-11-08 05:42 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストコードを追加しました。
ご確認をお願いいたします。

2021-11-08 06:43 UTC, hatanaka-akihiro requested changes

2021-11-08 06:43 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +    if ( folderId === "" || folderId === null ){
ここでの分岐はあまり良くないと思います。

関数呼び出し側にて、引数の値として '0' を指定させる方が良いと思います。

「folderId が空なら 0 になる」ということが解りやすくなると思うので。

2021-11-08 06:43 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +                  "type": "filer",
file の誤字ですか？

2021-11-08 06:43 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +});
marker を使用して、2 回以上、リクエストを送るパターンのテストケースを追加してください。

リクエストを繰り返した結果、HTTPリクエスト数の上限を超えてしまう場合のテストケースも追加してください。

2021-11-09 01:15 UTC, suese-sayaka commented on box-folder-search.xml
> +});
@hatanaka-akihiro  さん

教えてください。

473 行目以降に、marker を使用して2回以上リクエストを送るテストケースを記載したのですが、marker の使用や、2回のリクエストの書き方がおかしいでしょうか。
スクリプトの意味は理解できたつもりのですが、テストコードの書き方が分かりません。

2021-11-09 02:19 UTC, hatanaka-akihiro requested changes

2021-11-09 02:19 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +});
@suese-sayaka 

他のアイテムの単体テストでやっていますが、「1, 2... n 回目のリクエストでは．．．」という形で `httpClient.setRequestHandler()` を構成することです。

2021-11-11 02:47 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

2 回以上、リクエストを送るパターンのテストケースを追加しました。
リクエストを繰り返した結果、HTTPリクエスト数の上限を超えてしまう場合のテストケースを追加しました。

ご確認をお願いいたします。

2021-11-11 03:01 UTC, hatanaka-akihiro requested changes

2021-11-11 03:01 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +test('200 Success - 3 entries', () => {
`test()` の第1引数の話。

API リクエストとしては成功していますが、「検索するフォルダが無い」という意味では異常系。その旨が解るような名前にして欲しいです。

2021-11-11 03:01 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +});
@suese-sayaka 

現状でも構わないのですが、requestCount によって、responseObj が変わるように作ってみてください。できると思います。

2021-11-11 04:52 UTC, suese-sayaka commented on box-folder-search.xml
> +test('200 Success - 3 entries', () => {
名前を修正しました。

2021-11-11 04:52 UTC, suese-sayaka commented on box-folder-search.xml
> +});
修正しました。

2021-11-11 04:53 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。
ご確認をお願いいたします。

2021-11-11 07:15 UTC, hatanaka-akihiro requested changes

2021-11-11 07:15 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +});
あー違う。requestCount によって変えてほしいのは、entries。

実際の動作を考えると、API リクエストのたびに entries の中身は変わるはず。
同じファイル・フォルダを返すはずがないから。

末瀬さんのテストでは、entries の値が固定になっている。requestCount を活用して、entries の値も変わるようにできるはず。

かつ switch 文も要らない。requestCount だけで制御するように。

2021-11-12 05:36 UTC, hatanaka-akihiro requested changes

2021-11-12 05:36 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +});
少しヒントを書いておきます。

例えば、です。
ファイル・フォルダが合計 100,000 個あるフォルダを検索することを考えてください。
ID が 1 から 100,000。
奇数 ID がファイルで、偶数 ID がフォルダとします。

このフォルダを対象に、検索 API を返す場合のレスポンスを考えてください。
当然 limit = 1000 なので、1000 アイテムずつしかレスポンスには含まれません。

- 1 回目のリクエストで返すアイテムは 、ID が 1 から 1000 のもの。
- 2 回目のリクエストで返すアイテムは、 ID が 1001 から 2000 のもの。

と考えることになります。

2021-11-15 02:21 UTC, suese-sayaka commented on box-folder-search.xml
> +});
'Too many folders and files are in the specified folder'　のテストケースを修正しました。

2021-11-15 02:21 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

'Too many folders and files are in the specified folder'　のテストケースを修正しました。
ご確認をお願いいたします。

2021-11-15 02:46 UTC, hatanaka-akihiro requested changes

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +test('200 success - 2 requests', () => {
'Too many folders and files are in the specified folder' と同じ RequestHandler を使用するように改良してください。

 `setRequestHandler()` の処理を別関数として、共通で呼び出すようにできると思います。

その上で検索するフォルダ名を `test3002` など、2 回目以降の GET リクエストで見つかるフォルダの名前にする。

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +                      "id": (limitCount + 1) + requestCount*1000,
`(limitCount + 1) + requestCount*1000` の値は何か所かで使用しているので、for ループの先頭で、あらかじめ計算するのが良いと思います。

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +                      "name": "test${(limitCount + 1) + requestCount*1000}"
意図通り動いていないように思います。
ダブルクオートとバッククオートを間違えているのでは？

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +            // 1回のリクエストで responseObj の 配列"entries" に 1000 アイテム分の簡易版レプリゼンテーションを push する
「1 回のリクエストで」は要らないのでは？

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +            for(let limitCount = 0; limitCount < 1000; limitCount++){
変数名が変だと思いました。
ループをまわすための変数は、`i` `j` 一文字変数で良いです。

2021-11-15 02:46 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +            // 10回目のリクエストで返すアイテムは 、ID が 9001 から 10000 のもの
本当に？

例えば 1 回目のリクエストの際、この時点で requestCount の値は 1 になっていると思います。requestCount が 1 なら ID が 1001 から 2000 のアイテムを返しているはず。

2021-11-15 05:04 UTC, suese-sayaka commented on box-folder-search.xml
> +                      "name": "test${(limitCount + 1) + requestCount*1000}"
修正しました。

2021-11-15 05:05 UTC, suese-sayaka commented on box-folder-search.xml
> +            // 1回のリクエストで responseObj の 配列"entries" に 1000 アイテム分の簡易版レプリゼンテーションを push する
削除しました。

2021-11-15 05:05 UTC, suese-sayaka commented on box-folder-search.xml
> +            for(let limitCount = 0; limitCount < 1000; limitCount++){
修正しました。

2021-11-15 05:06 UTC, suese-sayaka commented on box-folder-search.xml
> +            // 10回目のリクエストで返すアイテムは 、ID が 9001 から 10000 のもの
コメント内容に合うように
const idNumber = (i + 1) + (requestCount - 1)*1000;
と修正しました。

2021-11-15 05:09 UTC, suese-sayaka commented on box-folder-search.xml
> +test('200 success - 2 requests', () => {
@hatanaka-akihiro  さん
まだ別関数にはしていません。
2回目で検索されるよう、test1002 を検索するテストケースを作成したのですが、ビルド結果が"Too many folders and files are in the specified folder"となります。
そもそも、「responseObj の 配列"entries" に 1000 アイテム分の簡易版レプリゼンテーションを push する」処理が間違っているでしょうか。配列にオブジェクトを追加できていないのかと思い、質問しました。

2021-11-15 06:01 UTC, hatanaka-akihiro requested changes

2021-11-15 06:01 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +               }
この閉じカッコのインデントがずれています。
対応する if 文にあわせて。

2021-11-15 06:01 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +test('200 success - 2 requests', () => {
entries に含まれる、ファイル名／フォルダ名は末瀬さんの意図した値になっているでしょうか。

ログ出力で確認してください。

2021-11-16 03:47 UTC, suese-sayaka commented on box-folder-search.xml
> +                      "name": "test${(limitCount + 1) + requestCount*1000}"
修正できていなかったので再修正しました。

2021-11-16 03:47 UTC, suese-sayaka commented on box-folder-search.xml
> +                      });
修正しました。

2021-11-16 03:47 UTC, suese-sayaka commented on box-folder-search.xml
> +               }
修正しました。

2021-11-16 03:49 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

setRequestHandler() の処理を別関数にしました。
ご確認をお願いいたします。

2021-11-16 04:41 UTC, hatanaka-akihiro requested changes

2021-11-16 04:41 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +let setRequestHandler = () => {
`setRequestHandler()` を上書きすることはないと思うので、`const` にするのが適当です。

2021-11-16 04:41 UTC, hatanaka-akihiro commented on box-folder-search.xml
> + * レスポンスオブジェクトを作成する
少し変か。
関数の役割が「○○を作成する」なら `createXXX()` という名前になるはず。
`setXXX()` という名前にならない。

「API リクエストに対するレスポンスを定義する」
「レスポンスを定義する」
「レスポンスを設定する」

あたりが適当だと思います。

2021-11-16 04:41 UTC, hatanaka-akihiro commented on box-folder-search.xml
> + * レスポンスオブジェクトを作成する
この関数を使用しているのは、最後 2 つのテストケースだけだと思います。

他は独自に `httpClient.setRequestHandler()` を実行している。

なので、最後 2 つのテストケースの直前に置く方が良いです。

2021-11-18 01:22 UTC, suese-sayaka commented on box-folder-search.xml
> +let setRequestHandler = () => {
修正しました。

2021-11-18 01:23 UTC, suese-sayaka commented on box-folder-search.xml
> + * レスポンスオブジェクトを作成する
コメントを「レスポンスを設定する」に修正しました。
この関数を最後 2 つのテストケースの直前に置きました。

2021-11-18 01:24 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
再修正しました。ご確認をお願いいたします。

2021-11-18 04:41 UTC, merged