add unit test code - google-sheets-sheet-delete
Questetra/Addon-XML pull request #379
Opened 2021-11-16 05:58 UTC by chica-non

畠中さん

テストコードを追加しました。レビューをお願いします。

2021-11-16 06:02 UTC, chica-non commented
Reviewer のリクエストをするのを忘れてました。

2021-11-18 05:41 UTC, hatanaka-akihiro requested changes

2021-11-18 05:41 UTC, hatanaka-akihiro commented on google-sheets-sheet-delete.xml
> +}
たいした話ではないですが、`SAMPLE_GET` `SAMPLE_POST` も、`assertGetRequest()` `assertPostRequest()` のそばで定義で良いです。

使用するのは 'Success' のテストケース以降ですし。

2021-11-18 05:41 UTC, hatanaka-akihiro commented on google-sheets-sheet-delete.xml
> +    prepareConfigs(configs, 'abc123', 'シート1');
'abc123' だらけなので、変えた方が良いです。

せっかっく `assertGetRequest()` でシート ID を指定できるようになっているのが、意味がない。

2021-11-24 01:47 UTC, chica-non commented
畠中さん

修正しました。レビューをお願いします。

2021-11-25 03:22 UTC, chica-non commented
畠中さん

以下について修正しました。レビューをお願いします。

2021-11-26 05:47 UTC, merged