fixed case of no collaborasion.
Questetra/Addon-XML pull request #383
Opened 2021-12-07 03:06 UTC by chica-non

巽さん

レビューをお願いします。
コラボレーションが一つもないケースについて修正しました。それに伴い単体テストも追加しました。

2021-12-07 05:39 UTC, tatsumiQ requested changes
コメントを1件入れていますので、ご確認ください。

あと、修正必須ではありませんが、テストコードの部分で定数の定義が点在しているのが気になりました。
もともとの書き方のように、テストコードの頭にまとめて定義しておいたほうが見やすいのではないでしょうか。

また、`SAMPLE_GET_FILE_NO_COLLABORATION` と　`SAMPLE_GET_FOLDER_NO_COLLABORATION` は、それぞれ一つの関数でしか使われていないので、その関数のなかで定義しても良いように思いました。

2021-12-07 05:39 UTC, tatsumiQ commented on box-collaboration-delete.xml
> +  if (Object.keys(jsonRes.entries).length === 0) {
`Object.keys()` は不要ではないでしょうか。
必要になるケースがあるのでしょうか。

```suggestion
  if (jsonRes.entries.length === 0) {
```

2021-12-08 00:53 UTC, hatanaka-akihiro commented
> あと、修正必須ではありませんが、テストコードの部分で定数の定義が点在しているのが気になりました。 もともとの書き方のように、テストコードの頭にまとめて定義しておいたほうが見やすいのではないでしょうか。

局所的にしか使用されていない定数は、直前に定義するでも構いません。「行ったり来たり」が理解を妨げるので。

> また、SAMPLE_GET_FILE_NO_COLLABORATION と　SAMPLE_GET_FOLDER_NO_COLLABORATION は、それぞれ一つの関数でしか使われていないので、その関数のなかで定義しても良いように思いました。

こちらはその通りです。関数内で定義しても構いません。

2021-12-08 01:39 UTC, chica-non commented
巽さん

レビューをお願いします。
以下を修正しました。
・jsonRes.entriesが空の場合、Object.keys()がなくても動きましたので、ご指摘の通り修正しました。
・テストコードの頭にまとめて定義しました。(畠中さんの指摘は今気づきました。)
・SAMPLE_GET_FILE_NO_COLLABORATION と　SAMPLE_GET_FOLDER_NO_COLLABORATIONを関数の中で宣言するように修正しました。

2021-12-09 01:08 UTC, tatsumiQ approved these changes

2021-12-09 01:08 UTC, merged