T8153: kintone: 選択肢データの一括取得　「レコード検索」に名前を変える等
Questetra/Addon-XML pull request #384
Opened 2021-12-09 02:34 UTC by tatsumiQ

2021-12-20 03:43 UTC, hatanaka-akihiro requested changes

2021-12-20 05:11 UTC, tatsumiQ commented on kintone-record-search.xml
> +  Array.prototype.push.apply(records, json.records); // レコードオブジェクトを配列に追加
`records.push(json.records)` だと、値ではなく配列が追加されてしまうためです。

2021-12-20 05:37 UTC, tatsumiQ commented on kintone-record-search.xml
> +  // フィールドコードの存在とフィールド型をチェック（フィールドコードが $id または $revision であればチェック不要）
fields の値が `$id` `$revision` だけの場合は API リクエストを送信しないよう、修正しました。

2021-12-20 05:37 UTC, tatsumiQ commented on kintone-record-search.xml
> +  return singleLineFlag;
修正しました。

2021-12-20 05:38 UTC, tatsumiQ commented on kintone-record-search.xml
> +    if ( dataDef !== null ) {
修正しました。

2021-12-20 05:39 UTC, tatsumiQ commented on kintone-record-search.xml
> +  const value1DataDef = engine.createDataDefinition('値_1', 1, 'q_fieldValues1', 'STRING_TEXTAREA');
そもそも `prepareConfigs()` で空文字列を渡せば済む話でした。修正しました。

2021-12-20 06:59 UTC, hatanaka-akihiro requested changes

2021-12-20 06:59 UTC, hatanaka-akihiro commented on kintone-record-search.xml
> +  if ( Array.from(fields).some(fieldCode => !fieldCode.equals("$id") && !fieldCode.equals("$revision")) ) {
`!==` では動作しなかったですか？

2021-12-20 06:59 UTC, hatanaka-akihiro commented on kintone-record-search.xml
> +  // フィールドコードの存在とフィールド型をチェック（フィールドコードが $id または $revision であればチェック不要）
`$id` `$revision` 以外が含まれていれば、`checkFields()` を呼び出すよりも、全部 `checkFields()` の中でチェックした方が良かったかも。

1. fields をコピーした上で、`$id` と `$revision` を delete。
2. fields が空なら終わり。空でなければ、API を呼び出してチェック。

だと、のちのちの `$id` `$revision` のチェックも考慮もいらない。

2021-12-20 06:59 UTC, hatanaka-akihiro commented on kintone-record-search.xml
> +    if ( fieldCode !== '$id' && fieldCode !== '$revision' ) {
```
if ( fieldCode !== '$id' || fieldCode !== '$revision' ) {
  return;
}
```

とした方が、インデントが深くならなくて良いです。

ただ先のコメントに記載したやり方だと、この時点で `$id` `$revision` を考慮しなくて良いようにできます。

2021-12-20 06:59 UTC, hatanaka-akihiro commented on kintone-record-search.xml
> +  Array.prototype.push.apply(records, json.records); // レコードオブジェクトを配列に追加
なるほど。了解です。

MDN を見る限り `concat()` だと大丈夫そうですが、return するように変えないとだめですね。

2021-12-21 02:21 UTC, tatsumiQ commented on kintone-record-search.xml
> +  if ( Array.from(fields).some(fieldCode => !fieldCode.equals("$id") && !fieldCode.equals("$revision")) ) {
`!==` でも動作したと思います。ロジックを変えたことでこの処理が不要になりました。

2021-12-21 03:06 UTC, merged