単体テストコードを追加
Questetra/Addon-XML pull request #391
Opened 2021-12-28 02:13 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストコードを追加しました。よろしくお願いいたします。

2021-12-28 02:32 UTC, hatanaka-akihiro requested changes

2021-12-28 02:32 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    prepareConfigs(configs, null, '2020-03-14 23:45', 'word1');
`prepareConfigs` の実装とも関係する話。日時型データ項目の値は、String ではないです。

「コンバータ (Date to 和暦テキスト)」を参照すること。

2022-01-04 02:05 UTC, suese-sayaka commented on box-file-link-create.xml
> +    prepareConfigs(configs, null, '2020-03-14 23:45', 'word1');
テストコードを修正しました。よろしくお願いします。

2022-01-04 03:05 UTC, hatanaka-akihiro requested changes

2022-01-04 03:05 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    engine.setData(passwordDef, null);
prepareConfigs の fileId には null を指定するテストケースがあるのに、unsharedDate と password には、なぜ null を指定しないか。

エラーになるからだと思いますが、エラーになるような prepareConfigs() に問題がある。

2022-01-04 03:05 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +<test><![CDATA[
「有効期限、パスワードを指定しない」というテストケースも必要です。

2022-01-04 05:41 UTC, suese-sayaka commented on box-file-link-create.xml
> +    engine.setData(passwordDef, null);
修正しました

2022-01-04 05:42 UTC, suese-sayaka commented on box-file-link-create.xml
> +<test><![CDATA[
テストケース（'200 Success - Not specified both unsharedDate and password'）を追加しました

2022-01-04 05:42 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。よろしくお願いします。

2022-01-04 06:08 UTC, hatanaka-akihiro requested changes

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    if ( unsharedDate !== "" && unsharedDate !== null ){
`assertPutRequest` の呼び出し方を見ていますが、`unsharedDate !== ""` の条件は必要ですか？

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    if ( password !== "" && password !== null ){
`password !== ''` の条件は必要ですか？

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    expect(request.url).toEqual(`https://api.box.com/2.0/files/22222222?fields=shared_link`);
`assertPutRequest()` が使えない理由は？

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    engine.setData(unsharedDateDef, unsharedDate);
インデントがおかしい

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    if ( unsharedDate !== "" && unsharedDate !== null ){
`prepareConfigs()` の呼び出し方を見ていますが、`unsharedDate !== ""` の条件は必要？

2022-01-04 06:08 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    if ( unsharedDate !== "" && unsharedDate !== null ){
仮に "" だったとすると、else の方の処理は正しくなるでしょうか。

2022-01-06 02:02 UTC, suese-sayaka commented on box-file-link-create.xml
> +    if ( unsharedDate !== "" && unsharedDate !== null ){
form-type="TEXTFIELD" el-enabled="true"
と間違えていました。修正しました。

2022-01-06 02:03 UTC, suese-sayaka commented on box-file-link-create.xml
> +    if ( password !== "" && password !== null ){
form-type="TEXTFIELD" el-enabled="true"
と間違えていました。修正しました。

2022-01-06 02:03 UTC, suese-sayaka commented on box-file-link-create.xml
> +    expect(request.url).toEqual(`https://api.box.com/2.0/files/22222222?fields=shared_link`);
修正しました。

2022-01-06 02:03 UTC, suese-sayaka commented on box-file-link-create.xml
> +    engine.setData(unsharedDateDef, unsharedDate);
修正しました。

2022-01-06 02:04 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。よろしくお願いします。

2022-01-06 03:14 UTC, hatanaka-akihiro requested changes

2022-01-06 03:14 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +    prepareConfigs(configs, null, '2020-03-14 23:45:00.0', 'word1');
"2020-03-14 23:45:00" で良いです。

2022-01-06 03:14 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +        engine.setData(unsharedDateDef, unsharedDate);
```engine.setData(unsharedDateDef, null);``` の方が解りやすいです。

2022-01-06 03:14 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +        expect(bodyObj.shared_link.unshared_at).toEqual(`${(unsharedDate.toString()).slice(0,19)}.0${timezone.slice(3)}`);
テストスクリプトでは

```engine.setTimeZoneOffsetInMinutes()```

を使用して、タイムゾーンの値をコントロール可能。

```
engine.setTimeZoneOffsetInMinutes(540);
let timezone = engine.getTimeZoneId(); // timezone = 'GMT+0900'
engine.setTimeZoneOffsetInMinutes(0);
timezone = engine.getTimeZoneId(); // timezone = 'GMT'
engine.setTimeZoneOffsetInMinutes(-330);
timezone = engine.getTimeZoneId(); // timezone = 'GMT-05:30'
```
となるはず。

なので、ここでのテストは、演算を一切行わず

```expect(bodyObj.shared_link.unshared_at).toEqual(unsharedDate);```

の方が良いです。このテストが通るように、```assertPutRequest()``` の引数を指定する。

2022-01-06 05:17 UTC, suese-sayaka commented on box-file-link-create.xml
> +    prepareConfigs(configs, null, '2020-03-14 23:45:00.0', 'word1');
修正しました

2022-01-06 05:17 UTC, suese-sayaka commented on box-file-link-create.xml
> +        engine.setData(unsharedDateDef, unsharedDate);
修正しました

2022-01-06 05:19 UTC, suese-sayaka commented on box-file-link-create.xml
> +        expect(bodyObj.shared_link.unshared_at).toEqual(`${(unsharedDate.toString()).slice(0,19)}.0${timezone.slice(3)}`);
expect(bodyObj.shared_link.unshared_at).toEqual(unsharedDate);
ではエラーが出たため、スクリプトで使用されている
+ timezone.slice(3)
を追加して、通ったのですが、畠中さんの指摘とは別のことをしているでしょうか。。

2022-01-06 05:26 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +        expect(bodyObj.shared_link.unshared_at).toEqual(`${(unsharedDate.toString()).slice(0,19)}.0${timezone.slice(3)}`);
別のことをしています。

`assertPutRequest()` の引数に指定する unsharedDate の値として、bodyObj.shared_link.unshared_at の値そのものを指定するようにしてください。タイムゾーン込みの文字列を、`assertPutRequest()` の引数に指定することになります。

2022-01-06 05:30 UTC, hatanaka-akihiro commented on box-file-link-create.xml
> +        expect(bodyObj.shared_link.unshared_at).toEqual(`${(unsharedDate.toString()).slice(0,19)}.0${timezone.slice(3)}`);
タイムゾーンの値も解った上で、put リクエストの値がどのようになっているか、テストをした方が良いからです。

2022-01-11 03:36 UTC, suese-sayaka commented on box-file-link-create.xml
> +        expect(bodyObj.shared_link.unshared_at).toEqual(`${(unsharedDate.toString()).slice(0,19)}.0${timezone.slice(3)}`);
@hatanaka-akihiro  さん
テストコードを修正しました。よろしくお願いいたします。

2022-01-12 01:24 UTC, hatanaka-akihiro approved these changes

2022-01-12 01:24 UTC, merged