単体テストコードを追加
Questetra/Addon-XML pull request #394
Opened 2022-01-17 02:20 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストコードを追加しました。

スクリプト部分の113行目
.queryParam("fields", "id,webViewLink")　ですが、id　と　webViewLink　の間にスペースがあるとビルドが通らなかったので、スペースを削除しました。

よろしくお願いいたします。

2022-01-17 02:45 UTC, hatanaka-akihiro requested changes

2022-01-17 02:45 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    .queryParam("fields", "id,webViewLink")
「ビルドに失敗した」のではなく、「テストに失敗した」のでは？

`,` を `%2C` にきちんと変換したようですが、スペースを変換しなかったことが、テストに失敗した原因ではないですか？

2022-01-17 02:45 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> + * Google ドライブ に接続するユーザが空でエラーになる場合
required="true" なので、空にはなりません。

ただ指定したユーザが削除された場合、「// UserID は空ではないが、対応する QuserView がない状態」になります。

つまりコメントが適当ではありません。

2022-01-17 02:45 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    "id": `fileId${folderId}`,
実際のところ、myDriveRoot の場合の id と webViewLink はどのような値になりますか？

2022-01-17 02:45 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    "webViewLink": `link${folderId}`
Link は `http://` とか `https://` とか URL にならないですか？

ある程度、実際を踏まえた値の方が良いな、と。

2022-01-17 02:45 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> + * Conf_ParentFolderId に固定値を指定し、その固定値の値が空の場合
どうせなら、Conf_FileIdItem と Conf_WebViewUrlItem が空のパターンにした方が良いです。

`required="true"` でないのに、すべて保存するパターンなので。

2022-01-17 05:20 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +    .queryParam("fields", "id,webViewLink")
%20 の他に + があることが分かりました。（以前、%20 でビルドではなく、テストに失敗していました。）
スクリプトを元に戻しました。ありがとうございました。

2022-01-17 05:21 UTC, suese-sayaka commented on google-sheets-file-create.xml
> + * Google ドライブ に接続するユーザが空でエラーになる場合
修正しました

2022-01-17 05:22 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +    "id": `fileId${folderId}`,
ログ出力させ、確認しました。"id":"fileIdmyDriveRoot"　"webViewLink":"https://linkmyDriveRoot"

実際のオブジェクトは以下になりました。
jsonStr:
 {
 "kind":"drive#file",
 "id":"fileIdmyDriveRoot",
 "name":"ファイル5",
 "mimeType":"string",
 "description":"string",
 "starred":true,
 "trashed":true,
 "explicitlyTrashed":true,
 "parents":["string123"],
 "webContentLink":"string123",
 "webViewLink":"https://linkmyDriveRoot"
 }

2022-01-17 05:22 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +    "webViewLink": `link${folderId}`
修正しました

2022-01-17 05:22 UTC, suese-sayaka commented on google-sheets-file-create.xml
> + * Conf_ParentFolderId に固定値を指定し、その固定値の値が空の場合
修正しました

2022-01-17 05:23 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。
よろしくお願いします。

2022-01-17 05:46 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    .queryParam("fields", "id,webViewLink")
スペースなしに変えるでも良かったのですが、後学のために指摘しました。

2022-01-17 05:48 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> + * Google ドライブ に対応する QuserView がなくエラーになる場合
「Google ドライブ に対応する QuserView がなく」という表現が、変に思いました。

2022-01-17 05:48 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    "id": `fileId${folderId}`,
いや。「実際のところ」というのは、「実際に Google の API にアクセスした場合」の話でした。

2022-01-18 01:12 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +    "id": `fileId${folderId}`,
確認しました。
1回目
{
 "id": "1FZrcNOJd6NHWwzyfgegyYpNkl2RG8IBk",
 "webViewLink": "https://drive.google.com/file/d/1FZrcNOJd6NHWwzyfgegyYpNkl2RG8IBk/view?usp=drivesdk"
}

2回目
{
 "id": "1n2Xw2L9CB1AHE0ColmTsU_PSrjaxXCtHuH9B4ZA88xo",
 "webViewLink": "https://docs.google.com/spreadsheets/d/1n2Xw2L9CB1AHE0ColmTsU_PSrjaxXCtHuH9B4ZA88xo/edit?usp=drivesdk"
}

毎回変わりそうなかんじです。

2022-01-18 01:16 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

Expected: a string ending with "Failed to update sheet title \n status: 400"
     but: was "org.graalvm.polyglot.PolyglotException: expected:<...23456789:batchUpdate[]> but was:<...23456789:batchUpdate[?fields=id%2C+webViewLink&supportsAllDrives=true]>"

2022-01-18 02:59 UTC, suese-sayaka commented on google-sheets-file-create.xml
> + * Google ドライブ に対応する QuserView がなくエラーになる場合
修正しました

2022-01-18 03:00 UTC, suese-sayaka commented
畠中さん
スクリプトコードと、単体テストコードを修正しました。
よろしくお願いいたします。

2022-01-18 04:47 UTC, hatanaka-akihiro requested changes

2022-01-18 04:47 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +        return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(preparePostUpdateSheetTitleResponse('fileId45678901', 'シート4')));
`assertPostUpdateSheetTitle()` で指定している fileId と一致していないのが気になりました。

2022-01-18 04:47 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +        return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(preparePostUpdateSheetTitleResponse('fileId45678901', 'シート4')));
一致していなくても、テストの観点では問題ないのですが。

2022-01-20 01:26 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +        return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(preparePostUpdateSheetTitleResponse('fileId45678901', 'シート4')));
修正しました

2022-01-20 01:27 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。よろしくお願いします。

2022-01-20 02:43 UTC, hatanaka-akihiro requested changes

2022-01-20 02:43 UTC, hatanaka-akihiro commented on google-sheets-file-create.xml
> +    "id": `fileId${id}`,
`fileId` を入れない方が良いです。

その方が、assertPostUpdateSheetTitle() との関係がはっきりして良いです。

例えばここ。

```
            return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(preparePostCreateFileResponse('spreadsheets23456789', 'ファイル2')));
        }
        assertPostUpdateSheetTitle(request, "fileIdspreadsheets23456789", 'シート2',);
```

片方は `fileId` 始まりで、片方はそうでない。

2022-01-20 04:47 UTC, suese-sayaka commented on google-sheets-file-create.xml
> +    "id": `fileId${id}`,
修正しました

2022-01-20 04:48 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。ご確認をお願いいたします。

2022-01-20 06:05 UTC, hatanaka-akihiro approved these changes

2022-01-20 06:05 UTC, merged