add unite test code
Questetra/Addon-XML pull request #395
Opened 2022-01-17 02:50 UTC by chica-non

畠中さん

単体テストコードを追加しました。ご確認よろしくお願いします。

2022-01-17 03:31 UTC, hatanaka-akihiro requested changes

2022-01-17 03:31 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> + * UserID 該当ユーザがいない、値が空でエラーになる場合
required="true" なので、値が空にはなりません。

ただ指定したユーザが削除された場合、「// UserID は空ではないが、対応する QuserView がない状態」になります。

つまりコメントが適当ではありません。

2022-01-17 03:31 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +    if (parentFolderId === '') {
`parentFolderId === ''` の場合に、parents の値がどうなるかについてのテストも入れましょう。

2022-01-17 03:31 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +        expect(bodyObj.name).toEqual(folderName);
`name` の値は、parentFolderId の状況に関係がないと思います。

2022-01-17 03:31 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> + * 親フォルダIDが空
FolderIdItem / WebViewUrlItem のどちらかを空にしましょうか。

次の正常系テストケースは、逆にする。

2022-01-18 02:57 UTC, chica-non commented
畠中さん

指摘箇所を修正しました。レビューをお願いします。

2022-01-18 05:10 UTC, hatanaka-akihiro requested changes

2022-01-18 05:10 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +  configs.putObject('WebViewUrlItem', webViewUrlItemDef);
> FolderIdItem / WebViewUrlItem のどちらかを空にしましょうか。

「値を空にする」という意味ではなく、「設定を空にする／設定しない」という意味です。

2022-01-18 05:10 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +  configs.putObject('FolderIdItem', folderIdItemDef);
> FolderIdItem / WebViewUrlItem のどちらかを空にしましょうか。

「値を空にする」という意味ではなく、「設定を空にする／設定しない」という意味です。

2022-01-24 01:30 UTC, chica-non commented
畠中さん
レビューをお願いします。
以下を変更しました。
・if (parentFolderId === '')の処理 nullからundefinedに変更
・FolderIdItem / WebViewUrlItem を値を空から未設定に

2022-01-24 03:27 UTC, hatanaka-akihiro requested changes

2022-01-24 03:27 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +  configs.put('UserID', '3');
`configs.put('UserId', '');` が正しいです。

チケット 8217 と同じ話。

2022-01-24 03:27 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +    webViewUrlItemDef
`webViewUrlItemDef` は、この後、使用していないのでは？

2022-01-24 03:27 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +    folderIdItemDef,
`folderIdItemDef` は、この後、使用していないのでは？

2022-01-24 05:16 UTC, chica-non commented
畠中さん
レビューをお願いします。
・configs.put('UserId', ''); に変更
・FolderIdItem / WebViewUrlItemが参照されないケースでは始めから設定しないように変更

2022-01-24 05:23 UTC, hatanaka-akihiro requested changes

2022-01-24 05:23 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +  configs.putObject('FolderIdItem', folderIdItemDef);
あえて NG にします。

`prepareConfigs()` を使用するのが間違いとは言っていません。

戻り値のうち、「`webViewUrlItemDef` は要らないのでは？」という指摘です。

2022-01-24 05:24 UTC, hatanaka-akihiro requested changes

2022-01-24 05:24 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
> +  configs.putObject('WebViewUrlItem', webViewUrlItemDef);
`prepareConfigs()` を使用するのが間違いとは言っていません。

使用した方が、プログラムがスッキリして良いと思います。

2022-01-25 01:33 UTC, chica-non commented
畠中さん

レビューをお願いします。
prepareConfigs()を使うように戻しました。

2022-01-25 04:48 UTC, hatanaka-akihiro approved these changes

2022-01-25 04:48 UTC, merged