T8066: Microsoft 365 Excel: 行挿入　シート名にスペースが含まれているとスクリプトエラー
Questetra/Addon-XML pull request #401
Opened 2022-02-03 01:52 UTC by tatsumiQ

2022-02-04 06:14 UTC, hatanaka-akihiro requested changes

2022-02-04 06:14 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +test('RowNumber is not an integer', () => {
本体のコード。`retrieveRowNumber()` を修正してもらえますか。

数値型データ項目から取得した場合は BigDecimal。そうでない場合は String。

BigDecimal であることが無視されて、暗黙の型変換によって動作していると思われるので。

2022-02-07 06:31 UTC, hatanaka-akihiro requested changes

2022-02-07 06:31 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +    rowNumber = configs.get( "conf_RowNumber" );
```
  const reg = new RegExp( '^[1-9][0-9]*$' );
  if ( !reg.test( rowNumber ) ){
    throw "Row number must be a positive integer.";
  }
  rowNumber = parseInt(rowNumber, 10); //parse to int
```
この辺の処理は、固定値の場合に特化した方が良いかと。
BigDecimal から number に直接持っていった方が良い。

BigDecimal が小数かどうかは `scale() > 0` で判定可能。

2022-02-07 06:31 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +    rowNumber = configs.get( "conf_RowNumber" );
QBPMS の数値型の最大値は 1,000,000,000,000。

Java int では扱えないものの、Javascript Number で扱える範囲ですかね。

2022-02-07 06:31 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +    rowNumber = configs.get( "conf_RowNumber" );
```
const reg = new RegExp( '^[1-9][0-9]*$' );
```

も桁数の上限を指定した方が安全か。Number で扱えない数字になることを避けるため。

2022-02-08 02:57 UTC, tatsumiQ commented on excel-row-insert.xml
> +    rowNumber = configs.get( "conf_RowNumber" );
> BigDecimal から number に直接持っていった方が良い。

`.longValueExact()` で Number に変換するようにしました。
`1.0` など、scale が 1 以上でも整数として解釈できる場合は、従来通り許容するようにしました。

> QBPMS の数値型の最大値は 1,000,000,000,000。
> Java int では扱えないものの、Javascript Number で扱える範囲ですかね。

Javascript Number で扱える最大値は 2^53 - 1 らしいので、QBPMS の数値型の最大値よりも大きいです。

> 桁数の上限を指定した方が安全か。Number で扱えない数字になることを避けるため。

行番号の最大値が 1048576 なので、8 桁以上の整数はエラーになるようにしました。

2022-02-08 04:38 UTC, hatanaka-akihiro requested changes

2022-02-08 04:38 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +  configs.put('conf_RowNumber', '9999999999999999');
正規表現でエラーになるパターンは 'RowNumber is not an integer (fixed value)' にある。
なので、正規表現でエラーにならず、上限を超える値の方が良いか。

数値 7 桁で、1048576 を超える値。`9999999` など。

2022-02-08 04:38 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +  prepareConfigs(SAMPLE_URL_1, SAMPLE_SHEET_1, '-1', SAMPLE_ROW);
下限は 1 で、`RowNumber is 0` のテストケースがあるので、さほど重要でない。

どうせなら、固定値で -1 か 0 の方が良かったか。

2022-02-08 04:38 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +  const rowNum = '5';
正常系で、行番号が小数のテストケースが無い。なので、`5.0` `5.00` などにした方が良いか。

2022-02-08 05:45 UTC, tatsumiQ commented on excel-row-insert.xml
> +  configs.put('conf_RowNumber', '9999999999999999');
`9999999` でテストするよう変更しました。

2022-02-08 05:45 UTC, tatsumiQ commented on excel-row-insert.xml
> +  prepareConfigs(SAMPLE_URL_1, SAMPLE_SHEET_1, '-1', SAMPLE_ROW);
固定値 `0` でテストするよう変更しました。

2022-02-08 05:47 UTC, tatsumiQ commented on excel-row-insert.xml
> +  const rowNum = '5';
行番号が小数のケースは `Success - Some columns are blank` のテストケースでもテストしていますが、こちらは上限チェックでもあるので、`Success - All columns are blank` でも小数の行番号でテストするようにしました。

2022-02-09 02:59 UTC, hatanaka-akihiro commented on excel-row-insert.xml
> +  const rowNum = '5';
> 行番号が小数のケースは Success - Some columns are blank のテストケースでもテストしていますが、

確かに。見落としていました。

2022-02-09 03:01 UTC, hatanaka-akihiro approved these changes

2022-02-09 03:01 UTC, merged