add unite test code
Questetra/Addon-XML pull request #402
Opened 2022-02-03 05:58 UTC by chica-non

畠中さん

単体テストコードを追加しました。レビューをお願います。

2022-02-03 06:11 UTC, chica-non commented
すみません。コメント部分が間違ってたので修正しました。
レビューをお願いします。

2022-02-03 10:05 UTC, hatanaka-akihiro requested changes

2022-02-03 10:05 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> + * 共有するファイル/フォルダの ID の数が１つの場合
保存先が「文字型単一行データ項目」でエラーにならない場合のテストケースが必要。

と考えると、このテストケースは文字型単一行データ項目で用意した方が良いです。

2022-02-03 10:05 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');
先の指摘事項に関わりますが、単一行用の `prepareConfigs()` を用意した方が良いです。

そうか、`prepareConfigs()` で `STRING_TEXTAREA` `STRING_TEXTFIELD` を切り替えられるようにする。

2022-02-04 02:46 UTC, chica-non commented
畠中さん
レビューをお願いします。
指摘事項を修正しました。
・定数を削除
・文字型データ項目単一行用のprepareConfigs()を追加
・IDが1つの場合、共有したファイル/フォルダの表示 URL を保存するデータ項目を複数行から単一行にデータに変更

2022-02-04 04:37 UTC, hatanaka-akihiro requested changes

2022-02-04 04:37 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');
`prepareConfigs_single_line()` を作成した理由は？

2022-02-04 04:37 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');
`prepareConfigs()` とは別関数にするなら、違う番号・フィールド名にするように。

2022-02-04 04:37 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +  const fileIdsDef = engine.createDataDefinition('共有するファイル/フォルダの ID', 1, 'q_fileIds', 'STRING_TEXTAREA');
`prepareConfigs()` とは別関数にするなら、違う番号・フィールド名にするように。

2022-02-04 04:37 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +  const quser = engine.createQuser(3, 'サウスポール', 'SouthPole@questetra.com');
`prepareConfigs()` とは別関数にするなら、違うユーザにするように。
結果は変わら無さそうですが。

2022-02-04 04:37 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> + * 共有するファイル/フォルダの ID の数が１つの場合
コメントにしっかり記載するように

2022-02-04 04:44 UTC, chica-non commented on google-drive-permission-create.xml
> +  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');
>prepareConfigs_single_line() を作成した理由は？
「単一行用の prepareConfigs() を用意した方が良いです。」と指摘があったからです。

2022-02-04 04:58 UTC, chica-non commented on google-drive-permission-create.xml
> +  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');
すみません。そういう意味じゃなかったですよね。前回のものは以下のようになってると思います。
/**
 * 共有するファイル/フォルダの ID が複数行で URL 出力先のデータ項目が単一行エラーになる場合
 */
test('SharedUrl is Single-line String data for Multiple ids', () => {
  prepareConfigs_single_line(`abc123\ndef456`, DOMAIN, 'test2.com', false, true);
  
  // 共有したファイル/フォルダの表示 URL を保存するデータ項目(単一行)を準備
  const sharedUrlItemDef = engine.createDataDefinition('作成したフォルダの表示 URL', 2, 'q_AddedSheetTitle', 'STRING_TEXTFIELD');

2022-02-04 05:48 UTC, chica-non commented
畠中さん
レビューをお願いします。
以下を修正しました。
・prepareConfigs_single_line()のデータ定義番号、フィールド名、ユーザを変更
・IDが1つのときのコメントを修正
・不要な文字型データ項目（単数行）を準備を削除
先ほどは通ってなかった処理があったので、修正しました。

2022-02-04 05:58 UTC, merged