単体テストコードを追加
Questetra/Addon-XML pull request #403
Opened 2022-02-07 05:56 UTC by suese-sayaka

@hatanaka-akihiro  さん

ビルドが通っていなくて途中ですが、質問です。

432~435 行目で、"org.graalvm.polyglot.PolyglotException: Cannot format given Object as a Date"
のエラーが出るので、一旦コメントアウトして進めています。
このエラーについて調べていたのですが、「JSFのconvertDateTimeでCannot format given Object as a Dateとなった時の対応方法」というページが見つかりました。今回のコードもこちらが該当するのでしょうか
https://qiita.com/ponsuke0531/items/6f9c14bfedcb74464f4a

そうではなくて、コードの書き方が間違っているなら教えてください。

2022-02-07 06:47 UTC, hatanaka-akihiro commented
> 432~435 行目で、"org.graalvm.polyglot.PolyglotException: Cannot format given Object as a Date" のエラーが出るので、一旦コメントアウトして進めています。

エラーが出る理由は単純です。

`java.text.SimpleDateFormat` オブジェクトの `format()` メソッドを使用したのは、`insertEvent()` で使われていたからだと思います。これの引数 `startDate` `endDate` に渡されている値を調べたところ、日時型データ項目の値です。日時型データの値は、`java.sql.Timestamp` オブジェクトになっています。

一方、`assertPostRequest()` の `startDate` `endDate` に渡している値は、単なる String です。`format()` メソッドに指定できる値ではありません。

2022-02-07 06:52 UTC, hatanaka-akihiro commented
「同じようにしなければならない」という発想が間違い。

POST リクエスト内、`start.datetime` `end.datetime` で指定されている値は単なる String なので、String でチェックすれば良いです。「どういう文字列になっているべきか」と考えれば良いです。

`start.timeZone` と `end.timeZone` も同じ。`engine.getTimeZoneId()` などとプログラムで記載するのではなく、「どういう文字列になっているべきか」考えて、チェックする。

2022-02-08 00:44 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ありがとうございます。
「どういう文字列になっているべきか」で修正し、その箇所はビルドが通ることを確認できました。

あと、559行目以降の、「終了時刻が空」（その場合、終了時刻は、開始時刻＋1時間）のテストケースで、以下のエラーが出ます。
`org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (addHours) on java.sql.Timestamp@48809f1d failed due to: Unknown identifier: addHours`
このテストケースに足りない処理が分からないので教えてください。

2022-02-08 01:25 UTC, hatanaka-akihiro commented
> あと、559行目以降の、「終了時刻が空」（その場合、終了時刻は、開始時刻＋1時間）のテストケースで、以下のエラーが出ます。 `org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (addHours) on java.sql.Timestamp@48809f1d failed due to: Unknown identifier: addHours` このテストケースに足りない処理が分からないので教えてください。

C4 / C5 は日時型データ項目の値になるのですが、その値は正確には `java.sql.Timestamp` ではありません。
そのサブクラスの `com.questetra.bpms.util.AddableTimestamp` です。

定義ファイルを見ると 100 行目に
```
endDate = startDate.addHours(1);
```
とあるのですが、`addHours()` というメソッドは `com.questetra.bpms.util.AddableTimestamp` が持つメソッドで、`java.sql.Timestamp` は持ちません。

C4 / C5 の日時型データ項目の値を用意している `prepareConfigs()` 内の処理

```
const datetimeS = java.sql.Timestamp.valueOf(startDate); 
```

となっているところ

```
const datetimeS = new com.questetra.bpms.util.AddableTimestamp(java.sql.Timestamp.valueOf(startDate).getTime());
```

としてみてください。

2022-02-08 03:06 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ありがとうございました。ビルドが通りました。
ご確認をお願いいたします。

2022-02-08 04:49 UTC, hatanaka-akihiro requested changes

2022-02-08 04:49 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    expect(url).toEqual(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events?conferenceDataVersion=1`);
インデントを下げた方が良いです。

2022-02-08 04:49 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    expect(bodyObj.start.timeZone).toEqual('GMT+09:00');
タイムゾーンが違う場合のテストも加えるように。

box-folder-link-create / box-file-link-create

2022-02-10 02:21 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> +    expect(url).toEqual(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events?conferenceDataVersion=1`);
修正しました

2022-02-10 02:22 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。
ご確認をお願いいたします。

2022-02-10 08:19 UTC, hatanaka-akihiro requested changes

2022-02-10 08:19 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    timezone = engine.getTimeZoneId();
意図した形のリクエストになっていることを確認しないといけない。

テスト対象のコードが以下で
` myObj.start.timeZone = engine.getTimeZoneId();`

それをテストするコードが
```
timezone = engine.getTimeZoneId();
expect(bodyObj.start.timeZone).toEqual(timezone);
```

これだと、テストになっていないです。

2022-02-10 08:19 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    timezone = engine.getTimeZoneId();
リクエストで timezone 部分が、どういうテキストになっていることを期待しているか。

Google Sheets の API 仕様を確認した上で、テストのコードを記載しないといけないです。

2022-02-14 01:19 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> +    timezone = engine.getTimeZoneId();
修正しました

2022-02-14 01:19 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。ご確認をお願いいたします。

2022-02-14 03:31 UTC, hatanaka-akihiro requested changes

2022-02-14 03:31 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +const assertPostRequest = ({url, method, contentType, body}, calendarId, eventTitle, startDate, endDate, location, description, meetUrlDataDef, timezone) => {
引数の順番。
変数間の関連性から考えて、endDate 直後が良いと思います。

コメントで、timezone が抜けています。

2022-02-14 03:31 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> + * @param parentFolderId
引数に `parentFolderId` は無いのでは。

2022-02-14 03:31 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> + *     meetDef: {Object}
`idDef` `urlDef` `meetDef` について、説明を書いておきましょう。

2022-02-14 05:01 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> +const assertPostRequest = ({url, method, contentType, body}, calendarId, eventTitle, startDate, endDate, location, description, meetUrlDataDef, timezone) => {
timezone の引数の順番を修正しました
コメントに timezone を追加しました

2022-02-14 05:01 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> + * @param parentFolderId
削除しました

2022-02-14 05:01 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> + *     meetDef: {Object}
説明を追加しました

2022-02-14 05:01 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
単体テストコードを修正しました。ご確認をお願いします。

2022-02-14 05:50 UTC, hatanaka-akihiro approved these changes

2022-02-14 05:50 UTC, merged