ハイフンを含むカレンダーIDに対応
Questetra/Addon-XML pull request #406
Opened 2022-02-21 01:58 UTC by suese-sayaka

@hatanaka-akihiro  さん

375行目の、「カレンダーIDにサポート外の文字が含まれていてエラーになる場合」のテストが通りません。

エラーメッセージが、以下になるのですが、これはどういう意味でしょうか
Expected: a string ending with "Invalid Calendar ID"
     but: was "
  Unexpected method call QbpmConfiguration.getLocale():"

2022-02-21 03:16 UTC, hatanaka-akihiro commented
" Unexpected method call QbpmConfiguration.getLocale():"

どこでこのエラーが発生しているのか解りませんが、テストで指定されているカレンダー ID は
"Invalid Calendar ID" となるようなカレンダー ID なのでしょうか。

"Invalid Calendar ID" とならない場合、"Event End Date comes before Event Start Date" のエラーが
出るような設定に変えては。

2022-02-21 05:32 UTC, suese-sayaka commented
もう一度調べなおし、カレンダーIDをチェックする処理を修正
ビルドがとおることを確認
QBPMS でテストケースをピックアップして確認
ハイフンを含むメールアドレスが無いため、QBPMSではそのテストができていない

2022-03-08 04:01 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
ソースコードを修正しました。ご確認をお願いいたします。

2022-03-09 08:19 UTC, hatanaka-akihiro requested changes

2022-03-09 08:19 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    prepareConfigs(configs, 'efghi^\w\.#?()＠56789!""#$%&\'+,/:;<=>[]^``.com', 'event5', '2022-01-05 10:03:00', '2022-01-05 18:03:00', 'location5', 'description5');
「サポート外」の文字を色々と含めると、「どれでエラーになっているか解らない」という問題があります。どれか 1 つだけの方が良いです。(実際に手でテストをする場合と同じです)

google-calendar-event-delete では 3 つの文字について、テストされていました。つまり Invalid Calendar ID で 3 つテストケースがある。

2022-03-09 08:19 UTC, hatanaka-akihiro commented on google-calendar-event-insert.xml
> +    } = prepareConfigs(configs, 'ghijk_78901-_.!*\'@a-sample.com', 'event7', '2022-01-07 10:03:00', '2022-01-07 18:03:00', 'location7', 'description7');
このテストケースが、カレンダー ID に許可されている文字をすべて使ったテストケースだと思います。
その旨をコメントにきちんと記載してください。

2022-03-10 02:15 UTC, suese-sayaka commented on google-calendar-event-insert.xml
> +    prepareConfigs(configs, 'efghi^\w\.#?()＠56789!""#$%&\'+,/:;<=>[]^``.com', 'event5', '2022-01-05 10:03:00', '2022-01-05 18:03:00', 'location5', 'description5');
どれか 1 つだけ サポート外の文字を含むIDのテストケースを、３つ作成しました。

2022-03-10 05:40 UTC, hatanaka-akihiro approved these changes

2022-03-10 05:40 UTC, merged