add unite test code and fix to handle if calenderID contains hypens
Questetra/Addon-XML pull request #407
Opened 2022-02-22 02:18 UTC by chica-non

畠中さん

レビューをお願いします。
・単体テストコードを追加
・ハイフンを含むカレンダー ID でも処理できるように修正

2022-02-22 06:26 UTC, hatanaka-akihiro requested changes

2022-02-22 06:26 UTC, hatanaka-akihiro commented on google-calendar-event-delete.xml
> +  if (calendarId.search(/^[\w!-/:-@¥[-`{-~]+$/) === -1) {
\w 以外、どの文字を許可する意図だったか、列挙してもらえますか。

`[` あたりが意図通りなのか、始まりのカッコがあるのに、
終わりのカッコが無いのはなぜか。

2022-02-22 06:26 UTC, hatanaka-akihiro commented on google-calendar-event-delete.xml
> +  if (calendarId.search(/^[\w!-/:-@¥[-`{-~]+$/) === -1) {
ASCII コード表の 33 番から 126 番を、ハイフンで範囲指定する正規表現はどうでしょうか。

`^[\x33-\x7E]+$`

2022-02-22 06:26 UTC, hatanaka-akihiro commented on google-calendar-event-delete.xml
> +  if (calendarId.search(/^[\w!-/:-@¥[-`{-~]+$/) === -1) {
そうか

> 予定削除成功(カレンダーID にurlで使える全ての記号を含む)

にあわせる。ここで使われている記号を増やす。

2022-02-25 02:03 UTC, chica-non commented on google-calendar-event-delete.xml
> +  if (calendarId.search(/^[\w!-/:-@¥[-`{-~]+$/) === -1) {
畠中さん
!-/:-@¥[-`{-~はASCIIコード〇～△までというような意味です。それぞれ以下の通りです。途中の\はエスケープです。
!-/ 　!から/まで　→　!"#$%&'()*+,-./
:-@　:から@まで　→　:;<=>?@
[-`　[から`まで　→　[\]^_`
{-~　{から~まで　→　{|}~
上記が[]中身の説明で、+$が末尾に[]の文字が 1 回以上という意味です。*$だと* は 0 回以上の繰り返しとなり、半角スペースを許可してしまう。

2022-03-01 01:41 UTC, hatanaka-akihiro commented on google-calendar-event-delete.xml
> +  if (calendarId.search(/^[\w!-/:-@¥[-`{-~]+$/) === -1) {
カレンダー ID の指定次第で、「他の API へのリクエストになってしまう」のは避けたいと思いました。

リリースされているバージョンでは

- 半角英数
- 記号は `.@` の 2 つ

が許可されていると思いますが、以下にしてください。

- 半角英数
- 記号は `-_.!*'@` の 7 つ (マイナス、アンダーバー、ピリオド、びっくり、アスタリスク、シングルクオート、アットマーク)

「予定削除成功(カレンダーID にurlで使える全ての記号を含む)」のテストケースと、メールアドレスで使用可能な文字を考慮。

- `#?` などはメールアドレスで使用可能だが、URL で特別な意味を持つので除外。
- `()\` は URL で使用可能だが、メールアドレスでは普通には使えないので除外。

2022-03-08 05:49 UTC, chica-non commented
畠中さん
レビューをお願いします。
カレンダーIDに半角英数、記号は -_.!*'@ の 7 つのみ許可するように変更しました。

2022-03-09 08:13 UTC, merged