Google スプレッドシート: 行取得　単体テストの追加
Questetra/Addon-XML pull request #409
Opened 2022-03-11 05:45 UTC by R-Matsubayashi

以下の事柄についての単体テストを追加
・行指定が不適切
・行番号が空
・列指定が不適切
・同じデータ項目を異なる列の出力に指定
・正常に取得できる
・404エラー
・取得した部分のセルがすべて空

2022-03-11 06:32 UTC, hatanaka-akihiro requested changes

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +const prepareConfigs = (configs, sheetId, sheetTitle, row, range, type) => {
残余引数
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/rest_parameters

を使ってはどうか。

かつ `type` は `types` に変える。複数ある前提のようなので。

`(configs, sheetId, sheetTitle, row, range, ...types) => {`

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    type.forEach(element => {
`type` を `types` に変えるので、`element` に `type` を使用したら良いです。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    prepareConfigs(configs, 'id', 'title', 'invalidrow', 'A:B', ['STRING_TEXTFIELD', 'STRING_TEXTFIELD']);
残余引数に変えると

`prepareConfigs(configs, 'id', 'title', 'invalidrow', 'A:B', 'STRING_TEXTFIELD', 'STRING_TEXTFIELD');`

に変わります。最後が配列でなくなる。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    type.forEach(element => {
`forEach` 第2引数は index なので、それを使う方が良いと思いました。

`types.forEach((type, index) => {`

ただし index は 0 始まりなので、1 始まりである今と異なります。
それはあわせる必要があります。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    */
コードを書きやすくするためのコメントでしょうか。消し忘れですかね。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    configs.put('conf_RowNo', row);
`conf_RowNo` は、`editable=false` の項目なので、データ項目経由でしか値を取得しない。その前提のコードになっていません。

`retrieveRowNo()` の実装が、`editable=true` を前提にしているため、勘違いしたのだと思いますが。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    const columnDefList = prepareConfigs(configs, 'id', 'title', '1', 'A:C', ['STRING_TEXTFIELD', 'DECIMAL', 'STRING_TEXTAREA'])
`select-data-type=STRING` なので、DECIMAL は要らないと思いました。

2022-03-11 06:32 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +        const ret = JSON.stringify({"values":[['A','2','う']]});
`STRING_TEXTFIELD` と `STRING_TEXTAREA` の違いがないので、`う` の方は複数行にした方が良いです。

2022-03-16 05:23 UTC, hatanaka-akihiro requested changes

2022-03-16 05:23 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    const types = [...Array(10)].map(() => 'STRING_TEXTFIELD');
```new Array(10).fill('STRING_TEXTFIELD')```

で、動かないでしょうか。

2022-03-16 05:23 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    const types = [...Array(10)].map(() => 'STRING_TEXTFIELD');
new はあってもなくても同じように動くみたいですが、ある方が良いと思います。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/Array

2022-03-17 02:29 UTC, hatanaka-akihiro requested changes

2022-03-17 02:29 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    const rowData = new Array(10).fill().map((_, i) => `値${i+1}`);
```new Array(10).map(...)```

で良いように思います。```fill()``` は要らない。

2022-03-17 02:34 UTC, hatanaka-akihiro commented on google-sheets-row-get.xml
> +    const rowData = new Array(10).fill().map((_, i) => `値${i+1}`);
ちなみに
```
Array.from({length: 10}, (_, i) => `値${i+1}`);
```
でも良さそうです。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/from

ただし GraalJS 上で未確認。```new Array(10).map(...)``` で良いと思います。

2022-03-17 04:32 UTC, tatsumiQ commented on google-sheets-row-get.xml
> +    const rowData = new Array(10).fill().map((_, i) => `値${i+1}`);
`fill()` を外してしまうと、動かなくなります。
参考) https://yucatio.hatenablog.com/entry/2019/04/07/110721

`Array.from()` のほうは動いたので、そちらを使用するようにしました。

2022-03-17 06:47 UTC, merged