change Calender IDs parameter check, add unit test code
Questetra/Addon-XML pull request #410
Opened 2022-03-14 05:18 UTC by chica-non

畠中さん

レビューをお願いします。
・Calender IDのパラメータチェックを変更
・単体テストコードを追加

2022-03-16 02:16 UTC, hatanaka-akihiro requested changes

2022-03-16 02:16 UTC, hatanaka-akihiro commented on google-calendar-event-move.xml
> +    if (calendarId.search(/^[\w\-_.!*'@]+$/) === -1) {
同じ正規表現を 2 箇所で使用しているので、変数として定義した方が良いです。

```
const calIdRegex = /^[\w\-_.!*'@]+$/;
```

とか。

2022-03-16 02:16 UTC, hatanaka-akihiro commented on google-calendar-event-move.xml
> +  configs.put('conf_CalendarId', calenderId,);
エラーにならないようですが、最後の `,` はいらない。

2022-03-16 02:16 UTC, hatanaka-akihiro commented on google-calendar-event-move.xml
> + * 予定移動成功 - 移動元カレンダーID/移動先カレンダーID 指定なし
コメントを変えてください。

正常系であっているのですが、「移動はしない」ので「移動成功」というのが変。

2022-03-16 02:16 UTC, hatanaka-akihiro commented on google-calendar-event-move.xml
> + * 予定移動成功 - 移動元カレンダーID/移動先カレンダーID 指定なし
「移動しない」正常系パターンで、移動元／移動先カレンダー ID を指定するパターンを追加してください。

2022-03-18 03:16 UTC, chica-non commented
畠中さん
レビューをお願いします。
修正は以下の通りです。
・正規表現を変数として定義
・余計なコンマを削除
・コメント変更

2022-03-18 05:26 UTC, hatanaka-akihiro requested changes

2022-03-18 05:26 UTC, hatanaka-akihiro commented on google-calendar-event-move.xml
> +  configs.put('conf_CalendarId', calenderId,);
残っているようです。186 行目。

2022-03-22 01:45 UTC, chica-non commented
畠中さん

レビューをお願いします。
・コンマを取り除きました。

2022-03-22 02:42 UTC, hatanaka-akihiro approved these changes

2022-03-22 02:43 UTC, merged