T7988: Box Sign: 署名リクエスト作成
Questetra/Addon-XML pull request #415
Opened 2022-04-05 05:48 UTC by tatsumiQ

2022-04-08 07:11 UTC, hatanaka-akihiro requested changes

2022-04-08 07:11 UTC, hatanaka-akihiro commented on box-sign-request-create.xml
> +  }
元のプログラムの方が、```passwords !== null``` の場合のループ回数が少なそうですが。

2022-04-08 07:11 UTC, hatanaka-akihiro commented on box-sign-request-create.xml
> +  }
末尾の空行は悩んだところですが、何行も許すのはやりすぎ。
「最後の '\n' は無視する」ぐらいで良いです。

2022-04-08 07:11 UTC, hatanaka-akihiro commented on box-sign-request-create.xml
> +}
```retrieveEmails()``` ```retrievePasswords()``` は、```makeFilledArray``` 以外の部分もほぼ同じ。

```
  if (passwordDef === null) {
    return null;
  }
```
に相当するコードが、```retrieveEmails()``` にあっても構わない。(必須なのでそもそも発生しないけど、呼び出し元でエラーにする手もある)

一応の指摘。

2022-04-11 02:16 UTC, tatsumiQ commented on box-sign-request-create.xml
> +}
関数を `retrieveFilledArray()` にまとめました。

2022-04-11 02:16 UTC, tatsumiQ commented on box-sign-request-create.xml
> +  }
最後の空行のみ無視する（削除する）ようにしました。

2022-04-11 02:17 UTC, tatsumiQ commented on box-sign-request-create.xml
> +  }
最大70回のループなので、ご提案のように最初から `emails.map(email => ({email}))` をセットするようにしました。

2022-04-12 02:28 UTC, merged