T8310 単体テストコードを追加
Questetra/Addon-XML pull request #417
Opened 2022-04-12 01:25 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストコードを追加しました。
よろしくお願いします。

2022-04-12 03:00 UTC, hatanaka-akihiro requested changes

2022-04-12 03:00 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> +        responseObj.valueRanges[0].values[0].push(i);
他のテストケースを見ると、values 配列の値は String のようなので、String に変換した方が良いです。

```
responseObj.valueRanges[0].values[0].push(String(i));
```

2022-04-12 03:00 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> +    }
responseObj より先に、1000 文字数のテキストを作った方が解りやすいかと。
あと私も使ったことがないのですが、```padEnd()``` ```padStart()``` というメソッドが使えそうです。

```
    const longText = ''.padEnd(1000, 'e');
    const responseObj = {
      "spreadsheetId": "56789efghi",
      "valueRanges": [
        {
          "range": "'sheet5'!D1:D5",
          "majorDimension": "COLUMNS",
          "values": [
            [
              "aa",
              "bb",
              "cc",
              "dd",
              "ee"              
            ]
          ]
        },
        {
          "range": "'sheet5'!F1:F5",
          "majorDimension": "COLUMNS",
          "values": [
            [
              "aaa",
              "bbb",
              "ccc",
              "ddd",
              longText
            ]
          ]
        }
      ]
    };
```

こちらでも良いか。

```
    const responseObj = {
      "spreadsheetId": "56789efghi",
      "valueRanges": [
        {
          "range": "'sheet5'!D1:D5",
          "majorDimension": "COLUMNS",
          "values": [
            [
              "aa",
              "bb",
              "cc",
              "dd",
              "ee"              
            ]
          ]
        },
        {
          "range": "'sheet5'!F1:F5",
          "majorDimension": "COLUMNS",
          "values": [
            [
              "aaa",
              "bbb",
              "ccc",
              "ddd",
              "".padEnd(1000, 'e') // 1000 文字のテキスト
            ]
          ]
        }
      ]
    };
```

2022-04-12 03:00 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空でエラーになる場合
すべて空というと

```
        {
          "range": "'sheet6'!A6:A10",
          "majorDimension": "COLUMNS",
          "values": [
            [
               "",
               "",
               "",
               "",
               ""
            ]
          ]
        }
```

を連想します。テストで記載されている API 応答になるのは、「設定で指定した列が、シートに存在しない場合」ですか？

2022-04-12 03:00 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> +          "range": "'sheet6'!B6:B10",
細かいですが、この ```range``` 指定で、```values``` が複数列にならないと思います。

2022-04-12 03:00 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> + * 取得した列が複数でエラーになる場合
「選択肢 ID または選択肢ラベルの領域として、複数列を指定した場合」ではないでしょうか。

設定は問題ないけど、API の応答が問題になるケースはあるのでしょうか。

「設定に問題がある」テストケースなのだと思うのですが。

2022-04-12 04:18 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> +          "range": "'sheet6'!B6:B10",
修正しました

2022-04-12 04:19 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> + * 取得した列が複数でエラーになる場合
ありがとうございます。「選択肢 ID または選択肢ラベルの領域として、複数列を指定した場合」です。「設定に問題がある」テストケースです。

APIで試してみましたが、設定は問題ないけど、API の応答が問題になるケースは無かったと思います。

2022-04-12 04:20 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。
ご確認をお願いいたします。

2022-04-14 04:57 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> +    }
よく考えたら、配列の値は同じ。

なら先に配列を１つ作成し、それを responseObj に設定するのが良いです。

2022-04-14 04:57 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> +			  "".padEnd(1001, 'e') // 1001 文字のテキスト
インデントが違って見えます。スペースとタブの違い？

2022-04-14 04:57 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空でエラーになる場合
なるほど。

シート上は列が存在するけど、全データが空であるため、API の応答としては values が無くなるわけですね。

では「取得した列のデータの中に、空文字がありエラーになる場合」の続きのテストケースとして、
定義した方が良いです。見た目上は「空文字がある」の特殊な形と言えるので。

あと「指定した全てのセルの値が空の場合、values がなくなる」旨を、responseObj の中に記載してください。

ちなみにですが、たとえば

- A 列の 10 までは空。11 に値がある。
- アイテムの指定は "A1:A10"

の場合も、responseObje から values はなくなるのですか？

2022-04-18 01:35 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> +    }
修正しました

2022-04-18 01:35 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> +			  "".padEnd(1001, 'e') // 1001 文字のテキスト
ありがとうございます。修正しました。

2022-04-18 01:40 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空でエラーになる場合
修正しました。


- A 列の 10 までは空。11 に値がある。
- アイテムの指定は "A1:A10"

の場合で、APIで確認しました。

responseObje から values はなくなりました。
シート上は列が存在するが、行範囲で全データが空であるため（行範囲以外でデータがあっても）、API の応答としては values が無くなるのだと思います。

2022-04-18 01:43 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。
ご確認をお願いします。

2022-04-18 02:18 UTC, hatanaka-akihiro requested changes

2022-04-18 02:18 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空で、データ情報を取得できずエラーになる場合
「データ情報を取得できず」というのは、余計では？

「データ情報は取得している (すべて空) 」と言えるので。

2022-04-18 02:19 UTC, hatanaka-akihiro commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空でエラーになる場合
> responseObje から values はなくなりました。

了解しました。

2022-04-18 03:19 UTC, suese-sayaka commented on google-sheets-choice-batchget.xml
> + * 取得した列のデータが全て空で、データ情報を取得できずエラーになる場合
修正しました。

2022-04-18 03:20 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストコードを修正しました。ご確認をお願いします。

2022-04-18 03:25 UTC, hatanaka-akihiro approved these changes

2022-04-18 03:25 UTC, merged