T8473: Google ドライブ: 共有リンク作成　共有するファイル/フォルダ指定を１つに限定する／すでに共有設定がある場合のエラー判定の緩和
Questetra/Addon-XML pull request #419
Opened 2022-04-18 05:58 UTC by tatsumiQ

2022-04-18 06:54 UTC, hatanaka-akihiro requested changes

2022-04-18 06:54 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +function getWebViewLink(quser, fileId) {
表示用 URL の取得に、別 API を発行するように変えた理由は？

2022-04-18 07:09 UTC, tatsumiQ commented on google-drive-permission-create.xml
> +function getWebViewLink(quser, fileId) {
もともと、まずファイル情報取得の GET リクエストを発行し、そのレスポンスから「共有済みかどうかの判定」と「URL の取得」を行っていました。

「共有済みかどうかの判定」の基準を緩和するにあたって、各 permission の type を見る必要があります。
各 permission の情報はファイル情報取得の GET のレスポンスに含まれる場合（おそらくマイドライブ内のファイル/フォルダの場合）と含まれない場合（おそらく共有ドライブ内のファイル/フォルダの場合）があり、確実に各 permission の情報を取得するために、permission の一覧を取得するリクエストを別途発行することにしました。

そのため、従来 2 回だった API リクエストが 3 回に増えています。
ファイル情報取得の GET のレスポンスに各 permission の情報がかならず含まれていればよかったのですが……。

2022-04-18 08:28 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> +function getWebViewLink(quser, fileId) {
「Google スプレッドシート: ファイル作成」等で登場する「表示用 URL」と、共有リンクは別 URL と思っていたのですが、同じということでしょうか。

つまり文字通り permission を与えて、表示用 URL を他の人も見れるように変えているということ？

2022-04-18 08:28 UTC, hatanaka-akihiro approved these changes

2022-04-18 08:28 UTC, merged

2022-04-19 01:25 UTC, tatsumiQ commented on google-drive-permission-create.xml
> +function getWebViewLink(quser, fileId) {
> 「Google スプレッドシート: ファイル作成」等で登場する「表示用 URL」と、共有リンクは別 URL と思っていたのですが、同じということでしょうか。

同じです。厳密には、表示用 URL の末尾には `?usp=drivesdk` のクエリがついていて、Web UI から取得できる共有リンクには `?usp=sharing` のクエリがついていますが、URL 自体は同じです。

後者の URL を API から直接取得する方法はなく、前者の表示用 URL を保存しています。（クエリがあってもなくても、権限があれば表示できます）

> つまり文字通り permission を与えて、表示用 URL を他の人も見れるように変えているということ？

はい。なので「共有リンク作成」「共有リンク削除」と呼ぶのは、厳密にいえば正しくないです。