add unit test code
Questetra/Addon-XML pull request #420
Opened 2022-04-22 02:42 UTC by chica-non

畠中さん

単体テストコードを追加しました。
レビューをお願いします。

2022-04-22 06:46 UTC, hatanaka-akihiro requested changes

2022-04-22 06:46 UTC, hatanaka-akihiro commented on gmail-message-label-remove.xml
> +  }
```
expect(execute).toThrow('Failed to get labels. status: 400');
```

```execute()``` が失敗することを期待するテストケースは、この形に変えてください。
参照: gmail-message-get.xml

2022-04-25 02:12 UTC, chica-non commented
畠中さん
レビューをお願いします。
execute() が失敗することを期待するテストケースについて修正しました。

2022-04-25 03:20 UTC, hatanaka-akihiro approved these changes

2022-04-25 03:21 UTC, merged