t8322 単体テストコードを追加
Questetra/Addon-XML pull request #422
Opened 2022-04-25 05:54 UTC by suese-sayaka

``@hatanaka-akihiro  さん

テストコード　337 行目以降
チャット投稿失敗の場合（存在しないチャンネル）について質問です。

このテストは、エラーですが、ステータスコード200で、レスポンスオブジェクトも返します。

ビルドすると、下記エラーになります。
```
org.graalvm.polyglot.PolyglotException: 

Expected: a string containing "Failed to send"
     but: was "function is expected to be throw error"
```

`expect(execute).toThrow(`Failed to send`);`
と書いてはいけないのでしょうか？

2022-04-25 08:16 UTC, hatanaka-akihiro commented
「```execute()``` しても失敗していない」ということです。
「失敗する意図のテスト」なのに失敗していないのであれば、テストの仕方を間違えているか、テスト対象のスクリプトにバグがある。

応答を間違えていると思います。
```JSON.stringify(preparePostResponse(responseObj))```

2022-04-26 02:48 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ありがとうございます。
応答を間違えていたことが分かりました。解決しました。
`JSON.stringify(preparePostResponse(responseObj))`

単体テストコードを作成しました。ご確認をお願いいたします。

2022-04-26 04:41 UTC, hatanaka-akihiro requested changes

2022-04-26 04:41 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
この attachment 変数は消し忘れですか？

2022-04-26 04:41 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +test('GET Failed', () => {
GET リクエストは見当たらないのですが．．．

2022-04-26 04:41 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +test('Failed - Private channel that bot is not joining', () => {
プログラム上は、'Non-existent channel' と区別がつきません。
なので、無くて良いですよ。

2022-04-26 04:41 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
この変数は消し忘れですか？

2022-04-28 03:22 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
必要かと思って書きました

2022-04-28 03:23 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +test('GET Failed', () => {
修正しました

2022-04-28 03:23 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +test('Failed - Private channel that bot is not joining', () => {
削除しました

2022-04-28 03:23 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
必要かと思って書きました

2022-04-28 03:24 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。
 t8492 Bot トークンの指定を削除　の対応もしました。

ご確認をお願いいたします。

2022-04-28 04:06 UTC, hatanaka-akihiro requested changes

2022-04-28 04:06 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  }
どこで使っていますか？

使っていないから、要らないと思ったのですが。

2022-04-28 04:06 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * Attachment 色が無効
「色が無効」だけだと、動作しないように思うのですが、正常に動作するのですよね？

「色が無効でも動作する」とか、コメントを考えた方が良いです。

2022-04-28 04:06 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * チャンネル　Attachment 色　Attachment テキスト　以外が未入力
次のテストケースと、書き方を統一した方が良いです。

「以外が未入力」「を入力」

解りにくいです。

2022-04-28 05:57 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + * Attachment 色が無効
修正しました

2022-04-28 05:58 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + * チャンネル　Attachment 色　Attachment テキスト　以外が未入力
修正しました

2022-04-28 05:58 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
すみません、勘違いしていました。
削除しました。

2022-04-28 05:59 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  }
すみません、勘違いしていました。
削除しました。

2022-04-28 05:59 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いします。

2022-04-28 06:23 UTC, hatanaka-akihiro requested changes

2022-04-28 06:23 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * チャンネル　Attachment 要約　Attachment 色　を入力
上のテストケースと、違いが解りにくかったです。

そもそもこのテストケースは必要でしょうか。

Attachment のタイトルが空で、リンクが設定されている、「正常系」のテストケースなら意味があると思います。
（タイトルが空なら、リンクは無視されるということの確認）

2022-04-28 06:23 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * チャンネル　Attachment 色　Attachment テキスト　を入力
「テキストが空」も記載した方が良いです。

2022-04-28 06:23 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * Cannel Attachment タイトル　Attachment タイトルリンク　Attachment テキスト　を入力
`Message to send isn't set.` のエラーが発生するパターンを考慮すると、絶対に含めないといけない正常系は、

「テキスト」「Attachment タイトル」「Attachment テキスト」のいずれかが設定されていて、他の２つは空

のパターンです。そのパターンは３つある。

2022-05-02 01:37 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + * チャンネル　Attachment 要約　Attachment 色　を入力
意味が分かりました。削除しました。

2022-05-02 01:38 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + * Cannel Attachment タイトル　Attachment タイトルリンク　Attachment テキスト　を入力
３つのパターンをテストできるよう、既存のテストケースを一部修正し、コメントを追加しました。①②③

2022-05-02 01:39 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いします。

2022-05-02 02:10 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +]]></test>
「タイトルリンクが設定されているが、無視される」正常系のテストケースが必要です。

既存のテストケースに含ませるか、新たにテストケースを追加するか。
私なら、既存のテストケースに含ませます。

なお「タイトルリンクが設定されていて、無視されない」テストケースはあります。「チャット投稿成功の場合」がそれ。

2022-05-02 04:03 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +]]></test>
「タイトルリンクが設定されているが、無視される」正常系のテストケース を追加しました。
「AttachmentタイトルリンクがURLの形式でないため、Attachmentタイトルにリンクが無い」正常系のテストケース を追加しました。

いずれも、既存のテストケースに含ませました。

2022-05-02 04:04 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いします。

2022-05-02 04:25 UTC, hatanaka-akihiro requested changes

2022-05-02 04:25 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * ※AttachmentタイトルリンクがURLの形式でないため、Attachmentタイトルにリンクが無いケース（チャット投稿は成功する）
"※" はどういう意味でしょうか。

2022-05-02 04:25 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * ※Attachmentタイトルリンクが設定されているが、Attachmentタイトルが未設定のため無視されるケース（チャット投稿は成功する）
この "※" の意味は？

2022-05-02 05:22 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

※ は意味が無いので削除しました。
英語 summary を変更しました。

2022-05-02 05:47 UTC, hatanaka-akihiro requested changes

2022-05-02 05:47 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +<summary>Sends a message to Slack with Bots.</summary>
"This Item..." で始めるように変えてもらえますか。

つまり

"This item sends a message to Slack with Bots."

2022-05-02 05:47 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
>  <summary locale="ja">Bots 機能を使って Slack にメッセージを投稿します。</summary>
「この工程は」で始まるように変えてもらえますか。つまり

「この工程は、Bots 機能を使って Slack にメッセージを投稿します。」

2022-05-09 00:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +<summary>Sends a message to Slack with Bots.</summary>
変更しました

2022-05-09 00:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
>  <summary locale="ja">Bots 機能を使って Slack にメッセージを投稿します。</summary>
変更しました

2022-05-09 06:37 UTC, hatanaka-akihiro approved these changes

2022-05-09 06:37 UTC, merged