T8463: Box: 電子すかし適用　の作成
Questetra/Addon-XML pull request #423
Opened 2022-04-25 06:06 UTC by tatsumiQ

2022-04-25 08:04 UTC, hatanaka-akihiro requested changes

2022-04-25 08:04 UTC, hatanaka-akihiro commented on box-file-watermark-apply.xml
> +                editable="true">
固定ファイルに対して、電子透かしを適応する利用シーンは考えにくいので、{{{editable="true"}}} でなくて良いと思いました。

利用シーンを思いつきますか？

2022-04-26 03:42 UTC, tatsumiQ commented on box-file-watermark-apply.xml
> +                editable="true">
とくに利用シーンが思いつかないため、`editable="true"` を削除しました。

2022-04-26 05:04 UTC, hatanaka-akihiro requested changes

2022-04-26 05:04 UTC, hatanaka-akihiro commented on box-file-watermark-apply.xml
> + * 新規適用の場合
新規適用と更新で API の応答が異なるようですが、その旨をコメントに記載してください。

そこ以外に、プログラム上の違いはないので。

2022-04-26 06:10 UTC, tatsumiQ commented on box-file-watermark-apply.xml
> + * 新規適用の場合
コメントを追記しました。

2022-04-26 07:04 UTC, hatanaka-akihiro approved these changes

2022-04-26 07:04 UTC, merged