add unit test code, modify summary
Questetra/Addon-XML pull request #428
Opened 2022-05-09 02:08 UTC by chica-non

畠中さん

レビューをお願いします。
・単体テストコードを作成
・summary を変更

2022-05-09 06:34 UTC, hatanaka-akihiro requested changes

2022-05-09 06:34 UTC, hatanaka-akihiro commented on onedrive-folder-create.xml
> + * フォルダ作成成功
後の方のテストとの区別のため、親フォルダURL をどうやって指定しているか、コメントに記載してください。

2022-05-09 06:34 UTC, hatanaka-akihiro commented on onedrive-folder-create.xml
> + * POST リクエストでエラー - 親フォルダURLを固定値で指定し、その値が空
「POST リクエストでエラー」で 4 つありますが、1 パターンで十分です。

リクエスト内容が違っていますが、そのテストは正常系でできていますし、わざわざ 4 つも設ける意味がないので。

2022-05-09 06:34 UTC, hatanaka-akihiro commented on onedrive-folder-create.xml
> + * GET リクエストでエラー - 親フォルダURLを固定値で指定
「GET リクエストでエラー」のテストが 2 パターンありますが、1 パターンで十分です。

リクエスト内容が違っていますが、そのテストは正常系でできていますし、わざわざ 2 つも設ける意味がないので。

2022-05-09 06:34 UTC, hatanaka-akihiro commented on onedrive-folder-create.xml
> + * POST リクエストでエラー - 親フォルダURLを固定値で指定し、その値が空
ただ「POST リクエストでエラー」のテストと「GET リクエストでエラー」のテスト。両方１パターンにしたとしても、リクエスト内容が違うような工夫は入れた方が良いです。

2022-05-10 02:27 UTC, chica-non commented
畠中さん

レビューをお願いします。
* エラーのテストケースをGET、POSTそれぞれ1つずつに
* テストケース減に伴い、連番を変更
* コメント変更

2022-05-12 00:39 UTC, hatanaka-akihiro approved these changes

2022-05-12 00:39 UTC, merged