t8491 テキストの最後にメンションを指定
Questetra/Addon-XML pull request #429
Opened 2022-05-10 02:18 UTC by suese-sayaka

@hatanaka-akihiro  さん
単体テストコードは未対応です。
Attachment でリンクが設定されていたら、テキストが空でも、メンションを指定できた方がよいかなと思いスクリプトを書きました。

2022-05-12 02:57 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

スクリプトコードを修正しました。ご確認をお願いいたします。
テストコードはまだ作成していません。

2022-05-12 06:33 UTC, hatanaka-akihiro requested changes

2022-05-12 06:33 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  if (email !== "" && email !== null){
空文字と null の両方をチェックしなければならないというのが、今一つ。

```decideMailAddress()``` の中で、```usersLookupByEmail()``` を呼び出すところまでしてしまったら良いです。

2022-05-12 06:33 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +    text = `${text}\n\n<@${slackIdNum}>`;
text が空の場合に、先頭に改行が 2 つ入るのが無駄だと思いました。

が、たいした話ではありません。

2022-05-16 03:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +    text = `${text}\n\n<@${slackIdNum}>`;
すみません。前回コメントできていませんでした。

先頭に改行がある場合、その改行部分は無視されて投稿されることを確認済（手動でも、アドオンでも）なので、この処理にしました。

2022-05-16 03:33 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

スクリプトコードと単体テストコードを修正しました。
ご確認をお願いします。

2022-05-16 04:52 UTC, hatanaka-akihiro requested changes

2022-05-16 04:52 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +    text = `${text}\n\n<@${slackIdNum}>`;
了解しました。

2022-05-16 04:52 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  * @return {String} mailAddress  Slack アカウントのメールアドレス
プログラムとコメントが合致していません。

2022-05-16 04:52 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +    mailAddress,
メールアドレスを返している理由はありますか？

2022-05-16 04:52 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +      const pattern = /^[A-Za-z0-9]{1}[A-Za-z0-9_.-]*@{1}[A-Za-z0-9_.-]+.[A-Za-z0-9]+$/;
slack に登録できるメールアドレスは、この正規表現で表せる範囲なのでしょうか？
それなら良いのですが．．．

そうでないなら、「チェックしない」で良いです。

ちなみに QBPMS でメールアドレスのチェックに使用している正規表現は、もっと複雑です。

2022-05-17 02:27 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +    mailAddress,
ありません。
修正しました。

2022-05-17 02:28 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +      const pattern = /^[A-Za-z0-9]{1}[A-Za-z0-9_.-]*@{1}[A-Za-z0-9_.-]+.[A-Za-z0-9]+$/;
slack に登録できるメールアドレス について、調べてみたのですが、見つけられませんでした。
「チェックしない」に修正しました。

2022-05-17 02:29 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
スクリプトとテストコードを修正しました。ご確認をお願いいたします。

2022-05-17 03:07 UTC, suese-sayaka commented
@hatanaka-akihiro さん

const user = engine.findDataByNumber( quserNum );
として、修正しました。

インデントを修正しました。

2022-05-17 03:21 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
すみません、インデントを再修正しました。

2022-05-17 04:22 UTC, hatanaka-akihiro requested changes

2022-05-17 04:22 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
>  /**
「メンションはユーザ型データ項目」のテストケースが無いように思いました。

2022-05-19 01:53 UTC, suese-sayaka commented on slack-chat-post-bots.xml
>  /**
@hatanaka-akihiro  さん

このテストケースを追加しようとしているのですが、

  // ユーザ型データ項目を準備して、config に指定
  const mentionDef = engine.createDataDefinition('メンション', 4, 'q_mention', 'QUSER');
  configs.putObject('conf_Mention', mentionDef);

として、 次に、 ユーザ型データ項目の値を指定したいのですが、その方法が分かりません。
参考になるテストコードがあれば教えてください。ひととおり探したつもりですが、見つけられませんでした。

2022-05-19 05:00 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
>  /**
`form-type="QUSER"` のアイテムを参考にしてください。
Google カレンダーやドライブ系のアイテムがそれにあたります。

ユーザ型データ項目に設定する値 の Quser オブジェクトの作成方法は、これらが参考になります。

2022-05-19 05:56 UTC, suese-sayaka commented on slack-chat-post-bots.xml
>  /**
ありがとうございます。

554行目からのテストケースを、「メンションはユーザ型データ項目」に変更しました。

2022-05-19 05:56 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

554行目からのテストケースを、「メンションはユーザ型データ項目」のケースに変更しました。
ご確認をお願いいたします。

2022-05-19 06:56 UTC, hatanaka-akihiro requested changes

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  configs.put('conf_Mention', '');
569 で conf_Mention を上書きしているので、要らないはず

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  engine.setDataByNumber("4", quser);
`engine.setData(mentionDef, quser);` の方が良いです。

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> + * メンションは文字型データ項目を選択していて空
1 つ上のテストケースから変えて、ユーザ型データ項目の方が良いです。

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  prepareConfigs(configs, 'channel10', '', '', '', '', 'title10', '', '');
文字型データ項目も、空の場合、値は null。

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  const attachment = prepareConfigs(configs, 'no-channel5', 'text5', '', 'fallback5', '#ff0000', 'title5', 'https://titleLink5', 'attachText5');
文字型データ項目も、空の場合、値は null。

2022-05-19 06:56 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
意図的に、「ユーザ型データ項目の値が空」での正常系のテストをケースを、省略しているかどうか。

2022-05-23 01:33 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  configs.put('conf_Mention', '');
削除しました

2022-05-23 01:35 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  engine.setDataByNumber("4", quser);
前回、engine.setData(mentionDef, quser);　で試したのですが、
org.graalvm.polyglot.PolyglotException: TypeError: user.getEmail is not a function
とエラーが出ましたので、engine.setDataByNumber("4", quser); で通ったので、この処理にしました。

engine.setData(mentionDef, quser);　にした場合、他に必要な処理があったら教えてください。

2022-05-23 01:36 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> + * メンションは文字型データ項目を選択していて空
修正しました

2022-05-23 01:36 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  prepareConfigs(configs, 'channel10', '', '', '', '', 'title10', '', '');
修正しました

2022-05-23 01:36 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  const attachment = prepareConfigs(configs, 'no-channel5', 'text5', '', 'fallback5', '#ff0000', 'title5', 'https://titleLink5', 'attachText5');
修正しました

2022-05-23 01:38 UTC, suese-sayaka commented on slack-chat-post-bots.xml
「ユーザ型データ項目の値が空」での正常系のテストをケースが、必要だと分かりました。
591 行目のテストケースを追加しました。

2022-05-23 01:48 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  engine.setDataByNumber("4", quser);
スクリプトにバグがあるから動作しないのだと思います。

変更した場合のスクリプトを見ていないので、どこにバグがあるのかは解りません。

2022-05-23 08:49 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +        const user = engine.findDataByNumber( quserNum );
```
const user = engine.findData(mailAddressDef);
```

で良いと思います。文字型でもユーザ型でも、 `engine.findData(mailAddressDef)` が登場しますね。
共通化できます。

`quserNum` は不要。

2022-05-23 08:49 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  const mentionDef = engine.createDataDefinition('メンション', 4, 'q_mention', 'QUSER');
文字型データ項目と同じ定義番号を使わない。同一アプリ内で、同じ定義番号のデータ項目が２つ以上存在することはありません。

2022-05-23 08:49 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +  engine.setDataByNumber("4", quser);
根本の理由は、文字型データ項目とユーザ型データ項目で、同じ定義番号を使用していることです。

2022-05-24 02:13 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +        const user = engine.findDataByNumber( quserNum );
修正しました

2022-05-24 02:13 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +  const mentionDef = engine.createDataDefinition('メンション', 4, 'q_mention', 'QUSER');
ありがとうございます。修正しました。

2022-05-24 02:13 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +test('Success- Invalid color setting and Invalid title-link setting', () => {
修正しました

2022-05-24 02:14 UTC, suese-sayaka commented
@hatanaka-akihiro さん
スクリプトとテストコードを修正しました。ご確認をお願いいたします。

2022-05-24 04:32 UTC, hatanaka-akihiro requested changes

2022-05-24 04:32 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +test('Success - Mention is a empty for user-type data items - Invalid color setting and Invalid title-link setting', () => {
`Mention is a empty for user-type data items`

では無いのでは？

2022-05-24 04:53 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +test('Success - Mention is a empty for user-type data items - Invalid color setting and Invalid title-link setting', () => {
すみません、間違えました。修正しました。

2022-05-24 04:53 UTC, suese-sayaka commented
@hatanaka-akihiro さん
修正しました。ご確認をお願いいたします。

2022-05-25 01:25 UTC, merged