T8462: Box: ファイルにメタデータ追加　作成
Questetra/Addon-XML pull request #430
Opened 2022-05-10 05:38 UTC by tatsumiQ

2022-05-26 10:42 UTC, hatanaka-akihiro requested changes

2022-05-26 10:42 UTC, hatanaka-akihiro commented on box-file-metadata-add.xml
> +    const result = options.find(option => option.key === value);
`Array.prototype.some()` で良いと思います。

2022-05-26 10:42 UTC, hatanaka-akihiro commented on box-file-metadata-add.xml
> +    return responseObj;
たいしたことではありませえんが、`JSON.stringify()` までしてしまって良かったのでは？

2022-05-26 10:42 UTC, hatanaka-akihiro commented on box-file-metadata-add.xml
> +    const regex = /^\d+(\.\d+)?$/;
8 進数解釈を避けるため、0 始まりを除外する正規表現にした方が良いか。

2022-05-26 10:42 UTC, hatanaka-akihiro commented on box-file-metadata-add.xml
> +        if (fieldName === '' || fieldName === null) { // フィールド名が空
「フィールド名が空で、値が空でない」というパターンは、この時点ではじいて良いような。

2022-05-27 02:39 UTC, tatsumiQ commented on box-file-metadata-add.xml
> +    const result = options.find(option => option.key === value);
`some()` を使うように修正しました。このメソッドの存在を忘れていました。

2022-05-27 02:39 UTC, tatsumiQ commented on box-file-metadata-add.xml
> +    return responseObj;
`JSON.stringify()` までするように修正しました。

2022-05-27 02:40 UTC, tatsumiQ commented on box-file-metadata-add.xml
> +    const regex = /^\d+(\.\d+)?$/;
0始まりの2桁以上の数を除外し、マイナス符号を許容する正規表現 `^\-?(\d|[1-9]\d+)(\.\d+)?$` に修正しました。

2022-05-27 02:41 UTC, tatsumiQ commented on box-file-metadata-add.xml
> +        if (fieldName === '' || fieldName === null) { // フィールド名が空
「フィールド名が空で、値が空でない」場合はエラーになるようにしました。

2022-05-30 06:07 UTC, merged