add unite test code, change summary
Questetra/Addon-XML pull request #431
Opened 2022-05-16 05:10 UTC by chica-non

畠中さん

レビューをお願いします。
・単体テストコードを追加
・summaryを変更

2022-05-16 05:47 UTC, hatanaka-akihiro requested changes

2022-05-16 05:47 UTC, hatanaka-akihiro commented on onedrive-file-delete.xml
> +<summary>This item deletes files and folders on OneDrive. You can delete multiple ones at once. When you delete multiple ones, you should write one URL on each line.</summary>
1 文目にあわせて改良してください。

2022-05-16 05:47 UTC, hatanaka-akihiro commented on onedrive-file-delete.xml
> +<summary locale="ja">この工程は、OneDrive 上のファイル / フォルダを削除します。一度に複数の削除が可能です。複数削除する場合、データ項目では1行につき1つずつ URL を書くようにしてください。</summary>
「この工程は」という主語を補って考えると、３文目がおかしいです。

2022-05-16 05:47 UTC, hatanaka-akihiro commented on onedrive-file-delete.xml
> +      return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(SAMPLE_GET1));
`SAMPLE_GET1` はさほど複雑なオブジェクトでもないので、定数に切り出さず、テストケース内で定義したほうが良いと思いました。

その上で、`DELETE Failed` のテストケースと、違う値を使用したほうが良いです。

2022-05-17 02:26 UTC, chica-non commented
畠中さん
レビューをお願いします。
・summaryを変更
・SAMPLE_GET1を削除し、テストケース内で定義するように変更

2022-05-17 02:40 UTC, hatanaka-akihiro approved these changes

2022-05-17 02:41 UTC, merged