change summary, add unite test code
Questetra/Addon-XML pull request #433
Opened 2022-05-24 05:39 UTC by chica-non

畠中さん

レビューをお願いします。
・サマリーを変更
・単体テストコードを追加

2022-05-25 01:16 UTC, hatanaka-akihiro requested changes

2022-05-25 01:16 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +    return httpClient.createHttpResponse(400, 'application/json', '{}');
リクエスト内容のテストが抜けています。

2022-05-25 01:16 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +const SAMPLE_SRC_GET = {
コメントを書く。

この辺のレスポンスも、「関数で作成すれば、色々な値のものを作れるのに」と思います。

2022-05-25 01:16 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +<summary>This item creates a copy of a file/folder into the specified folder on OneDrive.</summary>
感想です。

- コピーされるファイル / フォルダには "the" も"specified" も つけないのか
- "copy" を動詞で使っては

2022-05-31 02:41 UTC, chica-non commented
畠中さん
レビューをお願いします。
・サマリーを修正
・レスポンスの関数化
・抜けていたリクエスト内容のテストを追加

2022-05-31 05:49 UTC, hatanaka-akihiro requested changes

2022-05-31 05:49 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +const prepareDriveItemResponse = (id, driveId) => {
使われ方を見てですが、`JSON.stringify()` まで含めては？

2022-05-31 05:49 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +]]></test>
コピー状況が、completed でもなく、失敗にもならないパターンがある。

そのテストケースが抜けています。

2022-06-03 03:21 UTC, chica-non commented
畠中さん
レビューをお願いします。
・レスポンスを用意する関数でJSON.stringify() を含める
・コピー状況がnotStartedとinProgressのテストケースを追加

2022-06-03 05:15 UTC, hatanaka-akihiro requested changes

2022-06-03 05:15 UTC, hatanaka-akihiro commented on onedrive-file-copy.xml
> +]]></test>
コピー状況は notStarted -> inProgress -> Completed と遷移するのだと思います。

リクエストのタイミングによって、Completed 以外の状態は飛ばされる。
また notStarted と inProgress は繰り返される可能性がある。

無数のパターンがあることになりますが、

- Completed
- notStarted -> inProgress -> Completed

の2つを抑えた方が良いです。今は以下３パターン抑えているようですが。

- Completed
- notStarted -> Completed
- inProgress -> Completed

2022-06-06 01:56 UTC, chica-non commented
畠中さん

質問があります。
改めてコードを見てたのですが、コピー状況を確認し、ドライブアイテム ID を取得する関数、getNewItemId()は一回しか呼ばれないので、notStarted の後はそのまま処理が進むのではないでしょうか？
そして、その戻り値のnewItemIdは空""になるので、新しいURLを返す関数getNewItemUrl()でGETの処理(新しいURLを取得)が行われず、新しいURL を保存するデータ項目は空がセットされると思ったのですが、その理解であってますでしょうか？

2022-06-06 02:04 UTC, hatanaka-akihiro commented
> 質問があります。 改めてコードを見てたのですが、コピー状況を確認し、ドライブアイテム ID を取得する関数、getNewItemId()は一回しか呼ばれないので、notStarted の後はそのまま処理が進むのではないでしょうか？ そして、その戻り値のnewItemIdは空""になるので、新しいURLを返す関数getNewItemUrl()でGETの処理(新しいURLを取得)が行われず、新しいURL を保存するデータ項目は空がセットされると思ったのですが、その理解であってますでしょうか？

つまり notStarted や inProgress の場合も、その時点でアイテムの処理は終わるということでしょうか。
コードから読み取れる通りにテストを書くのも重要ですが、開発者の意図を確認するのも重要です。
コード自体が、開発者の意図から外れている可能性もありますし。

あと public なリポジトリなので、個人名を書かないように。

2022-06-06 02:15 UTC, chica-non commented
> つまり notStarted や inProgress の場合も、その時点でアイテムの処理は終わるということでしょうか。
そういうことみたいです。
エラーにはならないものの、新しいURLを取得したりはしません。
 
> 開発者に質問した方が良いです。 コードから読み取れる通りにテストを書くのも重要ですが、開発者の意図を確認するのも重要です。 コード自体が、開発者の意図から外れている可能性もありますし。
了解しました。確認してみます。

> あと public なリポジトリなので、個人名を書かないように。
すみません。知りませんでした。気を付けます。

2022-06-06 06:14 UTC, chica-non commented
レビューをお願いします。

notStarted や inProgress の場合のテストケースを修正しました。
開発者に確認したところ、コピー状況がnotStarted や inProgress の場合、その後のAPIリクエストなしで、URLを空文字列で上書きし、正常終了という処理にしているそうです。
「しばらく待ってから再度実行」のような処理の実装が難しいため、そのような仕様になっているそうです。

2022-06-06 06:35 UTC, chica-non commented
改めてレビューをお願いします。

notStarted や inProgress の場合のテストケースを修正しました。
開発者に確認したところ、コピー状況がnotStarted や inProgress の場合、その後のAPIリクエストなしで、URLを空文字列で上書きし、正常終了という処理にしているそうです。
「しばらく待ってから再度実行」のような処理の実装が難しいため、そのような仕様になっているそうです。

2022-06-06 07:27 UTC, hatanaka-akihiro approved these changes

2022-06-06 07:27 UTC, merged