t8323&8493  Slack: ファイルアップロード (Bots)
Questetra/Addon-XML pull request #434
Opened 2022-05-30 05:33 UTC by suese-sayaka

@hatanaka-akihiro さん

スクリプトコードの
     .multipart('file',file)
     .multipart('channels',channel)
を、検証するテストコードですが、「Box:ファイルアップロード」を参考にして、.multipart('file',file)　のテストコードは作成できて、ビルドがとおりました。

.multipart('channels',channel)
を検証するテストコードですが、「Box:ファイルアップロード」の、.multipart('attributes', JSON.stringify(attributes))　の部分を参考にしてみたのですが、ビルドでエラーが出てしまいます。

テストコードを以下のようにして、エラーになってしまうのですが、もし、他のテストコードを参考にできるアイテムがあったら教えてください。
    const channel = body.get('channel');
    expect(channel).toEqual(`${channels}`);
//    expect(channel.getName()).toEqual(`${channels}`);

2022-05-30 07:28 UTC, hatanaka-akihiro commented
```
const channel = body.get('channel');
```

まずパラメータ名を間違えています。

１つのパラメータ名に対して複数値がある場合があるので、```body.get()``` の戻り値はリストです。
だから、box-file-upload では、以下のようになっています。
```
const attributes = JSON.parse(body.get('attributes').get(0));
```

2022-05-31 02:07 UTC, suese-sayaka commented
@hatanaka-akihiro さん

ありがとうございます。
テストコードを修正しました。
summary の変更、トークンの指定を削除しました。
ご確認をお願いいたします。

2022-05-31 02:22 UTC, hatanaka-akihiro requested changes

2022-05-31 02:22 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +    expect(channel).toEqual(`${channels}`);
テンプレートを使う必要はないです。

2022-05-31 02:22 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +    expect(file.getLength()).toEqual(filesize);
複数ファイルのアップロードをチェックできるように改良しましょう。

2022-05-31 02:22 UTC, hatanaka-akihiro commented on slack-file-upload-bots.xml
> +      };
この通り、レスポンスの error プロパティにエラーメッセージが含まれているなら、throw するエラーにも含めた方が良いのでは。

2022-05-31 04:34 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> +    expect(file.getLength()).toEqual(filesize);
files の引数が不要だったので削除しました。

2022-05-31 04:35 UTC, suese-sayaka commented on slack-file-upload-bots.xml
> +      };
含めました（78行目）

2022-05-31 04:39 UTC, suese-sayaka commented
@hatanaka-akihiro さん

スクリプト
throw するエラーにエラーメッセージが出力されるように修正しました

テストコード
・アップロード失敗の場合　存在しないチャンネル
・アップロード失敗の場合　join していないチャンネル
のテストケースを削除しました　以下に含めました
・アップロード失敗の場合 ２つ目が存在しないチャンネル
・アップロード失敗の場合 ２つ目が join していないチャンネル

・アップロード成功の場合 ２つのチャンネル　と、・アップロード成功の場合 1ファイル　のケースを１つにまとめました。


ご確認をお願いいたします。

2022-05-31 06:51 UTC, hatanaka-akihiro approved these changes

2022-05-31 06:51 UTC, merged