t8513（任意Webサイト）: ファイル ダウンロード  HTTP認証設定/ summaryの変更
Questetra/Addon-XML pull request #436
Opened 2022-06-13 03:22 UTC by suese-sayaka

@hatanaka-akihiro  さん

定義ファイルを修正しました。
テストコードを修正しました。

ご確認をお願いいたします。

2022-06-13 05:52 UTC, hatanaka-akihiro requested changes

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +  <config name="conf_OAuth2" form-type="OAUTH2">
このアイテムについては、URL の方が先で。(設定項目の順番の話です)
URL の方が、必須で重要な設定項目なので。

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +    let httpRequest = httpClient.begin(); // HttpRequestWrapper
この後に

`if (oauth2 !== "" && oauth2 !== null){`

の分岐を入れた方が、すっきりすると思います。

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> + */
異常系のテストの書き方ですが、全面的に最近の書き方に変えてください。

（このアイテム内で、全面的に）

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> + * Box Oauth2 を設定  Basic 認証や OAuth2 が必要な URL
コメントとしては、「HTTP 認証設定を指定」ぐらいで良いです。

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +test('Success / Box Oauth2', () => {
Box と入れない方が良いです。

2022-06-13 05:52 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> + * 添付ファイル無
コメントが適当でないと思いました。

正常系なら条件の羅列も意味がありますが、これは異常系。

失敗する原因となっている条件を記載することが大事です。

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> +  <config name="conf_OAuth2" form-type="OAUTH2">
修正しました

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> +    let httpRequest = httpClient.begin(); // HttpRequestWrapper
修正しました

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> + */
修正しました

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> + * Box Oauth2 を設定  Basic 認証や OAuth2 が必要な URL
コメントを修正しました

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> +test('Success / Box Oauth2', () => {
修正しました

2022-06-14 01:38 UTC, suese-sayaka commented on any-website-file-download.xml
> + * 添付ファイル無
修正しました

2022-06-14 01:39 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

スクリプトとテストコードを修正しました。
テストコードのコメントは、全体的に見直して修正しました。

ご確認をお願いいたします。

2022-06-14 05:39 UTC, hatanaka-akihiro approved these changes

2022-06-14 05:39 UTC, merged