T8321: kintone: Delete Record - add unite test code/change summary
Questetra/Addon-XML pull request #437
Opened 2022-06-16 02:21 UTC by chica-non

レビューをお願いします。
・単体テストコードを追加
・summaryを変更

2022-06-16 02:48 UTC, hatanaka-akihiro requested changes

2022-06-16 02:48 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> + * サブドメインにアンダーバーが含まれていてエラー
コードを見ると「英数ハイフン」以外をチェックしている。

なので「アンダーバー」ではなく「英数ハイフン以外」と記載した方が良いです。

2022-06-16 02:48 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> + * サブドメインの文字数が多くてエラー
「32 文字以下」ということが解るようにコメントに書くか、そのようなコードにした方が良いです。

なお以下のメソッドが、特定の長さの文字を作るのに便利です。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd

2022-06-16 02:48 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> + * サブドメインの文字数が少なくてエラー
「3 文字以上」が valid であることが解るよう、コメントに書いた方が良いです。

2022-06-16 02:48 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> + * レコード削除成功1件 - basic認証
「basic 認証」だけだと、何のことか解らない。
「basic 認証あり」と書いた方が良いです。

2022-06-16 02:48 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> +test('200 Success - 100 records', () => {
HTTP リクエスト数の上限を意識したテストケースだと思いますが、

100 件ではなく、`httpClient.getRequestingLimit()` 件の方が良いです。

2022-06-16 04:57 UTC, chica-non commented on kintone-record-delete.xml
> +test('200 Success - 100 records', () => {
HTTPのリクエストは1回しか出してなくて、100件より多くのレコードがパラメータにある場合、kintoneが400を返すので、httpClient.getRequestingLimit()は関係なさそうだと思いました。

2022-06-16 05:12 UTC, hatanaka-akihiro commented on kintone-record-delete.xml
> +test('200 Success - 100 records', () => {
そうか。理解を間違えていました。

kintone では「現時点では 100 レコードまでまとめて削除できる」と解っているので、
テストの焦点は「クエリパラメータとして 100 個レコード id を指定できること」の確認になるわけですか。

いずれにせよ、なぜ 100 個なのか解るように、コメントに記載してください。


また `DELETE FAILED' のテストケースは、どうせなら「100件より多くのレコードがパラメータにある場合、
kintoneが400を返す」パターンにした方が良いです。１つ特徴的なので。またテストケースの順番も変える。

2022-06-17 06:01 UTC, hatanaka-akihiro requested changes

2022-06-20 01:51 UTC, chica-non commented
レビューをお願いします。
・sumdomainが33文字になっていない件、修正しました。

コンソール出力で確認
2022-06-20 10:27:07,916  INFO <> c.q.b.c.e.a.ServiceTaskAddonServiceImpl - config[conf_domain] test-06aaaaaaaaaaaaaaaaaaaaaaaaaa.cybozu.com

2022-06-20 02:25 UTC, merged