t8319: kintone: レコード追加　単体テストの追加／summary の変更
Questetra/Addon-XML pull request #441
Opened 2022-06-23 05:45 UTC by suese-sayaka

@hatanaka-akihiro さん

教えてください。
リクエストのテストを検証するコードで、398 行目
`expect(bodyObj.record).toEqual(recordObj);`
でビルドが失敗します。オブジェクトの検証が間違っているのでしょうか

（テストコードは、この処理をコメントアウトして、ビルドを通して作成しています。）

2022-06-23 06:27 UTC, hatanaka-akihiro commented
> @hatanaka-akihiro さん
> 
> 教えてください。 リクエストのテストを検証するコードで、398 行目 `expect(bodyObj.record).toEqual(recordObj);` でビルドが失敗します。オブジェクトの検証が間違っているのでしょうか
> 
> （テストコードは、この処理をコメントアウトして、ビルドを通して作成しています。）

まあ検証方法を間違えているのだと思います。
そもそも recordObj の中身は、意図した値になっているのでしょうか。

例えば "POST Failed" のテストケースで

```
  let fieldCode = configs.put(`conf_fieldCode1`, `フィールドコード_1`);
  let fieldValue = configs.put(`conf_fieldValue1`, data[0]);
	
  recordObj[fieldCode] = {
    "value": fieldValue
  };
```
となっていますが、recordObj の中身は、どのような値を意図しているのでしょうか。
それに対して、fieldCode, fieldValue の値は意図した値になっているでしょうか。

2022-06-27 02:43 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

単体テストの追加、summary を変更しました。ご確認をお願いいたします。

単体テストで、以前質問していた、リクエストのテストを検証するコードですが、
fieldCode, fieldValue の値は意図した値になっていませんでしたので、修正しました。ありがとうございました。

2022-06-27 04:47 UTC, hatanaka-akihiro requested changes

2022-06-27 04:47 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +	recordObj[`フィールドコード_${i+1}`] = {
インデントがおかしい。

2022-06-27 04:47 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +  const data = ['', '', '', '', '', '', ''];
このテストケースで要るのでしょうか？

2022-06-27 04:47 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> + * レコード追加成功（全てのフィールドコードに初期値のレコードが登録される）
> （全てのフィールドコードに初期値のレコードが登録される）

は記載しなくても良いです。「全てのフィールドコードが空白」というテストケースなので、何を言っているか解らないですし．．．

（おそらく言いたいことは、「レコードは追加される。そのレコードのフィールドの値は、kintone 側で設定された初期値の値になる。」ということかと。ただこれは、このテストケースに限らない話。指定しないフィールドの値は、全て kintone 側で設定された初期値の値になるはず。）

重要なことは、フィールドコードの設定が空の場合、値の設定が無視されるということだと思います。

2022-06-27 04:47 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> + * レコード追加成功（全てのフィールドコードに初期値のレコードが登録される）
つまり「値の設定はするけど、対応するフィールドコードの設定が空」というテストケースだと思います。

テストケースで、重要なポイントをおさえましょう。

ちなみに「指定しないフィールドの値は、全て kintone 側で設定された初期値の値になる」ということは、Addon のテストプログラムでは表現できません。

2022-06-27 04:47 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> + * C9F: フィールドコード_3 に存在しないフィールドコードを指定
存在しないフィールドコードを指定しても、kintone 側で無視されて、処理に影響しないのでしょうか。

Addon のテストプログラムでは表現できないテストケースなので、無くて良いです。

`Sucsess - 7fieldCodes` のテストケースと、実質的に差がありません。

2022-06-27 04:58 UTC, hatanaka-akihiro requested changes

2022-06-27 04:58 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +  configs.put(`conf_fieldValue2`, data[1]);
厳密なことを言うと、設定項目がある場合、`configs.get()` の値が null になることはありません。
つまり「設定をしない」項目についても、空文字列を put する方が、実際の挙動に近くなります。

2022-06-28 00:40 UTC, suese-sayaka commented on kintone-record-add.xml
> +	recordObj[`フィールドコード_${i+1}`] = {
修正しました

2022-06-28 00:41 UTC, suese-sayaka commented on kintone-record-add.xml
> +  const data = ['', '', '', '', '', '', ''];
削除しました

2022-06-28 00:41 UTC, suese-sayaka commented on kintone-record-add.xml
> + * レコード追加成功（全てのフィールドコードに初期値のレコードが登録される）
コメントを修正しました

2022-06-28 00:41 UTC, suese-sayaka commented on kintone-record-add.xml
> + * C9F: フィールドコード_3 に存在しないフィールドコードを指定
削除しました

2022-06-28 00:42 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。
ご確認をお願いいたします。

2022-06-28 05:54 UTC, hatanaka-akihiro requested changes

2022-06-28 05:54 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +
confi_fieldCode1 から conf_fieldCode7 まで
conf_fieldValue1 から conf_fieldValue7 まで、
`prepareConfigs()` の中で空に設定しておくのが良いと思いました。

その上で、各テストケースで必要であれば、設定を上書きする。

2022-06-28 05:54 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +    configs.put(`conf_fieldCode${i+1}`, ``); //全てのフィールドコードが空白
`prepareConfigs()` で空が設定されていれば、こちらのコードは不要になる。

2022-06-28 05:54 UTC, hatanaka-akihiro commented on kintone-record-add.xml
> +  const data = ['test1', '', '', '', '', '', ''];
配列にする必要は無くて、`test1` を定義した変数が存在するだけで良いのでは？

2022-06-30 02:59 UTC, suese-sayaka commented on kintone-record-add.xml
> +
onfi_fieldCode1 から conf_fieldCode7 まで
conf_fieldValue1 から conf_fieldValue7 まで、
prepareConfigs() の中で空に設定するように修正しました。

2022-06-30 03:00 UTC, suese-sayaka commented on kintone-record-add.xml
> +    configs.put(`conf_fieldCode${i+1}`, ``); //全てのフィールドコードが空白
削除しました。

2022-06-30 03:00 UTC, suese-sayaka commented on kintone-record-add.xml
> +  const data = ['test1', '', '', '', '', '', ''];
修正しました

2022-06-30 03:00 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いいたします。

2022-06-30 03:16 UTC, hatanaka-akihiro approved these changes

2022-06-30 03:17 UTC, merged