t8320 kintone: レコード更新　単体テストの追加／summary の変更
Questetra/Addon-XML pull request #444
Opened 2022-07-05 03:09 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストの追加、summary を変更しました。
ご確認をお願いいたします。

2022-07-05 06:37 UTC, hatanaka-akihiro requested changes

2022-07-05 06:37 UTC, hatanaka-akihiro commented on kintone-record-update.xml
> +  prepareConfigs(configs, '', 'test.kintone.com', '1', '3', '');
細かいけど、レコード ID として設定する、適切な値は null やね。

設定値 `configs.get()` は必ず string を返すので、空の場合、空文字列。
(`configs.getObject()` は何を返すか解らないので、null を返す)

データ項目の値は、空の場合、null。文字型とは限らないから。

2022-07-05 06:37 UTC, hatanaka-akihiro commented on kintone-record-update.xml
> +  configs.put('conf_fieldCode2', 'フィールドコード_1');
1 番目と 2 番目が一致しているのは、kintone-record-add と全く同じ。

変えた方が良いです。

2022-07-05 06:37 UTC, hatanaka-akihiro commented on kintone-record-update.xml
> +  recordObj[`フィールドコード_2`] = { //フィールドコードが空白の組(conf_fieldCode6 と conf_fieldValue6)は無視される
コメントがおかしい。

2022-07-05 06:37 UTC, hatanaka-akihiro commented on kintone-record-update.xml
> + * C8V: 値_2 が空白
「正しいフィールドコードを１つ指定」との関連が解るように記載した方が良いです。

2022-07-14 01:05 UTC, suese-sayaka commented on kintone-record-update.xml
> +  prepareConfigs(configs, '', 'test.kintone.com', '1', '3', '');
ありがとうございます。修正しました。

2022-07-14 01:05 UTC, suese-sayaka commented on kintone-record-update.xml
> +  configs.put('conf_fieldCode2', 'フィールドコード_1');
修正しました

2022-07-14 01:06 UTC, suese-sayaka commented on kintone-record-update.xml
> +  recordObj[`フィールドコード_2`] = { //フィールドコードが空白の組(conf_fieldCode6 と conf_fieldValue6)は無視される
修正しました

2022-07-14 01:06 UTC, suese-sayaka commented on kintone-record-update.xml
> + * C8V: 値_2 が空白
コメントを修正しました

2022-07-14 01:49 UTC, hatanaka-akihiro requested changes

2022-07-14 01:49 UTC, hatanaka-akihiro commented on kintone-record-update.xml
> + * フィールドコードが空白で、値のみ設定されている
もう１度、コメントを改良しましょう。

全体としては、「フィールドコードを１つだけ指定している」というテストケースです。
しかし、それに他のテストケースを含めているため、ややこしくなっています。

どういうテストケースを含めているのか、整理しましょう。
そして、それをコメントに表現する。

2022-07-14 02:42 UTC, suese-sayaka commented on kintone-record-update.xml
> + * フィールドコードが空白で、値のみ設定されている
コメントを修正しました

2022-07-14 03:13 UTC, hatanaka-akihiro approved these changes

2022-07-14 03:13 UTC, merged