T8558: Stripe: 顧客を検索　を作成
Questetra/Addon-XML pull request #446
Opened 2022-07-15 04:02 UTC by tatsumiQ

2022-07-26 08:56 UTC, hatanaka-akihiro requested changes

2022-07-26 08:56 UTC, hatanaka-akihiro commented on stripe-customer-search.xml
> +    // バリデーションエラーに任せているため、スクリプトエラーにならない
STRING_TEXTFIELD の場合、２ページ目以降のリクエストをする必要がありません。
（必要ならその時点でエラー）

なので、スクリプトレベルでもチェックする意味があると思いました。
「kintone: レコード検索」はそのような実装になっているようです。

2022-07-26 08:56 UTC, hatanaka-akihiro commented on stripe-customer-search.xml
> +        <config name="conf_Query" required="true" el-enabled="true" form-type="TEXTAREA">
query が空を認め、空の場合、'List all customers' の API を使用する場合、コードは何行ほど増えますか？

空だったら `created>0` という、全件検索できる query にする手もありますが。

2022-07-29 04:58 UTC, tatsumiQ commented on stripe-customer-search.xml
> +    // バリデーションエラーに任せているため、スクリプトエラーにならない
「kintone: レコード検索」と同様にチェックしてスクリプトエラーにするよう変更しました。

2022-07-29 05:00 UTC, tatsumiQ commented on stripe-customer-search.xml
> +        <config name="conf_Query" required="true" el-enabled="true" form-type="TEXTAREA">
'List all customers' の API を使用すると、40行ほど増えます。
（テストコードも増えるので、実際にはもっと増えます）
https://github.com/Questetra/Addon-XML/pull/446/commits/273042396a8db3bf35ea597f05e7d4d3381ee02a

query が空であれば `created>0` に設定するようにしました。

2022-07-29 08:50 UTC, hatanaka-akihiro requested changes

2022-07-29 08:50 UTC, hatanaka-akihiro commented on stripe-customer-search.xml
> +        nextPage = search(auth, query, nextPage, customerIds, customerNames, customerEmails);
「HTTP リクエスト数のチェック」は、QBPMS 任せだと思います。
それは良いとして、「検索結果が多すぎる」「絞り込みが足りない」ということが（少しでも）伝わるように、「今の時点での顧客件数」をログ出力するのが良いと思いました。

2022-07-29 08:50 UTC, hatanaka-akihiro commented on stripe-customer-search.xml
> +        // 最後のリクエストでも hasMore が true
サービスタスクのスクリプトで、`hasMore` は見ていないような。

2022-08-01 03:15 UTC, tatsumiQ commented on stripe-customer-search.xml
> +        nextPage = search(auth, query, nextPage, customerIds, customerNames, customerEmails);
顧客件数をログ出力するようにしました。

2022-08-01 03:19 UTC, tatsumiQ commented on stripe-customer-search.xml
> +        // 最後のリクエストでも hasMore が true
定義ファイル 154 行目でレスポンスの `has_more` プロパティを見ています。
`has_more` を見ずに `next_page` プロパティでチェックした方が良いでしょうか？

```
if (responseObj.next_page === undefined) {
    return responseObj.next_page;
}
```

2022-08-01 05:49 UTC, hatanaka-akihiro commented on stripe-customer-search.xml
> +        // 最後のリクエストでも hasMore が true
見落としていました。このままで良いです。

2022-08-01 05:49 UTC, hatanaka-akihiro approved these changes

2022-08-01 05:49 UTC, merged