T8615: Stripe: 請求書をメール送付　payment_method_types に wechat_pay が含まれているとエラー
Questetra/Addon-XML pull request #448
Opened 2022-08-01 06:51 UTC by tatsumiQ

2022-08-01 07:57 UTC, hatanaka-akihiro requested changes

2022-08-01 07:57 UTC, hatanaka-akihiro commented on stripe-invoice-send.xml
> +    checkPaymentMethodTypes(auth, invoiceId, paymentIntentId);
チェックせず、常に update する手も考えられます。

が、「'card' のみの状態から 'card' のみに更新すると、エラーになる」という理解であっていますか？

2022-08-02 01:23 UTC, tatsumiQ commented on stripe-invoice-send.xml
> +    checkPaymentMethodTypes(auth, invoiceId, paymentIntentId);
> 「'card' のみの状態から 'card' のみに更新すると、エラーになる」という理解であっていますか？
いえ、'card' のみの状態から 'card' のみに更新してもエラーにはなりません。

チェックしてから update しているのは、回収不能（uncollectible）ステータスの請求書への対応のためです。
回収不能（uncollectible）は、いちどこのステータスに変更すると元（オープンステータス）に戻すことはできませんが、支払いを行うことはできます。

「Stripe: 請求書をメール送付」も「Stripe: 請求書で課金」も、オープンと回収不能、どちらのステータスでも支払いできる仕様にしています。
ですが、回収不能ステータスの請求書は編集不可のため、「'card' のみへの更新」に失敗します。

チェックせずに update すると、回収不能ステータスの請求書には完全に非対応になってしまいます。
それを避けたほうがいいと考えました。
（たとえば、一度このアイテムで請求書をメール送付後、回収不能ステータスになったものを再送付しようとすると失敗してしまいます。チェックしてからの update であれば、再送付が可能になります）

補足）
請求書のステータスは、ダッシュボードから手動で変更できるほか、「支払期限がすぎた請求書を自動的に回収不能ステータスに変更する」設定も可能です。

2022-08-02 01:35 UTC, hatanaka-akihiro commented on stripe-invoice-send.xml
> +    checkPaymentMethodTypes(auth, invoiceId, paymentIntentId);
つまり以下の理解であっていますか？

- 回収不能ステータスである場合、
 - 「card のみ」であるなら、そのまま処理させる。
 - それ以外は失敗させる
- 回収不能ステータスでない場合、
 - 「card のみ」ならそのまま。
 - それ以外は「card のみ」に更新させる。

`checkInvoice()` で請求書のステータスは解ると思うので（予想）、「回収不能ステータス」かどうかで処理を分けて良いようにも思いました。（回収不能なら「card のみ」かどうかチェック。そうでないなら、「card のみ」に更新）
この辺の事情をプログラムに落とし込めるので。

2022-08-02 02:46 UTC, tatsumiQ commented on stripe-invoice-send.xml
> +    checkPaymentMethodTypes(auth, invoiceId, paymentIntentId);
現状の仕様はご認識のとおりです。

> `checkInvoice()` で請求書のステータスは解ると思うので（予想）
すこし厄介なのですが、`checkInvoice()` でステータス（回収不能かどうか）はわかります。
ただ、支払方法のタイプが「card のみ」かどうかは分かりません。

支払方法のタイプは
- Invoice オブジェクト
- Payment Intent オブジェクト
の両方に設定がありますが、Stripe のデフォルトの設定を使用する場合、Invoice オブジェクトの支払方法のタイプは null に設定されます。
そのため、「Stripe のデフォルトの設定により支払方法のタイプが card のみになっているかどうか」を調べるには、Payment Intent オブジェクトを見る必要があります。

2022-08-03 02:14 UTC, hatanaka-akihiro approved these changes

2022-08-03 02:14 UTC, merged