Slack: チャット投稿 (Incoming Webhook)単体テスト追加／summaryの変更
Questetra/Addon-XML pull request #453
Opened 2022-08-08 02:54 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストコードを追加しました。
summary の変更をしました。

ご確認をお願いいたします。

変更元のコードは、以下のものを流用しました。
https://raw.githubusercontent.com/Questetra/Addon-XML/release-2021-08-26/slack-chat-post-webhook.xml

アイコンの色がグリーンで、標準アイテムの紫と異なります。
こちらのファイルで、どこか設定する箇所があれば教えてください。

2022-08-08 03:22 UTC, hatanaka-akihiro requested changes

2022-08-08 03:22 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +        "text": `${text}`,
`text` だけで動くはずです。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Object_initializer
「略記プロパティ名」

2022-08-08 03:22 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +        return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(preparePostResponse('text3')));
`prepareConfigs()` の引数に指定している `text3` と対応しているのだと思います。
定数として切り出しましょう。

2022-08-08 04:02 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +        "text": `${text}`,
ありがとうございます。
修正しました。

2022-08-08 04:02 UTC, suese-sayaka commented
@hatanaka-akihiro  さん
修正しました。ご確認をお願いいたします。

2022-08-08 04:44 UTC, hatanaka-akihiro requested changes

2022-08-08 04:44 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +        "text": text,
できていないです。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Object_initializer
「略記プロパティ名」をもう１度、勉強しましょう。

2022-08-08 04:44 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +    "title": title,
`fallback` `color` `title` も略記プロパティ名で省略できそうです。

2022-08-08 05:29 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +        "text": text,
修正しました

2022-08-08 05:29 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +    "title": title,
修正しました

2022-08-08 05:29 UTC, suese-sayaka commented
@hatanaka-akihiro さん
修正しました。ご確認をお願いいたします。

2022-08-09 01:12 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いします。

2022-08-10 02:52 UTC, hatanaka-akihiro requested changes

2022-08-10 02:52 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +  prepareConfigs(configs, 'https://hooks.slack.com/services/ABCDE', null, '', color, title, '12345', '');
正常系の webhookUrl が、全て同じように思います。少なくとも 1 つは変えた方が良い。

2022-08-10 02:52 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +  //Attachmentタイトルが未設定のため、Attachmentタイトルリンクは設定されず、オブジェクトは空
コメントが不十分だと思う。

'Success - Attachment-text' のテストケースとの違いを、よく考えて。

2022-08-10 02:52 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +    "title_link": "12345",
「AttachmentタイトルリンクがURLの形式でないため、Attachmentタイトルにリンクが無いケース」との矛盾を感じました。

「Attachmentタイトルにリンクが無い」なら、「`title_link` プロパティがあるのはおかしいんじゃないの？」と思ってしまう。

「Attachmentタイトルにリンクが無い」というのは、Slack WebUI での表現の話で、API やプログラム上では表現されない話では？

2022-08-10 02:52 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +  const title = "title6"
`color` と `title` だけ対応して、webhook_url や title_link について対応しなかった理由は？これらも２か所以上で使われている。

他のテストケースでも、同じような対応をしなかった理由は？

2022-08-15 02:06 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +  prepareConfigs(configs, 'https://hooks.slack.com/services/ABCDE', null, '', color, title, '12345', '');
修正しました

2022-08-15 02:06 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +  //Attachmentタイトルが未設定のため、Attachmentタイトルリンクは設定されず、オブジェクトは空
コメントを追加しました

2022-08-15 02:07 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +    "title_link": "12345",
コメントを修正しました

2022-08-15 02:08 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +  const title = "title6"
「略記プロパティ名」と勘違いしていました
修正しました

2022-08-15 02:08 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-08-15 22:44 UTC, hatanaka-akihiro requested changes

2022-08-15 22:44 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +  const WebhookUrl = 'https://hooks.slack.com/services/ZZZZZ';
先頭は小文字にするのが一般的。

2022-08-15 22:44 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> +  const fallback = "fallback3";
「２回以上、使用されているリテラルについては、const 変数に切り出した方が良い」という意味の指摘でした。`webhookUrl` `mainText` 以外は１度しか使われていないので、元のままでも問題ありませんでした。

ただ、テストに使用しているデータが解りやすいので、このままで良いです。

2022-08-15 22:44 UTC, hatanaka-akihiro commented on slack-chat-post-webhook.xml
> + * AttachmentタイトルリンクがURLの形式でないため、Slack WebUI 上では Attachmentタイトルにリンクが無いケース（チャット投稿は成功する）
このプログラムの観点で言うと、

AttachmentタイトルリンクがURLの形式でないが、チャット投稿は成功する
（Slack WebUI 上では、無視されてリンクにならない)

と書くべき。プログラムからは、「リンクにならない」ということが全く解らないので。

2022-08-16 00:42 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> +  const WebhookUrl = 'https://hooks.slack.com/services/ZZZZZ';
修正しました

2022-08-16 00:42 UTC, suese-sayaka commented on slack-chat-post-webhook.xml
> + * AttachmentタイトルリンクがURLの形式でないため、Slack WebUI 上では Attachmentタイトルにリンクが無いケース（チャット投稿は成功する）
ありがとうございます。修正しました。

2022-08-16 00:42 UTC, suese-sayaka commented
@hatanaka-akihiro さん
テストコードを修正しました。ご確認をお願いします。

2022-08-17 02:54 UTC, merged