T8626: Stripe: 請求書をメール送付　支払い情報を保存しない設定ができるように／クレジットカード以外の支払いができるように
Questetra/Addon-XML pull request #455
Opened 2022-08-09 06:07 UTC by tatsumiQ

2022-08-10 01:20 UTC, hatanaka-akihiro requested changes

2022-08-10 01:20 UTC, hatanaka-akihiro commented on stripe-invoice-send.xml
> +            <label locale="ja">C3: カード情報を再利用するための設定を行わない</label>
「支払い完了時、顧客が使用したカード情報を、次回請求のために保存しない」とか。
C4 にあわせるのが良いと思います。

2022-08-10 01:20 UTC, hatanaka-akihiro commented on stripe-invoice-send.xml
> +            <label locale="ja">C3: カード情報を再利用するための設定を行わない</label>
他の案

- 顧客が使用したカードを、次回以降の請求で使用しない
- 顧客が使用したカードを、次回以降の請求対象としない

2022-08-12 01:56 UTC, tatsumiQ commented on stripe-invoice-send.xml
> +            <label locale="ja">C3: カード情報を再利用するための設定を行わない</label>
> 「支払い完了時、顧客が使用したカード情報を、次回請求のために保存しない」

off にしてもカード情報自体は保存され、認証が不要なカードであれば次回請求で利用できる。

> 顧客が使用したカードを、次回以降の請求で使用しない
> 顧客が使用したカードを、次回以降の請求対象としない

off にしても、認証が不要なカードであれば、次回請求で利用できる。

Stripe のドキュメントでは「今後の支払いのためにカードを最適化する」という表現。
https://stripe.com/docs/payments/payment-intents#future-usage

> [setup_future_usage](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-setup_future_usage) パラメーターは、将来の再使用に備えて決済手段を保存します。カードの場合、このパラメーターは [SCA](https://stripe.com/docs/strong-customer-authentication) などの地域の法規制やネットワーク規則に準拠してオーソリ率を最適化します。

仕様を整理すると、

| TOGGLE が off | TOGGLE が on |
| ------------- | ------------- |
| 支払いはカードのみ  | カード以外でも支払いできる  |
| 支払い時の認証ステップが増えるかも  | 支払い時の認証ステップが少なく済むかも  |
| 今後の請求でカード決済が失敗しにくい | 今後の請求でカード決済が「要認証」で失敗しやすい |

2022-08-12 02:07 UTC, tatsumiQ commented on stripe-invoice-send.xml
> +            <label locale="ja">C3: カード情報を再利用するための設定を行わない</label>
別案
- 「顧客が使用したカードの情報を、次回以降の請求のために最適化しない」
-「顧客が使用したカードの認証情報を、次回以降の請求で使用しない」
- 「支払い時、カード情報を次回以降の請求で使用する前提での認証を顧客にもとめない」（長すぎる）

2022-08-12 02:08 UTC, tatsumiQ commented on stripe-invoice-send.xml
> +            <label locale="ja">C3: カード情報を再利用するための設定を行わない</label>
Notes で補足する前提で、「顧客が使用したカードを、次回以降の請求で使用しない」がよさそう。
設定時に、on/off どちらにすればいいのかわかりやすい。

2022-08-12 03:04 UTC, hatanaka-akihiro approved these changes

2022-08-12 03:04 UTC, merged