8595: kintone: ファイルアップロード　単体テストの追加／summary の変更
Questetra/Addon-XML pull request #459
Opened 2022-08-19 05:54 UTC by suese-sayaka

@hatanaka-akihiro さん

テストコード作成とsummary の変更を行いました。
ご確認をお願いします。

2022-08-22 01:59 UTC, hatanaka-akihiro requested changes

2022-08-22 01:59 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  expect(bodyObj.record['添付ファイル'].value).toEqual(attachments);
`添付ファイル` というのは、config で指定しているフィールドコードだと思います。

まずその辺のつながりが、プログラムから解らないのが問題。

2022-08-22 01:59 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  expect(bodyObj.record['添付ファイル'].value).toEqual(attachments);
またプログラム上、「決め打ち」の値になっているということは、`添付ファイル` というフィールドコード以外でテストをしていないという疑問が出てきます。

2022-08-22 02:05 UTC, hatanaka-akihiro requested changes

2022-08-22 02:05 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +test('Necessary HTTP requests exceeds the limit', () => {
「境界値テスト」で検索してみてください。
本来的には、境界値の境目、正常系と異常系の両方のテストケースがあった方が良いです。

このアイテムは、「ファイル数制限 - 2」という、少し特殊なところに境界値があるので、正常系テストケースも作ってください。

2022-08-22 02:05 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +test('Necessary HTTP requests exceeds the limit', () => {
「複数 2 ファイル」はなくても良いです。

「ファイル最大数」も、「複数ファイル」のテストケースをカバーするので。

2022-08-22 06:02 UTC, suese-sayaka commented on kintone-file-upload.xml
> +  expect(bodyObj.record['添付ファイル'].value).toEqual(attachments);
@hatanaka-akihiro さん

添付ファイルというフィールドコード以外でテストできるように、
GET リクエストのレスポンスを準備（const prepareGetResponse）で、attachFileFieldCode の引数を渡すようにしました。
```
/**
 * GET リクエストのレスポンスを準備
 * @return responseObj
 */
const prepareGetResponse = (attachFileFieldCode) => {
  return {
    "record": {
      "`${attachFileFieldCode}`": {
        "type": "FILE",
        "value": [
          {
            "contentType": "text/plain",
            "fileKey":"201202061155587E339F9067544F1A92C743460E3D12B3297",
            "name": "test1.txt",
            "size": "23175"
          },
          {
            "contentType": "text/plain",
            "fileKey": "201202061155583C763E30196F419E83E91D2E4A03746C273",
            "name": "test2.txt",
            "size": "23175"
          }
        ]
	  }
    }
  };
};
```

PUT リクエストのテスト　（const assertPutRequest）では、
```
expect(bodyObj.record[`${attachFileFieldCode}`].value).toEqual(attachments);
```
として、検証するようにしたのですが、ビルドすると、
```
"org.graalvm.polyglot.PolyglotException: 添付ファイル does not exist in the record.

```
というエラーが出ます。

・GET リクエストのレスポンスを準備
・PUT リクエストのテスト
の、コードの書き方に問題があるのでしょうか

2022-08-22 06:16 UTC, hatanaka-akihiro requested changes

2022-08-22 06:16 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`": {
`` `${attachFileFieldCode}` `` という名前のプロパティ名になっています。

ダブルクオートが要らないと思います。

2022-08-22 06:16 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`" : {
`prepareGetResponse()` と同じ。

2022-08-22 06:16 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  expect(bodyObj.record[`${attachFileFieldCode}`].value).toEqual(attachments);
`expect(bodyObj.record[attachFileFieldCode].value)`

で動くと思います。

2022-08-22 06:23 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  expect(bodyObj.record['添付ファイル'].value).toEqual(attachments);
@suese-sayaka 

レスポンスを準備の方に問題があります。指摘をしました。

2022-08-22 06:23 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  expect(bodyObj.record[`${attachFileFieldCode}`].value).toEqual(attachments);
こちらは今のままでも動きます。
動きますが、「コードに無駄がある」という指摘です。

2022-08-22 23:59 UTC, suese-sayaka commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`": {
@hatanaka-akihiro  さん

質問する前は、ダブルクォートをつけずに書いていました。
その時のビルドのエラーが、以下でした。
```
javax.script.ScriptException: SyntaxError: <eval>:244:7 Expected ident but found 
      `${attachFileFieldCode}`: {
       ^
<eval>:244:7 Expected ; but found $
      `${attachFileFieldCode}` : {
       ^
<eval>:244:27 Expected ; but found file1
    files.add(createQfile(`file1.txt`, 1));
                           ^
<eval>:244:39 Expected an operand but found .
        files.add(createQfile(`ファイル${i}.txt`, 1 ));
                                       ^
<eval>:601:0 Missing close quote
```
よって、ダブルクォートをつけました。ダブルクォートをつけると、前回の質問のとおり、
```
"org.graalvm.polyglot.PolyglotException: 添付ファイル does not exist in the record.
```
となります。

他に、書き方を間違っていないか、見直してみます。


トラックで、「この問題は JSON.parse(body) する前の body の内容をログ出力」とありますが、
engine.log(body);
と書けばよいのでしょうか。このように書いても、出力されませんでした。間違っていたら教えてください。

2022-08-23 00:09 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`": {
https://qiita.com/zaburo/items/d42934bb42edb65182ed

このやり方だと上手くいくかな。

2022-08-23 00:19 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`": {
> engine.log(body); と書けばよいのでしょうか。

はい。

`engine.log('test test test');`

とすると

```
2022-08-23 09:11:20,063  INFO <> c.q.b.c.e.s.TestEngine - test test test
```

というようなログが、Jenkins の「コンソール出力」で確認できます。

2022-08-25 03:38 UTC, suese-sayaka commented on kintone-file-upload.xml
> +      "`${attachFileFieldCode}`": {
https://qiita.com/zaburo/items/d42934bb42edb65182ed
こちらで解決しました。ありがとうございました。

engine.log　についてもありがとうございます。
ログ出力で確認したかったため、いったん　engine.log　をいくつか残しています。不要なら削除します。

2022-08-25 03:39 UTC, suese-sayaka commented on kintone-file-upload.xml
> +  expect(bodyObj.record[`${attachFileFieldCode}`].value).toEqual(attachments);
動きました。ありがとうございます。

2022-08-25 03:39 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いします。

2022-08-25 06:14 UTC, hatanaka-akihiro requested changes

2022-08-25 06:14 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        "value": [
本来、`value` の要素数は、アップロードしたファイルの数に等しくなるのだと思います。
（テストケースによって、アップロードするファイル数が異なるのに、要素数が常に同じというのはおかしい）

もし PUT のレスポンスを、プログラムで利用していないのであれば、その旨を記載し、空のレスポンスを返すのが良いと思います。

2022-08-25 06:14 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        "value": [
`attachmentFileFieldCode` には、２つファイルが添付されていて、その状態からファイルをアップロードしている、ということでしょうか。

テストケースとしては、ファイルが添付されている／添付されていないの両パターン、あった方が良いです。
つまり `prepareGetResponse()` は、既にファイルが添付されている／されていない、複数パターンのレスポンスを返せる方が良いです。

2022-08-26 03:51 UTC, suese-sayaka commented on kintone-file-upload.xml
> +  configs.put(`conf_fieldCode`, `添付ファイル`);
修正しました

2022-08-26 03:51 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        if (reqCount === 0) {
削除しました

2022-08-26 03:51 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        while (reqCount <= httpClient.getRequestingLimit() - 2) {
if 文に修正しました

2022-08-26 03:54 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        "value": [
value の要素数は、もともと添付されているファイル数+ アップロードされたファイル数 なのかなと思っていました。

ファイルアップロード成功の場合の２つのテストケースで、このオブジェクトに fileKey の値を push するので、
もともとファイルが添付されている場合と、添付されていない場合で、２つのレスポンスを作成しました。

2022-08-26 03:55 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        "value": [
ファイルが添付されている／添付されていないのパターンを作成しました。

2022-08-26 06:24 UTC, hatanaka-akihiro requested changes

2022-08-29 01:48 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        "value": [
修正しました

2022-08-29 01:48 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        const attachments = prepareGetResponse(attachFileFieldCode);
修正しました

2022-08-29 01:53 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        "value": [
PUT のレスポンスは、プログラム (test タグではなく、script タグ内のスクリプト) で利用していません。
kintone api を参考にして、PUTのレスポンスを作成しましたが、script タグ内のスクリプトで使用していない場合は、空のレスポンスを返すのでよいのでしょうか。
このアイテムに限らず、他のアイテムでも、script タグ内のスクリプトで使用していないレスポンスは、テストコードでは空を返す処理にするのでしょうか。

2022-08-29 07:27 UTC, hatanaka-akihiro requested changes

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +  if (num !== 0){
要らない。

`num=0` の場合、`for` ループ内の処理は行われないです。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        "value": [
> script タグ内のスクリプトで使用していない場合は、空のレスポンスを返すのでよいのでしょうか。 

構いません。プログラムが解りやすくなるなら、そのようにすべきです。

ただし「その旨を記載し」と、このスレッドの最初に記載しています。「コメントに記載する」という意味です。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        valueAttachments = attachments.record[attachFileFieldCode].value;
const も let も書かないのは良くない。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            attachments = prepareGetResponse(attachFileFieldCode, 0);
`prepareGetResponse` 「GetResponse を準備する」と言いながら、変数名が `attachments` というのは、気に食わないです。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        attachments.record[attachFileFieldCode].value.push(postResponseObj);
`attachments` 絡みの処理は、もっときれいにできると思います。

次のテストケースとの、コードの違いが気になりました。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +    const attachFileFieldCode = "添付ファイル";
２つしかない正常系で、同じフィールドコードを使用しない。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +test('Sucsess - basic and guestSpaseId', () => {
`Sucsess` は誤字。

2022-08-29 07:27 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +    let postResponseObj;
`postResponseObj` を、`httpClient.setRequestHandler()` の外側で定義する必要はないと思います。

2022-08-30 02:22 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        "value": [
コメントにレスポンス不使用の旨を記載し、空のレスポンスを返すよう修正しました。

2022-08-30 02:22 UTC, suese-sayaka commented on kintone-file-upload.xml
> +  if (num !== 0){
修正しました

2022-08-30 02:23 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        valueAttachments = attachments.record[attachFileFieldCode].value;
attachments 絡みの処理を見直したため、valueAttachments　の変数を削除しました

2022-08-30 02:23 UTC, suese-sayaka commented on kintone-file-upload.xml
> +            attachments = prepareGetResponse(attachFileFieldCode, 0);
修正しました

2022-08-30 02:23 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        attachments.record[attachFileFieldCode].value.push(postResponseObj);
修正しました

2022-08-30 02:23 UTC, suese-sayaka commented on kintone-file-upload.xml
> +    const attachFileFieldCode = "添付ファイル";
修正しました

2022-08-30 02:23 UTC, suese-sayaka commented on kintone-file-upload.xml
> +test('Sucsess - basic and guestSpaseId', () => {
修正しました

2022-08-30 02:24 UTC, suese-sayaka commented on kintone-file-upload.xml
> +    let postResponseObj;
修正しました

2022-08-30 02:24 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。
ご確認をお願いします。

2022-08-30 08:06 UTC, hatanaka-akihiro requested changes

2022-08-30 08:06 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        attachments = getResponseObj.record[attachFileFieldCode].value;
この処理に間違いはないが、何をしているか解りにくい。

`attachments` は「添付ファイル」、`getResponseObj` は「GET リクエストに対する応答」。本来、この２つは結び付かない。

このような「客観的にみて何をしているか解りにくいところ」には、コメントを記載しましょう。

2022-08-30 08:06 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            attachments.push(postResponseObj);
ここも先の指摘と同じ。

処理に間違いはないが、何をしているか解りにくい。

このような「客観的にみて何をしているか解りにくいところ」には、コメントを記載しましょう。

2022-09-01 01:55 UTC, suese-sayaka commented on kintone-file-upload.xml
> +const assertPostRequest = ({url, method, body}, domain, guestSpaceId, appId, recordId, files, filename, filesize) => {
使用していませんでした。削除しました。

2022-09-01 01:55 UTC, suese-sayaka commented on kintone-file-upload.xml
> + * @param recordId
追加しました

2022-09-01 01:55 UTC, suese-sayaka commented on kintone-file-upload.xml
> +    let getResponseObj;
修正しました

2022-09-01 01:55 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        attachments = getResponseObj.record[attachFileFieldCode].value;
コメントを記載しました

2022-09-01 01:56 UTC, suese-sayaka commented on kintone-file-upload.xml
> +            attachments.push(postResponseObj);
コメントを記載しました

2022-09-01 01:56 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-09-01 05:50 UTC, hatanaka-akihiro requested changes

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        if (reqCount === 1) {
`else if` で。今の形でも間違っていませんが。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            attachments.push(postResponseObj);
「アップロードする」より「アップロードされる」とか「アップロードされた」と、受け身の方が良いです。

このブロックはリクエストを受ける側、つまりファイルをアップロードされる側の処理なので。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        if (reqCount <= httpClient.getRequestingLimit() - 2) {
念のための指摘ですが、ここも `else if` で。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            attachments = getResponseObj.record[attachFileFieldCode].value;
「レコードに添付されているファイルはない」状態のテストケース。

739 行目で `let attachments=[];` としておき、ここでは何もしないのが解りやすいかもしれません。

`getResponseObj.record[attachFileFieldCode].value` の値も `[]` だと思います。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            let fileName = `ファイル${reqCount}.txt`;
このブロック内で `fileName` は変化しないので、 `const` で。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            const fileSize = 1;
ファイルサイズが 1 であるのは、最初に用意しているファイルのサイズがすべて 1 だから、だと思います。

ファイルを用意するところより前に、ファイルサイズの変数を指定した方が良いです。

2022-09-01 05:50 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +            let fileName = `ファイル${reqCount}.txt`;
ファイル名を作る関数を用意。`const prepareFileName = num => `ファイル${num}.txt';

そしてこの関数を、ファイルを用意するところと、リクエストをチェックするところ。両方で使用すると良いでしょう。

2022-09-05 02:02 UTC, suese-sayaka commented on kintone-file-upload.xml
> +            attachments.push(postResponseObj);
修正しました

2022-09-05 02:02 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        if (reqCount === 1) {
修正しました

2022-09-05 02:02 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        if (reqCount <= httpClient.getRequestingLimit() - 2) {
修正しました

2022-09-05 02:04 UTC, suese-sayaka commented on kintone-file-upload.xml
> +            let fileName = `ファイル${reqCount}.txt`;
const に修正しました

ファイル名を作る関数を用意しました。
ファイル数が HTTP リクエスト数制限を超えてエラーになる場合　のテストケースにも使用するので、そのテストケースの前に関数を用意しました。

2022-09-05 02:04 UTC, suese-sayaka commented on kintone-file-upload.xml
> +            const fileSize = 1;
修正しました

2022-09-05 02:05 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

テストコードを修正しました。ご確認をお願いします。

2022-09-05 07:11 UTC, hatanaka-akihiro requested changes

2022-09-05 07:11 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        }else if (reqCount === 1) {
`} else if...`

スペースが抜けています。

2022-09-05 07:11 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        }else if (reqCount <= httpClient.getRequestingLimit() - 2) {
スペースが抜けています。

2022-09-05 07:11 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        engine.log("ファイルアップロード成功1")
インデントはあわせた方が良いです。上の `}` とずれているのがおかしい。

2022-09-05 07:11 UTC, hatanaka-akihiro commented on kintone-file-upload.xml
> +        assertPutRequest(request, domain, guestSpaceId, appId, recordId, attachments, attachFileFieldCode);
インデントはあわせた方が良いです。上の `}` とずれているのがおかしい。

2022-09-06 00:26 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        }else if (reqCount === 1) {
修正しました

2022-09-06 00:26 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        }else if (reqCount <= httpClient.getRequestingLimit() - 2) {
修正しました

2022-09-06 00:26 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        engine.log("ファイルアップロード成功1")
修正しました

2022-09-06 00:26 UTC, suese-sayaka commented on kintone-file-upload.xml
> +        assertPutRequest(request, domain, guestSpaceId, appId, recordId, attachments, attachFileFieldCode);
修正しました

2022-09-06 00:27 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-09-06 04:10 UTC, hatanaka-akihiro approved these changes

2022-09-06 04:10 UTC, merged