t8500: Generate Text File - be able to delete other files when saving…
Questetra/Addon-XML pull request #480
Opened 2022-09-27 05:09 UTC by chica-non

保存時に他のファイルを削除できるように／HTML ファイルで保存できるように　変更しました。

レビューをお願いします。

2022-09-27 05:18 UTC, chica-non commented
一行目が以下のように2行に分かれていたので、変更しました。
<?xml version="1.0" encoding="UTF-8"?>
<service-task-definition>

改めてレビューをお願いします。

2022-09-29 01:26 UTC, hatanaka-akihiro requested changes

2022-09-29 03:02 UTC, chica-non commented
レビューをお願いします。以下を修正しました。
・C5: 保存する際のファイルタイプのラベル変更、それに伴う処理
・deleteOtherFiles===true の場合、engine.findDataByNumber() の処理をしないように
・if文の書式

2022-10-05 02:14 UTC, hatanaka-akihiro requested changes

2022-10-05 02:14 UTC, hatanaka-akihiro commented on generator-textfile.xml
>    if(filename === "" ||filename === null) {
Visual Source Code でフォーマットできていないようです。
`<script>` タグ内のスクリプトも、フォーマットの対象です。

2022-10-05 03:05 UTC, chica-non commented
レビューをお願いします。

<script> タグ内のスクリプトをVisual Source Code でフォーマットしました。

2022-10-11 00:43 UTC, hatanaka-akihiro requested changes

2022-10-11 00:43 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    </item>
text/xml と application/json も増やそう。なんとなくですが。

2022-10-11 03:38 UTC, chica-non commented
text/xml と application/json も選択肢も増やしました。
レビューをお願いします。

2022-10-12 00:34 UTC, hatanaka-akihiro approved these changes

2022-10-12 00:34 UTC, merged