t8596: kintone: ファイルダウンロード　単体テストの追加／summary の変更
Questetra/Addon-XML pull request #481
Opened 2022-09-29 05:56 UTC by suese-sayaka

@hatanaka-akihiro  さん

単体テストの追加と summary の変更を行いました。
ご確認をお願いいたします。

2022-09-30 07:13 UTC, hatanaka-akihiro requested changes

2022-09-30 07:13 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    assertFile(files_data.get(1), name, contentType, 'UTF-8', 'testcase-7\n');
`testcase-7\n` と、最後に改行コードが入っているのは何でだろ？

レスポンスの値は `testcase-7` なので、不思議に思いました。

2022-09-30 07:13 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +        } else if (reqCount <= httpClient.getRequestingLimit() - 1) {
この else if の条件はなくて良い。

2022-09-30 07:13 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
この辺のコードを見ていると、`prepareGetResponse()` を使わない方がすっきりするような気もします。

2022-10-03 02:52 UTC, suese-sayaka commented on kintone-file-download.xml
> +    assertFile(files_data.get(1), name, contentType, 'UTF-8', 'testcase-7\n');
この部分は、
Box: ファイルダウンロード
https://raw.githubusercontent.com/Questetra/Addon-XML/release-2021-12-17/box-file-download.xml
(任意Webサイト): ファイル ダウンロード
https://raw.githubusercontent.com/Questetra/Addon-XML/release-2022-06-14/any-website-file-download.xml

を参考にしました。どちらも、最後に改行コードが入っていました。
改行コードが無い場合、ビルドでエラーになりました。

2022-10-03 02:52 UTC, suese-sayaka commented on kintone-file-download.xml
> +        } else if (reqCount <= httpClient.getRequestingLimit() - 1) {
修正しました

2022-10-03 02:52 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
修正しました

2022-10-03 02:53 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-10-05 02:23 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    assertFile(files_data.get(1), name, contentType, 'UTF-8', 'testcase-7\n');
`assertFile()` 内のコード次第です。

2022-10-05 02:56 UTC, hatanaka-akihiro requested changes

2022-10-05 02:56 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            engine.log("max-test2");
インデントがおかしいです。

コードを修正したら、フォーマットを行うように。

2022-10-05 02:56 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
この形にするなら、`fileKey` と `name` を決めるところを関数化し、`contentType` の値を定数化すると良いように思いました。

`prepareGetResponse()` 内部も含めて。

2022-10-06 02:09 UTC, suese-sayaka commented on kintone-file-download.xml
> +    assertFile(files_data.get(1), name, contentType, 'UTF-8', 'testcase-7\n');
ありがとうございます。修正しました。

2022-10-06 02:09 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
修正しました。

2022-10-06 02:10 UTC, suese-sayaka commented on kintone-file-download.xml
> +            engine.log("max-test2");
すみません、忘れていました。フォーマットしました。

2022-10-06 02:11 UTC, suese-sayaka commented
@hatanaka-akihiro さん
テストコードを修正しました。ご確認をお願いします。

2022-10-07 06:11 UTC, hatanaka-akihiro requested changes

2022-10-07 06:11 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    fileRepository.readFile(file, encoding, line => text += line);
`fileRepository.readFile()` は、1行ずつ (改行コード抜きで) 読み込むので、改行コードを入れる処理自体は間違っていないです。

問題は「どういう場合に改行コードを入れるか」という話です。

2022-10-07 06:11 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
`contentType` は、グローバルな定数にすればよいという意味でした。

> `fileKey` と `name` を決めるところを関数化し

が実現されていません。

2022-10-11 02:41 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
修正しました

2022-10-11 02:42 UTC, suese-sayaka commented on kintone-file-download.xml
> +    fileRepository.readFile(file, encoding, line => text += line);
修正しました。
「文字列中に、改行コードが含まれている場合」ということでしょうか？

2022-10-12 00:23 UTC, hatanaka-akihiro requested changes

2022-10-12 00:23 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    }
レスポンスの形が変わるのは良くないです。

また、この形は昔にやっていた形で、解りにくいと思います。

2022-10-12 00:23 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +const CONTENTTYPE = "text/plain";
言葉の区切りが解るように、`CONTENT_TYPE` とするのが一般的です。

2022-10-12 00:23 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
今の形は、ずっと前にやっていた形と同じで、あまり綺麗にならなかったと思います。

「i を引数にとって、`key-${i}` を返す関数を作った方が良いのではないか」という意見でした。
そしてそれを、`prepareGetResponse()` とテストの関数の２か所で使う。

例えば関数は以下です。

``const getFileKey = i => `key-${i}`;``

`fileKey` と `name` の値は決まった後ですが、それの値が２か所に分散していました。
関数を使って、それをまとめた方が良いのではないか、という指摘です。

2022-10-13 02:29 UTC, suese-sayaka commented on kintone-file-download.xml
> +    }
修正しました

2022-10-13 02:29 UTC, suese-sayaka commented on kintone-file-download.xml
> +const CONTENTTYPE = "text/plain";
修正しました

2022-10-13 02:30 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
ありがとうございます。
関数を作成し、修正しました。

2022-10-13 02:32 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-10-13 04:19 UTC, hatanaka-akihiro requested changes

2022-10-13 04:19 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    }
これはダメかな。
仮に本来は複数行のデータであっても、改行抜きで比較できてしまう。

１行しかないなら text の値も 1行、2行しかないなら 2 行になるようにしたい。
その場合、それぞれ改行コードの数はいくつか。

また `readFile()` の引数に指定した関数は、1行しかないなら 1 回、2行しかないなら 2 回呼ばれる。

2022-10-13 04:19 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
fileKey, name, contentType の変数 (配列) は要らないと思います。

2022-10-14 01:11 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
contentType の変数 (配列)　は、削除しました

fileKey, name, の変数 (配列) は、733 行目、747 行目で使用しているので、残しました。

2022-10-14 01:12 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-10-14 07:15 UTC, hatanaka-akihiro requested changes

2022-10-14 07:15 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +            }
> fileKey, name, の変数 (配列) は、733 行目、747 行目で使用しているので、残しました。

「その使用が要らない」という指摘です。

2022-10-14 07:15 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    }
「本来は複数行のデータであっても、改行抜きで比較できてしまう」という点は変わっていません。

`fileRepository.readFile()` の部分を改良して実現してください。

> また `readFile()` の引数に指定した関数は、1行しかないなら 1 回、2行しかないなら 2 回呼ばれる。
> １行しかないなら text の値も 1行、2行しかないなら 2 行になるようにしたい。

つまり 1 回しか呼ばれないなら text の値も 1 行、2 回しか呼ばれないなら text の値も 2 行になるようにしたい。それができていないから、本来は 1 行のデータなのに、`'testcase-7\n`、つまり ２行のデータと比較していた。

2022-10-17 01:43 UTC, suese-sayaka commented on kintone-file-download.xml
> +    }
修正しました

2022-10-17 01:43 UTC, suese-sayaka commented on kintone-file-download.xml
> +            }
修正しました

2022-10-17 01:44 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-10-18 07:50 UTC, hatanaka-akihiro requested changes

2022-10-18 07:50 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    expect(text).toEqual(body);
body に指定されるのは「期待する文字列の値」。
「期待する文字列の値」とは無関係に、ファイルに含まれていた文字列を再現したいです。

これまでヒントを書いていましたが、もう１回、ヒントを記載します。

`fileRepository.readFile()` の 3 番目の引数で指定する関数。
これは「ファイルが１行しかなければ１回しか呼ばれない」「ファイルが２行しか無ければ２回しか呼ばれない」ものです。「１行ということは、改行コード無し」「２行ということは、改行コードは１つ」です。

2022-10-18 07:50 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +const assertFile = (file, name, encoding, body) => {
encoding に指定されている値。すべて 'UTF-8' なので、encoding 引数は不要では？

そうかテストケースのいずれかには、UTF-8 でないものを入れた方が良いです。

2022-10-18 07:50 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    const num = 1; //レコードに添付されているファイル数
kintone 側の添付ファイル数も、QBPMS 側の添付ファイル数も 1 なので、num が何を意味しているのか、ちょっと解りにくいです。

どちらかを 2 にするか、名前を工夫した方が良いです。

2022-10-18 07:50 UTC, hatanaka-akihiro commented on kintone-file-download.xml
> +    const files_data = engine.findData(fileDef);
変数名にアンダーバーは、あまり使わないです。
`files` という名前が使われていたので、この名前にしたのでしょうか。
`resultFiles` とか、「実行結果のファイル」ということが解る名前にしましょう。

2022-10-20 02:05 UTC, suese-sayaka commented on kintone-file-download.xml
> +    expect(text).toEqual(body);
修正しました

2022-10-20 02:06 UTC, suese-sayaka commented on kintone-file-download.xml
> +const assertFile = (file, name, encoding, body) => {
テストケースのひとつは、UTF-8 でないものにしました

2022-10-20 02:06 UTC, suese-sayaka commented on kintone-file-download.xml
> +    const num = 1; //レコードに添付されているファイル数
両方修正しました

2022-10-20 02:07 UTC, suese-sayaka commented on kintone-file-download.xml
> +    const files_data = engine.findData(fileDef);
この変数名も　Box: ファイルダウンロード　の変数をそのまま使用してしまいました。
修正しました。

2022-10-21 05:20 UTC, hatanaka-akihiro requested changes

2022-10-25 00:49 UTC, suese-sayaka commented on kintone-file-download.xml
> +const assertFile = (file, name, encoding, body) => {
修正しました。

2022-10-25 00:50 UTC, suese-sayaka commented on kintone-file-download.xml
> +    }
修正しました。

チケットで教えていだだいたとおり、テストケースも、改行コードで終わるテストデータは使わないように修正しました。

2022-10-25 00:50 UTC, suese-sayaka commented
@hatanaka-akihiro さん

テストコードを修正しました。ご確認をお願いします。

2022-10-25 05:48 UTC, hatanaka-akihiro approved these changes

2022-10-25 05:48 UTC, merged