T8704: Stripe: 商品を検索　の作成
Questetra/Addon-XML pull request #485
Opened 2022-10-13 03:18 UTC by tatsumiQ

2022-10-14 06:47 UTC, hatanaka-akihiro requested changes

2022-10-14 06:47 UTC, hatanaka-akihiro commented on stripe-product-search.xml
> +test('Success - 1 product found', () => {
Success - 1 product found, saved to single-line data items

のテストケースがあるので、なくても良いと思いました。

2022-10-14 06:47 UTC, hatanaka-akihiro commented on stripe-product-search.xml
> +    Array.prototype.push.apply(defaultPriceIds, products.map(product => product.default_price));
配列自体が配列に push されないよう、このような形で記載しているのでしょうか。

prototype を使ったコードは、避けたいところ。

products を forEach でまわして、3 つの配列に追加していけばよいと思いました。

2022-10-14 06:47 UTC, hatanaka-akihiro commented on stripe-product-search.xml
> + */
このテストケースは、HTTP リクエスト時の query パラメータのチェックだけなので、異常系でも正常系でも、他のテストケースに混ぜたら良いと思いました。

2022-10-14 06:47 UTC, hatanaka-akihiro commented on stripe-product-search.xml
> + */
Success - max number of products found

のテストケースに含めてはどうでしょうか。

取り扱うデータが多いので、テストメソッドも減らした方が良いかと。

2022-10-17 01:28 UTC, tatsumiQ commented on stripe-product-search.xml
> +    Array.prototype.push.apply(defaultPriceIds, products.map(product => product.default_price));
深く考えずに書いてしまっていました。
products を forEach でまわす書き方に変更しました。
prototype のメソッドを使わないよう、気をつけます。

2022-10-17 01:29 UTC, tatsumiQ commented on stripe-product-search.xml
> + */
HTTP リクエスト回数が上限を超える場合のテストケースに混ぜました。

2022-10-17 04:13 UTC, hatanaka-akihiro requested changes

2022-10-17 08:42 UTC, hatanaka-akihiro approved these changes

2022-10-17 08:42 UTC, merged