t8873: Google Sheets: Append New Row -change summary and error cases
Questetra/Addon-XML pull request #521
Opened 2022-12-13 05:28 UTC by chica-non

レビューをお願いします。以下を変更しました。
・summary
・異常系のテストの形式

2022-12-14 00:53 UTC, hatanaka-akihiro requested changes

2022-12-14 00:53 UTC, hatanaka-akihiro commented on google-sheets-row-append.xml
> +<summary>This item adds new cells after the last row with data in a sheet, inserting a row into the sheet if necessary.</summary>
なんとなくですが、日本語と英語の意味が違うように思いました。

もともと「必要あれば行領域を拡大します」は、その意味するところを説明できていないように思うので、無くて良いのでは？

2022-12-15 02:48 UTC, chica-non commented
レビューをお願いします。

summaryを変更しました。
「必要あれば行領域を拡大します」という表現は日英ともに削除しました。
日本語はconfigでは「末尾行」となっているので、それに合わせて「シートの末尾行」に変更しました。

2022-12-15 06:00 UTC, hatanaka-akihiro requested changes

2022-12-15 06:00 UTC, hatanaka-akihiro commented on google-sheets-row-append.xml
> +<summary>This item adds a row to the last row with data in the sheet and fills each cell with data.</summary>
`adds a row to the last row` は違うと思います。日本語と同じで、「末尾行に行を１行追加」ではない。

`This item adds a row after the last row of the sheet, and fills each cell of that row with data.`
`This item adds a row at the last of the sheet, and fills each cell of that row with data.`
`This item adds a row with data, at the last of the sheet.`

とか。

2022-12-19 01:35 UTC, chica-non commented
レビューをお願いします。
summaryについて
日本語は元に戻し、英語は2番目の提案が日本語と合っていると思ったので、それに変更しました。

2022-12-19 02:52 UTC, hatanaka-akihiro approved these changes

2022-12-19 02:52 UTC, merged