T9140: Docraptor: PDF 生成　の作成
Questetra/Addon-XML pull request #548
Opened 2023-04-27 06:13 UTC by tatsumiQ

2023-05-08 06:50 UTC, hatanaka-akihiro requested changes

2023-05-08 06:50 UTC, hatanaka-akihiro commented on docraptor-pdf-generate.xml
> +    return fileRepository.readFile(sourceFile, decideCharset(contentType));
「コンバータ (Excel-CSV ファイル to テーブル型データ)」等で使われている

`fileRepository.readFile(sourceFile, charset, function (line) {});`

を使わなかったのは、どういう理由からでしたっけ？

2023-05-08 06:50 UTC, hatanaka-akihiro commented on docraptor-pdf-generate.xml
> +    let charset = contentType.split('charset=')[1];
`sourceFile.getCharset()` を使用するのが良いです。

15.1 で入ったメソッドなので、ドキュメントが追い付いていなかったのでしょう。

null か charset を返します。

2023-05-08 06:50 UTC, hatanaka-akihiro commented on docraptor-pdf-generate.xml
> +    requestBody.async = true; // 非同期生成をリクエストする
```
const requestBody = {
  document_type: 'pdf',
  document_content: html,
  async: true,
  name : `Questetra-m${processInstance.getProcessModelInfoId()}-p${processInstance.getProcessInstanceId()}`
};
```

が良いか。

2023-05-09 01:32 UTC, tatsumiQ commented on docraptor-pdf-generate.xml
> +    return fileRepository.readFile(sourceFile, decideCharset(contentType));
API リクエストの際にリクエストボディに全行を格納しなければならず、一行ずつ読み出すメリットがなさそうだったからです。

2023-05-11 07:26 UTC, hatanaka-akihiro requested changes

2023-05-12 08:17 UTC, hatanaka-akihiro requested changes

2023-05-12 08:17 UTC, hatanaka-akihiro commented on docraptor-pdf-generate.xml
> +            <label locale="ja">C2: 変換元の HTML が保存されているファイル型/文字型データ項目</label>
最近のアイテムは、データ型を記載せず「データ項目」としていたと思います。
セレクトコンポーネントの方で、データ型を表示しているので。

2023-05-12 08:18 UTC, hatanaka-akihiro requested changes

2023-05-12 08:18 UTC, hatanaka-akihiro commented on docraptor-pdf-generate.xml
> +            <label locale="ja">C3: 生成された PDF ファイルを保存するファイル型データ項目</label>
こちらも、ラベルから「ファイル型」の記載を削除。

2023-05-15 02:31 UTC, hatanaka-akihiro approved these changes

2023-05-15 02:31 UTC, merged