t9022: Converter (Text File to String type data) - add character encoding
Questetra/Addon-XML pull request #549
Opened 2023-05-08 05:35 UTC by chica-non

レビューをお願いします。以下を変更しました。
・ファイル型データ項目を読み込む際の文字コードを追加
・上記に伴う本体コードとテストコードを修正

2023-05-08 07:04 UTC, hatanaka-akihiro requested changes

2023-05-08 07:04 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +                <item value="x-UTF-16LE-BOM">
読み込みにおいて、この選択肢は不要。

BOM から Big Endian か Little Endian か判断するので。

2023-05-08 07:04 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +                    <label>UTF-16BE with BOM</label>
ラベルは「UTF-16」としてください。

2023-05-08 07:04 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +                    <label locale="ja">UTF-16 (BE BOM なし)</label>
ラベルは「UTF-16BE (BOM なし)」としてください。

2023-05-08 07:04 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +                    <label locale="ja">UTF-16 (LE BOM なし)</label>
ラベルは「UTF-16LE (BOM なし)」としてください。

2023-05-08 07:04 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    const characterEncoding = configs.get("conf_CharacterEncoding");
前の定義ファイルから存在しているアプリでは、`conf_CharacterEncoding` の設定は無い。

その考慮ができていない。

（「必須にしない」ということからも、考慮が必要ですが)

2023-06-16 01:58 UTC, chica-non commented
レビューをお願いします。
以下について変更しました。
・XML 部分について新しいものに合わせて項目の順番を変更
・label 変更に伴いソース変更
・テストコードにprepareConfigs() を追加

2023-06-16 02:47 UTC, hatanaka-akihiro requested changes

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +            <label locale="ja">C2: ファイルの Content-Type charset で指定された文字コードで読み込む</label>
「もしあれば」というニュアンスを入れられると良いですね。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    // ファイル型データに複数添付されている場合、エラー
myFiles が null の場合の処理を先頭に持ってきて、return してしまうと、見通しが良くなる気がします。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +        charset = 'UTF-8';
要らない。いきなり 'UTF-8' を return すれば良いです。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    files.add(engine.createQfile('1.txt', 'application/octet-stream', 'テスト1'));
4 引数の createQfile() を使用し、文字コードを明確化した方が良いです。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * ファイルのcharset: UTF-16
「読み込む際の文字コード」と「Content-Type の charset」を一致させない方が良いです。

プログラムは間違っていて、「Content-Type の charset を見ている」とも解釈できる。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * ファイルのcharset: null
コメント全般。「ファイルの文字コード」(charset と書かない方が良い) と「ContentType の charset」を明確化した方が良いです。つまり記載する。

テストケースによって、「ファイルの charset」が意味するところがぶれている。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * ファイルのContent-Type charset: x-UTF-16LE-BOM
コメントを間違えています。

また１つ上のテストケースと同じで、「読み込む際の文字コード」と「Content-Type の charset」を一致させない方が良いです。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * 読み込む際の文字コード: 空
関係ない設定でしょうが、テストケース全体の設計として、「空」ばかりでない方が良いです。

2023-06-16 02:47 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +test("success - read file's charset - true, reading - UTF-8, file's charset - UTF-16LE", () => {
これまでのテストケースがしっかり設計できていれば、無くて良いものだと思います。

2023-06-20 03:34 UTC, chica-non commented
レビューをお願いします。
変更点は以下の通りです。
・C2のラベル
・myFiles が null の場合の処理を先頭に変更
・変数でなく'UTF-8' を return
・テストケース全般

2023-06-20 05:16 UTC, hatanaka-akihiro requested changes

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    const charset = determineCharset(myFiles.get(0), readFileCharset, characterEncoding);
なんとなくですが、charset を決定する処理は updateData() 関数の外にあった方が良いと思います。
updateData() の引数が減り、役割がはっきりする。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    let charset = myFile.getCharset();
const で良いです。let でも問題ないですが。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * Content-Type: application/octet-stream; charset=UTF-16BE
「ファイルのエンコーディング」もコメントに書く。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    files.add(engine.createQfile('1.txt', 'application/octet-stream', 'UTF-16', 'テスト1'));
コメントに記載されているテスト内容と、プログラムとが合致していません。
「ファイルのエンコーディング: UTF-16LE」と記載されているのに、UTF-16 になっています。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    files.add(engine.createQfile('1.txt', 'application/octet-stream; charset=UTF-16BE', 'テスト1'));
このアイテムのテストでは、常に 4 引数の createQfile() メソッドを使用した方が良いです。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * Content-Type: application/octet-stream; charset=UTF-16LE
「ファイルのエンコーディング」もコメントに書く。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +
テストケース全体を見ると、ファイルのエンコーディングが x-UTF-16LE-BOM のものがありません。UTF-16LE が 2 つあるようです。UTF-8 が 2 つあるのは解ります。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> + * 読み込む際の文字コード: UTF-8
C2: false
C3: UTF-8

ぐらいの書き方の方が、解りやすい気がしてきました。

2023-06-20 05:16 UTC, hatanaka-akihiro commented on converter-textfile-to-string.xml
> +    files.add(engine.createQfile('1.txt', 'text/plain; charset=x-UTF-16LE-BOM', 'テスト1'));
このアイテムのテストでは、4 引数の createQfile() メソッドを使用した方が良いです。

2023-06-22 04:09 UTC, chica-non commented
レビューをお願いします。
以下を変更しました。
・ラベルを変更(C2、〇〇型)
・データ項目の設定を空文字からnullへ
・charset を決定する処理をupdateData()の関数外へ
・全般的にテストコードのコメント変更
・常に 4 引数の createQfile() メソッドを使用
・ファイルのエンコーディングが x-UTF-16LE-BOM のものを追加

2023-06-22 05:48 UTC, hatanaka-akihiro approved these changes

2023-06-22 05:48 UTC, merged