t9021:テキストファイル生成　保存する際の文字コードを指定できるように
Questetra/Addon-XML pull request #550
Opened 2023-05-18 04:05 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

ソースコード、テストコードを修正しました。

2023-05-18 05:00 UTC, hatanaka-akihiro requested changes

2023-05-18 05:00 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    <label locale="ja">C5: 保存する際の文字コード</label>
指定しない場合のデフォルト値が UTF-8 であることをはっきりさせたい。
UTF-8 の選択肢に「デフォルト」と記載すするか、C6 のラベルに記載するか。

2023-05-18 05:00 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    <label locale="ja">C6: 保存する際のファイルタイプ</label>
これも指定しない場合のデフォルト値が解るようにしたい。

2023-05-19 01:44 UTC, suese-sayaka commented on generator-textfile.xml
> +    let charset = `${characterEncoding}`;
目的はありませんでした。
修正しました。

2023-05-19 01:44 UTC, suese-sayaka commented on generator-textfile.xml
> +    }
修正しました。

2023-05-19 01:44 UTC, suese-sayaka commented on generator-textfile.xml
>      }
修正しました。

2023-05-19 01:45 UTC, suese-sayaka commented on generator-textfile.xml
> +    <label locale="ja">C5: 保存する際の文字コード</label>
ラベルに記載しました。
Google:カレンダー 予定追加　を参考にしました。

2023-05-19 01:45 UTC, suese-sayaka commented on generator-textfile.xml
> +    <label locale="ja">C6: 保存する際のファイルタイプ</label>
ラベルに記載しました。
Google:カレンダー 予定追加　を参考にしました。

2023-05-19 01:47 UTC, suese-sayaka commented
@hatanaka-akihiro さん

ソースコードを修正しました。ご確認をお願いします。

2023-05-22 00:11 UTC, hatanaka-akihiro requested changes

2023-05-22 00:11 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    <label>C5: Character encoding when saving(Not-selected UTF-8)</label>
Google カレンダー: 予定のカレンダー移動を参考にしてください。

C2: Calendar ID of the current event (Primary Calendar if blank)

2023-05-22 00:11 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    fileType = `${contentType}; charset=${characterEncoding}`;
インデント

2023-05-22 00:11 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    if (contentType === "application/json" && characterEncoding === "UTF-8") {
この書き方で行くなら、1 つ前の if ブロックに else if でふくめる方が良いと思いました。
`fileType` で比較するなら、別の if ブロックで良いです。

同じ characterEncoding で分岐させているので。

2023-05-22 02:31 UTC, suese-sayaka commented on generator-textfile.xml
> +    <label>C5: Character encoding when saving(Not-selected UTF-8)</label>
修正しました。

2023-05-22 02:31 UTC, suese-sayaka commented on generator-textfile.xml
> +    fileType = `${contentType}; charset=${characterEncoding}`;
修正しました。

2023-05-22 02:32 UTC, suese-sayaka commented on generator-textfile.xml
> +    if (contentType === "application/json" && characterEncoding === "UTF-8") {
修正しました。

2023-05-22 02:32 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

ソースコードを修正しました。ご確認をお願いします。

2023-05-22 06:28 UTC, hatanaka-akihiro requested changes

2023-05-22 06:28 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    <label>C5: Character encoding when saving(UTF-8 if not selected)</label>
半角カッコ前にはスペースを入れる。

2023-05-22 06:28 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    //application/json で UTF-8 の場合は、charset 無しで application/json のみ
このコメントは、else if の次の行に書いた方が良いです。
そうか同じ行で、else if の後ろ。

2023-05-23 01:20 UTC, suese-sayaka commented on generator-textfile.xml
> +    <label>C5: Character encoding when saving(UTF-8 if not selected)</label>
修正しました

2023-05-23 01:20 UTC, suese-sayaka commented on generator-textfile.xml
> +    //application/json で UTF-8 の場合は、charset 無しで application/json のみ
修正しました

2023-05-23 01:21 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いします。

2023-05-23 04:53 UTC, merged