T9206: SendGrid: メール送信　の作成
Questetra/Addon-XML pull request #556
Opened 2023-06-02 02:37 UTC by tatsumiQ

2023-06-06 07:28 UTC, hatanaka-akihiro requested changes

2023-06-06 07:28 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +        </config>
メール送信に直接関係のない設定項目なので、最後の方が良いと思います。

2023-06-08 08:41 UTC, hatanaka-akihiro requested changes

2023-06-08 08:41 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +            <label locale="ja">配信解除グループ</label>
「メールに埋め込む、配信解除用 URL に利用する」という側面もあるでしょうが、「送信先から除外する」という側面もあるのでは？

だとすると、「送信先」タブに入れて良いと思います。また「メール送信」の文脈から考えると、「送信除外リスト」というラベルの方が解りやすい気もします。

2023-06-09 02:23 UTC, tatsumiQ commented on sendgrid-email-send.xml
> +            <label locale="ja">配信解除グループ</label>
配信解除グループを「送信先」タブに入れました。

ラベルを変えることも検討しましたが、SendGrid の WebUI での名前をある程度想像できるラベルのほうがわかりやすいと思いました。
SendGrid の WebUI での名前が Unsubscribe Group なので。

この設定項目の役割が 2 つあること（送信先から除外されること、配信解除の URL に使用されること）は、ヘルプページに記載予定です。

2023-06-09 02:24 UTC, tatsumiQ commented on sendgrid-email-send.xml
> +                </config>
送信日時を先頭のタブに入れ、先頭のタブの名前を「API キーと送信設定」にしました。

2023-06-09 02:25 UTC, tatsumiQ commented on sendgrid-email-send.xml
> +const MAX_SEGMENT_ID_NUM = 10;
`<addon-version>2</addon-version>` にして、グローバル変数（定数）の定義を `<script>` で行うようにしました。

2023-06-09 02:57 UTC, hatanaka-akihiro requested changes

2023-06-09 02:57 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +                    <label locale="ja">C5: 配信解除グループの ID</label>
「配信停止グループ」が良さそうです。

https://sendgrid.kke.co.jp/docs/User_Manual_JP/Suppressions/advanced_suppression_manager.html

2023-06-09 02:57 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +                    <label locale="ja">C8: メール送信の ID を保存するデータ項目</label>
「メール送信 ID を...」で良いと思います。

2023-06-09 02:57 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +                    <label locale="ja">C9: メール送信のステータス確認ページの URL を保存するデータ項目</label>
「メール送信・ステータス確認ページの...」が良いと思います。「・」はスペースだけとか、無しでも良いと思います。

「...の...の」は避けたいと思ったので。

2023-06-09 02:57 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +    <summary locale="ja">この工程は、SendGrid のリストやセグメントに含まれる宛先にメールを一斉送信します。</summary>
「宛先に」の後に読点を入れようか。

2023-06-09 02:57 UTC, hatanaka-akihiro commented on sendgrid-email-send.xml
> +    }
`Object.assign()` を使った方が良いかな。今の形がダメなわけではないですが。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

```
Object.assign(emailConfig, {
  subject,
  html_content: htmlContent
});
```

2023-06-09 04:34 UTC, hatanaka-akihiro approved these changes

2023-06-09 04:34 UTC, merged