t9348 Box Sign: 署名リクエストキャンセル　の作成
Questetra/Addon-XML pull request #598
Opened 2023-08-24 04:33 UTC by suese-sayaka

@hatanaka-akihiro  さん

レビューをお願いします。

2023-08-28 05:38 UTC, suese-sayaka commented
@hatanaka-akihiro さん

 署名リクエストとしては完了している
　全員署名済
    拒否
    キャンセルされた 
場合、処理失敗ではなく、正常終了するように修正しました。

ご確認をお願いします。

2023-08-28 07:18 UTC, hatanaka-akihiro requested changes

2023-08-28 07:18 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +main();
addon-version=2 でのスクリプトの書き方を、 @tatsumiQ に教わってください。

2023-08-28 07:18 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +    const signRequest = getSignRequest(oauth2, requestId);
いきなり署名リクエストのキャンセルを試みて、そのエラー内容から判断することはできないですか？

2023-08-28 07:18 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +        cancelRequest(oauth2, requestId);
`checkStatus()` の中で `cancelRequest()` は行わない方が良いです。

その関数名の通り、status の check のみに専念させた方が良いです。

2023-08-28 07:18 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +    if (status !== 200) {
status != 200 の場合にしか、responseTxt は要らない。
なので if 文の中に持っていった方が良いです。（レスポンスの読み込み処理がなくなる)

2023-09-01 05:52 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

いきなり署名リクエストのキャンセルを試みて、エラーコードが bad_request の場合はエラー内容をログ出力したうえで正常終了するよう修正しました。

ご確認をお願いします。

2023-09-01 07:03 UTC, hatanaka-akihiro requested changes

2023-09-01 07:18 UTC, hatanaka-akihiro requested changes

2023-09-01 07:18 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +        const jsonRes = JSON.parse(responseTxt);
```
try {
  const jsonRes = JSON.parse(responseTxt);
   if (jsonRes.code === "bad_request") {
       engine.log(jsonRes.context_info.errors[0].message);
        return;
  }
} catch (ignore) {}

const error = `Failed to cancel. status: ${status}`;
engine.log(responseTxt);
throw error;
```

このように変えてください。JSON.parse() に失敗することにも備える。

2023-09-04 01:48 UTC, suese-sayaka commented on box-sign-request-cancel.xml
> +    const oauth2 = configs.get("conf_OAuth2");
configs.getObject()
に修正しました。

2023-09-04 01:48 UTC, suese-sayaka commented on box-sign-request-cancel.xml
> +        const jsonRes = JSON.parse(responseTxt);
修正しました。

2023-09-04 01:49 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

修正しました。
ご確認をお願いします。

2023-09-05 04:37 UTC, hatanaka-akihiro requested changes

2023-09-05 04:37 UTC, hatanaka-akihiro commented on box-sign-request-cancel.xml
> +    throw error;
インデントがおかしいです。

2023-09-07 01:31 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

インデントを修正しました。
ご確認をお願いします。

2023-09-07 03:27 UTC, suese-sayaka commented
@hatanaka-akihiro さん

以下の処理に修正しました。ご確認をお願いします。

ステータスコードが 200 の場合
正常終了

ステータスコードが 400 の場合
responseTxt　を全て出力（限定的にログ出力しない）
ステータスが「署名済み」、「キャンセル済み」、「拒否済み」、「変換中」の可能性がある旨を出力

それ以外
responseTxt　を全て出力し、エラー処理

2023-09-07 04:24 UTC, hatanaka-akihiro approved these changes

2023-09-07 04:24 UTC, merged