T9371: Twilio SendGrid: メール一斉送信　C2: 送信者 ID を固定値指定のみに変更
Questetra/Addon-XML pull request #599
Opened 2023-08-25 05:58 UTC by tatsumiQ

2023-08-25 07:24 UTC, hatanaka-akihiro requested changes

2023-08-25 07:24 UTC, hatanaka-akihiro commented on sendgrid-email-send-bulk.xml
> +                <config name="conf_SenderId" required="true" form-type="TEXTFIELD">
単一のメール送信が From / From アドレスの指定であるのに対し、こちらは ID の指定になっているのは、SendGrid の API の違いと考えて良いでしょうか。

2023-08-28 01:04 UTC, tatsumiQ commented on sendgrid-email-send-bulk.xml
> +                <config name="conf_SenderId" required="true" form-type="TEXTFIELD">
そうです。API のパラメータの仕様の違いによるものです。
- 単一メール送信のほうは、From の表示名を好きなように指定できる
- 一斉メール送信のほうは、メールアドレスの認証時に設定した名前が From の表示名として使用される
という違いもあります。

2023-08-28 04:54 UTC, hatanaka-akihiro approved these changes

2023-08-28 04:54 UTC, merged