T9342: Slack: ユーザ名取得　の作成
Questetra/Addon-XML pull request #601
Opened 2023-08-28 04:47 UTC by tatsumiQ

2023-08-29 06:55 UTC, hatanaka-akihiro requested changes

2023-08-29 06:55 UTC, hatanaka-akihiro commented on slack-username-get.xml
> +    <summary locale="ja">この工程は、指定した Slack のユーザのユーザ名やメールアドレスを取得します。</summary>
「この工程は、Slack ID から Slack ユーザ名やメールアドレスを取得します」でどうでしょうか。"Slack ID" と入れた方が良いと思うのと、「Slack のユーザのユーザ名」部分の「の」が冗長なので。

2023-08-29 06:55 UTC, hatanaka-akihiro commented on slack-username-get.xml
> +        throw 'Failed to get Email Address. Scope users:read.email is required.';
`setData()` の関数内で、Email Address に特化したエラーメッセージを出力するのは変だと思いました。

2023-09-01 01:38 UTC, tatsumiQ commented on slack-username-get.xml
> +        throw 'Failed to get Email Address. Scope users:read.email is required.';
メールアドレスの保存に特化した関数 `setEmailAddress()` を定義しました。

2023-09-01 01:40 UTC, tatsumiQ commented on slack-username-get.xml
> +    <summary locale="ja">この工程は、指定した Slack のユーザのユーザ名やメールアドレスを取得します。</summary>
提案いただいた通りに修正しました。
サマリーでは「Slack ID」、C2 では「Slack ユーザ ID」と表記がぶれているのが少し気になりますが、C2 は「Slack ユーザ ID」がわかりやすいと思いました。

2023-09-01 06:38 UTC, hatanaka-akihiro approved these changes

2023-09-01 06:38 UTC, merged