T9211: 開始: Microsoft 365 Outlook for Business: メール受信時／Microsoft 365 Outlook for Business: メール取得　の作成
Questetra/Addon-XML pull request #605
Opened 2023-09-04 04:52 UTC by tatsumiQ

2023-09-14 07:22 UTC, hatanaka-akihiro requested changes

2023-09-14 07:22 UTC, hatanaka-akihiro commented on outlook-message-get.xml
> +    }
`retrieveDefs()` の中でチェックし、「１つも設定されいなければ処理失敗」でも良いと思いました。

「１つも設定しないという使い方は考えにくい」「処理失敗にする方が楽そう」ということからです。

Gmail のアイテムと仕様が異なりますが。

2023-09-14 07:22 UTC, hatanaka-akihiro commented on outlook-message-get.xml
> +    }
その上で

```
const {FromAddressDef, FromNameDef} = retrieveDefs();
```

という書き方もありますが、今の方が楽ですかね。

2023-09-19 03:12 UTC, tatsumiQ commented on outlook-message-get.xml
> +    }
「１つも設定されいなければ処理失敗」に変更しました。

分割代入については、今のほうがすっきり書けている気がするので、そのままにしました。

2023-09-20 04:40 UTC, hatanaka-akihiro approved these changes

2023-09-20 04:40 UTC, merged