t9362: Trello: リスト ID 取得　の作成
Questetra/Addon-XML pull request #606
Opened 2023-09-07 04:50 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

2023-09-07 05:08 UTC, hatanaka-akihiro requested changes

2023-09-07 05:08 UTC, hatanaka-akihiro commented on trello-listid-get.xml
> +    engine.setDataByNumber(listId, trelloListId);
他のアイテムを参照してみてください。

最近は

```
const def = configs.getObject('conf_ListId');
engine.setData(def, trelloListId);
```

という実装パターンがほとんどだと思うのですが．．．

2023-09-07 05:08 UTC, hatanaka-akihiro commented on trello-listid-get.xml
> +};
テストケースを見ましたが、1つ目の要素の id と name も固定で決まっている方が良いと思いました。

2023-09-07 05:08 UTC, hatanaka-akihiro commented on trello-listid-get.xml
> +    let index = listObj.findIndex((listObj) => listObj.name === listName);
`findIndex()` 内の `listObj` と外側の `listObj` は別物だと思います。

違う名前にした方が良いです。

2023-09-08 04:24 UTC, suese-sayaka commented
@hatanaka-akihiro さん

レビューをお願いします。
指摘コメント以外に、C4: リストの名前　を、固定値指定のみに修正しました。

2023-09-08 04:30 UTC, hatanaka-akihiro approved these changes

2023-09-08 04:30 UTC, merged