t9363 Trello: ラベル ID 取得　の作成
Questetra/Addon-XML pull request #610
Opened 2023-09-12 03:27 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

2023-09-12 04:35 UTC, hatanaka-akihiro requested changes

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +	let labelsArray = labelNames.split("\n");
インデント

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    let trelloLabelId = [];
const で動くはず

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    }
configs から設定値を取得し、labelsArray を返すまでは、別関数にした方が良いと思いました。

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    let trelloLabelId = [];
名前に "trello" と入れたのはなぜか。"labelIds" や "labelIdsArray" でないのはなぜか、と思いました。

自分の中で、変数の名前規則を決めて、それに従った方が良いです。読む人の理解が進みやすくなる。

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    let index = labelObj.findIndex((labelElement) => labelElement.name === labelName);
`findIndex()` ではなく、`find()` を使えば index 変数は要らないんじゃないかと。

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +            "idBoard":"0000066666",
`idBoard` というのは、ボードの ID だと思います。`boardId` を指定してラベルを取得した場合、`idBoard` の値がバラバラになることはあるのでしょうか。

2023-09-12 04:35 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> + * 成功 -　ラベル名を 1 つ指定　- ボード内に 1 つ目と 3 つ目と 6 つ目にラベル名がある場合
> ボード内に 1 つ目と 3 つ目と 6 つ目にラベル名がある場合

の意味が解りにくいと思いました。

2023-09-14 05:56 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    }
別関数にしました

2023-09-14 05:57 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    let trelloLabelId = [];
修正しました

2023-09-14 05:57 UTC, suese-sayaka commented on trello-labelid-get.xml
> +	let labelsArray = labelNames.split("\n");
修正しました

2023-09-14 05:57 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    let index = labelObj.findIndex((labelElement) => labelElement.name === labelName);
修正しました

2023-09-14 05:58 UTC, suese-sayaka commented on trello-labelid-get.xml
> +            "idBoard":"0000066666",
バラバラになることはありません。修正しました
(idBoard　は、UI 上に表示される boardId とは異なる値でした)

2023-09-14 05:58 UTC, suese-sayaka commented on trello-labelid-get.xml
> + * 成功 -　ラベル名を 1 つ指定　- ボード内に 1 つ目と 3 つ目と 6 つ目にラベル名がある場合
修正しました

2023-09-14 05:59 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

上記の指摘に加え、チケットに指摘のあった「途中の空行は許さない」処理を加えました。
ご確認をお願いします。

2023-09-14 06:37 UTC, hatanaka-akihiro requested changes

2023-09-14 06:37 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    const labelArray = getLabelInformation(apiKey, apiToken, boardId);
`labelNamesArray` `labelIdsArray` から考えると、`labelsArray`

2023-09-14 06:37 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    let labelId;
要らないような。この変数に代入せず、いきなり return で良いかと。

2023-09-14 06:37 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +function getLabelInformation(apiKey, apiToken, boardId) {
`label` の一覧を返しているので、`getLabels()` が良いと思いました。

2023-09-14 06:42 UTC, hatanaka-akihiro requested changes

2023-09-14 06:42 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    }
単純に「最後だろうが、空行があったらエラー」でも良いと思いますが、親切に配慮するとしても「最後の改行１つ」だけで良いと思いました。（改行で終わる場合だけ、それを除去して評価する）

今だと「最後に２つ以上、改行が連続している」というテストケースも考える必要があります。ちなみに、そのテストケースは、単体テストに含まれていません。

2023-09-15 01:32 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    let labelId;
修正しました

2023-09-15 01:32 UTC, suese-sayaka commented on trello-labelid-get.xml
> +function getLabelInformation(apiKey, apiToken, boardId) {
修正しました

2023-09-15 01:32 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    const labelArray = getLabelInformation(apiKey, apiToken, boardId);
修正しました

2023-09-15 01:33 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    }
修正しました

2023-09-15 01:33 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いします。

2023-09-15 02:04 UTC, hatanaka-akihiro requested changes

2023-09-15 02:04 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +        labelIdsArray[i] = getLabelId(labelsArray, labelNamesArray[i]);
長さ 0 の配列に、index を指定して代入していることになる。あまり良くない。

```
const labelIdsArray = new Array(numOfLines);
```

とした方が良いです。

2023-09-15 02:04 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +        labelIdsArray[i] = getLabelId(labelsArray, labelNamesArray[i]);
そうか配列を一気に作成する。（この方が、格好良い）

```
const labelIdsArray = labelNamesArray.map(
  labelName => getLabelId(labelsArray, labelName)
);
```

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2023-09-15 03:58 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    }
修正しました

2023-09-15 04:00 UTC, suese-sayaka commented on trello-labelid-get.xml
> +    } else if (newLabelNamesArray.length !== labelNamesArray.length) {
全て改行の場合と、一部改行の場合で、エラー文言を変えていたので、
labelNamesArray.every(line =>
labelNamesArray.some(line =>
の 2 つを使用しました。

2023-09-15 04:01 UTC, suese-sayaka commented on trello-labelid-get.xml
> +        labelIdsArray[i] = getLabelId(labelsArray, labelNamesArray[i]);
修正しました

2023-09-15 04:01 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。よろしくお願いします。

2023-09-15 04:46 UTC, hatanaka-akihiro requested changes

2023-09-15 04:46 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +        throw "Empty lines are set.";
メッセージは `Empty lines are not allowed.` にしましょう。「空行が NG」とも設定ラベルで明記されていないので。

2023-09-15 04:46 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    if (labelNamesArray.every(line => line === '')) {
こちらの条件なしで。

「すべて空行の時だけエラーメッセージを変える」ことまでしなくて良いという判断。
「いずれか空行の時」のエラーメッセージで同じで良い。
（テストケースが増えますし）

2023-09-15 04:46 UTC, hatanaka-akihiro commented on trello-labelid-get.xml
> +    const numOfLines = labelNamesArray.length;
`numOfLines` は不要になったと思います。`labelIdsArray` の作成の仕方を変えたので。

2023-09-19 00:11 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。　ご確認をお願いします。

2023-09-19 00:27 UTC, hatanaka-akihiro approved these changes

2023-09-19 00:33 UTC, merged