t9364 Trello: メンバ ID 取得　の作成
Questetra/Addon-XML pull request #611
Opened 2023-09-19 04:02 UTC by suese-sayaka

@hatanaka-akihiro さん

定義ファイルを作成しました。
ご確認をお願いします。

2023-09-19 08:37 UTC, hatanaka-akihiro requested changes

2023-09-19 08:37 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +    let memberObj = membersArray.find(memberElement => memberElement.fullName === memberName);
`const` で動きそうです。

2023-09-19 08:37 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +    let memberNamesArray = memberNames.split("\n");
`const` で動きそうです。

2023-09-21 04:03 UTC, suese-sayaka commented on trello-memberid-get.xml
> +    let memberObj = membersArray.find(memberElement => memberElement.fullName === memberName);
修正しました

2023-09-21 04:04 UTC, suese-sayaka commented on trello-memberid-get.xml
> +    let memberNamesArray = memberNames.split("\n");
修正しました

2023-09-21 04:04 UTC, suese-sayaka commented
@hatanaka-akihiro さん

ユーザネームでもメンバ ID を取得できるよう修正しました。
ご確認をお願いします。

2023-09-22 00:44 UTC, hatanaka-akihiro requested changes

2023-09-22 00:44 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +            <label locale="ja">C4: メンバの名前（フルネームもしくはユーザネーム） （複数設定する場合、1件ごとに改行してください）</label>
１つのカッコにしましょう。文字数がもったいないですし。

2023-09-22 00:44 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +  * メンバ名が複数ある場合、最初に名前が一致したメンバの ID を取得する
最初にユーザ名またはフルネームが、設定したメンバ名に一致した、メンバの ID を取得する。

2023-09-22 00:44 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +  * メンバ名が複数ある場合、最初に名前が一致したメンバの ID を取得する
「複数ある場合」とか記載する必要が無いです。

2023-09-22 00:44 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +];
おそらくですが、fullName はスペースや漢字を許していて、ユーザ名は許していない。ユーザ名は大文字も許していないかもしれない。その辺を考慮したテストデータにした方が良いです。

2023-09-22 03:06 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いします。

2023-09-22 03:56 UTC, hatanaka-akihiro requested changes

2023-09-22 03:56 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +];
スペースも ASCII 文字。
fullName にASCII 文字でない文字も入れた方が良いという指摘です。つまり漢字やひらがな。全角英数も、非 ASCII 文字。

2023-09-22 03:57 UTC, hatanaka-akihiro commented on trello-memberid-get.xml
> +];
実際のテストでも、非 ASCII 文字を使用するのは重要です。

2023-09-25 00:46 UTC, suese-sayaka commented on trello-memberid-get.xml
> +];
修正しました
実際のテストでも、非 ASCII 文字を使用してテストしました

2023-09-25 00:58 UTC, merged