t9418 Slack: ユーザ ID 取得　Questetra が登録済みの Bot でも使用できるように
Questetra/Addon-XML pull request #612
Opened 2023-09-22 01:40 UTC by suese-sayaka

@hatanaka-akihiro  さん

Questetra が登録済みの Bot でも使用できるよう対応しました。
QBPMS 上では動作確認できたのですが、テストコードで失敗します。

https://sanjo.questetra.net/jenkins/job/userweb_test_addon/3580/com.questetra$bpms/console
このエラーはどういう意味か教えてください。

設定の準備で、認証設定の以下の箇所が間違えているのでしょうか？

```
const auth_OAuth2_V2 = httpClient.createAuthSettingOAuth2(
            'Slack',
            'https://slack.com/oauth/v2/authorize',
            'https://slack.com/api/oauth.v2.access',
            'chat:write,users:read,users:read.email',
            'consumer_key',
            'consumer_secret',
            'access_token'
        );
configs.putObject('conf_OAuth2_V2', auth_OAuth2_V2);
```

2023-09-22 02:25 UTC, hatanaka-akihiro commented
> 設定の準備で、認証設定の以下の箇所が間違えているのでしょうか？

いいや。

```
configs.putObject('conf_OAuth2_V2', '');
```

の方です。String を第２引数にとる、`putObject()` は定義されていません。
`putObject()` は `getObject()` に対応していますが、`getObject()` で String を返すものはありません。
なので `putObject()` で String の値を設定するのは間違い。

```
configs.put('conf_OAuth2_V2', '');
```

です。

2023-09-22 05:21 UTC, suese-sayaka commented
@hatanaka-akihiro さん

ありがとうございます。
修正し、テストコードのビルドが通りました。

ご確認をお願いします。

2023-09-22 06:23 UTC, hatanaka-akihiro requested changes

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +        <config name="conf_OAuth2_V2" form-type="OAUTH2" auth-type="OAUTH2"
`conf_OAuth2` で良いです。

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +    if (auth_OAuth2_V2 !== "" && auth_OAuth2_V2 !== null ){
`!== ""` ではなく `!== null` で。
`getObject()` で String が返ってくることはありません。

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +        auth = auth_OAuth2_V2;
いきなり return が解りやすいです。

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +        auth = auth_Token;
ここもいきなり return が解りやすいです。

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +const prepareConfigs = (configs, user, oauth2, token) => {
oauth2 と token は boolean で良いのでは？

2023-09-22 06:23 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> + * @@param {AuthSettingWrapper} or {String} auth
`or {String}` の場合があるのでしょうか？

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> +        <config name="conf_OAuth2_V2" form-type="OAUTH2" auth-type="OAUTH2"
修正しました

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> +    if (auth_OAuth2_V2 !== "" && auth_OAuth2_V2 !== null ){
修正しました

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> +        auth = auth_OAuth2_V2;
修正しました

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> +        auth = auth_Token;
修正しました

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> +const prepareConfigs = (configs, user, oauth2, token) => {
修正しました

2023-09-25 02:35 UTC, suese-sayaka commented on slack-userid-get.xml
> + * @@param {AuthSettingWrapper} or {String} auth
勘違いしていました　コメントを削除しました

2023-09-25 02:36 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました　ご確認をお願いいたします

2023-09-25 02:50 UTC, hatanaka-akihiro requested changes

2023-09-25 02:50 UTC, hatanaka-akihiro commented on slack-userid-get.xml
> +    }else if (auth_OAuth2 === null &&  auth_Token !== null){
`auth_OAuth2 === null` の条件は要らないと思います。null の時しか、ここに来ない。

2023-09-25 04:00 UTC, suese-sayaka commented on slack-userid-get.xml
> +    }else if (auth_OAuth2 === null &&  auth_Token !== null){
理解しました　修正しました

2023-09-25 04:01 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました　ご確認をお願いします

2023-09-25 06:05 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

「メッセージ送信 (Block Kit 対応)」もこちらのブランチに作成しました。
ご確認をお願いします。

2023-09-25 06:10 UTC, merged