T9432: Microsoft 365 Outlook for Business: メールのカテゴリ解除　の作成
Questetra/Addon-XML pull request #615
Opened 2023-09-25 02:40 UTC by tatsumiQ

2023-09-25 06:14 UTC, hatanaka-akihiro requested changes

2023-09-25 06:14 UTC, hatanaka-akihiro commented on outlook-message-category-remove.xml
> +        .filter(category => category !== '');
最後の改行コードを除外するだけで良いです。途中の空行はエラーで。

2023-09-26 01:39 UTC, tatsumiQ commented on outlook-message-category-remove.xml
> +        .filter(category => category !== '');
修正し、テストケースも追加しました。

2023-09-26 04:57 UTC, hatanaka-akihiro approved these changes

2023-09-26 04:57 UTC, merged