t9410 Box: フォルダ検索　engine-type の変更、auth-type の設定
Questetra/Addon-XML pull request #691
Opened 2024-02-05 05:47 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

異常系のテストコードの処理を以下に修正しました。

```
/**
 * 異常系のテスト
 * @param func
 * @param errorMsg
 */
const assertError = (func, errorMsg) => {
    let failed = false;
        try {
        main();
        } catch (e) {
    failed=true;
    }
    if (!failed) {
        fail();
    }
};
```

2024-02-05 07:13 UTC, hatanaka-akihiro requested changes

2024-02-05 07:13 UTC, hatanaka-akihiro commented on box-folder-search.xml
> +        try {
インデントが整っていないようです。

2024-02-06 00:02 UTC, suese-sayaka commented on box-folder-search.xml
> +        try {
インデントを修正しました。

2024-02-06 05:52 UTC, hatanaka-akihiro approved these changes

2024-02-06 05:52 UTC, merged