t9895 (任意Webサイト): ファイル ダウンロード　engine-type の変更／廃止予定の authSetting(String) の使用をやめる
Questetra/Addon-XML pull request #723
Opened 2024-04-15 01:06 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします

engine-type を 3 に変更しました
addon-version を 2 に設定しました
廃止予定の authSetting(String) の使用をやめる対応をしました

2024-04-15 23:58 UTC, hatanaka-akihiro requested changes

2024-04-15 23:58 UTC, hatanaka-akihiro commented on any-website-file-download.xml
> +const prepareConfigs = (configs,  url, files, fileName, authName) => {
この関数の中、インデントがおかしい。

引数の名前。`authName` は `authType` の方が適当じゃないかと思いました。

2024-04-16 01:03 UTC, suese-sayaka commented
@hatanaka-akihiro さん
レビューをお願いします。

異常系のテストについてもインデントを修正しました。

2024-04-16 05:51 UTC, hatanaka-akihiro approved these changes

2024-04-16 05:51 UTC, merged