T9890 Slack アイテム engine-type の変更／廃止予定の authSetting(String) の使用をやめる／廃止予定の設定を削除する
Questetra/Addon-XML pull request #727
Opened 2024-04-18 02:20 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

engine-type を 3 に変更しました。
addon-version 2 を設定しました。
auth-type を指定し、認証設定で AuthSettingWrapper を利用するように修正しました。(Slack: ファイルアップロード (Bots)、Slack: チャット投稿 (Bots))
廃止予定の設定を削除しました。(Slack: チャット投稿 (Bots))

2024-04-18 06:32 UTC, hatanaka-akihiro requested changes

2024-04-18 06:32 UTC, hatanaka-akihiro commented on slack-chat-post-bots.xml
> +        <config name="conf_OAuth2" required="true" form-type="OAUTH2" auth-type="OAUTH2"
config の name の値を、安易に変えてはいけません。

定義ファイルのバージョンアップで、これを利用したアイテムの、設定の継続性が失われるからです。

これについては `conf_OAuth2_V2` を残さないといけません。

2024-04-19 02:04 UTC, suese-sayaka commented on slack-chat-post-bots.xml
> +        <config name="conf_OAuth2" required="true" form-type="OAUTH2" auth-type="OAUTH2"
理解し、修正しました。

2024-04-19 02:05 UTC, suese-sayaka commented
@hatanaka-akihiro さん

slack-chat-post-bots.xml について修正しました。
レビューをお願いします。

2024-04-19 06:24 UTC, hatanaka-akihiro approved these changes

2024-04-19 06:24 UTC, merged