T9892
Questetra/Addon-XML pull request #728
Opened 2024-04-23 02:28 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

engine-type を 3 に変更しました
addon-version を 2 に設定しました
auth-type を指定し、認証設定で AuthSettingWrapper を利用するように修正しました。

2024-04-23 06:32 UTC, hatanaka-akihiro requested changes

2024-04-23 06:32 UTC, hatanaka-akihiro commented on stripe-customer-create.xml
> +        main();
`func()` の間違い？

引数の `func` が使われていません。

2024-04-23 06:34 UTC, hatanaka-akihiro commented on stripe-customer-create.xml
> +        main();
`main` 関数の呼び出し固定でも良いと思いますが、その場合、引数の `func` は不要になります。

2024-04-30 02:32 UTC, suese-sayaka commented on stripe-customer-create.xml
> +        main();
修正しました。

2024-04-30 02:33 UTC, suese-sayaka commented
@hatanaka-akihiro さん

レビューをお願いします。
異常系のテストコードを修正しました。

2024-04-30 04:39 UTC, hatanaka-akihiro approved these changes

2024-04-30 04:39 UTC, merged