t9886 Trello: カード作成　廃止予定の getOAuth2Token(String) の使用をやめる
Questetra/Addon-XML pull request #733
Opened 2024-04-30 04:46 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

廃止予定の getOAuth2Token() の使用をやめました
異常系のテストコードを修正しました。

2024-04-30 05:43 UTC, hatanaka-akihiro requested changes

2024-04-30 05:43 UTC, hatanaka-akihiro commented on trello-card-create.xml
> +    //configs.put('conf_ApiToken', 'TrelloApiToken');
コメントの形で、コードを残す必要はないと思います。

2024-05-02 00:32 UTC, suese-sayaka commented on trello-card-create.xml
> +    //configs.put('conf_ApiToken', 'TrelloApiToken');
削除し忘れていました。すみません。
修正しました。

2024-05-02 00:32 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。レビューをお願いします。

2024-05-02 06:00 UTC, hatanaka-akihiro approved these changes

2024-05-02 06:00 UTC, merged