T9922
Questetra/Addon-XML pull request #745
Opened 2024-05-28 01:49 UTC by suese-sayaka

@hatanaka-akihiro  さん

レビューをお願いします。

テストコードで、異常系のテストも修正しています。

2024-05-28 05:21 UTC, hatanaka-akihiro requested changes

2024-05-28 05:21 UTC, hatanaka-akihiro commented on google-sheets-cell-updateandget.xml
> +        throw `${label} is empty.`;
最近のパターンだと、`throw new Error(...);` の方が良いのでは？

2024-05-28 05:21 UTC, hatanaka-akihiro commented on google-sheets-cell-updateandget.xml
> +    }
```
    const dataDef = configs.getObject( confName );
    let string;
    if (dataDef !== null) {
        string = engine.findData(dataDef);
    } else {
        string = configs.get(confName);
   }
```
結果は同じですが、こちらの形の方が良いと思いました。

2024-05-30 01:57 UTC, suese-sayaka commented on google-sheets-cell-updateandget.xml
> +        throw `${label} is empty.`;
修正しました

2024-05-30 01:57 UTC, suese-sayaka commented on google-sheets-cell-updateandget.xml
> +    }
修正しました

2024-05-30 01:58 UTC, suese-sayaka commented
@hatanaka-akihiro さん

他のファイルも該当箇所を修正しました。
レビューをお願いします。

2024-05-30 02:47 UTC, hatanaka-akihiro approved these changes

2024-05-30 02:47 UTC, merged