T10085,T10087: Gmail: メール取得　プロセスログ出力の強化／入れ子のマルチパートの添付ファイルが保存されるように
Questetra/Addon-XML pull request #751
Opened 2024-06-24 03:01 UTC by tatsumiQ

2024-06-24 07:25 UTC, hatanaka-akihiro requested changes

2024-06-24 07:25 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +    engine.log(`Part ${index} was ignored. ${part.mimeType} `);
part オブジェクトを stringify() した結果を出力しては？

添付ファイルでもなく、本文ともみなされない part がここに来るのだと思います。

ここでのログ出力が、重要だと考えています。

2024-06-24 07:25 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>      }
2 つ目以降の plain text や html パートはログ出力した方が良いです。

今のロジックだと、無視されたことが残らないので。

2024-06-24 07:25 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>      }
両方あるメールの場合、片方は無視されるので、1 つ目からログ出力して良いと思いました。

2024-06-24 07:25 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +  // ファイル名 があれば添付ファイルとみなす
`if ( disposition === "attachment" || part.body.attachmentId !== undefined ) {`

の条件に入れて良いのではないかと思いました。

- disposition が "attachment" である
- attachmentId が指定されている
- fileName が指定されている

「上記いずれかを満たす場合、添付ファイルとみなす」のだと思ったので。

2024-06-27 03:42 UTC, tatsumiQ commented on gmail-message-get.xml
> +    engine.log(`Part ${index} was ignored. ${part.mimeType} `);
更新後の定義ファイルの 325 行目にて、part オブジェクトを stringify した結果を出力するようにしました。
part オブジェクトには base64 エンコードされた本文データも含むので、本文データが長い場合はログ出力される文字列も長くなります。
チケットに詳細を記載します。

2024-06-27 03:51 UTC, tatsumiQ commented on gmail-message-get.xml
>      }
まず、本文パートの候補になるパート（`Content-Disposition` が `attachment` でなく、`filename` も `attachmentId` もないパート）が見つかった場合には、
`Part ${part.partId} may be a body part. Content-Disposition: ${disposition}, Content-Type: ${contentType}`
のログを出力するようにしました。（更新後のファイルの 358 行目）

その後、保存する本文パートとして採用されなかったパートについては、325 行目にてそのパートの詳細（part オブジェクトを stringify した結果）がログ出力されます。

同じマルチパート内に text/plain のパート、text/html のパートがそれぞれ複数ある場合は、2 つめ以降を添付ファイルとして保存するようにしました。
これにより、すべてのパートについて、

- 本文パートとして保存する
- 無視された本文パートとしてログ出力する（325 行目）（text/plain と text/html のパートが両方ある場合の、text/html パート等を想定）
- 添付ファイルとして保存する

のいずれかになります。

2024-06-27 05:00 UTC, hatanaka-akihiro requested changes

2024-06-28 01:57 UTC, tatsumiQ commented on gmail-message-get.xml
>      }
10087 のチケットにも書きましたが、本文パート／添付ファイルの判定ロジックを変更しました。
ロジックの流れを変えただけで、結果は同じです。

> 「本文候補だけど採用されなかったパート」については、文章が含まれているので、全部ログ出力するのはやりすぎかと思いました。base64 エンコードされている状態でしょうけど、先頭何文字かだけで良いか。

`body.data` は先頭20文字だけ抜粋するようにしました。

> 「添付ファイルとして採用されなかったパート」についても、もうちょっとログ出力しておかないかと思いました。

本文の候補にならなかったパートをすべて添付ファイルとして保存するように変えたので、「添付ファイルとして採用されなかったパート」は「本文の候補になったパート」と同義になりました。
「本文の候補になったものの、採用されなかったパート」のプロセスログ出力で十分かと思いますが、どうでしょうか。
チケットにプロセスログの出力例を記載しています。

2024-06-28 02:00 UTC, tatsumiQ commented on gmail-message-get.xml
> +  // ファイル名 があれば添付ファイルとみなす
コメントの返信途中でこの件の対応が抜けていることに気づき、方法は違いますが対応しました。
2箇所でファイル名の空判定をしているので、`isFileNameBlank()` を定義しました。

2024-06-28 02:00 UTC, tatsumiQ commented on gmail-message-get.xml
> +function attachment( part ) {
ロジックの変更により、この関数は削除しました。

2024-06-28 02:52 UTC, hatanaka-akihiro requested changes

2024-06-28 02:52 UTC, hatanaka-akihiro commented on gmail-message-get.xml
> +      if ( part.mimeType === "text/plain" && textPart === null ) {
```
if (textPart === null && part.mimeType === 'text/plain' && !isObviouslyAttachment(part)) {
  ...
}
if (htmlPart === null && part.mimeType === 'text/plain' && !isObviouslyAttachment(part)) {
  ...
}

function isObviouslyAttachment(part) {
  const disposition = getDisposition(part);
  return disposition === "attachment" || part.body.attachmentId !== undefined || !isFileNameBlank(part);
}

```

の方が良いんじゃないかと思いました。

2024-06-28 02:52 UTC, hatanaka-akihiro commented on gmail-message-get.xml
>      }
気になるのは、本文候補の part

- 同一 multipart 内、２番目以降は添付ファイルとして扱われる
- 候補になって採用されなければ無視される

と処理が違う点です。同一 multipart 内の２番目以降も無視した方が良いんじゃないかと思いました。

2024-06-28 06:16 UTC, merged