t7099 コンバータ（ファイルコピー）の作成
Questetra/Addon-XML pull request #754
Opened 2024-07-02 05:59 UTC by suese-sayaka

@hatanaka-akihiro  さん

テストコードについて教えてください。

最後のテストケース　success - Same File type data - deleteOtherFiles - with name　について
 * コピー成功
 * コピー元のファイル型データ項目とコピー先のファイル型データ項目が同一
 * コピー元のファイル型データには 1 ファイル添付
 * 他のファイルを削除する
 * ファイル名を指定
 
ビルドが失敗します。ファイル名を指定していますが、ファイル名が変更されていないというエラーが出ます。
expected:<[qqq].txt> but was:<[test].txt>
もともと、test.txt　の名前のファイルを、別名 qqq.txt にするテストなのですが、上記のエラーになります。

テストの書き方、設定の準備の書き方で、よくないところがあったら教えてください。

2024-07-05 01:56 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

レビューをお願いします。
間違って理解していた仕様について、修正しました。

2024-07-08 03:47 UTC, suese-sayaka commented on converter-file-copy.xml
> +        if (sourceFile !== null && sourceFile.size() > 1) {
修正しました

2024-07-08 03:49 UTC, suese-sayaka commented on converter-file-copy.xml
> +    const copyToFile = engine.findData(copyToFileDef);
修正しました。

copyToFile は他で参照していなかったので削除しました。

2024-07-08 03:59 UTC, suese-sayaka commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
sourceFile.size() を参照するように以下のように変更すると

```
 copyFiles = copyFile(sourceFiles, deleteOtherFiles, fileName);

    //// == ワークフローデータへの代入 / Data Updating ==
    engine.setData(copyToFileDef, copyFiles);
}

/**
  * ファイルをコピーする
  * @param {Qfile} sourceFiles コピー元ファイル
  * @param {boolean} deleteOtherFiles 保存時に他のファイルを削除するかどうか
  * @param {String} filename 保存ファイル名
  */
function copyFile(sourceFiles, deleteOtherFiles, fileName) {
    let myFiles;
    if (deleteOtherFiles === true) {
        myFiles = new java.util.ArrayList();
    } else {
        // ワークフローデータからファイル型データの配列を取得
        myFiles = engine.findData(configs.getObject("conf_CopyToFileDataId"));
        if (myFiles === null) {
            myFiles = new java.util.ArrayList();
        }
    }

    let qfile;
    for(let i = 0; i < sourceFiles.size(); i ++){
        let sourceFilesInfo = sourceFiles.get(i);
        if(fileName !== "" && fileName !== null) {
            qfile = new com.questetra.bpms.core.event.scripttask.NewQfile(fileName, sourceFilesInfo.getContentType(), sourceFilesInfo);
        } else {
            qfile = new com.questetra.bpms.core.event.scripttask.NewQfile(sourceFilesInfo.getName(), sourceFilesInfo.getContentType(), sourceFilesInfo); //ファイルデータをそのまま複製保存する
        }
        myFiles.add(qfile);
    }
    return myFiles;
```

C1. コピー元ファイル型データ項目 と C2. コピー先ファイル型データ項目 が同じ
C3. 保存時に他のファイルを削除する TRUE
の場合、ビルトも、QBPMS も以下のエラーが出てしまいます。

```
スクリプトエラーが発生しました。 TypeError: instantiate on com.questetra.bpms.core.event.scripttask.NewQfile failed due to: no applicable overload found (overloads: [Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttask.ByteArrayWrapper)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttask.QfileView)]], arguments: [logo7099.png (TruffleString), image/webp (TruffleString), JavaObject[com.questetra.bpms.core.event.scripttask.NewQfile@3df6704a (com.questetra.bpms.core.event.scripttask.NewQfile)] (HostObject)]) at line number 51
```

いったん num のままで提出しています。
原因が分かりません。sourceFile.size() を参照する位置に問題があるのでしょうか。

2024-07-08 04:00 UTC, suese-sayaka commented on converter-file-copy.xml
> +        myFiles = engine.findData(configs.getObject("conf_CopyToFileDataId"));
参照していなかったので削除しました。

2024-07-08 04:00 UTC, suese-sayaka commented on converter-file-copy.xml
> +            qfile = new com.questetra.bpms.core.event.scripttask.NewQfile(fileName, sourceFile.get(i).getContentType(), sourceFile.get(i));
修正しました。

2024-07-08 04:16 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
エラーが発生しているのは、テストコード上での話ですか？

QBPMS 上で動かしても、エラーが発生していますか？

テストコード上で、コピー元とコピー先が同じデータ項目である場合に、エラーが発生していないですか？

2024-07-08 04:19 UTC, hatanaka-akihiro requested changes

2024-07-08 04:19 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +        myFiles = engine.findData(configs.getObject("conf_CopyToFileDataId"));
修正の仕方ですが、`copyFile()` 関数内で `configs` にアクセスしているのを削除してください。

`configs` へのアクセスは、１か所 (`main()` 関数) に集中しておいた方が良いです。

2024-07-09 00:59 UTC, suese-sayaka commented on converter-file-copy.xml
> +        myFiles = engine.findData(configs.getObject("conf_CopyToFileDataId"));
修正しました。

2024-07-09 01:05 UTC, suese-sayaka commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
テストコード上でも、QBPMS 上で動かしても、エラーが発生しました。

テストコード上のエラー

```
リグレッション
TypeError: instantiate on com.questetra.bpms.core.event.scripttask.NewQfile failed due to: no applicable overload found (overloads: [Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttask.ByteArrayWrapper)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttask.QfileView)]], arguments: [test.png (TruffleString), image/png (TruffleString), JavaObject[com.questetra.bpms.core.event.scripttask.NewQfile@6f0bd3de (com.questetra.bpms.core.event.scripttask.NewQfile)] (HostObject)])
```

QBPMS でのエラー
```
スクリプトエラーが発生しました。 TypeError: instantiate on com.questetra.bpms.core.event.scripttask.NewQfile failed due to: no applicable overload found (overloads: [Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttaスクリプトエラーが発生しました。 TypeError: instantiate on com.questetra.bpms.core.event.scripttask.NewQfile failed due to: no applicable overload found (overloads: [Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scriptsk.ByteArrayWrapper)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,java.lang.String,java.lang.String)], Method[public com.questetra.bpms.core.event.scripttask.NewQfile(java.lang.String,java.lang.String,com.questetra.bpms.core.event.scripttask.QfileView)]], arguments: [logo7099.png (TruffleString), image/webp (TruffleString), JavaObject[com.questetra.bpms.core.event.scripttask.NewQfile@3df6704a (com.questetra.bpms.core.event.scripttask.NewQfile)] (HostObject)]) at line number 51
```

C1. コピー元ファイル型データ項目 と C2. コピー先ファイル型データ項目 が同じ
C3. 保存時に他のファイルを削除する TRUE
の条件の時です。

C1. コピー元ファイル型データ項目 と C2. コピー先ファイル型データ項目 が同じであっても、
C3. 保存時に他のファイルを削除する が FALSE の場合は、テストコード上でも、QBPMS 上で動かしても、OKでした。

2024-07-09 01:48 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
@suese-sayaka 

> C1. コピー元ファイル型データ項目 と C2. コピー先ファイル型データ項目 が同じ C3. 保存時に他のファイルを削除する TRUE の条件の時です。
> 
> C1. コピー元ファイル型データ項目 と C2. コピー先ファイル型データ項目 が同じであっても、 C3. 保存時に他のファイルを削除する が FALSE の場合は、テストコード上でも、QBPMS 上で動かしても、OKでした。

この部分、本当ですか？

エラーになるのは「C3 が FALSE（削除しない）」の場合で、「C3　が TRUE（削除する）」の場合はエラーにならない

と推測していました。

コピー先とコピー元が同じであるため、「`sourceFiles` と `myFiles` が同じリストを指しているのではないか」と推測しています。

2024-07-09 02:23 UTC, suese-sayaka commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
@hatanaka-akihiro さん

すみません、反対です。
エラーになるのは「C3 が FALSE（削除しない）」の場合で、「C3　が TRUE（削除する）」の場合はエラーになりませんでした。

2024-07-09 02:29 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
ならエラーになるのは、コピー先とコピー元が同じであるため、「sourceFiles と myFiles が同じリストを指している」のだと思います。

`copyFile()` の前半。以下のように改良してください。別途、`configs` にアクセスしている点も改良してください。
動作確認していませんが、おそらく以下でエラーにならないようになると思います。

```
    let myFiles = new java.util.ArrayList();
    if (deleteOtherFiles === false) {
        // ワークフローデータからファイル型データの配列を取得。
        const copyToFiles = engine.findData(configs.getObject("conf_CopyToFileDataId"));
        if (copyToFiles !== null) {
            myFiles.addAll(copyToFiles);
        }
    }
```

2024-07-09 05:48 UTC, suese-sayaka commented on converter-file-copy.xml
> +function copyFile(sourceFile, deleteOtherFiles, num, fileName) {
ありがとうございます。

テストコードも、QBPMS でもエラーになりませんでした。

2024-07-10 07:17 UTC, hatanaka-akihiro requested changes

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    // ファイル名が指定されていて、コピー元のファイル型データに複数添付されている場合、エラー
インデントがおかしい

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    }
ここまでの処理は、`copyFile()` の外、`main()` で行った方が良いと思います。

ファイルをコピーする処理そのものではないから。

「コピー先ファイル型データ項目に、既にあるファイルを残すかどうか」という処理。

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +        // ワークフローデータからファイル型データの配列を取得。
コメントがおかしいです。

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    }
コピーした後に行っても良い。

「既にあるファイルを残す」という場合のみ、コピー先データ項目用のリストに追加していく。

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    copyFiles = copyFile(sourceFiles, deleteOtherFiles, fileName, copyToFiles);
なぜ `let` や `const` が無いか。

`copyFiles` と `copyToFiles` のネーミングが今一つです。

ちなみに `source` の対義語は `destination` (省略する場合は `dest`) です。

2024-07-10 07:17 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    copyFiles = copyFile(sourceFiles, deleteOtherFiles, fileName, copyToFiles);
`copyTo` の対義語は `copyFrom` です。

2024-07-11 03:22 UTC, suese-sayaka commented on converter-file-copy.xml
> +        // ワークフローデータからファイル型データの配列を取得。
コメントを別の箇所に修正しました。

2024-07-11 03:23 UTC, suese-sayaka commented on converter-file-copy.xml
> +    copyFiles = copyFile(sourceFiles, deleteOtherFiles, fileName, copyToFiles);
const で定義しました。

copyFiles と copyToFiles を修正しました。

2024-07-11 03:24 UTC, suese-sayaka commented on converter-file-copy.xml
> +    }
修正しました。

2024-07-11 03:24 UTC, suese-sayaka commented on converter-file-copy.xml
> +    // ファイル名が指定されていて、コピー元のファイル型データに複数添付されている場合、エラー
修正しました。

2024-07-11 03:24 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いいたします。

2024-07-11 04:57 UTC, hatanaka-akihiro requested changes

2024-07-11 04:57 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    const newFiles = copyFile(sourceFiles, fileName, myFiles);
```
// コピー元データ項目にあるファイルをコピー
const newFiles = copyFiles(sourceFiles, fileName);

if (deleteOtherFiles === false && destinationFiles !== null) {
  // コピー先データ項目に元からある、ファイルを残す場合、リストに残すファイルを追加する
  newFiles.addAll(destinationFiles);
}
```

これで動作するように、関数 `copyFile()` を書き換えてください。
(ついでに関数名を `copyFiles()` と複数形に変えています)

おそらく @suese-sayaka は、こちらの方がしっくり理解できる気がします。

2024-07-11 04:57 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    let qfile;
この `qfile` は for ループの中で宣言した方が良いです。
for ループの中でしか使用されないからです。

2024-07-11 04:57 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +function copyFile(sourceFiles, fileName, myFiles) {
私が言うようにプログラムを変える場合、

`let myFiles = new java.util.ArrayList();`

が関数の先頭で必要になります。

2024-07-11 04:57 UTC, hatanaka-akihiro commented on converter-file-copy.xml
> +    const newFiles = copyFile(sourceFiles, fileName, myFiles);
ただしこの改良をすると、「先にコピーされたファイル、後にコピー前から存在するファイル」の順番に変わります。

「先にコピー前から存在するファイル、後にコピーされたファイル」の順番にしたい場合は

`newFiles.addAll(0, destinationFiles);`

としてください。

2024-07-12 03:36 UTC, suese-sayaka commented on converter-file-copy.xml
> +    const newFiles = copyFile(sourceFiles, fileName, myFiles);
ありがとうございます。
修正しました。

2024-07-12 03:36 UTC, suese-sayaka commented on converter-file-copy.xml
> +    let qfile;
修正しました。

2024-07-12 03:37 UTC, suese-sayaka commented on converter-file-copy.xml
> +function copyFile(sourceFiles, fileName, myFiles) {
関数の先頭に追加しました。

2024-07-12 03:37 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。ご確認をお願いします。

2024-07-16 05:51 UTC, hatanaka-akihiro requested changes

2024-07-17 01:38 UTC, suese-sayaka commented on converter-file-copy.xml
> +    let myFiles = new java.util.ArrayList();
修正しました

2024-07-17 01:38 UTC, suese-sayaka commented on converter-file-copy.xml
> +	    let qfile;
修正しました

2024-07-17 01:39 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

修正しました。レビューをお願いします。

2024-07-17 02:15 UTC, hatanaka-akihiro approved these changes

2024-07-17 02:15 UTC, merged