t9358 Trello: カードをアーカイブ　の作成
Questetra/Addon-XML pull request #766
Opened 2024-08-08 05:05 UTC by suese-sayaka

@hatanaka-akihiro さん

レビューをお願いします。

2024-08-08 06:33 UTC, tatsumiQ requested changes
レビューしました。各コメントを確認してください。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +
このあたりで、カード ID の個数の上限チェック（HTTP リクエスト数の上限を超えていないか）を確認したほうがいいです。

「Box: フォルダ削除」などを参考にしてみてください。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +        cardArchive(apiKey, apiToken, cardIdsArray[i]);
関数名は動詞を先頭にするのが普通なので、`cardArchive()` よりも `archiveCard()` の方がいいです。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +    const cardIdsDef = configs.getObject('conf_CardIds');
`conf_CardIds` は `editable="true"` でないので、このあたりの処理はいらないと思います。

```
const cardIds = engine.findData(configs.getObject('conf_CardIds'));
```

で、直接文字列を取得してしまっていいはずです。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +    const url = `https://api.trello.com/1/cards/${cardId}`;
`cardId` として不正な文字列が入力されていても想定外のリクエストにならないように、`${encodeURIComponent(cardId)}` としたほうがいいです。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +
また、このエラーになる場合のテストケースを、テスト仕様書と単体テストに追加しておいてください。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +    let requestCount = 0;
`requestCount` をどこにも使っていないことが気になります。

すべての cardId についてリクエストが送信されたことを確認しておいたほうがいいので、

- `httpClient.setRequestHandler()` 内、return 前に `requestCount++;`
- `main();` 実行後に、`expect(requestCount).toEqual(2);` で、正しい回数リクエストが送信されたことを確認

としておくのがいいかなと思います。

2024-08-08 06:33 UTC, tatsumiQ commented on trello-card-archive.xml
> +    for (let i = 0; i < 100; i++) {
最大数 100 でテストするのでなく、`httpClient.getRequestingLimit()` でテストするようにしてください。

また、最大数を超える場合にエラーになることを確認するテストケースも追加してください。

2024-08-09 01:36 UTC, suese-sayaka commented on trello-card-archive.xml
> +
カード ID の個数の上限チェックの処理を追加しました。
エラーになる場合のテストケースを、テスト仕様書と単体テストに追加しました。

2024-08-09 01:36 UTC, suese-sayaka commented on trello-card-archive.xml
> +        cardArchive(apiKey, apiToken, cardIdsArray[i]);
修正しました。

2024-08-09 01:36 UTC, suese-sayaka commented on trello-card-archive.xml
> +    const cardIdsDef = configs.getObject('conf_CardIds');
修正しました。

2024-08-09 01:36 UTC, suese-sayaka commented on trello-card-archive.xml
> +    const url = `https://api.trello.com/1/cards/${cardId}`;
修正しました。

2024-08-09 01:40 UTC, suese-sayaka commented on trello-card-archive.xml
> +    let requestCount = 0;
assertRequest(request, `12345${requestCount++}`);
で使用しています。

expect(requestCount).toEqual(2);　の処理を追加しました。

HTTP リクエスト数の上限内のテストケースでも、正しい回数リクエストが送信されたことを確認する処理を追加しました。
expect(requestCount).toEqual(httpClient.getRequestingLimit());

2024-08-09 01:41 UTC, suese-sayaka commented on trello-card-archive.xml
> +    for (let i = 0; i < 100; i++) {
修正しました。
エラーになることを確認するテストケースを追加しました。

2024-08-09 01:41 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。レビューをお願いします。

2024-08-09 02:57 UTC, tatsumiQ commented on trello-card-archive.xml
> +    let requestCount = 0;
> assertRequest(request, 12345${requestCount++});
> で使用しています。

なるほど。見逃していました。
修正ありがとうございました。

2024-08-09 02:59 UTC, tatsumiQ commented
修正を確認しました。問題ありません。

2024-08-09 04:29 UTC, hatanaka-akihiro approved these changes

2024-08-09 04:29 UTC, merged