t9359: Trello: カード移動　の作成
Questetra/Addon-XML pull request #767
Opened 2024-08-13 04:18 UTC by suese-sayaka

@tatsumiQ さん

レビューをお願いします。

2024-08-13 07:08 UTC, tatsumiQ requested changes
レビューしました。

2024-08-16 01:02 UTC, suese-sayaka commented on trello-card-move.xml
> +    <summary locale="ja">この工程は、Trello のカードを移動します。</summary>
修正しました。

2024-08-16 01:02 UTC, suese-sayaka commented on trello-card-move.xml
> +        .queryParam("closed", "false")
修正しました。

2024-08-16 01:02 UTC, suese-sayaka commented on trello-card-move.xml
> +        }
修正しました。

2024-08-16 01:02 UTC, suese-sayaka commented on trello-card-move.xml
> +    if (numOfLines > httpClient.getRequestingLimit()) {
修正しました。

2024-08-16 01:06 UTC, suese-sayaka commented on trello-card-move.xml
> +        moveCard(apiKey, apiToken, cardIdsArray[i], listId);
カードの状態（アーカイブ済みかどうか）を確認する関数　checkCard　を追加しました。

2024-08-16 01:07 UTC, suese-sayaka commented
@tatsumiQ  さん

修正しました。ご確認をお願いします。

2024-08-16 05:47 UTC, tatsumiQ requested changes
レビューしました。単体テストで修正いただきたい箇所があります。

2024-08-16 05:47 UTC, tatsumiQ commented on trello-card-move.xml
> +    });
`if (reqCount === 0)` と `if (reqCount%2 === 0)` は、`if (reqCount%2 === 0)` にまとめられるはずです。

ID のチェックのところでややこしくなったのだと思いますが、`reqCount` と カード ID のインクリメントを分けると、わかりやすくなるのではないでしょうか。
```
    let reqCount = 0;
    let cardIndex = 0;
    httpClient.setRequestHandler((request) => {
        if (reqCount%2 === 0) {
            assertGetRequest(request, `ID${cardIndex}`);
            reqCount++;
            return httpClient.createHttpResponse(200, 'application/json', JSON.stringify(prepareGetResponse(`ID${cardIndex}`, false)));
        }
        assertPutRequest(request, `ID${cardIndex}`, 'L456DEF');
        reqCount++;
        cardIndex++;
        return httpClient.createHttpResponse(200, 'application/json', '{}');
    });
```

※このように変更する場合、494 行目の ```ids += `ID${i*2}\n`;``` のところも ```ids += `ID${i}\n`;``` でよくなるはずです。

2024-08-16 05:47 UTC, tatsumiQ commented on trello-card-move.xml
> +    });
ここも、HTTP リクエスト数の上限のテストと同様に修正をお願いします。

2024-08-23 03:32 UTC, suese-sayaka commented on trello-card-move.xml
> +    });
修正しました。

2024-08-23 03:32 UTC, suese-sayaka commented
@tatsumiQ さん

テストコードを修正しました。ご確認をお願いします。

2024-08-23 05:28 UTC, tatsumiQ requested changes
前回のレビュー時に気づかずにすみません。
カードアーカイブと同様に、API リクエストで失敗した際、カード ID をログかエラーメッセージで出力するようにしておきましょう。

2024-08-23 05:28 UTC, tatsumiQ commented on trello-card-move.xml
> +        throw new Error(`Failed to get card information. status: ${status}`);
カードアーカイブと同様に、ここでもカード ID を出力しておきましょう。

2024-08-23 05:28 UTC, tatsumiQ commented on trello-card-move.xml
> +        throw new Error(`Failed to move. status: ${status}`);
ここでもカード ID を出力しておくようにしましょう。

2024-08-26 02:34 UTC, suese-sayaka commented on trello-card-move.xml
> +        throw new Error(`Failed to move. status: ${status}`);
修正しました。

2024-08-26 02:34 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-08-27 01:15 UTC, tatsumiQ approved these changes

2024-08-29 02:03 UTC, suese-sayaka commented
@tatsumiQ さん

成功時のカード ID を出力するように修正しました。
ご確認をお願いします。

2024-08-29 03:30 UTC, tatsumiQ approved these changes

2024-08-29 04:11 UTC, hatanaka-akihiro approved these changes

2024-08-29 04:11 UTC, merged