T10183
Questetra/Addon-XML pull request #770
Opened 2024-09-06 04:35 UTC by suese-sayaka

@tatsumiQ さん

定義ファイルを作成しました。
ご確認お願い致します。

2024-09-06 07:04 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +        throw new Error(`Failed to add a collaborator. status: ${status}`);
```suggestion
    if (status !== 201) {
        // including 204: already a collaborator etc. (permission might have been updated)
        engine.log(responseStr);
        throw new Error(`Failed to add a collaborator. status: ${status}`);
```

上記の書き方でなくても良いのですが、204 レスポンスの場合を含むことをコメントに書いておいていただきたいです。
事前にチェック済みなので普通は起こり得ないはずですが、100% ありえないわけではないので。

2024-09-09 01:27 UTC, tatsumiQ requested changes
単体テストをレビューしました。

2024-09-09 01:27 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +const assertGetInviteeRequest = ({ url, method }, ownerAndRepo, name, permission) => {
name, permission は不要な引数です。

2024-09-09 01:27 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +const prepareGetInviteeResponse = (permission, name, boolean) => {
今回の場合、レスポンスを動的に生成する必要はあまりないと思います。premission を引数にとる必要もありません。
box-collaboration-delete のように、レスポンスを定数にしたほうがわかりやすいのではないでしょうか。

また、owner, invitee, inviter の名前が同じだと、意図通り invitee の名前で存在チェックができているかどうかの確認ができません。

2024-09-09 01:27 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +const assertPutCollaborationRequest = ({ url, method }, ownerAndRepo, name) => {
permission を引数に含めて、リクエストボディもテストしてください。
```
onst assertPutCollaborationRequest = ({ url, method, body }, ownerAndRepo, name, permission) => {
    (中略)
    const bodyObj = JSON.parse(body);
    expect(bodyObj.permission).toEqual(permission);
```

2024-09-09 01:27 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +
URL とユーザ名を固定値で指定する正常系のテストケースも追加してください。

2024-09-09 02:55 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +            <label>C3: The handle of the GitHub user to invite</label>
修正しました。

2024-09-09 02:55 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    return repositoryUrl;
修正しました。

2024-09-09 02:56 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +        <config name="conf_Name" required="true" form-type="SELECT" select-data-type="STRING_TEXTFIELD" editable="true">
conf_UserName　に修正しました。

2024-09-09 02:56 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    const jsonRes = JSON.parse(responseStr);
修正しました。

2024-09-09 02:56 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    }
ありがとうございます。
修正しまｓた。

2024-09-09 02:56 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    jsonReq["permission"] = permission;
修正しました。

2024-09-09 02:56 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    const jsonRes = JSON.parse(responseStr);
削除しました。

2024-09-09 02:57 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    const jsonRes = JSON.parse(responseStr);
修正しました。

2024-09-09 02:57 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    } else {
修正しました。

2024-09-09 02:57 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +        throw new Error(`Failed to add a collaborator. status: ${status}`);
コメントを追加しました。

2024-09-09 02:58 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +const assertGetInviteeRequest = ({ url, method }, ownerAndRepo, name, permission) => {
削除しました。

2024-09-09 02:58 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +const assertPutCollaborationRequest = ({ url, method }, ownerAndRepo, name) => {
修正しました。

2024-09-09 02:59 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +
既存のテストケースに、固定値を指定するパターンを作成しました。

2024-09-09 03:04 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +const prepareGetInviteeResponse = (permission, name, boolean) => {
ユーザーがリポジトリ招待中であるかどうかを確認するために、
boolean のパラメータで、リポジトリ招待中かそうでないかのレスポンスを作成するようにしたのですが、
リポジトリ招待中の場合と、そうでない場合の 2 つのレスポンスを、それぞれ定数で作成するということでしょうか？

2024-09-09 04:52 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +const prepareGetInviteeResponse = (permission, name, boolean) => {
レスポンスを 1 つ用意しておいて、テストケースによってユーザ名の指定を変えれば良いと思います。
招待中のテストケースでは、レスポンスに含まれるユーザ名を指定する。
招待中でないテストケースでは、レスポンスに含まれないユーザ名を指定する。

2024-09-09 05:18 UTC, tatsumiQ requested changes
修正箇所をレビューしました。
スクリプトのほうで、ひとつ見逃していると思われるコメントがあったので、そちらの対応もお願いします。

2024-09-09 05:18 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +        assertPutCollaborationRequest(request, 'user5/user5repo', 'user5', null);
null でもテストに通るのかもしれませんが、厳密には undefined かなと思いました。

2024-09-10 01:13 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +    }
修正しました。

2024-09-10 01:13 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +        assertPutCollaborationRequest(request, 'user5/user5repo', 'user5', null);
修正しました。

2024-09-10 01:13 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +const prepareGetInviteeResponse = (permission, name, boolean) => {
ありがとうございます。
修正しました。
レスポンスを定数にしました。

2024-09-10 01:14 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いいたします。
見逃していた、スクリプトの指摘箇所も修正しました。

2024-09-10 01:39 UTC, tatsumiQ requested changes
レビューしました。あと１点だけ、修正をお願いします。

2024-09-10 01:39 UTC, tatsumiQ commented on github-repository-collaborater-add.xml
> +const getInviteeResponse =  [
定数を定義する場合、名前を大文字にするのが定例になっています。
`INVITEE_RESPONSE` や `INVITEE_LIST` としておくのが良いと思います。

名前から、それが関数なのか、変数なのか、定数なのかわかったほうが、コードとして読みやすいです。

2024-09-10 04:01 UTC, suese-sayaka commented on github-repository-collaborater-add.xml
> +const getInviteeResponse =  [
承知しました。INVITEE_RESPONSE に修正しました。

2024-09-10 05:09 UTC, tatsumiQ approved these changes

2024-09-10 06:13 UTC, merged