t10184 GitHub: リポジトリコラボレーター削除　の作成
Questetra/Addon-XML pull request #772
Opened 2024-09-17 02:10 UTC by suese-sayaka

@tatsumiQ さん

定義ファイルを作成しました。
ご確認をお願いします。

2024-09-17 06:04 UTC, tatsumiQ requested changes
レビュー途中ですが、いったん投稿します。

2024-09-17 06:04 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +    }
```suggestion
    if (status === 204) {
        // success: the user is a collaborator
        return;
    }
    if (status === 404) {
        throw new Error(`${handle} is not a collaborator. status: ${status}`);
    }
    engine.log(responseStr);
    throw new Error(`Failed to get a ${handle} information. status: ${status}`);
```
404 の場合と、それ以外の不正なレスポンスの場合とで、エラーメッセージを分けておいたほうが良いと思いました。

2024-09-17 06:38 UTC, tatsumiQ requested changes
レビューコメントを追加しました。

2024-09-17 06:38 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +const assertDeleteCollaborationRequest = ({ url, method, body }, ownerAndRepo, name) => {
body パラメータはいらないと思います。

2024-09-24 05:00 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +    <help-page-url locale="ja">https://support.questetra.com/ja/bpmn-icons/service-task-github-repository-collaborator-remove//</help-page-url>
修正しました。

2024-09-24 05:00 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +function main() {
修正しました。

2024-09-24 05:01 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +const checkInvitee = (auth, ownerAndRepo, handle) => {
追加しました。

2024-09-24 05:01 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +        throw new Error(`${handle} is a user pending for an invitation cannot be removed.`);
修正しました。

2024-09-24 05:01 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +    }
修正しました。

2024-09-24 05:01 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +const assertDeleteCollaborationRequest = ({ url, method, body }, ownerAndRepo, name) => {
削除しました。

2024-09-24 05:02 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-09-24 06:45 UTC, tatsumiQ requested changes
単体テストで、テストケースの追加をお願いします。

2024-09-24 06:45 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> + * ユーザーがリポジトリコラボレータであるかどうかを確認する API リクエストでエラー
スクリプトのほうで、レスポンスステータスが 404 の場合とそれ以外の場合とでエラーメッセージを分けたと思います。
テストのほうも、404 の場合と、それ以外の場合の両方のテストケースを用意してください。

2024-09-26 00:26 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> + * ユーザーがリポジトリコラボレータであるかどうかを確認する API リクエストでエラー
404 以外の場合のテストケースを追加しました。

2024-09-26 00:27 UTC, suese-sayaka commented
@tatsumiQ さん

テストケースを追加しました。
ご確認をお願いいたします。

2024-09-26 01:08 UTC, tatsumiQ approved these changes

2024-09-26 01:48 UTC, merged