t10200 テキストファイル生成　保存する際のファイルタイプに Markdown を追加する
Questetra/Addon-XML pull request #774
Opened 2024-09-30 04:14 UTC by suese-sayaka

@hatanaka-akihiro  さん

レビューをお願いします。

テストケースも追加しました。

2024-09-30 04:37 UTC, hatanaka-akihiro requested changes

2024-09-30 04:37 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    </item>
順番ですが、`text/html` の次にしてください。

2024-09-30 04:37 UTC, hatanaka-akihiro commented on generator-textfile.xml
> +    const fileDef = prepareConfigs(true, 'テスト8.txt', '<ol>\n<li>item1\n<ul>\n<li>item2</li>\n</ul></li>\n</ol>', '', 'text/markdown');
本質ではありませんが、Markdown っぽいデータにしましょう。

業務マニュアルの機能をテストしているので、Markdown には触れているはずです。

2024-10-01 00:27 UTC, suese-sayaka commented on generator-textfile.xml
> +    </item>
修正しました。

2024-10-01 00:27 UTC, suese-sayaka commented on generator-textfile.xml
> +    const fileDef = prepareConfigs(true, 'テスト8.txt', '<ol>\n<li>item1\n<ul>\n<li>item2</li>\n</ul></li>\n</ol>', '', 'text/markdown');
修正しました。

2024-10-01 00:27 UTC, suese-sayaka commented
@hatanaka-akihiro さん

修正しました。
ご確認をお願いいたします。

2024-10-01 00:45 UTC, hatanaka-akihiro approved these changes

2024-10-01 00:45 UTC, merged