T10266
Questetra/Addon-XML pull request #775
Opened 2024-10-03 02:30 UTC by suese-sayaka

@tatsumiQ さん

チケット 10266 の comment:3 の指摘について、スクリプトを修正しました。
テストコードを作成しました。

ご確認をお願いいたします。

2024-10-03 03:42 UTC, tatsumiQ requested changes
スクリプト部分のみレビューしました。
招待のキャンセルに 404 で失敗した場合は、処理継続したほうがいいのではと思いました。

2024-10-03 03:42 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +       return;
```suggestion
       const isInviteeRemoved = removeInvitee(auth, ownerAndRepo, handle, invitationId);
       if (isInviteeRemoved) {
           return;
       }
```

`removedInvitee()` で 404 レスポンスになり削除できなかった場合、「招待が承認され、ユーザがコラボレータになった」場合も考えられるのではないかと思います。

その場合は `checkCollaborator()` に進んだほうが良いので、「removeInvitee() で招待のキャンセルに成功した場合は、return する」ように変更したほうが良いと思いました。

2024-10-03 03:42 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +        return invitation.id;
```suggestion
        engine.log('Invitation found.');
        return invitation.id;
```
なくてもいいのですが、ログ出力しておくのが良いかと思いました。

2024-10-03 03:42 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +const removeInvitee = (auth, ownerAndRepo, handle, invitationId) => {
```suggestion
const removeInvitation = (auth, ownerAndRepo, handle, invitationId) => {
```
エラーメッセージ等で `remove the invitation` とするなら、関数名も揃えておいたほうが良いと思いました。

2024-10-03 03:42 UTC, tatsumiQ commented on github-repository-collaborater-remove.xml
> +    engine.log(`Succeeded to remove the invitation(${handle}).`);
```suggestion
    if (status === 204) { // 招待のキャンセル成功
        engine.log(`Succeeded to remove the invitation(${handle}).`);
        return true;
    }
    if (status === 404) { // 招待が承認済み or キャンセル済み
        engine.log(`Failed to remove invitation as it is already approved or removed.`);
        return false;
    }
    engine.log(responseStr);
    throw new Error(`Failed to remove the invitation. status: ${status}`);
```

招待のキャンセル成功時は true を、招待が見つからずキャンセルできなかった場合は false を return するようにすれば、以下のように処理を分岐させることができます。

- 招待のキャンセルに成功したときは、その時点で正常終了
- 招待が見つからずキャンセルできなかった場合は、承認済みの可能性があるので、`checkCollaborator()` に処理継続

2024-10-04 05:58 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +       return;
理解しました。修正しました。

2024-10-04 05:58 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +        return invitation.id;
修正しました。

2024-10-04 05:58 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +const removeInvitee = (auth, ownerAndRepo, handle, invitationId) => {
修正しました。

2024-10-04 05:59 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +    engine.log(`Succeeded to remove the invitation(${handle}).`);
理解しました。修正しました。

2024-10-04 05:59 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-10-04 06:47 UTC, tatsumiQ approved these changes

2024-10-04 08:21 UTC, hatanaka-akihiro requested changes

2024-10-04 08:21 UTC, hatanaka-akihiro commented on github-repository-collaborater-remove.xml
> +    invitationId = checkInvitee(auth, ownerAndRepo, handle);
const で良さそうです。

2024-10-04 08:21 UTC, hatanaka-akihiro commented on github-repository-collaborater-remove.xml
> +    }
```suggestion
    if (invitation === undefined){
      return undefined;
    }
    engine.log('Invitation found.');
    return invitation.id;
```

2024-10-07 01:25 UTC, suese-sayaka commented on github-repository-collaborater-remove.xml
> +    invitationId = checkInvitee(auth, ownerAndRepo, handle);
修正しました。

2024-10-07 01:27 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

修正しました。レビューをお願いします。

2024-10-08 00:12 UTC, suese-sayaka commented
@hatanaka-akihiro さん

コメントを修正しました。ご確認をお願いいたします。

2024-10-08 00:33 UTC, hatanaka-akihiro approved these changes

2024-10-08 00:33 UTC, merged