t10249&t10250 OpenAI ChatGPT: チャット　o1-preview / o1-mini モデル追加  回答保存データ項目に、文字型 Markdown 追加
Questetra/Addon-XML pull request #776
Opened 2024-10-25 04:55 UTC by suese-sayaka

@tatsumiQ  さん

レビューをお願いします。

2024-10-25 05:49 UTC, tatsumiQ requested changes
レビューしました。

2024-10-25 05:49 UTC, tatsumiQ commented on chatgpt-chat-completion.xml
> +    engine.log(`Completion_tokens_details: ${usage.completion_tokens_details.reasoning_tokens}`);
以下の点が気になっています。

- `Completion_tokens_details` だけ、ほかのログ（`Completion Tokens` 等）とラベルの形式が異なっている
- `Completion_tokens_details: {数値}` と表示されても、その数値の意味するところがわかりにくいのでは
- （確認したわけではないので、問題ないなら良いのですが）`reasoning_tokens` がないモデルの場合、この行でエラーになったりしないでしょうか

「Completion Tokens に含まれる内訳の情報」であることがわかるように、ログを出力したいところです。
たとえば、以下のように `JSON.stringify()` した結果をそのまま出力してしまっても良いと思います。
```suggestion
    engine.log(`Completion Tokens Details: ${JSON.stringify(usage.completion_tokens_details)}`);
```

2024-10-25 05:49 UTC, tatsumiQ commented on chatgpt-chat-completion.xml
> + * max_completion_tokens の値　max_tokens は Deprecated
```suggestion
 * config から、max_completion_tokens として設定する最大トークン数を読み出す
 * max_tokens は Deprecated
```

`max_completion_tokens の値` では意味が曖昧だと思いました。

2024-10-28 01:02 UTC, suese-sayaka commented on chatgpt-chat-completion.xml
> +    engine.log(`Completion_tokens_details: ${usage.completion_tokens_details.reasoning_tokens}`);
指摘いただいた 3 点について理解し、修正しました。
ログ出力について確認しました。

2024-10-28 01:03 UTC, suese-sayaka commented on chatgpt-chat-completion.xml
> + * max_completion_tokens の値　max_tokens は Deprecated
修正しました。

2024-10-28 01:03 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-10-28 01:32 UTC, tatsumiQ approved these changes

2024-10-28 05:36 UTC, hatanaka-akihiro approved these changes

2024-10-28 05:36 UTC, merged