t10225&10305 Google Vertex AI: Gemini: チャット PDFに対応／回答を保存するデータ項目に文字型 Markdown を追加
Questetra/Addon-XML pull request #777
Opened 2024-11-08 02:57 UTC by suese-sayaka

@tatsumiQ さん

レビューをお願いします。

PDF かどうかを判断する処理は、application から始まる種類が多そうだったので、
!contentType.startsWith('application/pdf')　にしました。

2024-11-08 05:19 UTC, tatsumiQ requested changes
コードの変更はこれで良いと思います。
I1 のラベルにも「PDF」を追加したほうが良いと思いました。

2024-11-11 01:21 UTC, suese-sayaka commented
@tatsumiQ さん

 I1 のラベル（日本語・英語）に「PDF」を追加しました。
ご確認をお願いいたします。

2024-11-11 04:51 UTC, tatsumiQ commented
細かいのですが、英語ラベルのほう、`PDFs` と複数形にしておいていただけますか。
ほかの名詞が複数形なので、統一しておいたほうがいいと思いました。

2024-11-12 00:36 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-11-12 01:47 UTC, tatsumiQ approved these changes
レビューしました。問題ありません。

2024-11-12 01:52 UTC, hatanaka-akihiro approved these changes

2024-11-12 01:52 UTC, merged