T10326 Google ドライブ系アイテム　アイコンの変更
Questetra/Addon-XML pull request #778
Opened 2024-11-19 00:28 UTC by suese-sayaka

@hatanaka-akihiro さん

各アイテムについて、修正しました。ご確認をお願いします。

2024-11-19 00:45 UTC, hatanaka-akihiro requested changes

2024-11-19 00:45 UTC, hatanaka-akihiro commented on google-drive-file-delete.xml
>  };
関数の引数が変わったら、普通は「関数の呼び出し側」の変更も必要になります。

このアイテム、自動テストに合格しているのでしょうか。

2024-11-19 00:45 UTC, hatanaka-akihiro commented on google-drive-folder-create.xml
>  };
google-drive-file-delete.xml

と同じ指摘です。

2024-11-19 00:45 UTC, hatanaka-akihiro commented on google-drive-permission-create.xml
> -const assertError = (func, errorMsg) => {
google-drive-file-delete.xml

と同じ指摘です。

2024-11-19 00:45 UTC, hatanaka-akihiro commented on google-drive-permission-delete.xml
> -const assertError = (func, errorMsg) => {
google-drive-file-delete.xml

と同じ指摘です。

2024-11-19 04:46 UTC, suese-sayaka commented on google-drive-folder-create.xml
>  };
google-drive-file-delete.xml
と同様に修正しました。

2024-11-19 04:46 UTC, suese-sayaka commented on google-drive-permission-create.xml
> -const assertError = (func, errorMsg) => {
google-drive-file-delete.xml
と同様に修正しました。

2024-11-19 05:09 UTC, hatanaka-akihiro requested changes

2024-11-19 05:09 UTC, hatanaka-akihiro commented on google-drive-file-delete.xml
>  };
どういう変更が行われたか確認しました。

もともと

```
expect(e.message).toEqual(errorMsg);
```

が合格していた理由がよく解りません。しかしまあ、この点は良いでしょう。

改良の方向性として、引数の `func` を無くすのは間違っていないと思います。
常に `main()` を呼び出すなら、`func()` としなくて良い。
間違っていたのは、`assertError()` を呼び出している側も、一緒に改良しなかった点です。

2024-11-19 05:12 UTC, hatanaka-akihiro commented on google-drive-file-delete.xml
>  };
引数の `func` を無くすのは良いので、`assertError` を呼び出している

```
assertError(main, 'User not found');
```

などを

```
assertError('User not found');
```

に変える必要があるでしょう。

2024-11-21 01:14 UTC, suese-sayaka commented on google-drive-file-delete.xml
>  };
修正しました。

2024-11-21 01:15 UTC, suese-sayaka commented on google-drive-folder-create.xml
>  };
google-drive-file-delete.xml
と同様に修正しました。

2024-11-21 01:15 UTC, suese-sayaka commented on google-drive-permission-create.xml
> -const assertError = (func, errorMsg) => {
google-drive-file-delete.xml
と同様に修正しました。

2024-11-21 01:15 UTC, suese-sayaka commented on google-drive-permission-delete.xml
> -const assertError = (func, errorMsg) => {
google-drive-file-delete.xml
と同様に修正しました。

2024-11-21 01:16 UTC, suese-sayaka commented
@hatanaka-akihiro  さん

修正しました。ご確認をお願いします。

2024-11-21 02:18 UTC, hatanaka-akihiro approved these changes

2024-11-21 02:22 UTC, merged