t10328&10304 Amazon Bedrock: Anthropic Claude: チャット モデルの追加、削除  文字型 Markdown の追加
Questetra/Addon-XML pull request #780
Opened 2024-11-26 05:31 UTC by suese-sayaka

@tatsumiQ さん

定義ファイルを修正しました。ご確認をお願いします。

2024-11-26 06:20 UTC, tatsumiQ requested changes
設定項目の順番変更も、お願いします。

2024-11-26 06:20 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +            </item>
Claude 3.5 Haiku を、Claude 3.5 Sonnet v2 の後ろに移動させてもらえますか。
3 が Sonnet, Haiku, Opus という順番なので、3.5 もあわせたほうが良いと思いました。

2024-11-28 00:46 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +const MODEL_3_SONNET_v2 = 'anthropic.claude-3-5-sonnet-20241022-v2:0';
修正しました。

2024-11-28 00:46 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +            </item>
修正しました。

2024-11-28 00:46 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-11-28 01:20 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +const MODEL_3_SONNET_v2 = 'anthropic.claude-3-5-sonnet-20241022-v2:0';
書き方が伝わりづらくすみません。3 と 3.5 は別物なので、3.5 だとわかる名前のほうが後々混乱しにくいと思いました。

2024-11-28 02:06 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +const MODEL_3_SONNET_v2 = 'anthropic.claude-3-5-sonnet-20241022-v2:0';
すみません。理解しました。修正しました。

2024-11-28 02:36 UTC, tatsumiQ approved these changes

2024-11-28 02:51 UTC, hatanaka-akihiro approved these changes

2024-11-28 02:51 UTC, merged