t10394 Amazon Bedrock: Anthropic Claude: チャット　クロスリージョン推論への対応
Questetra/Addon-XML pull request #781
Opened 2024-12-09 05:28 UTC by suese-sayaka

@tatsumiQ さん

クロスリージョン推論への対応をしました。ご確認をお願いします。

2024-12-09 05:58 UTC, tatsumiQ requested changes
レビューしました。

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    if (useCrossRegion === true) {
```suggestion
    if (useCrossRegion) {
```
useCrossRegion 自体が boolean なので、比較演算子は不要です。

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +function retrieveCrossRegionModel(model, region) {
retrieve は「取得する」という意味で、アドオンのメソッドではよく、config などから情報を読み出すメソッドに使っています。
このメソッドの役割は、コメントにもある通り「決定する」なので、`decideCrossRegionModel` などにメソッド名を変更したほうが良いと思います。

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +        throw new Error(`${region} is not supported by cross-region inference.`);
```suggestion
        throw new Error(`Cross-region inference is not supported in ${region}.`);
```
英文がすこしおかしいと思います。
is not supported by ~ とすると、「〜によってサポートされていません」という意味になるので、この場合は意味が通りません。

「クロスリージョン推論は、このリージョンではサポートされていません」というメッセージのほうがシンプルかなと思いました。

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    return model;
元々この関数にあった、モデル名が `anthropic.claude` ではじまるかどうかのバリデーションがなくなってしまっていますが、何か理由がありますか？

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    return model;
C4 で設定するモデルに、固定値で `anthoropic.claude` ではじまりでないモデル ID を設定する必要があるのでしょうか？

2024-12-09 05:58 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    if (model.startsWith(MODEL_PREFIX)){
`retrieveModel()` 内で `anthoropic.claude` ではじまることをテストしていれば、この if 文は不要です。

2024-12-13 04:50 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    return model;
C5: クロスリージョン推論を利用する　を ON にしつつ、us. などを付けたモデル ID を設定するユーザもいるかと思い、このような処理にしました。

2024-12-13 05:18 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    return model;
us. などをつけた ID は、正確には "Model id" ではなく、"Inference profile ID" と別の名前がついていたかと思います。
C5 に、モデル ID 以外の文字列を入力させる仕様は、良くないです。
従来通り `anthoropic.claude` ではじまるモデル ID のみ許可する仕様のほうがシンプルで、良いと思います。

2024-12-16 00:44 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    if (useCrossRegion === true) {
修正しました。

2024-12-16 00:44 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +function retrieveCrossRegionModel(model, region) {
修正しました。

2024-12-16 00:44 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +        throw new Error(`${region} is not supported by cross-region inference.`);
修正しました。

2024-12-16 00:45 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    return model;
理解しました。
修正しました。

2024-12-16 00:45 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    if (model.startsWith(MODEL_PREFIX)){
削除しました。

2024-12-16 00:46 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。
ご確認をお願いします。

2024-12-16 01:18 UTC, tatsumiQ requested changes
レビューしました。

2024-12-16 01:18 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
>      }
ここの if 文を削除して、後ろの if 文にまとめることができます。

2024-12-16 01:18 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
>      return model;
次のように先に return したほうが、今回はシンプルになると思います。

```suggestion
    if (region.startsWith('us-')){
        return `us.${model}`;
    } else if(region.startsWith('eu-')){
        return `eu.${model}`;
    } else if (region.startsWith('ap-')){
        return `apac.${model}`;
    }
    throw new Error(`Cross-region inference is not supported in ${region}.`);
```

2024-12-16 01:34 UTC, tatsumiQ requested changes
テストコードもレビューしました。

元々あった、`anthropic.claude` ではじまらないモデル ID を指定した場合にエラーになるテストケースがなくなっていると思うので、戻しておいてください。

2024-12-16 01:34 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> + * クロスリージョン推論を利用する 固定値で指定
「固定値で指定」のテストにはなっていないと思うので、このコメントを削除しておいてください。

2024-12-16 01:34 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    prepareConfigs(key, secret, region, 'anthropic.claude-3-5-haiku-20241022-v1:0', true, maxTokens, temperature, stopSequences, '', message);
ここで `MODEL_3_5_HAIKU` を使って指定し、後のリクエストの確認などでは
```
`us.${MODEL_3_5_HAIKU}`
```
としても良いと思います。
せっかく定数を定義しているので。

2024-12-16 01:34 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +    const region = 'us-east-1';
788 行目にもクロスリージョン推論のテストがあり、どちらも us リージョンです。
どちらかを別のリージョンに変えたほうが、様々なパターンをテストできて良いと思いました。

2024-12-16 01:34 UTC, tatsumiQ commented on aws-bedrock-anthropic-claude-chat.xml
> +        assertRequest(request, region, 'us.anthropic.claude-3-5-sonnet-20241022-v2:0', MAX_TOKENS_DEFAULT, 1, [], '', message, images);
ここも
```
`us.${MODEL_3_5_SONNET_V2}`
```
で確認するのがよいと思います。

2024-12-16 04:12 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
>      }
理解しました。修正しました。

2024-12-16 04:13 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
>      return model;
理解しました。修正しました。

2024-12-16 04:13 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> + * クロスリージョン推論を利用する 固定値で指定
削除しました。

2024-12-16 04:14 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    prepareConfigs(key, secret, region, 'anthropic.claude-3-5-haiku-20241022-v1:0', true, maxTokens, temperature, stopSequences, '', message);
修正しました。

2024-12-16 04:14 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +    const region = 'us-east-1';
修正しました。

2024-12-16 04:14 UTC, suese-sayaka commented on aws-bedrock-anthropic-claude-chat.xml
> +        assertRequest(request, region, 'us.anthropic.claude-3-5-sonnet-20241022-v2:0', MAX_TOKENS_DEFAULT, 1, [], '', message, images);
修正しました。

2024-12-16 04:15 UTC, suese-sayaka commented
@tatsumiQ さん

修正しました。ご確認をお願いします。

2024-12-16 05:07 UTC, tatsumiQ approved these changes

2024-12-16 06:05 UTC, hatanaka-akihiro approved these changes

2024-12-16 06:05 UTC, merged